#pragma once

#include <array>
#include <mutex>
#include <unordered_map>

#include <khrapi/Binding.h>

#include <glesbinding/glesbinding_api.h>

#include <glesbinding/gles/types.h>

#include <glesbinding/ContextHandle.h>
#include <glesbinding/ProcAddress.h>


namespace glesbinding
{

class GLESBINDING_API Binding : public khrapi::Binding<Binding, ContextHandle, getProcAddress, getCurrentContext>
{
public:
    using array_t = std::array<khrapi::AbstractFunction *, 674>;
    
    static const array_t s_functions;
    
    static const array_t & functions();
    
    static ContextHandle & context();
    static int & pos();
    static std::recursive_mutex & mutex();
    static std::unordered_map<ContextHandle, int> & bindings();

    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint> ActiveShaderProgram;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint> ActiveShaderProgramEXT;
    static khrapi::Function<Binding, void, gles::GLenum> ActiveTexture;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLclampf> AlphaFuncQCOM;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint> AttachShader;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum> BeginConditionalRenderNV;
    static khrapi::Function<Binding, void, gles::GLuint> BeginPerfMonitorAMD;
    static khrapi::Function<Binding, void, gles::GLuint> BeginPerfQueryINTEL;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint> BeginQuery;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint> BeginQueryEXT;
    static khrapi::Function<Binding, void, gles::GLenum> BeginTransformFeedback;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, const gles::GLchar *> BindAttribLocation;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint> BindBuffer;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLuint> BindBufferBase;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLuint, gles::GLintptr, gles::GLsizeiptr> BindBufferRange;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint> BindFramebuffer;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLint, gles::GLboolean, gles::GLint, gles::GLenum, gles::GLenum> BindImageTexture;
    static khrapi::Function<Binding, void, gles::GLuint> BindProgramPipeline;
    static khrapi::Function<Binding, void, gles::GLuint> BindProgramPipelineEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint> BindRenderbuffer;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint> BindSampler;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint> BindTexture;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint> BindTransformFeedback;
    static khrapi::Function<Binding, void, gles::GLuint> BindVertexArray;
    static khrapi::Function<Binding, void, gles::GLuint> BindVertexArrayOES;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLintptr, gles::GLsizei> BindVertexBuffer;
    static khrapi::Function<Binding, void> BlendBarrierKHR;
    static khrapi::Function<Binding, void> BlendBarrierNV;
    static khrapi::Function<Binding, void, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat> BlendColor;
    static khrapi::Function<Binding, void, gles::GLenum> BlendEquation;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum> BlendEquationSeparate;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLenum> BlendEquationSeparateiEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLenum> BlendEquationSeparateiOES;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum> BlendEquationiEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum> BlendEquationiOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum> BlendFunc;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLenum, gles::GLenum> BlendFuncSeparate;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLenum, gles::GLenum, gles::GLenum> BlendFuncSeparateiEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLenum, gles::GLenum, gles::GLenum> BlendFuncSeparateiOES;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLenum> BlendFunciEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLenum> BlendFunciOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint> BlendParameteriNV;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::ClearBufferMask, gles::GLenum> BlitFramebuffer;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLbitfield, gles::GLenum> BlitFramebufferANGLE;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLbitfield, gles::GLenum> BlitFramebufferNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizeiptr, const void *, gles::GLenum> BufferData;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizeiptr, const void *, gles::GLbitfield> BufferStorageEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLintptr, gles::GLsizeiptr, const void *> BufferSubData;
    static khrapi::Function<Binding, gles::GLenum, gles::GLenum> CheckFramebufferStatus;
    static khrapi::Function<Binding, void, gles::ClearBufferMask> Clear;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLfloat, gles::GLint> ClearBufferfi;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, const gles::GLfloat *> ClearBufferfv;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, const gles::GLint *> ClearBufferiv;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, const gles::GLuint *> ClearBufferuiv;
    static khrapi::Function<Binding, void, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat> ClearColor;
    static khrapi::Function<Binding, void, gles::GLfloat> ClearDepthf;
    static khrapi::Function<Binding, void, gles::GLint> ClearStencil;
    static khrapi::Function<Binding, gles::GLenum, gles::GLsync, gles::SyncObjectMask, gles::GLuint64> ClientWaitSync;
    static khrapi::Function<Binding, gles::GLenum, gles::GLsync, gles::GLbitfield, gles::GLuint64> ClientWaitSyncAPPLE;
    static khrapi::Function<Binding, void, gles::GLboolean, gles::GLboolean, gles::GLboolean, gles::GLboolean> ColorMask;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLboolean, gles::GLboolean, gles::GLboolean, gles::GLboolean> ColorMaskiEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLboolean, gles::GLboolean, gles::GLboolean, gles::GLboolean> ColorMaskiOES;
    static khrapi::Function<Binding, void, gles::GLuint> CompileShader;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLenum, gles::GLsizei, gles::GLsizei, gles::GLint, gles::GLsizei, const void *> CompressedTexImage2D;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLenum, gles::GLsizei, gles::GLsizei, gles::GLsizei, gles::GLint, gles::GLsizei, const void *> CompressedTexImage3D;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLenum, gles::GLsizei, gles::GLsizei, gles::GLsizei, gles::GLint, gles::GLsizei, const void *> CompressedTexImage3DOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLenum, gles::GLsizei, const void *> CompressedTexSubImage2D;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLsizei, gles::GLenum, gles::GLsizei, const void *> CompressedTexSubImage3D;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLsizei, gles::GLenum, gles::GLsizei, const void *> CompressedTexSubImage3DOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLintptr, gles::GLintptr, gles::GLsizeiptr> CopyBufferSubData;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLintptr, gles::GLintptr, gles::GLsizeiptr> CopyBufferSubDataNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLuint, gles::GLenum, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLsizei> CopyImageSubDataEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLuint, gles::GLenum, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLsizei> CopyImageSubDataOES;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint> CopyPathNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLenum, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLint> CopyTexImage2D;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei> CopyTexSubImage2D;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei> CopyTexSubImage3D;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei> CopyTexSubImage3DOES;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLint, gles::GLsizei> CopyTextureLevelsAPPLE;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLenum, const void *, gles::GLuint, gles::GLenum, gles::GLenum, const gles::GLfloat *> CoverFillPathInstancedNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum> CoverFillPathNV;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLenum, const void *, gles::GLuint, gles::GLenum, gles::GLenum, const gles::GLfloat *> CoverStrokePathInstancedNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum> CoverStrokePathNV;
    static khrapi::Function<Binding, void, gles::GLboolean> CoverageMaskNV;
    static khrapi::Function<Binding, void, gles::GLenum> CoverageModulationNV;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLfloat *> CoverageModulationTableNV;
    static khrapi::Function<Binding, void, gles::GLenum> CoverageOperationNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint *> CreatePerfQueryINTEL;
    static khrapi::Function<Binding, gles::GLuint> CreateProgram;
    static khrapi::Function<Binding, gles::GLuint, gles::GLenum> CreateShader;
    static khrapi::Function<Binding, gles::GLuint, gles::GLenum, gles::GLsizei, const gles::GLchar *const*> CreateShaderProgramv;
    static khrapi::Function<Binding, gles::GLuint, gles::GLenum, gles::GLsizei, const gles::GLchar **> CreateShaderProgramvEXT;
    static khrapi::Function<Binding, void, gles::GLenum> CullFace;
    static khrapi::Function<Binding, void, gles::GLDEBUGPROCKHR, const void *> DebugMessageCallbackKHR;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLenum, gles::GLsizei, const gles::GLuint *, gles::GLboolean> DebugMessageControlKHR;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLuint, gles::GLenum, gles::GLsizei, const gles::GLchar *> DebugMessageInsertKHR;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLuint *> DeleteBuffers;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLuint *> DeleteFencesNV;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLuint *> DeleteFramebuffers;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei> DeletePathsNV;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLuint *> DeletePerfMonitorsAMD;
    static khrapi::Function<Binding, void, gles::GLuint> DeletePerfQueryINTEL;
    static khrapi::Function<Binding, void, gles::GLuint> DeleteProgram;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLuint *> DeleteProgramPipelines;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLuint *> DeleteProgramPipelinesEXT;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLuint *> DeleteQueries;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLuint *> DeleteQueriesEXT;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLuint *> DeleteRenderbuffers;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLuint *> DeleteSamplers;
    static khrapi::Function<Binding, void, gles::GLuint> DeleteShader;
    static khrapi::Function<Binding, void, gles::GLsync> DeleteSync;
    static khrapi::Function<Binding, void, gles::GLsync> DeleteSyncAPPLE;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLuint *> DeleteTextures;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLuint *> DeleteTransformFeedbacks;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLuint *> DeleteVertexArrays;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLuint *> DeleteVertexArraysOES;
    static khrapi::Function<Binding, void, gles::GLenum> DepthFunc;
    static khrapi::Function<Binding, void, gles::GLboolean> DepthMask;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, const gles::GLfloat *> DepthRangeArrayfvNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLfloat, gles::GLfloat> DepthRangeIndexedfNV;
    static khrapi::Function<Binding, void, gles::GLfloat, gles::GLfloat> DepthRangef;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint> DetachShader;
    static khrapi::Function<Binding, void, gles::GLenum> Disable;
    static khrapi::Function<Binding, void, gles::GLuint> DisableDriverControlQCOM;
    static khrapi::Function<Binding, void, gles::GLuint> DisableVertexAttribArray;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint> DisableiEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint> DisableiNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint> DisableiOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, const gles::GLenum *> DiscardFramebufferEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLuint> DispatchCompute;
    static khrapi::Function<Binding, void, gles::GLintptr> DispatchComputeIndirect;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLsizei> DrawArrays;
    static khrapi::Function<Binding, void, gles::GLenum, const void *> DrawArraysIndirect;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLsizei, gles::GLsizei> DrawArraysInstanced;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLsizei, gles::GLsizei> DrawArraysInstancedANGLE;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLuint> DrawArraysInstancedBaseInstanceEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLsizei, gles::GLsizei> DrawArraysInstancedEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLsizei, gles::GLsizei> DrawArraysInstancedNV;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLenum *> DrawBuffers;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLenum *> DrawBuffersEXT;
    static khrapi::Function<Binding, void, gles::GLint, const gles::GLenum *, const gles::GLint *> DrawBuffersIndexedEXT;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLenum *> DrawBuffersNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, const void *> DrawElements;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, const void *, gles::GLint> DrawElementsBaseVertexEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, const void *, gles::GLint> DrawElementsBaseVertexOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, const void *> DrawElementsIndirect;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, const void *, gles::GLsizei> DrawElementsInstanced;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, const void *, gles::GLsizei> DrawElementsInstancedANGLE;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, const void *, gles::GLsizei, gles::GLuint> DrawElementsInstancedBaseInstanceEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, const void *, gles::GLsizei, gles::GLint, gles::GLuint> DrawElementsInstancedBaseVertexBaseInstanceEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, const void *, gles::GLsizei, gles::GLint> DrawElementsInstancedBaseVertexEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, const void *, gles::GLsizei, gles::GLint> DrawElementsInstancedBaseVertexOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, const void *, gles::GLsizei> DrawElementsInstancedEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, const void *, gles::GLsizei> DrawElementsInstancedNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLuint, gles::GLsizei, gles::GLenum, const void *> DrawRangeElements;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLuint, gles::GLsizei, gles::GLenum, const void *, gles::GLint> DrawRangeElementsBaseVertexEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLuint, gles::GLsizei, gles::GLenum, const void *, gles::GLint> DrawRangeElementsBaseVertexOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLeglImageOES> EGLImageTargetRenderbufferStorageOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLeglImageOES> EGLImageTargetTexture2DOES;
    static khrapi::Function<Binding, void, gles::GLenum> Enable;
    static khrapi::Function<Binding, void, gles::GLuint> EnableDriverControlQCOM;
    static khrapi::Function<Binding, void, gles::GLuint> EnableVertexAttribArray;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint> EnableiEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint> EnableiNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint> EnableiOES;
    static khrapi::Function<Binding, void> EndConditionalRenderNV;
    static khrapi::Function<Binding, void, gles::GLuint> EndPerfMonitorAMD;
    static khrapi::Function<Binding, void, gles::GLuint> EndPerfQueryINTEL;
    static khrapi::Function<Binding, void, gles::GLenum> EndQuery;
    static khrapi::Function<Binding, void, gles::GLenum> EndQueryEXT;
    static khrapi::Function<Binding, void, gles::GLbitfield> EndTilingQCOM;
    static khrapi::Function<Binding, void> EndTransformFeedback;
    static khrapi::Function<Binding, void, gles::GLenum, void **> ExtGetBufferPointervQCOM;
    static khrapi::Function<Binding, void, gles::GLuint *, gles::GLint, gles::GLint *> ExtGetBuffersQCOM;
    static khrapi::Function<Binding, void, gles::GLuint *, gles::GLint, gles::GLint *> ExtGetFramebuffersQCOM;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLchar *, gles::GLint *> ExtGetProgramBinarySourceQCOM;
    static khrapi::Function<Binding, void, gles::GLuint *, gles::GLint, gles::GLint *> ExtGetProgramsQCOM;
    static khrapi::Function<Binding, void, gles::GLuint *, gles::GLint, gles::GLint *> ExtGetRenderbuffersQCOM;
    static khrapi::Function<Binding, void, gles::GLuint *, gles::GLint, gles::GLint *> ExtGetShadersQCOM;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint, gles::GLenum, gles::GLint *> ExtGetTexLevelParameterivQCOM;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLsizei, gles::GLenum, gles::GLenum, void *> ExtGetTexSubImageQCOM;
    static khrapi::Function<Binding, void, gles::GLuint *, gles::GLint, gles::GLint *> ExtGetTexturesQCOM;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> ExtIsProgramBinaryQCOM;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLint> ExtTexObjectStateOverrideiQCOM;
    static khrapi::Function<Binding, gles::GLsync, gles::GLenum, gles::UnusedMask> FenceSync;
    static khrapi::Function<Binding, gles::GLsync, gles::GLenum, gles::GLbitfield> FenceSyncAPPLE;
    static khrapi::Function<Binding, void> Finish;
    static khrapi::Function<Binding, void, gles::GLuint> FinishFenceNV;
    static khrapi::Function<Binding, void> Flush;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLintptr, gles::GLsizeiptr> FlushMappedBufferRange;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLintptr, gles::GLsizeiptr> FlushMappedBufferRangeEXT;
    static khrapi::Function<Binding, void, gles::GLuint> FragmentCoverageColorNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLint> FramebufferParameteri;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLenum, gles::GLuint> FramebufferRenderbuffer;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLsizei, const gles::GLfloat *> FramebufferSampleLocationsfvNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLenum, gles::GLuint, gles::GLint> FramebufferTexture2D;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLenum, gles::GLuint, gles::GLint, gles::GLsizei> FramebufferTexture2DMultisampleEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLenum, gles::GLuint, gles::GLint, gles::GLsizei> FramebufferTexture2DMultisampleIMG;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLenum, gles::GLuint, gles::GLint, gles::GLint> FramebufferTexture3DOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLuint, gles::GLint> FramebufferTextureEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLuint, gles::GLint, gles::GLint> FramebufferTextureLayer;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLuint, gles::GLint, gles::GLint, gles::GLsizei> FramebufferTextureMultiviewOVR;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLuint, gles::GLint> FramebufferTextureOES;
    static khrapi::Function<Binding, void, gles::GLenum> FrontFace;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLuint *> GenBuffers;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLuint *> GenFencesNV;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLuint *> GenFramebuffers;
    static khrapi::Function<Binding, gles::GLuint, gles::GLsizei> GenPathsNV;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLuint *> GenPerfMonitorsAMD;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLuint *> GenProgramPipelines;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLuint *> GenProgramPipelinesEXT;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLuint *> GenQueries;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLuint *> GenQueriesEXT;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLuint *> GenRenderbuffers;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLuint *> GenSamplers;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLuint *> GenTextures;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLuint *> GenTransformFeedbacks;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLuint *> GenVertexArrays;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLuint *> GenVertexArraysOES;
    static khrapi::Function<Binding, void, gles::GLenum> GenerateMipmap;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLint *, gles::GLenum *, gles::GLchar *> GetActiveAttrib;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLint *, gles::GLenum *, gles::GLchar *> GetActiveUniform;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLchar *> GetActiveUniformBlockName;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLenum, gles::GLint *> GetActiveUniformBlockiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, const gles::GLuint *, gles::GLenum, gles::GLint *> GetActiveUniformsiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLuint *> GetAttachedShaders;
    static khrapi::Function<Binding, gles::GLint, gles::GLuint, const gles::GLchar *> GetAttribLocation;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLboolean *> GetBooleani_v;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLboolean *> GetBooleanv;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLint64 *> GetBufferParameteri64v;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLint *> GetBufferParameteriv;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, void **> GetBufferPointerv;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, void **> GetBufferPointervOES;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLfloat *> GetCoverageModulationTableNV;
    static khrapi::Function<Binding, gles::GLuint, gles::GLuint, gles::GLsizei, gles::GLenum *, gles::GLenum *, gles::GLuint *, gles::GLenum *, gles::GLsizei *, gles::GLchar *> GetDebugMessageLogKHR;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLchar *> GetDriverControlStringQCOM;
    static khrapi::Function<Binding, void, gles::GLint *, gles::GLsizei, gles::GLuint *> GetDriverControlsQCOM;
    static khrapi::Function<Binding, gles::GLenum> GetError;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint *> GetFenceivNV;
    static khrapi::Function<Binding, void, gles::GLuint *> GetFirstPerfQueryIdINTEL;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLfloat *> GetFloati_vNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLfloat *> GetFloatv;
    static khrapi::Function<Binding, gles::GLint, gles::GLuint, const gles::GLchar *> GetFragDataLocation;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLenum, gles::GLint *> GetFramebufferAttachmentParameteriv;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLint *> GetFramebufferParameteriv;
    static khrapi::Function<Binding, gles::GLenum> GetGraphicsResetStatusEXT;
    static khrapi::Function<Binding, gles::GLenum> GetGraphicsResetStatusKHR;
    static khrapi::Function<Binding, gles::GLuint64, gles::GLuint, gles::GLint, gles::GLboolean, gles::GLint, gles::GLenum> GetImageHandleNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLint64 *> GetInteger64i_v;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint64 *> GetInteger64v;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint64 *> GetInteger64vAPPLE;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLint *> GetIntegeri_v;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLint *> GetIntegeri_vEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint *> GetIntegerv;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei, gles::GLint *> GetInternalformatSampleivNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLenum, gles::GLsizei, gles::GLint *> GetInternalformativ;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLfloat *> GetMultisamplefv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint *> GetNextPerfQueryIdINTEL;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLchar *> GetObjectLabelEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLchar *> GetObjectLabelKHR;
    static khrapi::Function<Binding, void, const void *, gles::GLsizei, gles::GLsizei *, gles::GLchar *> GetObjectPtrLabelKHR;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLubyte *> GetPathCommandsNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLfloat *> GetPathCoordsNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLfloat *> GetPathDashArrayNV;
    static khrapi::Function<Binding, gles::GLfloat, gles::GLuint, gles::GLsizei, gles::GLsizei> GetPathLengthNV;
    static khrapi::Function<Binding, void, gles::PathRenderingMaskNV, gles::GLuint, gles::GLsizei, gles::GLsizei, gles::GLfloat *> GetPathMetricRangeNV;
    static khrapi::Function<Binding, void, gles::PathRenderingMaskNV, gles::GLsizei, gles::GLenum, const void *, gles::GLuint, gles::GLsizei, gles::GLfloat *> GetPathMetricsNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLfloat *> GetPathParameterfvNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint *> GetPathParameterivNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, const void *, gles::GLuint, gles::GLfloat, gles::GLfloat, gles::GLenum, gles::GLfloat *> GetPathSpacingNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLuint, gles::GLchar *, gles::GLuint, gles::GLchar *, gles::GLuint *, gles::GLuint *, gles::GLuint *, gles::GLuint *, gles::GLuint64 *> GetPerfCounterInfoINTEL;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLsizei, gles::GLuint *, gles::GLint *> GetPerfMonitorCounterDataAMD;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLenum, void *> GetPerfMonitorCounterInfoAMD;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLchar *> GetPerfMonitorCounterStringAMD;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint *, gles::GLint *, gles::GLsizei, gles::GLuint *> GetPerfMonitorCountersAMD;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLchar *> GetPerfMonitorGroupStringAMD;
    static khrapi::Function<Binding, void, gles::GLint *, gles::GLsizei, gles::GLuint *> GetPerfMonitorGroupsAMD;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLsizei, gles::GLvoid *, gles::GLuint *> GetPerfQueryDataINTEL;
    static khrapi::Function<Binding, void, gles::GLchar *, gles::GLuint *> GetPerfQueryIdByNameINTEL;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLchar *, gles::GLuint *, gles::GLuint *, gles::GLuint *, gles::GLuint *> GetPerfQueryInfoINTEL;
    static khrapi::Function<Binding, void, gles::GLenum, void **> GetPointervKHR;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLenum *, void *> GetProgramBinary;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLenum *, void *> GetProgramBinaryOES;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLchar *> GetProgramInfoLog;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLenum, gles::GLint *> GetProgramInterfaceiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLchar *> GetProgramPipelineInfoLog;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLchar *> GetProgramPipelineInfoLogEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint *> GetProgramPipelineiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint *> GetProgramPipelineivEXT;
    static khrapi::Function<Binding, gles::GLuint, gles::GLuint, gles::GLenum, const gles::GLchar *> GetProgramResourceIndex;
    static khrapi::Function<Binding, gles::GLint, gles::GLuint, gles::GLenum, const gles::GLchar *> GetProgramResourceLocation;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLchar *> GetProgramResourceName;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLuint, gles::GLsizei, const gles::GLenum *, gles::GLsizei, gles::GLsizei *, gles::GLfloat *> GetProgramResourcefvNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLuint, gles::GLsizei, const gles::GLenum *, gles::GLsizei, gles::GLsizei *, gles::GLint *> GetProgramResourceiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint *> GetProgramiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint64 *> GetQueryObjecti64vEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint *> GetQueryObjectivEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLuint64 *> GetQueryObjectui64vEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLuint *> GetQueryObjectuiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLuint *> GetQueryObjectuivEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLint *> GetQueryiv;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLint *> GetQueryivEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLint *> GetRenderbufferParameteriv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint *> GetSamplerParameterIivEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint *> GetSamplerParameterIivOES;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLuint *> GetSamplerParameterIuivEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLuint *> GetSamplerParameterIuivOES;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLfloat *> GetSamplerParameterfv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint *> GetSamplerParameteriv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLchar *> GetShaderInfoLog;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLint *, gles::GLint *> GetShaderPrecisionFormat;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLchar *> GetShaderSource;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint *> GetShaderiv;
    static khrapi::Function<Binding, const gles::GLubyte *, gles::GLenum> GetString;
    static khrapi::Function<Binding, const gles::GLubyte *, gles::GLenum, gles::GLuint> GetStringi;
    static khrapi::Function<Binding, void, gles::GLsync, gles::GLenum, gles::GLsizei, gles::GLsizei *, gles::GLint *> GetSynciv;
    static khrapi::Function<Binding, void, gles::GLsync, gles::GLenum, gles::GLsizei, gles::GLsizei *, gles::GLint *> GetSyncivAPPLE;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLenum, gles::GLfloat *> GetTexLevelParameterfv;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLenum, gles::GLint *> GetTexLevelParameteriv;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLint *> GetTexParameterIivEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLint *> GetTexParameterIivOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLuint *> GetTexParameterIuivEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLuint *> GetTexParameterIuivOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLfloat *> GetTexParameterfv;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLint *> GetTexParameteriv;
    static khrapi::Function<Binding, gles::GLuint64, gles::GLuint> GetTextureHandleNV;
    static khrapi::Function<Binding, gles::GLuint64, gles::GLuint, gles::GLuint> GetTextureSamplerHandleNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLsizei *, gles::GLenum *, gles::GLchar *> GetTransformFeedbackVarying;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLchar *> GetTranslatedShaderSourceANGLE;
    static khrapi::Function<Binding, gles::GLuint, gles::GLuint, const gles::GLchar *> GetUniformBlockIndex;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, const gles::GLchar *const*, gles::GLuint *> GetUniformIndices;
    static khrapi::Function<Binding, gles::GLint, gles::GLuint, const gles::GLchar *> GetUniformLocation;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLfloat *> GetUniformfv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLint *> GetUniformiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLuint *> GetUniformuiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint *> GetVertexAttribIiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLuint *> GetVertexAttribIuiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, void **> GetVertexAttribPointerv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLfloat *> GetVertexAttribfv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint *> GetVertexAttribiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLfloat *> GetnUniformfvEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLfloat *> GetnUniformfvKHR;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLint *> GetnUniformivEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLint *> GetnUniformivKHR;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLuint *> GetnUniformuivKHR;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum> Hint;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLchar *> InsertEventMarkerEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLuint, gles::GLfloat> InterpolatePathsNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, const gles::GLenum *> InvalidateFramebuffer;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, const gles::GLenum *, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei> InvalidateSubFramebuffer;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> IsBuffer;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLenum> IsEnabled;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLenum, gles::GLuint> IsEnablediEXT;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLenum, gles::GLuint> IsEnablediNV;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLenum, gles::GLuint> IsEnablediOES;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> IsFenceNV;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> IsFramebuffer;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint64> IsImageHandleResidentNV;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> IsPathNV;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint, gles::GLuint, gles::GLfloat, gles::GLfloat> IsPointInFillPathNV;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint, gles::GLfloat, gles::GLfloat> IsPointInStrokePathNV;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> IsProgram;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> IsProgramPipeline;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> IsProgramPipelineEXT;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> IsQuery;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> IsQueryEXT;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> IsRenderbuffer;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> IsSampler;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> IsShader;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLsync> IsSync;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLsync> IsSyncAPPLE;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> IsTexture;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint64> IsTextureHandleResidentNV;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> IsTransformFeedback;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> IsVertexArray;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> IsVertexArrayOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLsizei, const gles::GLchar *> LabelObjectEXT;
    static khrapi::Function<Binding, void, gles::GLfloat> LineWidth;
    static khrapi::Function<Binding, void, gles::GLuint> LinkProgram;
    static khrapi::Function<Binding, void, gles::GLuint64> MakeImageHandleNonResidentNV;
    static khrapi::Function<Binding, void, gles::GLuint64, gles::GLenum> MakeImageHandleResidentNV;
    static khrapi::Function<Binding, void, gles::GLuint64> MakeTextureHandleNonResidentNV;
    static khrapi::Function<Binding, void, gles::GLuint64> MakeTextureHandleResidentNV;
    static khrapi::Function<Binding, void *, gles::GLenum, gles::GLenum> MapBufferOES;
    static khrapi::Function<Binding, void *, gles::GLenum, gles::GLintptr, gles::GLsizeiptr, gles::BufferAccessMask> MapBufferRange;
    static khrapi::Function<Binding, void *, gles::GLenum, gles::GLintptr, gles::GLsizeiptr, gles::GLbitfield> MapBufferRangeEXT;
    static khrapi::Function<Binding, void, gles::GLenum, const gles::GLfloat *> MatrixLoad3x2fNV;
    static khrapi::Function<Binding, void, gles::GLenum, const gles::GLfloat *> MatrixLoad3x3fNV;
    static khrapi::Function<Binding, void, gles::GLenum, const gles::GLfloat *> MatrixLoadTranspose3x3fNV;
    static khrapi::Function<Binding, void, gles::GLenum, const gles::GLfloat *> MatrixMult3x2fNV;
    static khrapi::Function<Binding, void, gles::GLenum, const gles::GLfloat *> MatrixMult3x3fNV;
    static khrapi::Function<Binding, void, gles::GLenum, const gles::GLfloat *> MatrixMultTranspose3x3fNV;
    static khrapi::Function<Binding, void, gles::MemoryBarrierMask> MemoryBarrier;
    static khrapi::Function<Binding, void, gles::MemoryBarrierMask> MemoryBarrierByRegion;
    static khrapi::Function<Binding, void, gles::GLfloat> MinSampleShadingOES;
    static khrapi::Function<Binding, void, gles::GLenum, const gles::GLint *, const gles::GLsizei *, gles::GLsizei> MultiDrawArraysEXT;
    static khrapi::Function<Binding, void, gles::GLenum, const void *, gles::GLsizei, gles::GLsizei> MultiDrawArraysIndirectEXT;
    static khrapi::Function<Binding, void, gles::GLenum, const gles::GLsizei *, gles::GLenum, const void *const*, gles::GLsizei, const gles::GLint *> MultiDrawElementsBaseVertexEXT;
    static khrapi::Function<Binding, void, gles::GLenum, const gles::GLsizei *, gles::GLenum, const void *const*, gles::GLsizei, const gles::GLint *> MultiDrawElementsBaseVertexOES;
    static khrapi::Function<Binding, void, gles::GLenum, const gles::GLsizei *, gles::GLenum, const void *const*, gles::GLsizei> MultiDrawElementsEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, const void *, gles::GLsizei, gles::GLsizei> MultiDrawElementsIndirectEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLsizei, const gles::GLfloat *> NamedFramebufferSampleLocationsfvNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLsizei, const gles::GLchar *> ObjectLabelKHR;
    static khrapi::Function<Binding, void, const void *, gles::GLsizei, const gles::GLchar *> ObjectPtrLabelKHR;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint> PatchParameteriEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint> PatchParameteriOES;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, const gles::GLubyte *, gles::GLsizei, gles::GLenum, const void *> PathCommandsNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, gles::GLenum, const void *> PathCoordsNV;
    static khrapi::Function<Binding, void, gles::GLenum> PathCoverDepthFuncNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, const gles::GLfloat *> PathDashArrayNV;
    static khrapi::Function<Binding, gles::GLenum, gles::GLuint, gles::GLenum, const void *, gles::PathFontStyle, gles::GLuint, gles::GLsizei, gles::GLuint, gles::GLfloat> PathGlyphIndexArrayNV;
    static khrapi::Function<Binding, gles::GLenum, gles::GLenum, const void *, gles::PathFontStyle, gles::GLuint, gles::GLfloat, gles::GLuint_array_2> PathGlyphIndexRangeNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, const void *, gles::PathFontStyle, gles::GLuint, gles::GLsizei, gles::GLenum, gles::GLuint, gles::GLfloat> PathGlyphRangeNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, const void *, gles::PathFontStyle, gles::GLsizei, gles::GLenum, const void *, gles::GLenum, gles::GLuint, gles::GLfloat> PathGlyphsNV;
    static khrapi::Function<Binding, gles::GLenum, gles::GLuint, gles::GLenum, gles::GLsizeiptr, const void *, gles::GLsizei, gles::GLuint, gles::GLsizei, gles::GLuint, gles::GLfloat> PathMemoryGlyphIndexArrayNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLfloat> PathParameterfNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, const gles::GLfloat *> PathParameterfvNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint> PathParameteriNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, const gles::GLint *> PathParameterivNV;
    static khrapi::Function<Binding, void, gles::GLfloat, gles::GLfloat> PathStencilDepthOffsetNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLuint> PathStencilFuncNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLsizei, const void *> PathStringNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, gles::GLsizei, gles::GLsizei, const gles::GLubyte *, gles::GLsizei, gles::GLenum, const void *> PathSubCommandsNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, gles::GLsizei, gles::GLenum, const void *> PathSubCoordsNV;
    static khrapi::Function<Binding, void> PauseTransformFeedback;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint> PixelStorei;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint, gles::GLsizei, gles::GLsizei, gles::GLfloat, gles::GLfloat *, gles::GLfloat *, gles::GLfloat *, gles::GLfloat *> PointAlongPathNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum> PolygonModeNV;
    static khrapi::Function<Binding, void, gles::GLfloat, gles::GLfloat> PolygonOffset;
    static khrapi::Function<Binding, void> PopDebugGroupKHR;
    static khrapi::Function<Binding, void> PopGroupMarkerEXT;
    static khrapi::Function<Binding, void, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat> PrimitiveBoundingBoxEXT;
    static khrapi::Function<Binding, void, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat> PrimitiveBoundingBoxOES;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, const void *, gles::GLsizei> ProgramBinary;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, const void *, gles::GLint> ProgramBinaryOES;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint> ProgramParameteri;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint> ProgramParameteriEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLenum, gles::GLint, const gles::GLfloat *> ProgramPathFragmentInputGenNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLfloat> ProgramUniform1f;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLfloat> ProgramUniform1fEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLfloat *> ProgramUniform1fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLfloat *> ProgramUniform1fvEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLint> ProgramUniform1i;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLint> ProgramUniform1iEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLint *> ProgramUniform1iv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLint *> ProgramUniform1ivEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLuint> ProgramUniform1ui;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLuint> ProgramUniform1uiEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLuint *> ProgramUniform1uiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLuint *> ProgramUniform1uivEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLfloat, gles::GLfloat> ProgramUniform2f;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLfloat, gles::GLfloat> ProgramUniform2fEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLfloat *> ProgramUniform2fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLfloat *> ProgramUniform2fvEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLint, gles::GLint> ProgramUniform2i;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLint, gles::GLint> ProgramUniform2iEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLint *> ProgramUniform2iv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLint *> ProgramUniform2ivEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLuint, gles::GLuint> ProgramUniform2ui;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLuint, gles::GLuint> ProgramUniform2uiEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLuint *> ProgramUniform2uiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLuint *> ProgramUniform2uivEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLfloat, gles::GLfloat, gles::GLfloat> ProgramUniform3f;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLfloat, gles::GLfloat, gles::GLfloat> ProgramUniform3fEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLfloat *> ProgramUniform3fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLfloat *> ProgramUniform3fvEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLint, gles::GLint, gles::GLint> ProgramUniform3i;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLint, gles::GLint, gles::GLint> ProgramUniform3iEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLint *> ProgramUniform3iv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLint *> ProgramUniform3ivEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLuint, gles::GLuint, gles::GLuint> ProgramUniform3ui;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLuint, gles::GLuint, gles::GLuint> ProgramUniform3uiEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLuint *> ProgramUniform3uiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLuint *> ProgramUniform3uivEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat> ProgramUniform4f;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat> ProgramUniform4fEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLfloat *> ProgramUniform4fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLfloat *> ProgramUniform4fvEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint> ProgramUniform4i;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint> ProgramUniform4iEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLint *> ProgramUniform4iv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLint *> ProgramUniform4ivEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLuint, gles::GLuint, gles::GLuint, gles::GLuint> ProgramUniform4ui;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLuint, gles::GLuint, gles::GLuint, gles::GLuint> ProgramUniform4uiEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLuint *> ProgramUniform4uiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLuint *> ProgramUniform4uivEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLuint64> ProgramUniformHandleui64NV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLuint64 *> ProgramUniformHandleui64vNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> ProgramUniformMatrix2fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> ProgramUniformMatrix2fvEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> ProgramUniformMatrix2x3fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> ProgramUniformMatrix2x3fvEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> ProgramUniformMatrix2x4fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> ProgramUniformMatrix2x4fvEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> ProgramUniformMatrix3fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> ProgramUniformMatrix3fvEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> ProgramUniformMatrix3x2fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> ProgramUniformMatrix3x2fvEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> ProgramUniformMatrix3x4fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> ProgramUniformMatrix3x4fvEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> ProgramUniformMatrix4fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> ProgramUniformMatrix4fvEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> ProgramUniformMatrix4x2fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> ProgramUniformMatrix4x2fvEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> ProgramUniformMatrix4x3fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> ProgramUniformMatrix4x3fvEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLsizei, const gles::GLchar *> PushDebugGroupKHR;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLchar *> PushGroupMarkerEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum> QueryCounterEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLboolean> RasterSamplesEXT;
    static khrapi::Function<Binding, void, gles::GLenum> ReadBuffer;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint> ReadBufferIndexedEXT;
    static khrapi::Function<Binding, void, gles::GLenum> ReadBufferNV;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLenum, gles::GLenum, void *> ReadPixels;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLenum, gles::GLenum, gles::GLsizei, void *> ReadnPixelsEXT;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLenum, gles::GLenum, gles::GLsizei, void *> ReadnPixelsKHR;
    static khrapi::Function<Binding, void> ReleaseShaderCompiler;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLsizei, gles::GLsizei> RenderbufferStorage;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei, gles::GLsizei> RenderbufferStorageMultisample;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei, gles::GLsizei> RenderbufferStorageMultisampleANGLE;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei, gles::GLsizei> RenderbufferStorageMultisampleAPPLE;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei, gles::GLsizei> RenderbufferStorageMultisampleEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei, gles::GLsizei> RenderbufferStorageMultisampleIMG;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei, gles::GLsizei> RenderbufferStorageMultisampleNV;
    static khrapi::Function<Binding, void> ResolveDepthValuesNV;
    static khrapi::Function<Binding, void> ResolveMultisampleFramebufferAPPLE;
    static khrapi::Function<Binding, void> ResumeTransformFeedback;
    static khrapi::Function<Binding, void, gles::GLfloat, gles::GLboolean> SampleCoverage;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLbitfield> SampleMaski;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, const gles::GLint *> SamplerParameterIivEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, const gles::GLint *> SamplerParameterIivOES;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, const gles::GLuint *> SamplerParameterIuivEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, const gles::GLuint *> SamplerParameterIuivOES;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLfloat> SamplerParameterf;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, const gles::GLfloat *> SamplerParameterfv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint> SamplerParameteri;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, const gles::GLint *> SamplerParameteriv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei> Scissor;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, const gles::GLint *> ScissorArrayvNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei> ScissorIndexedNV;
    static khrapi::Function<Binding, void, gles::GLuint, const gles::GLint *> ScissorIndexedvNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLboolean, gles::GLuint, gles::GLint, gles::GLuint *> SelectPerfMonitorCountersAMD;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum> SetFenceNV;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLuint *, gles::GLenum, const void *, gles::GLsizei> ShaderBinary;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, const gles::GLchar *const*, const gles::GLint *> ShaderSource;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLuint, gles::GLuint, gles::GLbitfield> StartTilingQCOM;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLenum, const void *, gles::GLuint, gles::GLenum, gles::GLuint, gles::GLenum, const gles::GLfloat *> StencilFillPathInstancedNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLuint> StencilFillPathNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLuint> StencilFunc;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLint, gles::GLuint> StencilFuncSeparate;
    static khrapi::Function<Binding, void, gles::GLuint> StencilMask;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint> StencilMaskSeparate;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLenum> StencilOp;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLenum, gles::GLenum> StencilOpSeparate;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLenum, const void *, gles::GLuint, gles::GLint, gles::GLuint, gles::GLenum, const gles::GLfloat *> StencilStrokePathInstancedNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLuint> StencilStrokePathNV;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLenum, const void *, gles::GLuint, gles::GLenum, gles::GLuint, gles::GLenum, gles::GLenum, const gles::GLfloat *> StencilThenCoverFillPathInstancedNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLuint, gles::GLenum> StencilThenCoverFillPathNV;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLenum, const void *, gles::GLuint, gles::GLint, gles::GLuint, gles::GLenum, gles::GLenum, const gles::GLfloat *> StencilThenCoverStrokePathInstancedNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLuint, gles::GLenum> StencilThenCoverStrokePathNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint> SubpixelPrecisionBiasNV;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> TestFenceNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLuint> TexBufferEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLuint> TexBufferOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLuint, gles::GLintptr, gles::GLsizeiptr> TexBufferRangeEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLuint, gles::GLintptr, gles::GLsizeiptr> TexBufferRangeOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLint, gles::GLenum, gles::GLenum, const void *> TexImage2D;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLsizei, gles::GLint, gles::GLenum, gles::GLenum, const void *> TexImage3D;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLenum, gles::GLsizei, gles::GLsizei, gles::GLsizei, gles::GLint, gles::GLenum, gles::GLenum, const void *> TexImage3DOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLsizei, gles::GLboolean> TexPageCommitmentARB;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, const gles::GLint *> TexParameterIivEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, const gles::GLint *> TexParameterIivOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, const gles::GLuint *> TexParameterIuivEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, const gles::GLuint *> TexParameterIuivOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLfloat> TexParameterf;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, const gles::GLfloat *> TexParameterfv;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLint> TexParameteri;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, const gles::GLint *> TexParameteriv;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei> TexStorage1DEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei, gles::GLsizei> TexStorage2D;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei, gles::GLsizei> TexStorage2DEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei, gles::GLsizei, gles::GLboolean> TexStorage2DMultisample;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei, gles::GLsizei, gles::GLsizei> TexStorage3D;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei, gles::GLsizei, gles::GLsizei> TexStorage3DEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei, gles::GLsizei, gles::GLsizei, gles::GLboolean> TexStorage3DMultisampleOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLenum, gles::GLenum, const void *> TexSubImage2D;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLsizei, gles::GLenum, gles::GLenum, const void *> TexSubImage3D;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLsizei, gles::GLenum, gles::GLenum, const void *> TexSubImage3DOES;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei> TextureStorage1DEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei, gles::GLsizei> TextureStorage2DEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei, gles::GLsizei, gles::GLsizei> TextureStorage3DEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLuint, gles::GLenum, gles::GLuint, gles::GLuint, gles::GLuint, gles::GLuint> TextureViewEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLuint, gles::GLenum, gles::GLuint, gles::GLuint, gles::GLuint, gles::GLuint> TextureViewOES;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, const gles::GLchar *const*, gles::GLenum> TransformFeedbackVaryings;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLenum, const gles::GLfloat *> TransformPathNV;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLfloat> Uniform1f;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, const gles::GLfloat *> Uniform1fv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLint> Uniform1i;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, const gles::GLint *> Uniform1iv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLuint> Uniform1ui;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, const gles::GLuint *> Uniform1uiv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLfloat, gles::GLfloat> Uniform2f;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, const gles::GLfloat *> Uniform2fv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLint, gles::GLint> Uniform2i;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, const gles::GLint *> Uniform2iv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLuint, gles::GLuint> Uniform2ui;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, const gles::GLuint *> Uniform2uiv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLfloat, gles::GLfloat, gles::GLfloat> Uniform3f;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, const gles::GLfloat *> Uniform3fv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLint, gles::GLint, gles::GLint> Uniform3i;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, const gles::GLint *> Uniform3iv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLuint, gles::GLuint, gles::GLuint> Uniform3ui;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, const gles::GLuint *> Uniform3uiv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat> Uniform4f;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, const gles::GLfloat *> Uniform4fv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint> Uniform4i;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, const gles::GLint *> Uniform4iv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLuint, gles::GLuint, gles::GLuint, gles::GLuint> Uniform4ui;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, const gles::GLuint *> Uniform4uiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLuint> UniformBlockBinding;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLuint64> UniformHandleui64NV;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, const gles::GLuint64 *> UniformHandleui64vNV;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> UniformMatrix2fv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> UniformMatrix2x3fv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> UniformMatrix2x3fvNV;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> UniformMatrix2x4fv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> UniformMatrix2x4fvNV;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> UniformMatrix3fv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> UniformMatrix3x2fv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> UniformMatrix3x2fvNV;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> UniformMatrix3x4fv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> UniformMatrix3x4fvNV;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> UniformMatrix4fv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> UniformMatrix4x2fv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> UniformMatrix4x2fvNV;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> UniformMatrix4x3fv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> UniformMatrix4x3fvNV;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLenum> UnmapBuffer;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLenum> UnmapBufferOES;
    static khrapi::Function<Binding, void, gles::GLuint> UseProgram;
    static khrapi::Function<Binding, void, gles::GLuint, gles::UseProgramStageMask, gles::GLuint> UseProgramStages;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLbitfield, gles::GLuint> UseProgramStagesEXT;
    static khrapi::Function<Binding, void, gles::GLuint> ValidateProgram;
    static khrapi::Function<Binding, void, gles::GLuint> ValidateProgramPipeline;
    static khrapi::Function<Binding, void, gles::GLuint> ValidateProgramPipelineEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLfloat> VertexAttrib1f;
    static khrapi::Function<Binding, void, gles::GLuint, const gles::GLfloat *> VertexAttrib1fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLfloat, gles::GLfloat> VertexAttrib2f;
    static khrapi::Function<Binding, void, gles::GLuint, const gles::GLfloat *> VertexAttrib2fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLfloat, gles::GLfloat, gles::GLfloat> VertexAttrib3f;
    static khrapi::Function<Binding, void, gles::GLuint, const gles::GLfloat *> VertexAttrib3fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat> VertexAttrib4f;
    static khrapi::Function<Binding, void, gles::GLuint, const gles::GLfloat *> VertexAttrib4fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint> VertexAttribBinding;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint> VertexAttribDivisor;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint> VertexAttribDivisorANGLE;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint> VertexAttribDivisorEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint> VertexAttribDivisorNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLenum, gles::GLboolean, gles::GLuint> VertexAttribFormat;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLint, gles::GLint, gles::GLint> VertexAttribI4i;
    static khrapi::Function<Binding, void, gles::GLuint, const gles::GLint *> VertexAttribI4iv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLuint, gles::GLuint, gles::GLuint> VertexAttribI4ui;
    static khrapi::Function<Binding, void, gles::GLuint, const gles::GLuint *> VertexAttribI4uiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLenum, gles::GLuint> VertexAttribIFormat;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLenum, gles::GLsizei, const void *> VertexAttribIPointer;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLenum, gles::GLboolean, gles::GLsizei, const void *> VertexAttribPointer;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint> VertexBindingDivisor;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei> Viewport;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, const gles::GLfloat *> ViewportArrayvNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat> ViewportIndexedfNV;
    static khrapi::Function<Binding, void, gles::GLuint, const gles::GLfloat *> ViewportIndexedfvNV;
    static khrapi::Function<Binding, void, gles::GLsync, gles::UnusedMask, gles::GLuint64> WaitSync;
    static khrapi::Function<Binding, void, gles::GLsync, gles::GLbitfield, gles::GLuint64> WaitSyncAPPLE;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, const gles::GLuint *, const gles::GLfloat *> WeightPathsNV;

};

} // namespace glesbinding
