#pragma once

#include <array>
#include <vector>
#include <functional>

#include <khrapi/Function.h>

#include <glesbinding/glesbinding_api.h>

#include <glesbinding/gles/types.h>

#include <glesbinding/ContextHandle.h>


namespace glesbinding
{

class GLESBINDING_API Binding
{
public:
    using array_t = std::array<khrapi::AbstractFunction *, 674>;
    using ContextSwitchCallback = std::function<void(ContextHandle)>;

    Binding() = delete;
    
    static khrapi::ProcAddress getProcAddress(const char * name);

    static void initialize(bool resolveFunctions = true);
    static void initialize(ContextHandle context, bool useContext = true, bool resolveFunctions = true);
    
    static void registerAdditionalFunction(khrapi::AbstractFunction * function);

    static void resolveFunctions();

    static void useCurrentContext();
    static void useContext(ContextHandle context);

    static void releaseCurrentContext();
    static void releaseContext(ContextHandle context);
    
    static void addContextSwitchCallback(ContextSwitchCallback callback);

    static size_t size();

    static const array_t & functions();
    static const std::vector<khrapi::AbstractFunction *> & additionalFunctions();

    static int currentPos();

    static void setCallbackMask(khrapi::CallbackMask mask);
    static void setCallbackMaskExcept(khrapi::CallbackMask mask, const std::set<std::string> & blackList);
    static void addCallbackMask(khrapi::CallbackMask mask);
    static void addCallbackMaskExcept(khrapi::CallbackMask mask, const std::set<std::string> & blackList);
    static void removeCallbackMask(khrapi::CallbackMask mask);

protected:
    static void provideState(int pos);
    static void neglectState(int pos);
    static void setStatePos(int pos);

public:
    
    // to reduce per instance hasState checks and provide/neglect states for all instances,
    // max pos is used to provide m_states size, which is identical for all instances.
    static int s_maxpos;

    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint> iveShaderProgram;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint> iveShaderProgramEXT;
    static khrapi::Function<Binding, void, gles::GLenum> iveTexture;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLclampf> haFuncQCOM;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint> achShader;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum> inConditionalRenderNV;
    static khrapi::Function<Binding, void, gles::GLuint> inPerfMonitorAMD;
    static khrapi::Function<Binding, void, gles::GLuint> inPerfQueryINTEL;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint> inQuery;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint> inQueryEXT;
    static khrapi::Function<Binding, void, gles::GLenum> inTransformFeedback;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, const gles::GLchar *> dAttribLocation;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint> dBuffer;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLuint> dBufferBase;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLuint, gles::GLintptr, gles::GLsizeiptr> dBufferRange;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint> dFramebuffer;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLint, gles::GLboolean, gles::GLint, gles::GLenum, gles::GLenum> dImageTexture;
    static khrapi::Function<Binding, void, gles::GLuint> dProgramPipeline;
    static khrapi::Function<Binding, void, gles::GLuint> dProgramPipelineEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint> dRenderbuffer;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint> dSampler;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint> dTexture;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint> dTransformFeedback;
    static khrapi::Function<Binding, void, gles::GLuint> dVertexArray;
    static khrapi::Function<Binding, void, gles::GLuint> dVertexArrayOES;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLintptr, gles::GLsizei> dVertexBuffer;
    static khrapi::Function<Binding, void> ndBarrierKHR;
    static khrapi::Function<Binding, void> ndBarrierNV;
    static khrapi::Function<Binding, void, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat> ndColor;
    static khrapi::Function<Binding, void, gles::GLenum> ndEquation;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum> ndEquationSeparate;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLenum> ndEquationSeparateiEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLenum> ndEquationSeparateiOES;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum> ndEquationiEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum> ndEquationiOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum> ndFunc;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLenum, gles::GLenum> ndFuncSeparate;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLenum, gles::GLenum, gles::GLenum> ndFuncSeparateiEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLenum, gles::GLenum, gles::GLenum> ndFuncSeparateiOES;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLenum> ndFunciEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLenum> ndFunciOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint> ndParameteriNV;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::ClearBufferMask, gles::GLenum> tFramebuffer;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLES2bitfield, gles::GLenum> tFramebufferANGLE;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLES2bitfield, gles::GLenum> tFramebufferNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizeiptr, const void *, gles::GLenum> ferData;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizeiptr, const void *, gles::GLES2bitfield> ferStorageEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLintptr, gles::GLsizeiptr, const void *> ferSubData;
    static khrapi::Function<Binding, gles::GLenum, gles::GLenum> ckFramebufferStatus;
    static khrapi::Function<Binding, void, gles::ClearBufferMask> ar;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLfloat, gles::GLint> arBufferfi;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, const gles::GLfloat *> arBufferfv;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, const gles::GLint *> arBufferiv;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, const gles::GLuint *> arBufferuiv;
    static khrapi::Function<Binding, void, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat> arColor;
    static khrapi::Function<Binding, void, gles::GLfloat> arDepthf;
    static khrapi::Function<Binding, void, gles::GLint> arStencil;
    static khrapi::Function<Binding, gles::GLenum, gles::GLsync, gles::SyncObjectMask, gles::GLuint64> entWaitSync;
    static khrapi::Function<Binding, gles::GLenum, gles::GLsync, gles::GLES2bitfield, gles::GLuint64> entWaitSyncAPPLE;
    static khrapi::Function<Binding, void, gles::GLboolean, gles::GLboolean, gles::GLboolean, gles::GLboolean> orMask;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLboolean, gles::GLboolean, gles::GLboolean, gles::GLboolean> orMaskiEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLboolean, gles::GLboolean, gles::GLboolean, gles::GLboolean> orMaskiOES;
    static khrapi::Function<Binding, void, gles::GLuint> pileShader;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLenum, gles::GLsizei, gles::GLsizei, gles::GLint, gles::GLsizei, const void *> pressedTexImage2D;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLenum, gles::GLsizei, gles::GLsizei, gles::GLsizei, gles::GLint, gles::GLsizei, const void *> pressedTexImage3D;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLenum, gles::GLsizei, gles::GLsizei, gles::GLsizei, gles::GLint, gles::GLsizei, const void *> pressedTexImage3DOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLenum, gles::GLsizei, const void *> pressedTexSubImage2D;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLsizei, gles::GLenum, gles::GLsizei, const void *> pressedTexSubImage3D;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLsizei, gles::GLenum, gles::GLsizei, const void *> pressedTexSubImage3DOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLintptr, gles::GLintptr, gles::GLsizeiptr> yBufferSubData;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLintptr, gles::GLintptr, gles::GLsizeiptr> yBufferSubDataNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLuint, gles::GLenum, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLsizei> yImageSubDataEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLuint, gles::GLenum, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLsizei> yImageSubDataOES;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint> yPathNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLenum, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLint> yTexImage2D;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei> yTexSubImage2D;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei> yTexSubImage3D;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei> yTexSubImage3DOES;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLint, gles::GLsizei> yTextureLevelsAPPLE;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLenum, const void *, gles::GLuint, gles::GLenum, gles::GLenum, const gles::GLfloat *> erFillPathInstancedNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum> erFillPathNV;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLenum, const void *, gles::GLuint, gles::GLenum, gles::GLenum, const gles::GLfloat *> erStrokePathInstancedNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum> erStrokePathNV;
    static khrapi::Function<Binding, void, gles::GLboolean> erageMaskNV;
    static khrapi::Function<Binding, void, gles::GLenum> erageModulationNV;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLfloat *> erageModulationTableNV;
    static khrapi::Function<Binding, void, gles::GLenum> erageOperationNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint *> atePerfQueryINTEL;
    static khrapi::Function<Binding, gles::GLuint> ateProgram;
    static khrapi::Function<Binding, gles::GLuint, gles::GLenum> ateShader;
    static khrapi::Function<Binding, gles::GLuint, gles::GLenum, gles::GLsizei, const gles::GLchar *const*> ateShaderProgramv;
    static khrapi::Function<Binding, gles::GLuint, gles::GLenum, gles::GLsizei, const gles::GLchar **> ateShaderProgramvEXT;
    static khrapi::Function<Binding, void, gles::GLenum> lFace;
    static khrapi::Function<Binding, void, gles::GLDEBUGPROCKHR, const void *> ugMessageCallbackKHR;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLenum, gles::GLsizei, const gles::GLuint *, gles::GLboolean> ugMessageControlKHR;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLuint, gles::GLenum, gles::GLsizei, const gles::GLchar *> ugMessageInsertKHR;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLuint *> eteBuffers;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLuint *> eteFencesNV;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLuint *> eteFramebuffers;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei> etePathsNV;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLuint *> etePerfMonitorsAMD;
    static khrapi::Function<Binding, void, gles::GLuint> etePerfQueryINTEL;
    static khrapi::Function<Binding, void, gles::GLuint> eteProgram;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLuint *> eteProgramPipelines;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLuint *> eteProgramPipelinesEXT;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLuint *> eteQueries;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLuint *> eteQueriesEXT;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLuint *> eteRenderbuffers;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLuint *> eteSamplers;
    static khrapi::Function<Binding, void, gles::GLuint> eteShader;
    static khrapi::Function<Binding, void, gles::GLsync> eteSync;
    static khrapi::Function<Binding, void, gles::GLsync> eteSyncAPPLE;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLuint *> eteTextures;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLuint *> eteTransformFeedbacks;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLuint *> eteVertexArrays;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLuint *> eteVertexArraysOES;
    static khrapi::Function<Binding, void, gles::GLenum> thFunc;
    static khrapi::Function<Binding, void, gles::GLboolean> thMask;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, const gles::GLfloat *> thRangeArrayfvNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLfloat, gles::GLfloat> thRangeIndexedfNV;
    static khrapi::Function<Binding, void, gles::GLfloat, gles::GLfloat> thRangef;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint> achShader;
    static khrapi::Function<Binding, void, gles::GLenum> able;
    static khrapi::Function<Binding, void, gles::GLuint> ableDriverControlQCOM;
    static khrapi::Function<Binding, void, gles::GLuint> ableVertexAttribArray;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint> ableiEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint> ableiNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint> ableiOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, const gles::GLenum *> cardFramebufferEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLuint> patchCompute;
    static khrapi::Function<Binding, void, gles::GLintptr> patchComputeIndirect;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLsizei> wArrays;
    static khrapi::Function<Binding, void, gles::GLenum, const void *> wArraysIndirect;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLsizei, gles::GLsizei> wArraysInstanced;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLsizei, gles::GLsizei> wArraysInstancedANGLE;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLuint> wArraysInstancedBaseInstanceEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLsizei, gles::GLsizei> wArraysInstancedEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLsizei, gles::GLsizei> wArraysInstancedNV;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLenum *> wBuffers;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLenum *> wBuffersEXT;
    static khrapi::Function<Binding, void, gles::GLint, const gles::GLenum *, const gles::GLint *> wBuffersIndexedEXT;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLenum *> wBuffersNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, const void *> wElements;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, const void *, gles::GLint> wElementsBaseVertexEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, const void *, gles::GLint> wElementsBaseVertexOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, const void *> wElementsIndirect;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, const void *, gles::GLsizei> wElementsInstanced;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, const void *, gles::GLsizei> wElementsInstancedANGLE;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, const void *, gles::GLsizei, gles::GLuint> wElementsInstancedBaseInstanceEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, const void *, gles::GLsizei, gles::GLint, gles::GLuint> wElementsInstancedBaseVertexBaseInstanceEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, const void *, gles::GLsizei, gles::GLint> wElementsInstancedBaseVertexEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, const void *, gles::GLsizei, gles::GLint> wElementsInstancedBaseVertexOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, const void *, gles::GLsizei> wElementsInstancedEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, const void *, gles::GLsizei> wElementsInstancedNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLuint, gles::GLsizei, gles::GLenum, const void *> wRangeElements;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLuint, gles::GLsizei, gles::GLenum, const void *, gles::GLint> wRangeElementsBaseVertexEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLuint, gles::GLsizei, gles::GLenum, const void *, gles::GLint> wRangeElementsBaseVertexOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLeglImageOES> ImageTargetRenderbufferStorageOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLeglImageOES> ImageTargetTexture2DOES;
    static khrapi::Function<Binding, void, gles::GLenum> ble;
    static khrapi::Function<Binding, void, gles::GLuint> bleDriverControlQCOM;
    static khrapi::Function<Binding, void, gles::GLuint> bleVertexAttribArray;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint> bleiEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint> bleiNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint> bleiOES;
    static khrapi::Function<Binding, void> ConditionalRenderNV;
    static khrapi::Function<Binding, void, gles::GLuint> PerfMonitorAMD;
    static khrapi::Function<Binding, void, gles::GLuint> PerfQueryINTEL;
    static khrapi::Function<Binding, void, gles::GLenum> Query;
    static khrapi::Function<Binding, void, gles::GLenum> QueryEXT;
    static khrapi::Function<Binding, void, gles::GLES2bitfield> TilingQCOM;
    static khrapi::Function<Binding, void> TransformFeedback;
    static khrapi::Function<Binding, void, gles::GLenum, void **> GetBufferPointervQCOM;
    static khrapi::Function<Binding, void, gles::GLuint *, gles::GLint, gles::GLint *> GetBuffersQCOM;
    static khrapi::Function<Binding, void, gles::GLuint *, gles::GLint, gles::GLint *> GetFramebuffersQCOM;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLchar *, gles::GLint *> GetProgramBinarySourceQCOM;
    static khrapi::Function<Binding, void, gles::GLuint *, gles::GLint, gles::GLint *> GetProgramsQCOM;
    static khrapi::Function<Binding, void, gles::GLuint *, gles::GLint, gles::GLint *> GetRenderbuffersQCOM;
    static khrapi::Function<Binding, void, gles::GLuint *, gles::GLint, gles::GLint *> GetShadersQCOM;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint, gles::GLenum, gles::GLint *> GetTexLevelParameterivQCOM;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLsizei, gles::GLenum, gles::GLenum, void *> GetTexSubImageQCOM;
    static khrapi::Function<Binding, void, gles::GLuint *, gles::GLint, gles::GLint *> GetTexturesQCOM;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> IsProgramBinaryQCOM;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLint> TexObjectStateOverrideiQCOM;
    static khrapi::Function<Binding, gles::GLsync, gles::GLenum, gles::UnusedMask> ceSync;
    static khrapi::Function<Binding, gles::GLsync, gles::GLenum, gles::GLES2bitfield> ceSyncAPPLE;
    static khrapi::Function<Binding, void> ish;
    static khrapi::Function<Binding, void, gles::GLuint> ishFenceNV;
    static khrapi::Function<Binding, void> sh;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLintptr, gles::GLsizeiptr> shMappedBufferRange;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLintptr, gles::GLsizeiptr> shMappedBufferRangeEXT;
    static khrapi::Function<Binding, void, gles::GLuint> gmentCoverageColorNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLint> mebufferParameteri;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLenum, gles::GLuint> mebufferRenderbuffer;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLsizei, const gles::GLfloat *> mebufferSampleLocationsfvNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLenum, gles::GLuint, gles::GLint> mebufferTexture2D;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLenum, gles::GLuint, gles::GLint, gles::GLsizei> mebufferTexture2DMultisampleEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLenum, gles::GLuint, gles::GLint, gles::GLsizei> mebufferTexture2DMultisampleIMG;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLenum, gles::GLuint, gles::GLint, gles::GLint> mebufferTexture3DOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLuint, gles::GLint> mebufferTextureEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLuint, gles::GLint, gles::GLint> mebufferTextureLayer;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLuint, gles::GLint, gles::GLint, gles::GLsizei> mebufferTextureMultiviewOVR;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLuint, gles::GLint> mebufferTextureOES;
    static khrapi::Function<Binding, void, gles::GLenum> ntFace;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLuint *> Buffers;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLuint *> FencesNV;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLuint *> Framebuffers;
    static khrapi::Function<Binding, gles::GLuint, gles::GLsizei> PathsNV;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLuint *> PerfMonitorsAMD;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLuint *> ProgramPipelines;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLuint *> ProgramPipelinesEXT;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLuint *> Queries;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLuint *> QueriesEXT;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLuint *> Renderbuffers;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLuint *> Samplers;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLuint *> Textures;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLuint *> TransformFeedbacks;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLuint *> VertexArrays;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLuint *> VertexArraysOES;
    static khrapi::Function<Binding, void, gles::GLenum> erateMipmap;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLint *, gles::GLenum *, gles::GLchar *> ActiveAttrib;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLint *, gles::GLenum *, gles::GLchar *> ActiveUniform;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLchar *> ActiveUniformBlockName;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLenum, gles::GLint *> ActiveUniformBlockiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, const gles::GLuint *, gles::GLenum, gles::GLint *> ActiveUniformsiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLuint *> AttachedShaders;
    static khrapi::Function<Binding, gles::GLint, gles::GLuint, const gles::GLchar *> AttribLocation;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLboolean *> Booleani_v;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLboolean *> Booleanv;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLint64 *> BufferParameteri64v;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLint *> BufferParameteriv;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, void **> BufferPointerv;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, void **> BufferPointervOES;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLfloat *> CoverageModulationTableNV;
    static khrapi::Function<Binding, gles::GLuint, gles::GLuint, gles::GLsizei, gles::GLenum *, gles::GLenum *, gles::GLuint *, gles::GLenum *, gles::GLsizei *, gles::GLchar *> DebugMessageLogKHR;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLchar *> DriverControlStringQCOM;
    static khrapi::Function<Binding, void, gles::GLint *, gles::GLsizei, gles::GLuint *> DriverControlsQCOM;
    static khrapi::Function<Binding, gles::GLenum> Error;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint *> FenceivNV;
    static khrapi::Function<Binding, void, gles::GLuint *> FirstPerfQueryIdINTEL;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLfloat *> Floati_vNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLfloat *> Floatv;
    static khrapi::Function<Binding, gles::GLint, gles::GLuint, const gles::GLchar *> FragDataLocation;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLenum, gles::GLint *> FramebufferAttachmentParameteriv;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLint *> FramebufferParameteriv;
    static khrapi::Function<Binding, gles::GLenum> GraphicsResetStatusEXT;
    static khrapi::Function<Binding, gles::GLenum> GraphicsResetStatusKHR;
    static khrapi::Function<Binding, gles::GLuint64, gles::GLuint, gles::GLint, gles::GLboolean, gles::GLint, gles::GLenum> ImageHandleNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLint64 *> Integer64i_v;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint64 *> Integer64v;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint64 *> Integer64vAPPLE;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLint *> Integeri_v;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLint *> Integeri_vEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint *> Integerv;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei, gles::GLint *> InternalformatSampleivNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLenum, gles::GLsizei, gles::GLint *> Internalformativ;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLfloat *> Multisamplefv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint *> NextPerfQueryIdINTEL;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLchar *> ObjectLabelEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLchar *> ObjectLabelKHR;
    static khrapi::Function<Binding, void, const void *, gles::GLsizei, gles::GLsizei *, gles::GLchar *> ObjectPtrLabelKHR;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLubyte *> PathCommandsNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLfloat *> PathCoordsNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLfloat *> PathDashArrayNV;
    static khrapi::Function<Binding, gles::GLfloat, gles::GLuint, gles::GLsizei, gles::GLsizei> PathLengthNV;
    static khrapi::Function<Binding, void, gles::PathRenderingMaskNV, gles::GLuint, gles::GLsizei, gles::GLsizei, gles::GLfloat *> PathMetricRangeNV;
    static khrapi::Function<Binding, void, gles::PathRenderingMaskNV, gles::GLsizei, gles::GLenum, const void *, gles::GLuint, gles::GLsizei, gles::GLfloat *> PathMetricsNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLfloat *> PathParameterfvNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint *> PathParameterivNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, const void *, gles::GLuint, gles::GLfloat, gles::GLfloat, gles::GLenum, gles::GLfloat *> PathSpacingNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLuint, gles::GLchar *, gles::GLuint, gles::GLchar *, gles::GLuint *, gles::GLuint *, gles::GLuint *, gles::GLuint *, gles::GLuint64 *> PerfCounterInfoINTEL;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLsizei, gles::GLuint *, gles::GLint *> PerfMonitorCounterDataAMD;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLenum, void *> PerfMonitorCounterInfoAMD;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLchar *> PerfMonitorCounterStringAMD;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint *, gles::GLint *, gles::GLsizei, gles::GLuint *> PerfMonitorCountersAMD;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLchar *> PerfMonitorGroupStringAMD;
    static khrapi::Function<Binding, void, gles::GLint *, gles::GLsizei, gles::GLuint *> PerfMonitorGroupsAMD;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLsizei, gles::GLvoid *, gles::GLuint *> PerfQueryDataINTEL;
    static khrapi::Function<Binding, void, gles::GLchar *, gles::GLuint *> PerfQueryIdByNameINTEL;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLchar *, gles::GLuint *, gles::GLuint *, gles::GLuint *, gles::GLuint *> PerfQueryInfoINTEL;
    static khrapi::Function<Binding, void, gles::GLenum, void **> PointervKHR;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLenum *, void *> ProgramBinary;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLenum *, void *> ProgramBinaryOES;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLchar *> ProgramInfoLog;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLenum, gles::GLint *> ProgramInterfaceiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLchar *> ProgramPipelineInfoLog;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLchar *> ProgramPipelineInfoLogEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint *> ProgramPipelineiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint *> ProgramPipelineivEXT;
    static khrapi::Function<Binding, gles::GLuint, gles::GLuint, gles::GLenum, const gles::GLchar *> ProgramResourceIndex;
    static khrapi::Function<Binding, gles::GLint, gles::GLuint, gles::GLenum, const gles::GLchar *> ProgramResourceLocation;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLchar *> ProgramResourceName;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLuint, gles::GLsizei, const gles::GLenum *, gles::GLsizei, gles::GLsizei *, gles::GLfloat *> ProgramResourcefvNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLuint, gles::GLsizei, const gles::GLenum *, gles::GLsizei, gles::GLsizei *, gles::GLint *> ProgramResourceiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint *> Programiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint64 *> QueryObjecti64vEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint *> QueryObjectivEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLuint64 *> QueryObjectui64vEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLuint *> QueryObjectuiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLuint *> QueryObjectuivEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLint *> Queryiv;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLint *> QueryivEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLint *> RenderbufferParameteriv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint *> SamplerParameterIivEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint *> SamplerParameterIivOES;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLuint *> SamplerParameterIuivEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLuint *> SamplerParameterIuivOES;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLfloat *> SamplerParameterfv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint *> SamplerParameteriv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLchar *> ShaderInfoLog;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLint *, gles::GLint *> ShaderPrecisionFormat;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLchar *> ShaderSource;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint *> Shaderiv;
    static khrapi::Function<Binding, const gles::GLubyte *, gles::GLenum> String;
    static khrapi::Function<Binding, const gles::GLubyte *, gles::GLenum, gles::GLuint> Stringi;
    static khrapi::Function<Binding, void, gles::GLsync, gles::GLenum, gles::GLsizei, gles::GLsizei *, gles::GLint *> Synciv;
    static khrapi::Function<Binding, void, gles::GLsync, gles::GLenum, gles::GLsizei, gles::GLsizei *, gles::GLint *> SyncivAPPLE;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLenum, gles::GLfloat *> TexLevelParameterfv;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLenum, gles::GLint *> TexLevelParameteriv;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLint *> TexParameterIivEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLint *> TexParameterIivOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLuint *> TexParameterIuivEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLuint *> TexParameterIuivOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLfloat *> TexParameterfv;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLint *> TexParameteriv;
    static khrapi::Function<Binding, gles::GLuint64, gles::GLuint> TextureHandleNV;
    static khrapi::Function<Binding, gles::GLuint64, gles::GLuint, gles::GLuint> TextureSamplerHandleNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLsizei *, gles::GLenum *, gles::GLchar *> TransformFeedbackVarying;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, gles::GLsizei *, gles::GLchar *> TranslatedShaderSourceANGLE;
    static khrapi::Function<Binding, gles::GLuint, gles::GLuint, const gles::GLchar *> UniformBlockIndex;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, const gles::GLchar *const*, gles::GLuint *> UniformIndices;
    static khrapi::Function<Binding, gles::GLint, gles::GLuint, const gles::GLchar *> UniformLocation;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLfloat *> Uniformfv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLint *> Uniformiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLuint *> Uniformuiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint *> VertexAttribIiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLuint *> VertexAttribIuiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, void **> VertexAttribPointerv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLfloat *> VertexAttribfv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint *> VertexAttribiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLfloat *> nUniformfvEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLfloat *> nUniformfvKHR;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLint *> nUniformivEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLint *> nUniformivKHR;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLuint *> nUniformuivKHR;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum> t;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLchar *> ertEventMarkerEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLuint, gles::GLfloat> erpolatePathsNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, const gles::GLenum *> alidateFramebuffer;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, const gles::GLenum *, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei> alidateSubFramebuffer;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> uffer;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLenum> nabled;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLenum, gles::GLuint> nablediEXT;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLenum, gles::GLuint> nablediNV;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLenum, gles::GLuint> nablediOES;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> enceNV;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> ramebuffer;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint64> mageHandleResidentNV;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> athNV;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint, gles::GLuint, gles::GLfloat, gles::GLfloat> ointInFillPathNV;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint, gles::GLfloat, gles::GLfloat> ointInStrokePathNV;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> rogram;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> rogramPipeline;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> rogramPipelineEXT;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> uery;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> ueryEXT;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> enderbuffer;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> ampler;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> hader;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLsync> ync;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLsync> yncAPPLE;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> exture;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint64> extureHandleResidentNV;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> ransformFeedback;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> ertexArray;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> ertexArrayOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLsizei, const gles::GLchar *> elObjectEXT;
    static khrapi::Function<Binding, void, gles::GLfloat> eWidth;
    static khrapi::Function<Binding, void, gles::GLuint> kProgram;
    static khrapi::Function<Binding, void, gles::GLuint64> eImageHandleNonResidentNV;
    static khrapi::Function<Binding, void, gles::GLuint64, gles::GLenum> eImageHandleResidentNV;
    static khrapi::Function<Binding, void, gles::GLuint64> eTextureHandleNonResidentNV;
    static khrapi::Function<Binding, void, gles::GLuint64> eTextureHandleResidentNV;
    static khrapi::Function<Binding, void *, gles::GLenum, gles::GLenum> BufferOES;
    static khrapi::Function<Binding, void *, gles::GLenum, gles::GLintptr, gles::GLsizeiptr, gles::BufferAccessMask> BufferRange;
    static khrapi::Function<Binding, void *, gles::GLenum, gles::GLintptr, gles::GLsizeiptr, gles::GLES2bitfield> BufferRangeEXT;
    static khrapi::Function<Binding, void, gles::GLenum, const gles::GLfloat *> rixLoad3x2fNV;
    static khrapi::Function<Binding, void, gles::GLenum, const gles::GLfloat *> rixLoad3x3fNV;
    static khrapi::Function<Binding, void, gles::GLenum, const gles::GLfloat *> rixLoadTranspose3x3fNV;
    static khrapi::Function<Binding, void, gles::GLenum, const gles::GLfloat *> rixMult3x2fNV;
    static khrapi::Function<Binding, void, gles::GLenum, const gles::GLfloat *> rixMult3x3fNV;
    static khrapi::Function<Binding, void, gles::GLenum, const gles::GLfloat *> rixMultTranspose3x3fNV;
    static khrapi::Function<Binding, void, gles::MemoryBarrierMask> oryBarrier;
    static khrapi::Function<Binding, void, gles::MemoryBarrierMask> oryBarrierByRegion;
    static khrapi::Function<Binding, void, gles::GLfloat> SampleShadingOES;
    static khrapi::Function<Binding, void, gles::GLenum, const gles::GLint *, const gles::GLsizei *, gles::GLsizei> tiDrawArraysEXT;
    static khrapi::Function<Binding, void, gles::GLenum, const void *, gles::GLsizei, gles::GLsizei> tiDrawArraysIndirectEXT;
    static khrapi::Function<Binding, void, gles::GLenum, const gles::GLsizei *, gles::GLenum, const void *const*, gles::GLsizei, const gles::GLint *> tiDrawElementsBaseVertexEXT;
    static khrapi::Function<Binding, void, gles::GLenum, const gles::GLsizei *, gles::GLenum, const void *const*, gles::GLsizei, const gles::GLint *> tiDrawElementsBaseVertexOES;
    static khrapi::Function<Binding, void, gles::GLenum, const gles::GLsizei *, gles::GLenum, const void *const*, gles::GLsizei> tiDrawElementsEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, const void *, gles::GLsizei, gles::GLsizei> tiDrawElementsIndirectEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLsizei, const gles::GLfloat *> edFramebufferSampleLocationsfvNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLsizei, const gles::GLchar *> ectLabelKHR;
    static khrapi::Function<Binding, void, const void *, gles::GLsizei, const gles::GLchar *> ectPtrLabelKHR;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint> chParameteriEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint> chParameteriOES;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, const gles::GLubyte *, gles::GLsizei, gles::GLenum, const void *> hCommandsNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, gles::GLenum, const void *> hCoordsNV;
    static khrapi::Function<Binding, void, gles::GLenum> hCoverDepthFuncNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, const gles::GLfloat *> hDashArrayNV;
    static khrapi::Function<Binding, gles::GLenum, gles::GLuint, gles::GLenum, const void *, gles::PathFontStyle, gles::GLuint, gles::GLsizei, gles::GLuint, gles::GLfloat> hGlyphIndexArrayNV;
    static khrapi::Function<Binding, gles::GLenum, gles::GLenum, const void *, gles::PathFontStyle, gles::GLuint, gles::GLfloat, gles::GLuint_array_2> hGlyphIndexRangeNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, const void *, gles::PathFontStyle, gles::GLuint, gles::GLsizei, gles::GLenum, gles::GLuint, gles::GLfloat> hGlyphRangeNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, const void *, gles::PathFontStyle, gles::GLsizei, gles::GLenum, const void *, gles::GLenum, gles::GLuint, gles::GLfloat> hGlyphsNV;
    static khrapi::Function<Binding, gles::GLenum, gles::GLuint, gles::GLenum, gles::GLsizeiptr, const void *, gles::GLsizei, gles::GLuint, gles::GLsizei, gles::GLuint, gles::GLfloat> hMemoryGlyphIndexArrayNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLfloat> hParameterfNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, const gles::GLfloat *> hParameterfvNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint> hParameteriNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, const gles::GLint *> hParameterivNV;
    static khrapi::Function<Binding, void, gles::GLfloat, gles::GLfloat> hStencilDepthOffsetNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLuint> hStencilFuncNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLsizei, const void *> hStringNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, gles::GLsizei, gles::GLsizei, const gles::GLubyte *, gles::GLsizei, gles::GLenum, const void *> hSubCommandsNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, gles::GLsizei, gles::GLenum, const void *> hSubCoordsNV;
    static khrapi::Function<Binding, void> seTransformFeedback;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint> elStorei;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint, gles::GLsizei, gles::GLsizei, gles::GLfloat, gles::GLfloat *, gles::GLfloat *, gles::GLfloat *, gles::GLfloat *> ntAlongPathNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum> ygonModeNV;
    static khrapi::Function<Binding, void, gles::GLfloat, gles::GLfloat> ygonOffset;
    static khrapi::Function<Binding, void> DebugGroupKHR;
    static khrapi::Function<Binding, void> GroupMarkerEXT;
    static khrapi::Function<Binding, void, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat> mitiveBoundingBoxEXT;
    static khrapi::Function<Binding, void, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat> mitiveBoundingBoxOES;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, const void *, gles::GLsizei> gramBinary;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, const void *, gles::GLint> gramBinaryOES;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint> gramParameteri;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint> gramParameteriEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLenum, gles::GLint, const gles::GLfloat *> gramPathFragmentInputGenNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLfloat> gramUniform1f;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLfloat> gramUniform1fEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLfloat *> gramUniform1fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLfloat *> gramUniform1fvEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLint> gramUniform1i;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLint> gramUniform1iEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLint *> gramUniform1iv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLint *> gramUniform1ivEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLuint> gramUniform1ui;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLuint> gramUniform1uiEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLuint *> gramUniform1uiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLuint *> gramUniform1uivEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLfloat, gles::GLfloat> gramUniform2f;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLfloat, gles::GLfloat> gramUniform2fEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLfloat *> gramUniform2fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLfloat *> gramUniform2fvEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLint, gles::GLint> gramUniform2i;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLint, gles::GLint> gramUniform2iEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLint *> gramUniform2iv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLint *> gramUniform2ivEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLuint, gles::GLuint> gramUniform2ui;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLuint, gles::GLuint> gramUniform2uiEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLuint *> gramUniform2uiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLuint *> gramUniform2uivEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLfloat, gles::GLfloat, gles::GLfloat> gramUniform3f;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLfloat, gles::GLfloat, gles::GLfloat> gramUniform3fEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLfloat *> gramUniform3fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLfloat *> gramUniform3fvEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLint, gles::GLint, gles::GLint> gramUniform3i;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLint, gles::GLint, gles::GLint> gramUniform3iEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLint *> gramUniform3iv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLint *> gramUniform3ivEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLuint, gles::GLuint, gles::GLuint> gramUniform3ui;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLuint, gles::GLuint, gles::GLuint> gramUniform3uiEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLuint *> gramUniform3uiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLuint *> gramUniform3uivEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat> gramUniform4f;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat> gramUniform4fEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLfloat *> gramUniform4fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLfloat *> gramUniform4fvEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint> gramUniform4i;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint> gramUniform4iEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLint *> gramUniform4iv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLint *> gramUniform4ivEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLuint, gles::GLuint, gles::GLuint, gles::GLuint> gramUniform4ui;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLuint, gles::GLuint, gles::GLuint, gles::GLuint> gramUniform4uiEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLuint *> gramUniform4uiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLuint *> gramUniform4uivEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLuint64> gramUniformHandleui64NV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, const gles::GLuint64 *> gramUniformHandleui64vNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> gramUniformMatrix2fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> gramUniformMatrix2fvEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> gramUniformMatrix2x3fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> gramUniformMatrix2x3fvEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> gramUniformMatrix2x4fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> gramUniformMatrix2x4fvEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> gramUniformMatrix3fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> gramUniformMatrix3fvEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> gramUniformMatrix3x2fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> gramUniformMatrix3x2fvEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> gramUniformMatrix3x4fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> gramUniformMatrix3x4fvEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> gramUniformMatrix4fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> gramUniformMatrix4fvEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> gramUniformMatrix4x2fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> gramUniformMatrix4x2fvEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> gramUniformMatrix4x3fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> gramUniformMatrix4x3fvEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint, gles::GLsizei, const gles::GLchar *> hDebugGroupKHR;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLchar *> hGroupMarkerEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum> ryCounterEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLboolean> terSamplesEXT;
    static khrapi::Function<Binding, void, gles::GLenum> dBuffer;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint> dBufferIndexedEXT;
    static khrapi::Function<Binding, void, gles::GLenum> dBufferNV;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLenum, gles::GLenum, void *> dPixels;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLenum, gles::GLenum, gles::GLsizei, void *> dnPixelsEXT;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLenum, gles::GLenum, gles::GLsizei, void *> dnPixelsKHR;
    static khrapi::Function<Binding, void> easeShaderCompiler;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLsizei, gles::GLsizei> derbufferStorage;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei, gles::GLsizei> derbufferStorageMultisample;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei, gles::GLsizei> derbufferStorageMultisampleANGLE;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei, gles::GLsizei> derbufferStorageMultisampleAPPLE;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei, gles::GLsizei> derbufferStorageMultisampleEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei, gles::GLsizei> derbufferStorageMultisampleIMG;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei, gles::GLsizei> derbufferStorageMultisampleNV;
    static khrapi::Function<Binding, void> olveDepthValuesNV;
    static khrapi::Function<Binding, void> olveMultisampleFramebufferAPPLE;
    static khrapi::Function<Binding, void> umeTransformFeedback;
    static khrapi::Function<Binding, void, gles::GLfloat, gles::GLboolean> pleCoverage;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLES2bitfield> pleMaski;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, const gles::GLint *> plerParameterIivEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, const gles::GLint *> plerParameterIivOES;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, const gles::GLuint *> plerParameterIuivEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, const gles::GLuint *> plerParameterIuivOES;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLfloat> plerParameterf;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, const gles::GLfloat *> plerParameterfv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLint> plerParameteri;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, const gles::GLint *> plerParameteriv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei> ssor;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, const gles::GLint *> ssorArrayvNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei> ssorIndexedNV;
    static khrapi::Function<Binding, void, gles::GLuint, const gles::GLint *> ssorIndexedvNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLboolean, gles::GLuint, gles::GLint, gles::GLuint *> ectPerfMonitorCountersAMD;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum> FenceNV;
    static khrapi::Function<Binding, void, gles::GLsizei, const gles::GLuint *, gles::GLenum, const void *, gles::GLsizei> derBinary;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, const gles::GLchar *const*, const gles::GLint *> derSource;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLuint, gles::GLuint, gles::GLES2bitfield> rtTilingQCOM;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLenum, const void *, gles::GLuint, gles::GLenum, gles::GLuint, gles::GLenum, const gles::GLfloat *> ncilFillPathInstancedNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLuint> ncilFillPathNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLuint> ncilFunc;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLint, gles::GLuint> ncilFuncSeparate;
    static khrapi::Function<Binding, void, gles::GLuint> ncilMask;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLuint> ncilMaskSeparate;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLenum> ncilOp;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLenum, gles::GLenum> ncilOpSeparate;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLenum, const void *, gles::GLuint, gles::GLint, gles::GLuint, gles::GLenum, const gles::GLfloat *> ncilStrokePathInstancedNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLuint> ncilStrokePathNV;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLenum, const void *, gles::GLuint, gles::GLenum, gles::GLuint, gles::GLenum, gles::GLenum, const gles::GLfloat *> ncilThenCoverFillPathInstancedNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLuint, gles::GLenum> ncilThenCoverFillPathNV;
    static khrapi::Function<Binding, void, gles::GLsizei, gles::GLenum, const void *, gles::GLuint, gles::GLint, gles::GLuint, gles::GLenum, gles::GLenum, const gles::GLfloat *> ncilThenCoverStrokePathInstancedNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLuint, gles::GLenum> ncilThenCoverStrokePathNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint> pixelPrecisionBiasNV;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLuint> tFenceNV;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLuint> BufferEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLuint> BufferOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLuint, gles::GLintptr, gles::GLsizeiptr> BufferRangeEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLuint, gles::GLintptr, gles::GLsizeiptr> BufferRangeOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLint, gles::GLenum, gles::GLenum, const void *> Image2D;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLsizei, gles::GLint, gles::GLenum, gles::GLenum, const void *> Image3D;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLenum, gles::GLsizei, gles::GLsizei, gles::GLsizei, gles::GLint, gles::GLenum, gles::GLenum, const void *> Image3DOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLsizei, gles::GLboolean> PageCommitmentARB;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, const gles::GLint *> ParameterIivEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, const gles::GLint *> ParameterIivOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, const gles::GLuint *> ParameterIuivEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, const gles::GLuint *> ParameterIuivOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLfloat> Parameterf;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, const gles::GLfloat *> Parameterfv;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, gles::GLint> Parameteri;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLenum, const gles::GLint *> Parameteriv;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei> Storage1DEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei, gles::GLsizei> Storage2D;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei, gles::GLsizei> Storage2DEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei, gles::GLsizei, gles::GLboolean> Storage2DMultisample;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei, gles::GLsizei, gles::GLsizei> Storage3D;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei, gles::GLsizei, gles::GLsizei> Storage3DEXT;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei, gles::GLsizei, gles::GLsizei, gles::GLboolean> Storage3DMultisampleOES;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLenum, gles::GLenum, const void *> SubImage2D;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLsizei, gles::GLenum, gles::GLenum, const void *> SubImage3D;
    static khrapi::Function<Binding, void, gles::GLenum, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei, gles::GLsizei, gles::GLenum, gles::GLenum, const void *> SubImage3DOES;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei> tureStorage1DEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei, gles::GLsizei> tureStorage2DEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLsizei, gles::GLenum, gles::GLsizei, gles::GLsizei, gles::GLsizei> tureStorage3DEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLuint, gles::GLenum, gles::GLuint, gles::GLuint, gles::GLuint, gles::GLuint> tureViewEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLenum, gles::GLuint, gles::GLenum, gles::GLuint, gles::GLuint, gles::GLuint, gles::GLuint> tureViewOES;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, const gles::GLchar *const*, gles::GLenum> nsformFeedbackVaryings;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLenum, const gles::GLfloat *> nsformPathNV;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLfloat> form1f;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, const gles::GLfloat *> form1fv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLint> form1i;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, const gles::GLint *> form1iv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLuint> form1ui;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, const gles::GLuint *> form1uiv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLfloat, gles::GLfloat> form2f;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, const gles::GLfloat *> form2fv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLint, gles::GLint> form2i;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, const gles::GLint *> form2iv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLuint, gles::GLuint> form2ui;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, const gles::GLuint *> form2uiv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLfloat, gles::GLfloat, gles::GLfloat> form3f;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, const gles::GLfloat *> form3fv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLint, gles::GLint, gles::GLint> form3i;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, const gles::GLint *> form3iv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLuint, gles::GLuint, gles::GLuint> form3ui;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, const gles::GLuint *> form3uiv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat> form4f;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, const gles::GLfloat *> form4fv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLint, gles::GLint, gles::GLint, gles::GLint> form4i;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, const gles::GLint *> form4iv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLuint, gles::GLuint, gles::GLuint, gles::GLuint> form4ui;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, const gles::GLuint *> form4uiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLuint> formBlockBinding;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLuint64> formHandleui64NV;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, const gles::GLuint64 *> formHandleui64vNV;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> formMatrix2fv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> formMatrix2x3fv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> formMatrix2x3fvNV;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> formMatrix2x4fv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> formMatrix2x4fvNV;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> formMatrix3fv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> formMatrix3x2fv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> formMatrix3x2fvNV;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> formMatrix3x4fv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> formMatrix3x4fvNV;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> formMatrix4fv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> formMatrix4x2fv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> formMatrix4x2fvNV;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> formMatrix4x3fv;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLsizei, gles::GLboolean, const gles::GLfloat *> formMatrix4x3fvNV;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLenum> apBuffer;
    static khrapi::Function<Binding, gles::GLboolean, gles::GLenum> apBufferOES;
    static khrapi::Function<Binding, void, gles::GLuint> Program;
    static khrapi::Function<Binding, void, gles::GLuint, gles::UseProgramStageMask, gles::GLuint> ProgramStages;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLES2bitfield, gles::GLuint> ProgramStagesEXT;
    static khrapi::Function<Binding, void, gles::GLuint> idateProgram;
    static khrapi::Function<Binding, void, gles::GLuint> idateProgramPipeline;
    static khrapi::Function<Binding, void, gles::GLuint> idateProgramPipelineEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLfloat> texAttrib1f;
    static khrapi::Function<Binding, void, gles::GLuint, const gles::GLfloat *> texAttrib1fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLfloat, gles::GLfloat> texAttrib2f;
    static khrapi::Function<Binding, void, gles::GLuint, const gles::GLfloat *> texAttrib2fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLfloat, gles::GLfloat, gles::GLfloat> texAttrib3f;
    static khrapi::Function<Binding, void, gles::GLuint, const gles::GLfloat *> texAttrib3fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat> texAttrib4f;
    static khrapi::Function<Binding, void, gles::GLuint, const gles::GLfloat *> texAttrib4fv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint> texAttribBinding;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint> texAttribDivisor;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint> texAttribDivisorANGLE;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint> texAttribDivisorEXT;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint> texAttribDivisorNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLenum, gles::GLboolean, gles::GLuint> texAttribFormat;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLint, gles::GLint, gles::GLint> texAttribI4i;
    static khrapi::Function<Binding, void, gles::GLuint, const gles::GLint *> texAttribI4iv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint, gles::GLuint, gles::GLuint, gles::GLuint> texAttribI4ui;
    static khrapi::Function<Binding, void, gles::GLuint, const gles::GLuint *> texAttribI4uiv;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLenum, gles::GLuint> texAttribIFormat;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLenum, gles::GLsizei, const void *> texAttribIPointer;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLint, gles::GLenum, gles::GLboolean, gles::GLsizei, const void *> texAttribPointer;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLuint> texBindingDivisor;
    static khrapi::Function<Binding, void, gles::GLint, gles::GLint, gles::GLsizei, gles::GLsizei> wport;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, const gles::GLfloat *> wportArrayvNV;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLfloat, gles::GLfloat, gles::GLfloat, gles::GLfloat> wportIndexedfNV;
    static khrapi::Function<Binding, void, gles::GLuint, const gles::GLfloat *> wportIndexedfvNV;
    static khrapi::Function<Binding, void, gles::GLsync, gles::UnusedMask, gles::GLuint64> tSync;
    static khrapi::Function<Binding, void, gles::GLsync, gles::GLES2bitfield, gles::GLuint64> tSyncAPPLE;
    static khrapi::Function<Binding, void, gles::GLuint, gles::GLsizei, const gles::GLuint *, const gles::GLfloat *> ghtPathsNV;

protected:
	static const array_t s_functions;
	static std::vector<khrapi::AbstractFunction *> s_additionalFunctions;
	static std::vector<ContextSwitchCallback> s_callbacks;
};

} // namespace glesbinding
