#pragma once

#include <array>
#include <mutex>
#include <unordered_map>

#include <khrapi/Binding.h>

#include <glpbinding/glpbinding_api.h>

#include <glpbinding/glp/types.h>

#include <glpbinding/ContextHandle.h>
#include <glpbinding/ProcAddress.h>


namespace glpbinding
{

class GLPBINDING_API Binding : public khrapi::Binding<Binding, ContextHandle, getProcAddress, getCurrentContext>
{
public:
    using array_t = std::array<khrapi::AbstractFunction *, 719>;
    
    static const array_t s_functions;
    
    static const array_t & functions();
    
    static ContextHandle & context();
    static int & pos();
    static std::recursive_mutex & mutex();
    static std::unordered_map<ContextHandle, int> & bindings();

    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint> ActiveShaderProgram;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint> ActiveShaderProgramEXT;
    static khrapi::Function<Binding, void, glp::GLenum> ActiveTexture;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLclampf> AlphaFuncQCOM;
    static khrapi::Function<Binding, void> ApplyFramebufferAttachmentCMAAINTEL;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint> AttachShader;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum> BeginConditionalRenderNV;
    static khrapi::Function<Binding, void, glp::GLuint> BeginPerfMonitorAMD;
    static khrapi::Function<Binding, void, glp::GLuint> BeginPerfQueryINTEL;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint> BeginQuery;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint> BeginQueryEXT;
    static khrapi::Function<Binding, void, glp::GLenum> BeginTransformFeedback;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint, const glp::GLchar *> BindAttribLocation;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint> BindBuffer;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint, glp::GLuint> BindBufferBase;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint, glp::GLuint, glp::GLintptr, glp::GLsizeiptr> BindBufferRange;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint> BindFramebuffer;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint, glp::GLint, glp::GLboolean, glp::GLint, glp::GLenum, glp::GLenum> BindImageTexture;
    static khrapi::Function<Binding, void, glp::GLuint> BindProgramPipeline;
    static khrapi::Function<Binding, void, glp::GLuint> BindProgramPipelineEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint> BindRenderbuffer;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint> BindSampler;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint> BindTexture;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint> BindTransformFeedback;
    static khrapi::Function<Binding, void, glp::GLuint> BindVertexArray;
    static khrapi::Function<Binding, void, glp::GLuint> BindVertexArrayOES;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint, glp::GLintptr, glp::GLsizei> BindVertexBuffer;
    static khrapi::Function<Binding, void> BlendBarrier;
    static khrapi::Function<Binding, void> BlendBarrierKHR;
    static khrapi::Function<Binding, void> BlendBarrierNV;
    static khrapi::Function<Binding, void, glp::GLfloat, glp::GLfloat, glp::GLfloat, glp::GLfloat> BlendColor;
    static khrapi::Function<Binding, void, glp::GLenum> BlendEquation;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum> BlendEquationSeparate;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLenum> BlendEquationSeparatei;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLenum> BlendEquationSeparateiEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLenum> BlendEquationSeparateiOES;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum> BlendEquationi;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum> BlendEquationiEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum> BlendEquationiOES;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum> BlendFunc;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLenum, glp::GLenum> BlendFuncSeparate;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLenum, glp::GLenum, glp::GLenum> BlendFuncSeparatei;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLenum, glp::GLenum, glp::GLenum> BlendFuncSeparateiEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLenum, glp::GLenum, glp::GLenum> BlendFuncSeparateiOES;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLenum> BlendFunci;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLenum> BlendFunciEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLenum> BlendFunciOES;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint> BlendParameteriNV;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::ClearBufferMask, glp::GLenum> BlitFramebuffer;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLbitfield, glp::GLenum> BlitFramebufferANGLE;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLbitfield, glp::GLenum> BlitFramebufferNV;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizeiptr, const void *, glp::GLenum> BufferData;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizeiptr, const void *, glp::GLbitfield> BufferStorageEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLintptr, glp::GLsizeiptr, const void *> BufferSubData;
    static khrapi::Function<Binding, glp::GLenum, glp::GLenum> CheckFramebufferStatus;
    static khrapi::Function<Binding, void, glp::ClearBufferMask> Clear;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, glp::GLfloat, glp::GLint> ClearBufferfi;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, const glp::GLfloat *> ClearBufferfv;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, const glp::GLint *> ClearBufferiv;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, const glp::GLuint *> ClearBufferuiv;
    static khrapi::Function<Binding, void, glp::GLfloat, glp::GLfloat, glp::GLfloat, glp::GLfloat> ClearColor;
    static khrapi::Function<Binding, void, glp::GLfloat> ClearDepthf;
    static khrapi::Function<Binding, void, glp::GLint> ClearStencil;
    static khrapi::Function<Binding, glp::GLenum, glp::GLsync, glp::SyncObjectMask, glp::GLuint64> ClientWaitSync;
    static khrapi::Function<Binding, glp::GLenum, glp::GLsync, glp::GLbitfield, glp::GLuint64> ClientWaitSyncAPPLE;
    static khrapi::Function<Binding, void, glp::GLboolean, glp::GLboolean, glp::GLboolean, glp::GLboolean> ColorMask;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLboolean, glp::GLboolean, glp::GLboolean, glp::GLboolean> ColorMaski;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLboolean, glp::GLboolean, glp::GLboolean, glp::GLboolean> ColorMaskiEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLboolean, glp::GLboolean, glp::GLboolean, glp::GLboolean> ColorMaskiOES;
    static khrapi::Function<Binding, void, glp::GLuint> CompileShader;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, glp::GLenum, glp::GLsizei, glp::GLsizei, glp::GLint, glp::GLsizei, const void *> CompressedTexImage2D;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, glp::GLenum, glp::GLsizei, glp::GLsizei, glp::GLsizei, glp::GLint, glp::GLsizei, const void *> CompressedTexImage3D;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, glp::GLenum, glp::GLsizei, glp::GLsizei, glp::GLsizei, glp::GLint, glp::GLsizei, const void *> CompressedTexImage3DOES;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, glp::GLint, glp::GLint, glp::GLsizei, glp::GLsizei, glp::GLenum, glp::GLsizei, const void *> CompressedTexSubImage2D;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLsizei, glp::GLsizei, glp::GLsizei, glp::GLenum, glp::GLsizei, const void *> CompressedTexSubImage3D;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLsizei, glp::GLsizei, glp::GLsizei, glp::GLenum, glp::GLsizei, const void *> CompressedTexSubImage3DOES;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLintptr, glp::GLintptr, glp::GLsizeiptr> CopyBufferSubData;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLintptr, glp::GLintptr, glp::GLsizeiptr> CopyBufferSubDataNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLuint, glp::GLenum, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLsizei, glp::GLsizei, glp::GLsizei> CopyImageSubData;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLuint, glp::GLenum, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLsizei, glp::GLsizei, glp::GLsizei> CopyImageSubDataEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLuint, glp::GLenum, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLsizei, glp::GLsizei, glp::GLsizei> CopyImageSubDataOES;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint> CopyPathNV;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, glp::GLenum, glp::GLint, glp::GLint, glp::GLsizei, glp::GLsizei, glp::GLint> CopyTexImage2D;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLsizei, glp::GLsizei> CopyTexSubImage2D;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLsizei, glp::GLsizei> CopyTexSubImage3D;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLsizei, glp::GLsizei> CopyTexSubImage3DOES;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint, glp::GLint, glp::GLsizei> CopyTextureLevelsAPPLE;
    static khrapi::Function<Binding, void, glp::GLsizei, glp::GLenum, const void *, glp::GLuint, glp::GLenum, glp::GLenum, const glp::GLfloat *> CoverFillPathInstancedNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum> CoverFillPathNV;
    static khrapi::Function<Binding, void, glp::GLsizei, glp::GLenum, const void *, glp::GLuint, glp::GLenum, glp::GLenum, const glp::GLfloat *> CoverStrokePathInstancedNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum> CoverStrokePathNV;
    static khrapi::Function<Binding, void, glp::GLboolean> CoverageMaskNV;
    static khrapi::Function<Binding, void, glp::GLenum> CoverageModulationNV;
    static khrapi::Function<Binding, void, glp::GLsizei, const glp::GLfloat *> CoverageModulationTableNV;
    static khrapi::Function<Binding, void, glp::GLenum> CoverageOperationNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint *> CreatePerfQueryINTEL;
    static khrapi::Function<Binding, glp::GLuint> CreateProgram;
    static khrapi::Function<Binding, glp::GLuint, glp::GLenum> CreateShader;
    static khrapi::Function<Binding, glp::GLuint, glp::GLenum, glp::GLsizei, const glp::GLchar *const*> CreateShaderProgramv;
    static khrapi::Function<Binding, glp::GLuint, glp::GLenum, glp::GLsizei, const glp::GLchar **> CreateShaderProgramvEXT;
    static khrapi::Function<Binding, void, glp::GLenum> CullFace;
    static khrapi::Function<Binding, void, glp::GLDEBUGPROC, const void *> DebugMessageCallback;
    static khrapi::Function<Binding, void, glp::GLDEBUGPROCKHR, const void *> DebugMessageCallbackKHR;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLenum, glp::GLsizei, const glp::GLuint *, glp::GLboolean> DebugMessageControl;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLenum, glp::GLsizei, const glp::GLuint *, glp::GLboolean> DebugMessageControlKHR;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLuint, glp::GLenum, glp::GLsizei, const glp::GLchar *> DebugMessageInsert;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLuint, glp::GLenum, glp::GLsizei, const glp::GLchar *> DebugMessageInsertKHR;
    static khrapi::Function<Binding, void, glp::GLsizei, const glp::GLuint *> DeleteBuffers;
    static khrapi::Function<Binding, void, glp::GLsizei, const glp::GLuint *> DeleteFencesNV;
    static khrapi::Function<Binding, void, glp::GLsizei, const glp::GLuint *> DeleteFramebuffers;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLsizei> DeletePathsNV;
    static khrapi::Function<Binding, void, glp::GLsizei, glp::GLuint *> DeletePerfMonitorsAMD;
    static khrapi::Function<Binding, void, glp::GLuint> DeletePerfQueryINTEL;
    static khrapi::Function<Binding, void, glp::GLuint> DeleteProgram;
    static khrapi::Function<Binding, void, glp::GLsizei, const glp::GLuint *> DeleteProgramPipelines;
    static khrapi::Function<Binding, void, glp::GLsizei, const glp::GLuint *> DeleteProgramPipelinesEXT;
    static khrapi::Function<Binding, void, glp::GLsizei, const glp::GLuint *> DeleteQueries;
    static khrapi::Function<Binding, void, glp::GLsizei, const glp::GLuint *> DeleteQueriesEXT;
    static khrapi::Function<Binding, void, glp::GLsizei, const glp::GLuint *> DeleteRenderbuffers;
    static khrapi::Function<Binding, void, glp::GLsizei, const glp::GLuint *> DeleteSamplers;
    static khrapi::Function<Binding, void, glp::GLuint> DeleteShader;
    static khrapi::Function<Binding, void, glp::GLsync> DeleteSync;
    static khrapi::Function<Binding, void, glp::GLsync> DeleteSyncAPPLE;
    static khrapi::Function<Binding, void, glp::GLsizei, const glp::GLuint *> DeleteTextures;
    static khrapi::Function<Binding, void, glp::GLsizei, const glp::GLuint *> DeleteTransformFeedbacks;
    static khrapi::Function<Binding, void, glp::GLsizei, const glp::GLuint *> DeleteVertexArrays;
    static khrapi::Function<Binding, void, glp::GLsizei, const glp::GLuint *> DeleteVertexArraysOES;
    static khrapi::Function<Binding, void, glp::GLenum> DepthFunc;
    static khrapi::Function<Binding, void, glp::GLboolean> DepthMask;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLsizei, const glp::GLfloat *> DepthRangeArrayfvNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLfloat, glp::GLfloat> DepthRangeIndexedfNV;
    static khrapi::Function<Binding, void, glp::GLfloat, glp::GLfloat> DepthRangef;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint> DetachShader;
    static khrapi::Function<Binding, void, glp::GLenum> Disable;
    static khrapi::Function<Binding, void, glp::GLuint> DisableDriverControlQCOM;
    static khrapi::Function<Binding, void, glp::GLuint> DisableVertexAttribArray;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint> Disablei;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint> DisableiEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint> DisableiNV;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint> DisableiOES;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, const glp::GLenum *> DiscardFramebufferEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint, glp::GLuint> DispatchCompute;
    static khrapi::Function<Binding, void, glp::GLintptr> DispatchComputeIndirect;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, glp::GLsizei> DrawArrays;
    static khrapi::Function<Binding, void, glp::GLenum, const void *> DrawArraysIndirect;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, glp::GLsizei, glp::GLsizei> DrawArraysInstanced;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, glp::GLsizei, glp::GLsizei> DrawArraysInstancedANGLE;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, glp::GLsizei, glp::GLsizei, glp::GLuint> DrawArraysInstancedBaseInstanceEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, glp::GLsizei, glp::GLsizei> DrawArraysInstancedEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, glp::GLsizei, glp::GLsizei> DrawArraysInstancedNV;
    static khrapi::Function<Binding, void, glp::GLsizei, const glp::GLenum *> DrawBuffers;
    static khrapi::Function<Binding, void, glp::GLsizei, const glp::GLenum *> DrawBuffersEXT;
    static khrapi::Function<Binding, void, glp::GLint, const glp::GLenum *, const glp::GLint *> DrawBuffersIndexedEXT;
    static khrapi::Function<Binding, void, glp::GLsizei, const glp::GLenum *> DrawBuffersNV;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, glp::GLenum, const void *> DrawElements;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, glp::GLenum, const void *, glp::GLint> DrawElementsBaseVertex;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, glp::GLenum, const void *, glp::GLint> DrawElementsBaseVertexEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, glp::GLenum, const void *, glp::GLint> DrawElementsBaseVertexOES;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, const void *> DrawElementsIndirect;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, glp::GLenum, const void *, glp::GLsizei> DrawElementsInstanced;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, glp::GLenum, const void *, glp::GLsizei> DrawElementsInstancedANGLE;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, glp::GLenum, const void *, glp::GLsizei, glp::GLuint> DrawElementsInstancedBaseInstanceEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, glp::GLenum, const void *, glp::GLsizei, glp::GLint> DrawElementsInstancedBaseVertex;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, glp::GLenum, const void *, glp::GLsizei, glp::GLint, glp::GLuint> DrawElementsInstancedBaseVertexBaseInstanceEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, glp::GLenum, const void *, glp::GLsizei, glp::GLint> DrawElementsInstancedBaseVertexEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, glp::GLenum, const void *, glp::GLsizei, glp::GLint> DrawElementsInstancedBaseVertexOES;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, glp::GLenum, const void *, glp::GLsizei> DrawElementsInstancedEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, glp::GLenum, const void *, glp::GLsizei> DrawElementsInstancedNV;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint, glp::GLuint, glp::GLsizei, glp::GLenum, const void *> DrawRangeElements;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint, glp::GLuint, glp::GLsizei, glp::GLenum, const void *, glp::GLint> DrawRangeElementsBaseVertex;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint, glp::GLuint, glp::GLsizei, glp::GLenum, const void *, glp::GLint> DrawRangeElementsBaseVertexEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint, glp::GLuint, glp::GLsizei, glp::GLenum, const void *, glp::GLint> DrawRangeElementsBaseVertexOES;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLeglImageOES> EGLImageTargetRenderbufferStorageOES;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLeglImageOES> EGLImageTargetTexture2DOES;
    static khrapi::Function<Binding, void, glp::GLenum> Enable;
    static khrapi::Function<Binding, void, glp::GLuint> EnableDriverControlQCOM;
    static khrapi::Function<Binding, void, glp::GLuint> EnableVertexAttribArray;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint> Enablei;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint> EnableiEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint> EnableiNV;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint> EnableiOES;
    static khrapi::Function<Binding, void> EndConditionalRenderNV;
    static khrapi::Function<Binding, void, glp::GLuint> EndPerfMonitorAMD;
    static khrapi::Function<Binding, void, glp::GLuint> EndPerfQueryINTEL;
    static khrapi::Function<Binding, void, glp::GLenum> EndQuery;
    static khrapi::Function<Binding, void, glp::GLenum> EndQueryEXT;
    static khrapi::Function<Binding, void, glp::GLbitfield> EndTilingQCOM;
    static khrapi::Function<Binding, void> EndTransformFeedback;
    static khrapi::Function<Binding, void, glp::GLenum, void **> ExtGetBufferPointervQCOM;
    static khrapi::Function<Binding, void, glp::GLuint *, glp::GLint, glp::GLint *> ExtGetBuffersQCOM;
    static khrapi::Function<Binding, void, glp::GLuint *, glp::GLint, glp::GLint *> ExtGetFramebuffersQCOM;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLchar *, glp::GLint *> ExtGetProgramBinarySourceQCOM;
    static khrapi::Function<Binding, void, glp::GLuint *, glp::GLint, glp::GLint *> ExtGetProgramsQCOM;
    static khrapi::Function<Binding, void, glp::GLuint *, glp::GLint, glp::GLint *> ExtGetRenderbuffersQCOM;
    static khrapi::Function<Binding, void, glp::GLuint *, glp::GLint, glp::GLint *> ExtGetShadersQCOM;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLint, glp::GLenum, glp::GLint *> ExtGetTexLevelParameterivQCOM;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLsizei, glp::GLsizei, glp::GLsizei, glp::GLenum, glp::GLenum, void *> ExtGetTexSubImageQCOM;
    static khrapi::Function<Binding, void, glp::GLuint *, glp::GLint, glp::GLint *> ExtGetTexturesQCOM;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLuint> ExtIsProgramBinaryQCOM;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLint> ExtTexObjectStateOverrideiQCOM;
    static khrapi::Function<Binding, glp::GLsync, glp::GLenum, glp::UnusedMask> FenceSync;
    static khrapi::Function<Binding, glp::GLsync, glp::GLenum, glp::GLbitfield> FenceSyncAPPLE;
    static khrapi::Function<Binding, void> Finish;
    static khrapi::Function<Binding, void, glp::GLuint> FinishFenceNV;
    static khrapi::Function<Binding, void> Flush;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLintptr, glp::GLsizeiptr> FlushMappedBufferRange;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLintptr, glp::GLsizeiptr> FlushMappedBufferRangeEXT;
    static khrapi::Function<Binding, void, glp::GLuint> FragmentCoverageColorNV;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLint> FramebufferParameteri;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLenum, glp::GLuint> FramebufferRenderbuffer;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint, glp::GLsizei, const glp::GLfloat *> FramebufferSampleLocationsfvNV;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLuint, glp::GLint> FramebufferTexture;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLenum, glp::GLuint, glp::GLint> FramebufferTexture2D;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLenum, glp::GLuint, glp::GLint, glp::GLsizei> FramebufferTexture2DMultisampleEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLenum, glp::GLuint, glp::GLint, glp::GLsizei> FramebufferTexture2DMultisampleIMG;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLenum, glp::GLuint, glp::GLint, glp::GLint> FramebufferTexture3DOES;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLuint, glp::GLint> FramebufferTextureEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLuint, glp::GLint, glp::GLint> FramebufferTextureLayer;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLuint, glp::GLint, glp::GLint, glp::GLsizei> FramebufferTextureMultiviewOVR;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLuint, glp::GLint> FramebufferTextureOES;
    static khrapi::Function<Binding, void, glp::GLenum> FrontFace;
    static khrapi::Function<Binding, void, glp::GLsizei, glp::GLuint *> GenBuffers;
    static khrapi::Function<Binding, void, glp::GLsizei, glp::GLuint *> GenFencesNV;
    static khrapi::Function<Binding, void, glp::GLsizei, glp::GLuint *> GenFramebuffers;
    static khrapi::Function<Binding, glp::GLuint, glp::GLsizei> GenPathsNV;
    static khrapi::Function<Binding, void, glp::GLsizei, glp::GLuint *> GenPerfMonitorsAMD;
    static khrapi::Function<Binding, void, glp::GLsizei, glp::GLuint *> GenProgramPipelines;
    static khrapi::Function<Binding, void, glp::GLsizei, glp::GLuint *> GenProgramPipelinesEXT;
    static khrapi::Function<Binding, void, glp::GLsizei, glp::GLuint *> GenQueries;
    static khrapi::Function<Binding, void, glp::GLsizei, glp::GLuint *> GenQueriesEXT;
    static khrapi::Function<Binding, void, glp::GLsizei, glp::GLuint *> GenRenderbuffers;
    static khrapi::Function<Binding, void, glp::GLsizei, glp::GLuint *> GenSamplers;
    static khrapi::Function<Binding, void, glp::GLsizei, glp::GLuint *> GenTextures;
    static khrapi::Function<Binding, void, glp::GLsizei, glp::GLuint *> GenTransformFeedbacks;
    static khrapi::Function<Binding, void, glp::GLsizei, glp::GLuint *> GenVertexArrays;
    static khrapi::Function<Binding, void, glp::GLsizei, glp::GLuint *> GenVertexArraysOES;
    static khrapi::Function<Binding, void, glp::GLenum> GenerateMipmap;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint, glp::GLsizei, glp::GLsizei *, glp::GLint *, glp::GLenum *, glp::GLchar *> GetActiveAttrib;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint, glp::GLsizei, glp::GLsizei *, glp::GLint *, glp::GLenum *, glp::GLchar *> GetActiveUniform;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint, glp::GLsizei, glp::GLsizei *, glp::GLchar *> GetActiveUniformBlockName;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint, glp::GLenum, glp::GLint *> GetActiveUniformBlockiv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLsizei, const glp::GLuint *, glp::GLenum, glp::GLint *> GetActiveUniformsiv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLsizei, glp::GLsizei *, glp::GLuint *> GetAttachedShaders;
    static khrapi::Function<Binding, glp::GLint, glp::GLuint, const glp::GLchar *> GetAttribLocation;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint, glp::GLboolean *> GetBooleani_v;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLboolean *> GetBooleanv;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLint64 *> GetBufferParameteri64v;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLint *> GetBufferParameteriv;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, void **> GetBufferPointerv;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, void **> GetBufferPointervOES;
    static khrapi::Function<Binding, void, glp::GLsizei, glp::GLfloat *> GetCoverageModulationTableNV;
    static khrapi::Function<Binding, glp::GLuint, glp::GLuint, glp::GLsizei, glp::GLenum *, glp::GLenum *, glp::GLuint *, glp::GLenum *, glp::GLsizei *, glp::GLchar *> GetDebugMessageLog;
    static khrapi::Function<Binding, glp::GLuint, glp::GLuint, glp::GLsizei, glp::GLenum *, glp::GLenum *, glp::GLuint *, glp::GLenum *, glp::GLsizei *, glp::GLchar *> GetDebugMessageLogKHR;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLsizei, glp::GLsizei *, glp::GLchar *> GetDriverControlStringQCOM;
    static khrapi::Function<Binding, void, glp::GLint *, glp::GLsizei, glp::GLuint *> GetDriverControlsQCOM;
    static khrapi::Function<Binding, glp::GLenum> GetError;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLint *> GetFenceivNV;
    static khrapi::Function<Binding, void, glp::GLuint *> GetFirstPerfQueryIdINTEL;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint, glp::GLfloat *> GetFloati_vNV;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLfloat *> GetFloatv;
    static khrapi::Function<Binding, glp::GLint, glp::GLuint, const glp::GLchar *> GetFragDataLocation;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLenum, glp::GLint *> GetFramebufferAttachmentParameteriv;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLint *> GetFramebufferParameteriv;
    static khrapi::Function<Binding, glp::GLenum> GetGraphicsResetStatus;
    static khrapi::Function<Binding, glp::GLenum> GetGraphicsResetStatusEXT;
    static khrapi::Function<Binding, glp::GLenum> GetGraphicsResetStatusKHR;
    static khrapi::Function<Binding, glp::GLuint64, glp::GLuint, glp::GLint, glp::GLboolean, glp::GLint, glp::GLenum> GetImageHandleNV;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint, glp::GLint64 *> GetInteger64i_v;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint64 *> GetInteger64v;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint64 *> GetInteger64vAPPLE;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint, glp::GLint *> GetIntegeri_v;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint, glp::GLint *> GetIntegeri_vEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint *> GetIntegerv;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLsizei, glp::GLenum, glp::GLsizei, glp::GLint *> GetInternalformatSampleivNV;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLenum, glp::GLsizei, glp::GLint *> GetInternalformativ;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint, glp::GLfloat *> GetMultisamplefv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint *> GetNextPerfQueryIdINTEL;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint, glp::GLsizei, glp::GLsizei *, glp::GLchar *> GetObjectLabel;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint, glp::GLsizei, glp::GLsizei *, glp::GLchar *> GetObjectLabelEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint, glp::GLsizei, glp::GLsizei *, glp::GLchar *> GetObjectLabelKHR;
    static khrapi::Function<Binding, void, const void *, glp::GLsizei, glp::GLsizei *, glp::GLchar *> GetObjectPtrLabel;
    static khrapi::Function<Binding, void, const void *, glp::GLsizei, glp::GLsizei *, glp::GLchar *> GetObjectPtrLabelKHR;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLubyte *> GetPathCommandsNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLfloat *> GetPathCoordsNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLfloat *> GetPathDashArrayNV;
    static khrapi::Function<Binding, glp::GLfloat, glp::GLuint, glp::GLsizei, glp::GLsizei> GetPathLengthNV;
    static khrapi::Function<Binding, void, glp::PathRenderingMaskNV, glp::GLuint, glp::GLsizei, glp::GLsizei, glp::GLfloat *> GetPathMetricRangeNV;
    static khrapi::Function<Binding, void, glp::PathRenderingMaskNV, glp::GLsizei, glp::GLenum, const void *, glp::GLuint, glp::GLsizei, glp::GLfloat *> GetPathMetricsNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLfloat *> GetPathParameterfvNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLint *> GetPathParameterivNV;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, glp::GLenum, const void *, glp::GLuint, glp::GLfloat, glp::GLfloat, glp::GLenum, glp::GLfloat *> GetPathSpacingNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint, glp::GLuint, glp::GLchar *, glp::GLuint, glp::GLchar *, glp::GLuint *, glp::GLuint *, glp::GLuint *, glp::GLuint *, glp::GLuint64 *> GetPerfCounterInfoINTEL;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLsizei, glp::GLuint *, glp::GLint *> GetPerfMonitorCounterDataAMD;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint, glp::GLenum, void *> GetPerfMonitorCounterInfoAMD;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint, glp::GLsizei, glp::GLsizei *, glp::GLchar *> GetPerfMonitorCounterStringAMD;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint *, glp::GLint *, glp::GLsizei, glp::GLuint *> GetPerfMonitorCountersAMD;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLsizei, glp::GLsizei *, glp::GLchar *> GetPerfMonitorGroupStringAMD;
    static khrapi::Function<Binding, void, glp::GLint *, glp::GLsizei, glp::GLuint *> GetPerfMonitorGroupsAMD;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint, glp::GLsizei, glp::GLvoid *, glp::GLuint *> GetPerfQueryDataINTEL;
    static khrapi::Function<Binding, void, glp::GLchar *, glp::GLuint *> GetPerfQueryIdByNameINTEL;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint, glp::GLchar *, glp::GLuint *, glp::GLuint *, glp::GLuint *, glp::GLuint *> GetPerfQueryInfoINTEL;
    static khrapi::Function<Binding, void, glp::GLenum, void **> GetPointerv;
    static khrapi::Function<Binding, void, glp::GLenum, void **> GetPointervKHR;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLsizei, glp::GLsizei *, glp::GLenum *, void *> GetProgramBinary;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLsizei, glp::GLsizei *, glp::GLenum *, void *> GetProgramBinaryOES;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLsizei, glp::GLsizei *, glp::GLchar *> GetProgramInfoLog;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLenum, glp::GLint *> GetProgramInterfaceiv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLsizei, glp::GLsizei *, glp::GLchar *> GetProgramPipelineInfoLog;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLsizei, glp::GLsizei *, glp::GLchar *> GetProgramPipelineInfoLogEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLint *> GetProgramPipelineiv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLint *> GetProgramPipelineivEXT;
    static khrapi::Function<Binding, glp::GLuint, glp::GLuint, glp::GLenum, const glp::GLchar *> GetProgramResourceIndex;
    static khrapi::Function<Binding, glp::GLint, glp::GLuint, glp::GLenum, const glp::GLchar *> GetProgramResourceLocation;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLuint, glp::GLsizei, glp::GLsizei *, glp::GLchar *> GetProgramResourceName;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLuint, glp::GLsizei, const glp::GLenum *, glp::GLsizei, glp::GLsizei *, glp::GLfloat *> GetProgramResourcefvNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLuint, glp::GLsizei, const glp::GLenum *, glp::GLsizei, glp::GLsizei *, glp::GLint *> GetProgramResourceiv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLint *> GetProgramiv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLint64 *> GetQueryObjecti64vEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLint *> GetQueryObjectivEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLuint64 *> GetQueryObjectui64vEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLuint *> GetQueryObjectuiv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLuint *> GetQueryObjectuivEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLint *> GetQueryiv;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLint *> GetQueryivEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLint *> GetRenderbufferParameteriv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLint *> GetSamplerParameterIiv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLint *> GetSamplerParameterIivEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLint *> GetSamplerParameterIivOES;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLuint *> GetSamplerParameterIuiv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLuint *> GetSamplerParameterIuivEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLuint *> GetSamplerParameterIuivOES;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLfloat *> GetSamplerParameterfv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLint *> GetSamplerParameteriv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLsizei, glp::GLsizei *, glp::GLchar *> GetShaderInfoLog;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLint *, glp::GLint *> GetShaderPrecisionFormat;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLsizei, glp::GLsizei *, glp::GLchar *> GetShaderSource;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLint *> GetShaderiv;
    static khrapi::Function<Binding, const glp::GLubyte *, glp::GLenum> GetString;
    static khrapi::Function<Binding, const glp::GLubyte *, glp::GLenum, glp::GLuint> GetStringi;
    static khrapi::Function<Binding, void, glp::GLsync, glp::GLenum, glp::GLsizei, glp::GLsizei *, glp::GLint *> GetSynciv;
    static khrapi::Function<Binding, void, glp::GLsync, glp::GLenum, glp::GLsizei, glp::GLsizei *, glp::GLint *> GetSyncivAPPLE;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, glp::GLenum, glp::GLfloat *> GetTexLevelParameterfv;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, glp::GLenum, glp::GLint *> GetTexLevelParameteriv;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLint *> GetTexParameterIiv;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLint *> GetTexParameterIivEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLint *> GetTexParameterIivOES;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLuint *> GetTexParameterIuiv;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLuint *> GetTexParameterIuivEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLuint *> GetTexParameterIuivOES;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLfloat *> GetTexParameterfv;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLint *> GetTexParameteriv;
    static khrapi::Function<Binding, glp::GLuint64, glp::GLuint> GetTextureHandleNV;
    static khrapi::Function<Binding, glp::GLuint64, glp::GLuint, glp::GLuint> GetTextureSamplerHandleNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint, glp::GLsizei, glp::GLsizei *, glp::GLsizei *, glp::GLenum *, glp::GLchar *> GetTransformFeedbackVarying;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLsizei, glp::GLsizei *, glp::GLchar *> GetTranslatedShaderSourceANGLE;
    static khrapi::Function<Binding, glp::GLuint, glp::GLuint, const glp::GLchar *> GetUniformBlockIndex;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLsizei, const glp::GLchar *const*, glp::GLuint *> GetUniformIndices;
    static khrapi::Function<Binding, glp::GLint, glp::GLuint, const glp::GLchar *> GetUniformLocation;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLfloat *> GetUniformfv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLint *> GetUniformiv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLuint *> GetUniformuiv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLint *> GetVertexAttribIiv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLuint *> GetVertexAttribIuiv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, void **> GetVertexAttribPointerv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLfloat *> GetVertexAttribfv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLint *> GetVertexAttribiv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, glp::GLfloat *> GetnUniformfv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, glp::GLfloat *> GetnUniformfvEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, glp::GLfloat *> GetnUniformfvKHR;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, glp::GLint *> GetnUniformiv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, glp::GLint *> GetnUniformivEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, glp::GLint *> GetnUniformivKHR;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, glp::GLuint *> GetnUniformuiv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, glp::GLuint *> GetnUniformuivKHR;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum> Hint;
    static khrapi::Function<Binding, void, glp::GLsizei, const glp::GLchar *> InsertEventMarkerEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint, glp::GLuint, glp::GLfloat> InterpolatePathsNV;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, const glp::GLenum *> InvalidateFramebuffer;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, const glp::GLenum *, glp::GLint, glp::GLint, glp::GLsizei, glp::GLsizei> InvalidateSubFramebuffer;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLuint> IsBuffer;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLenum> IsEnabled;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLenum, glp::GLuint> IsEnabledi;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLenum, glp::GLuint> IsEnablediEXT;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLenum, glp::GLuint> IsEnablediNV;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLenum, glp::GLuint> IsEnablediOES;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLuint> IsFenceNV;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLuint> IsFramebuffer;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLuint64> IsImageHandleResidentNV;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLuint> IsPathNV;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLuint, glp::GLuint, glp::GLfloat, glp::GLfloat> IsPointInFillPathNV;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLuint, glp::GLfloat, glp::GLfloat> IsPointInStrokePathNV;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLuint> IsProgram;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLuint> IsProgramPipeline;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLuint> IsProgramPipelineEXT;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLuint> IsQuery;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLuint> IsQueryEXT;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLuint> IsRenderbuffer;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLuint> IsSampler;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLuint> IsShader;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLsync> IsSync;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLsync> IsSyncAPPLE;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLuint> IsTexture;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLuint64> IsTextureHandleResidentNV;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLuint> IsTransformFeedback;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLuint> IsVertexArray;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLuint> IsVertexArrayOES;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint, glp::GLsizei, const glp::GLchar *> LabelObjectEXT;
    static khrapi::Function<Binding, void, glp::GLfloat> LineWidth;
    static khrapi::Function<Binding, void, glp::GLuint> LinkProgram;
    static khrapi::Function<Binding, void, glp::GLuint64> MakeImageHandleNonResidentNV;
    static khrapi::Function<Binding, void, glp::GLuint64, glp::GLenum> MakeImageHandleResidentNV;
    static khrapi::Function<Binding, void, glp::GLuint64> MakeTextureHandleNonResidentNV;
    static khrapi::Function<Binding, void, glp::GLuint64> MakeTextureHandleResidentNV;
    static khrapi::Function<Binding, void *, glp::GLenum, glp::GLenum> MapBufferOES;
    static khrapi::Function<Binding, void *, glp::GLenum, glp::GLintptr, glp::GLsizeiptr, glp::BufferAccessMask> MapBufferRange;
    static khrapi::Function<Binding, void *, glp::GLenum, glp::GLintptr, glp::GLsizeiptr, glp::GLbitfield> MapBufferRangeEXT;
    static khrapi::Function<Binding, void, glp::GLenum, const glp::GLfloat *> MatrixLoad3x2fNV;
    static khrapi::Function<Binding, void, glp::GLenum, const glp::GLfloat *> MatrixLoad3x3fNV;
    static khrapi::Function<Binding, void, glp::GLenum, const glp::GLfloat *> MatrixLoadTranspose3x3fNV;
    static khrapi::Function<Binding, void, glp::GLenum, const glp::GLfloat *> MatrixMult3x2fNV;
    static khrapi::Function<Binding, void, glp::GLenum, const glp::GLfloat *> MatrixMult3x3fNV;
    static khrapi::Function<Binding, void, glp::GLenum, const glp::GLfloat *> MatrixMultTranspose3x3fNV;
    static khrapi::Function<Binding, void, glp::MemoryBarrierMask> MemoryBarrier;
    static khrapi::Function<Binding, void, glp::MemoryBarrierMask> MemoryBarrierByRegion;
    static khrapi::Function<Binding, void, glp::GLfloat> MinSampleShading;
    static khrapi::Function<Binding, void, glp::GLfloat> MinSampleShadingOES;
    static khrapi::Function<Binding, void, glp::GLenum, const glp::GLint *, const glp::GLsizei *, glp::GLsizei> MultiDrawArraysEXT;
    static khrapi::Function<Binding, void, glp::GLenum, const void *, glp::GLsizei, glp::GLsizei> MultiDrawArraysIndirectEXT;
    static khrapi::Function<Binding, void, glp::GLenum, const glp::GLsizei *, glp::GLenum, const void *const*, glp::GLsizei, const glp::GLint *> MultiDrawElementsBaseVertexEXT;
    static khrapi::Function<Binding, void, glp::GLenum, const glp::GLsizei *, glp::GLenum, const void *const*, glp::GLsizei, const glp::GLint *> MultiDrawElementsBaseVertexOES;
    static khrapi::Function<Binding, void, glp::GLenum, const glp::GLsizei *, glp::GLenum, const void *const*, glp::GLsizei> MultiDrawElementsEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, const void *, glp::GLsizei, glp::GLsizei> MultiDrawElementsIndirectEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint, glp::GLsizei, const glp::GLfloat *> NamedFramebufferSampleLocationsfvNV;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint, glp::GLsizei, const glp::GLchar *> ObjectLabel;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint, glp::GLsizei, const glp::GLchar *> ObjectLabelKHR;
    static khrapi::Function<Binding, void, const void *, glp::GLsizei, const glp::GLchar *> ObjectPtrLabel;
    static khrapi::Function<Binding, void, const void *, glp::GLsizei, const glp::GLchar *> ObjectPtrLabelKHR;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint> PatchParameteri;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint> PatchParameteriEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint> PatchParameteriOES;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLsizei, const glp::GLubyte *, glp::GLsizei, glp::GLenum, const void *> PathCommandsNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLsizei, glp::GLenum, const void *> PathCoordsNV;
    static khrapi::Function<Binding, void, glp::GLenum> PathCoverDepthFuncNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLsizei, const glp::GLfloat *> PathDashArrayNV;
    static khrapi::Function<Binding, glp::GLenum, glp::GLuint, glp::GLenum, const void *, glp::PathFontStyle, glp::GLuint, glp::GLsizei, glp::GLuint, glp::GLfloat> PathGlyphIndexArrayNV;
    static khrapi::Function<Binding, glp::GLenum, glp::GLenum, const void *, glp::PathFontStyle, glp::GLuint, glp::GLfloat, glp::GLuint_array_2> PathGlyphIndexRangeNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, const void *, glp::PathFontStyle, glp::GLuint, glp::GLsizei, glp::GLenum, glp::GLuint, glp::GLfloat> PathGlyphRangeNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, const void *, glp::PathFontStyle, glp::GLsizei, glp::GLenum, const void *, glp::GLenum, glp::GLuint, glp::GLfloat> PathGlyphsNV;
    static khrapi::Function<Binding, glp::GLenum, glp::GLuint, glp::GLenum, glp::GLsizeiptr, const void *, glp::GLsizei, glp::GLuint, glp::GLsizei, glp::GLuint, glp::GLfloat> PathMemoryGlyphIndexArrayNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLfloat> PathParameterfNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, const glp::GLfloat *> PathParameterfvNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLint> PathParameteriNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, const glp::GLint *> PathParameterivNV;
    static khrapi::Function<Binding, void, glp::GLfloat, glp::GLfloat> PathStencilDepthOffsetNV;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, glp::GLuint> PathStencilFuncNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLsizei, const void *> PathStringNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLsizei, glp::GLsizei, glp::GLsizei, const glp::GLubyte *, glp::GLsizei, glp::GLenum, const void *> PathSubCommandsNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLsizei, glp::GLsizei, glp::GLenum, const void *> PathSubCoordsNV;
    static khrapi::Function<Binding, void> PauseTransformFeedback;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint> PixelStorei;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLuint, glp::GLsizei, glp::GLsizei, glp::GLfloat, glp::GLfloat *, glp::GLfloat *, glp::GLfloat *, glp::GLfloat *> PointAlongPathNV;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum> PolygonModeNV;
    static khrapi::Function<Binding, void, glp::GLfloat, glp::GLfloat> PolygonOffset;
    static khrapi::Function<Binding, void> PopDebugGroup;
    static khrapi::Function<Binding, void> PopDebugGroupKHR;
    static khrapi::Function<Binding, void> PopGroupMarkerEXT;
    static khrapi::Function<Binding, void, glp::GLfloat, glp::GLfloat, glp::GLfloat, glp::GLfloat, glp::GLfloat, glp::GLfloat, glp::GLfloat, glp::GLfloat> PrimitiveBoundingBox;
    static khrapi::Function<Binding, void, glp::GLfloat, glp::GLfloat, glp::GLfloat, glp::GLfloat, glp::GLfloat, glp::GLfloat, glp::GLfloat, glp::GLfloat> PrimitiveBoundingBoxEXT;
    static khrapi::Function<Binding, void, glp::GLfloat, glp::GLfloat, glp::GLfloat, glp::GLfloat, glp::GLfloat, glp::GLfloat, glp::GLfloat, glp::GLfloat> PrimitiveBoundingBoxOES;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, const void *, glp::GLsizei> ProgramBinary;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, const void *, glp::GLint> ProgramBinaryOES;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLint> ProgramParameteri;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLint> ProgramParameteriEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLenum, glp::GLint, const glp::GLfloat *> ProgramPathFragmentInputGenNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLfloat> ProgramUniform1f;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLfloat> ProgramUniform1fEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, const glp::GLfloat *> ProgramUniform1fv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, const glp::GLfloat *> ProgramUniform1fvEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLint> ProgramUniform1i;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLint> ProgramUniform1iEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, const glp::GLint *> ProgramUniform1iv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, const glp::GLint *> ProgramUniform1ivEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLuint> ProgramUniform1ui;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLuint> ProgramUniform1uiEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, const glp::GLuint *> ProgramUniform1uiv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, const glp::GLuint *> ProgramUniform1uivEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLfloat, glp::GLfloat> ProgramUniform2f;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLfloat, glp::GLfloat> ProgramUniform2fEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, const glp::GLfloat *> ProgramUniform2fv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, const glp::GLfloat *> ProgramUniform2fvEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLint, glp::GLint> ProgramUniform2i;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLint, glp::GLint> ProgramUniform2iEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, const glp::GLint *> ProgramUniform2iv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, const glp::GLint *> ProgramUniform2ivEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLuint, glp::GLuint> ProgramUniform2ui;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLuint, glp::GLuint> ProgramUniform2uiEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, const glp::GLuint *> ProgramUniform2uiv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, const glp::GLuint *> ProgramUniform2uivEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLfloat, glp::GLfloat, glp::GLfloat> ProgramUniform3f;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLfloat, glp::GLfloat, glp::GLfloat> ProgramUniform3fEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, const glp::GLfloat *> ProgramUniform3fv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, const glp::GLfloat *> ProgramUniform3fvEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLint, glp::GLint, glp::GLint> ProgramUniform3i;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLint, glp::GLint, glp::GLint> ProgramUniform3iEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, const glp::GLint *> ProgramUniform3iv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, const glp::GLint *> ProgramUniform3ivEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLuint, glp::GLuint, glp::GLuint> ProgramUniform3ui;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLuint, glp::GLuint, glp::GLuint> ProgramUniform3uiEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, const glp::GLuint *> ProgramUniform3uiv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, const glp::GLuint *> ProgramUniform3uivEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLfloat, glp::GLfloat, glp::GLfloat, glp::GLfloat> ProgramUniform4f;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLfloat, glp::GLfloat, glp::GLfloat, glp::GLfloat> ProgramUniform4fEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, const glp::GLfloat *> ProgramUniform4fv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, const glp::GLfloat *> ProgramUniform4fvEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLint> ProgramUniform4i;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLint> ProgramUniform4iEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, const glp::GLint *> ProgramUniform4iv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, const glp::GLint *> ProgramUniform4ivEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLuint, glp::GLuint, glp::GLuint, glp::GLuint> ProgramUniform4ui;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLuint, glp::GLuint, glp::GLuint, glp::GLuint> ProgramUniform4uiEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, const glp::GLuint *> ProgramUniform4uiv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, const glp::GLuint *> ProgramUniform4uivEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLuint64> ProgramUniformHandleui64NV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, const glp::GLuint64 *> ProgramUniformHandleui64vNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> ProgramUniformMatrix2fv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> ProgramUniformMatrix2fvEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> ProgramUniformMatrix2x3fv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> ProgramUniformMatrix2x3fvEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> ProgramUniformMatrix2x4fv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> ProgramUniformMatrix2x4fvEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> ProgramUniformMatrix3fv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> ProgramUniformMatrix3fvEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> ProgramUniformMatrix3x2fv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> ProgramUniformMatrix3x2fvEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> ProgramUniformMatrix3x4fv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> ProgramUniformMatrix3x4fvEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> ProgramUniformMatrix4fv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> ProgramUniformMatrix4fvEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> ProgramUniformMatrix4x2fv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> ProgramUniformMatrix4x2fvEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> ProgramUniformMatrix4x3fv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> ProgramUniformMatrix4x3fvEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint, glp::GLsizei, const glp::GLchar *> PushDebugGroup;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint, glp::GLsizei, const glp::GLchar *> PushDebugGroupKHR;
    static khrapi::Function<Binding, void, glp::GLsizei, const glp::GLchar *> PushGroupMarkerEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum> QueryCounterEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLboolean> RasterSamplesEXT;
    static khrapi::Function<Binding, void, glp::GLenum> ReadBuffer;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint> ReadBufferIndexedEXT;
    static khrapi::Function<Binding, void, glp::GLenum> ReadBufferNV;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLint, glp::GLsizei, glp::GLsizei, glp::GLenum, glp::GLenum, void *> ReadPixels;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLint, glp::GLsizei, glp::GLsizei, glp::GLenum, glp::GLenum, glp::GLsizei, void *> ReadnPixels;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLint, glp::GLsizei, glp::GLsizei, glp::GLenum, glp::GLenum, glp::GLsizei, void *> ReadnPixelsEXT;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLint, glp::GLsizei, glp::GLsizei, glp::GLenum, glp::GLenum, glp::GLsizei, void *> ReadnPixelsKHR;
    static khrapi::Function<Binding, void> ReleaseShaderCompiler;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLsizei, glp::GLsizei> RenderbufferStorage;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, glp::GLenum, glp::GLsizei, glp::GLsizei> RenderbufferStorageMultisample;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, glp::GLenum, glp::GLsizei, glp::GLsizei> RenderbufferStorageMultisampleANGLE;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, glp::GLenum, glp::GLsizei, glp::GLsizei> RenderbufferStorageMultisampleAPPLE;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, glp::GLenum, glp::GLsizei, glp::GLsizei> RenderbufferStorageMultisampleEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, glp::GLenum, glp::GLsizei, glp::GLsizei> RenderbufferStorageMultisampleIMG;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, glp::GLenum, glp::GLsizei, glp::GLsizei> RenderbufferStorageMultisampleNV;
    static khrapi::Function<Binding, void> ResolveDepthValuesNV;
    static khrapi::Function<Binding, void> ResolveMultisampleFramebufferAPPLE;
    static khrapi::Function<Binding, void> ResumeTransformFeedback;
    static khrapi::Function<Binding, void, glp::GLfloat, glp::GLboolean> SampleCoverage;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLbitfield> SampleMaski;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, const glp::GLint *> SamplerParameterIiv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, const glp::GLint *> SamplerParameterIivEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, const glp::GLint *> SamplerParameterIivOES;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, const glp::GLuint *> SamplerParameterIuiv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, const glp::GLuint *> SamplerParameterIuivEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, const glp::GLuint *> SamplerParameterIuivOES;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLfloat> SamplerParameterf;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, const glp::GLfloat *> SamplerParameterfv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLint> SamplerParameteri;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, const glp::GLint *> SamplerParameteriv;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLint, glp::GLsizei, glp::GLsizei> Scissor;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLsizei, const glp::GLint *> ScissorArrayvNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLint, glp::GLsizei, glp::GLsizei> ScissorIndexedNV;
    static khrapi::Function<Binding, void, glp::GLuint, const glp::GLint *> ScissorIndexedvNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLboolean, glp::GLuint, glp::GLint, glp::GLuint *> SelectPerfMonitorCountersAMD;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum> SetFenceNV;
    static khrapi::Function<Binding, void, glp::GLsizei, const glp::GLuint *, glp::GLenum, const void *, glp::GLsizei> ShaderBinary;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLsizei, const glp::GLchar *const*, const glp::GLint *> ShaderSource;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint, glp::GLuint, glp::GLuint, glp::GLbitfield> StartTilingQCOM;
    static khrapi::Function<Binding, void, glp::GLsizei, glp::GLenum, const void *, glp::GLuint, glp::GLenum, glp::GLuint, glp::GLenum, const glp::GLfloat *> StencilFillPathInstancedNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLuint> StencilFillPathNV;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, glp::GLuint> StencilFunc;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLint, glp::GLuint> StencilFuncSeparate;
    static khrapi::Function<Binding, void, glp::GLuint> StencilMask;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLuint> StencilMaskSeparate;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLenum> StencilOp;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLenum, glp::GLenum> StencilOpSeparate;
    static khrapi::Function<Binding, void, glp::GLsizei, glp::GLenum, const void *, glp::GLuint, glp::GLint, glp::GLuint, glp::GLenum, const glp::GLfloat *> StencilStrokePathInstancedNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLuint> StencilStrokePathNV;
    static khrapi::Function<Binding, void, glp::GLsizei, glp::GLenum, const void *, glp::GLuint, glp::GLenum, glp::GLuint, glp::GLenum, glp::GLenum, const glp::GLfloat *> StencilThenCoverFillPathInstancedNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLuint, glp::GLenum> StencilThenCoverFillPathNV;
    static khrapi::Function<Binding, void, glp::GLsizei, glp::GLenum, const void *, glp::GLuint, glp::GLint, glp::GLuint, glp::GLenum, glp::GLenum, const glp::GLfloat *> StencilThenCoverStrokePathInstancedNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLuint, glp::GLenum> StencilThenCoverStrokePathNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint> SubpixelPrecisionBiasNV;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLuint> TestFenceNV;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLuint> TexBuffer;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLuint> TexBufferEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLuint> TexBufferOES;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLuint, glp::GLintptr, glp::GLsizeiptr> TexBufferRange;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLuint, glp::GLintptr, glp::GLsizeiptr> TexBufferRangeEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLuint, glp::GLintptr, glp::GLsizeiptr> TexBufferRangeOES;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, glp::GLint, glp::GLsizei, glp::GLsizei, glp::GLint, glp::GLenum, glp::GLenum, const void *> TexImage2D;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, glp::GLint, glp::GLsizei, glp::GLsizei, glp::GLsizei, glp::GLint, glp::GLenum, glp::GLenum, const void *> TexImage3D;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, glp::GLenum, glp::GLsizei, glp::GLsizei, glp::GLsizei, glp::GLint, glp::GLenum, glp::GLenum, const void *> TexImage3DOES;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLsizei, glp::GLsizei, glp::GLsizei, glp::GLboolean> TexPageCommitmentARB;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, const glp::GLint *> TexParameterIiv;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, const glp::GLint *> TexParameterIivEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, const glp::GLint *> TexParameterIivOES;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, const glp::GLuint *> TexParameterIuiv;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, const glp::GLuint *> TexParameterIuivEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, const glp::GLuint *> TexParameterIuivOES;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLfloat> TexParameterf;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, const glp::GLfloat *> TexParameterfv;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, glp::GLint> TexParameteri;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLenum, const glp::GLint *> TexParameteriv;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, glp::GLenum, glp::GLsizei> TexStorage1DEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, glp::GLenum, glp::GLsizei, glp::GLsizei> TexStorage2D;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, glp::GLenum, glp::GLsizei, glp::GLsizei> TexStorage2DEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, glp::GLenum, glp::GLsizei, glp::GLsizei, glp::GLboolean> TexStorage2DMultisample;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, glp::GLenum, glp::GLsizei, glp::GLsizei, glp::GLsizei> TexStorage3D;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, glp::GLenum, glp::GLsizei, glp::GLsizei, glp::GLsizei> TexStorage3DEXT;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, glp::GLenum, glp::GLsizei, glp::GLsizei, glp::GLsizei, glp::GLboolean> TexStorage3DMultisample;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLsizei, glp::GLenum, glp::GLsizei, glp::GLsizei, glp::GLsizei, glp::GLboolean> TexStorage3DMultisampleOES;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, glp::GLint, glp::GLint, glp::GLsizei, glp::GLsizei, glp::GLenum, glp::GLenum, const void *> TexSubImage2D;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLsizei, glp::GLsizei, glp::GLsizei, glp::GLenum, glp::GLenum, const void *> TexSubImage3D;
    static khrapi::Function<Binding, void, glp::GLenum, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLsizei, glp::GLsizei, glp::GLsizei, glp::GLenum, glp::GLenum, const void *> TexSubImage3DOES;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLsizei, glp::GLenum, glp::GLsizei> TextureStorage1DEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLsizei, glp::GLenum, glp::GLsizei, glp::GLsizei> TextureStorage2DEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLsizei, glp::GLenum, glp::GLsizei, glp::GLsizei, glp::GLsizei> TextureStorage3DEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLuint, glp::GLenum, glp::GLuint, glp::GLuint, glp::GLuint, glp::GLuint> TextureViewEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLenum, glp::GLuint, glp::GLenum, glp::GLuint, glp::GLuint, glp::GLuint, glp::GLuint> TextureViewOES;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLsizei, const glp::GLchar *const*, glp::GLenum> TransformFeedbackVaryings;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint, glp::GLenum, const glp::GLfloat *> TransformPathNV;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLfloat> Uniform1f;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLsizei, const glp::GLfloat *> Uniform1fv;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLint> Uniform1i;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLsizei, const glp::GLint *> Uniform1iv;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLuint> Uniform1ui;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLsizei, const glp::GLuint *> Uniform1uiv;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLfloat, glp::GLfloat> Uniform2f;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLsizei, const glp::GLfloat *> Uniform2fv;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLint, glp::GLint> Uniform2i;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLsizei, const glp::GLint *> Uniform2iv;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLuint, glp::GLuint> Uniform2ui;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLsizei, const glp::GLuint *> Uniform2uiv;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLfloat, glp::GLfloat, glp::GLfloat> Uniform3f;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLsizei, const glp::GLfloat *> Uniform3fv;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLint, glp::GLint, glp::GLint> Uniform3i;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLsizei, const glp::GLint *> Uniform3iv;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLuint, glp::GLuint, glp::GLuint> Uniform3ui;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLsizei, const glp::GLuint *> Uniform3uiv;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLfloat, glp::GLfloat, glp::GLfloat, glp::GLfloat> Uniform4f;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLsizei, const glp::GLfloat *> Uniform4fv;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLint, glp::GLint, glp::GLint, glp::GLint> Uniform4i;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLsizei, const glp::GLint *> Uniform4iv;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLuint, glp::GLuint, glp::GLuint, glp::GLuint> Uniform4ui;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLsizei, const glp::GLuint *> Uniform4uiv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint, glp::GLuint> UniformBlockBinding;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLuint64> UniformHandleui64NV;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLsizei, const glp::GLuint64 *> UniformHandleui64vNV;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> UniformMatrix2fv;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> UniformMatrix2x3fv;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> UniformMatrix2x3fvNV;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> UniformMatrix2x4fv;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> UniformMatrix2x4fvNV;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> UniformMatrix3fv;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> UniformMatrix3x2fv;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> UniformMatrix3x2fvNV;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> UniformMatrix3x4fv;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> UniformMatrix3x4fvNV;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> UniformMatrix4fv;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> UniformMatrix4x2fv;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> UniformMatrix4x2fvNV;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> UniformMatrix4x3fv;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLsizei, glp::GLboolean, const glp::GLfloat *> UniformMatrix4x3fvNV;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLenum> UnmapBuffer;
    static khrapi::Function<Binding, glp::GLboolean, glp::GLenum> UnmapBufferOES;
    static khrapi::Function<Binding, void, glp::GLuint> UseProgram;
    static khrapi::Function<Binding, void, glp::GLuint, glp::UseProgramStageMask, glp::GLuint> UseProgramStages;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLbitfield, glp::GLuint> UseProgramStagesEXT;
    static khrapi::Function<Binding, void, glp::GLuint> ValidateProgram;
    static khrapi::Function<Binding, void, glp::GLuint> ValidateProgramPipeline;
    static khrapi::Function<Binding, void, glp::GLuint> ValidateProgramPipelineEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLfloat> VertexAttrib1f;
    static khrapi::Function<Binding, void, glp::GLuint, const glp::GLfloat *> VertexAttrib1fv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLfloat, glp::GLfloat> VertexAttrib2f;
    static khrapi::Function<Binding, void, glp::GLuint, const glp::GLfloat *> VertexAttrib2fv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLfloat, glp::GLfloat, glp::GLfloat> VertexAttrib3f;
    static khrapi::Function<Binding, void, glp::GLuint, const glp::GLfloat *> VertexAttrib3fv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLfloat, glp::GLfloat, glp::GLfloat, glp::GLfloat> VertexAttrib4f;
    static khrapi::Function<Binding, void, glp::GLuint, const glp::GLfloat *> VertexAttrib4fv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint> VertexAttribBinding;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint> VertexAttribDivisor;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint> VertexAttribDivisorANGLE;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint> VertexAttribDivisorEXT;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint> VertexAttribDivisorNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLenum, glp::GLboolean, glp::GLuint> VertexAttribFormat;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLint, glp::GLint, glp::GLint> VertexAttribI4i;
    static khrapi::Function<Binding, void, glp::GLuint, const glp::GLint *> VertexAttribI4iv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint, glp::GLuint, glp::GLuint, glp::GLuint> VertexAttribI4ui;
    static khrapi::Function<Binding, void, glp::GLuint, const glp::GLuint *> VertexAttribI4uiv;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLenum, glp::GLuint> VertexAttribIFormat;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLenum, glp::GLsizei, const void *> VertexAttribIPointer;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLint, glp::GLenum, glp::GLboolean, glp::GLsizei, const void *> VertexAttribPointer;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLuint> VertexBindingDivisor;
    static khrapi::Function<Binding, void, glp::GLint, glp::GLint, glp::GLsizei, glp::GLsizei> Viewport;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLsizei, const glp::GLfloat *> ViewportArrayvNV;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLfloat, glp::GLfloat, glp::GLfloat, glp::GLfloat> ViewportIndexedfNV;
    static khrapi::Function<Binding, void, glp::GLuint, const glp::GLfloat *> ViewportIndexedfvNV;
    static khrapi::Function<Binding, void, glp::GLsync, glp::UnusedMask, glp::GLuint64> WaitSync;
    static khrapi::Function<Binding, void, glp::GLsync, glp::GLbitfield, glp::GLuint64> WaitSyncAPPLE;
    static khrapi::Function<Binding, void, glp::GLuint, glp::GLsizei, const glp::GLuint *, const glp::GLfloat *> WeightPathsNV;

};

} // namespace glpbinding
