
#pragma once


#include <wglbinding/nogl.h>

#include <wglbinding/wglbinding_features.h>

#include <wglbinding/SharedBitfield.h>


namespace wgl
{



// import bitfields to namespace

WGLBINDING_CONSTEXPR static const None GL_NONE_BIT = None::GL_NONE_BIT;
WGLBINDING_CONSTEXPR static const None WGL_ACCESS_READ_ONLY_NV = None::WGL_ACCESS_READ_ONLY_NV;
WGLBINDING_CONSTEXPR static const None WGL_ACCESS_READ_WRITE_NV = None::WGL_ACCESS_READ_WRITE_NV;
WGLBINDING_CONSTEXPR static const None WGL_CONTEXT_CORE_PROFILE_BIT_ARB = None::WGL_CONTEXT_CORE_PROFILE_BIT_ARB;
WGLBINDING_CONSTEXPR static const None WGL_CONTEXT_DEBUG_BIT_ARB = None::WGL_CONTEXT_DEBUG_BIT_ARB;
WGLBINDING_CONSTEXPR static const None WGL_FRONT_COLOR_BUFFER_BIT_ARB = None::WGL_FRONT_COLOR_BUFFER_BIT_ARB;
WGLBINDING_CONSTEXPR static const None WGL_IMAGE_BUFFER_MIN_ACCESS_I3D = None::WGL_IMAGE_BUFFER_MIN_ACCESS_I3D;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_MAIN_PLANE = None::WGL_SWAP_MAIN_PLANE;
WGLBINDING_CONSTEXPR static const None WGL_ACCESS_WRITE_DISCARD_NV = None::WGL_ACCESS_WRITE_DISCARD_NV;
WGLBINDING_CONSTEXPR static const None WGL_BACK_COLOR_BUFFER_BIT_ARB = None::WGL_BACK_COLOR_BUFFER_BIT_ARB;
WGLBINDING_CONSTEXPR static const None WGL_CONTEXT_COMPATIBILITY_PROFILE_BIT_ARB = None::WGL_CONTEXT_COMPATIBILITY_PROFILE_BIT_ARB;
WGLBINDING_CONSTEXPR static const None WGL_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB = None::WGL_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB;
WGLBINDING_CONSTEXPR static const None WGL_IMAGE_BUFFER_LOCK_I3D = None::WGL_IMAGE_BUFFER_LOCK_I3D;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_OVERLAY1 = None::WGL_SWAP_OVERLAY1;
WGLBINDING_CONSTEXPR static const None WGL_CONTEXT_ES2_PROFILE_BIT_EXT = None::WGL_CONTEXT_ES2_PROFILE_BIT_EXT;
WGLBINDING_CONSTEXPR static const None WGL_CONTEXT_ES_PROFILE_BIT_EXT = None::WGL_CONTEXT_ES_PROFILE_BIT_EXT;
WGLBINDING_CONSTEXPR static const None WGL_CONTEXT_ROBUST_ACCESS_BIT_ARB = None::WGL_CONTEXT_ROBUST_ACCESS_BIT_ARB;
WGLBINDING_CONSTEXPR static const None WGL_DEPTH_BUFFER_BIT_ARB = None::WGL_DEPTH_BUFFER_BIT_ARB;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_OVERLAY2 = None::WGL_SWAP_OVERLAY2;
WGLBINDING_CONSTEXPR static const None WGL_CONTEXT_RESET_ISOLATION_BIT_ARB = None::WGL_CONTEXT_RESET_ISOLATION_BIT_ARB;
WGLBINDING_CONSTEXPR static const None WGL_STENCIL_BUFFER_BIT_ARB = None::WGL_STENCIL_BUFFER_BIT_ARB;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_OVERLAY3 = None::WGL_SWAP_OVERLAY3;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_OVERLAY4 = None::WGL_SWAP_OVERLAY4;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_OVERLAY5 = None::WGL_SWAP_OVERLAY5;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_OVERLAY6 = None::WGL_SWAP_OVERLAY6;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_OVERLAY7 = None::WGL_SWAP_OVERLAY7;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_OVERLAY8 = None::WGL_SWAP_OVERLAY8;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_OVERLAY9 = None::WGL_SWAP_OVERLAY9;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_OVERLAY10 = None::WGL_SWAP_OVERLAY10;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_OVERLAY11 = None::WGL_SWAP_OVERLAY11;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_OVERLAY12 = None::WGL_SWAP_OVERLAY12;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_OVERLAY13 = None::WGL_SWAP_OVERLAY13;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_OVERLAY14 = None::WGL_SWAP_OVERLAY14;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_OVERLAY15 = None::WGL_SWAP_OVERLAY15;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_UNDERLAY1 = None::WGL_SWAP_UNDERLAY1;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_UNDERLAY2 = None::WGL_SWAP_UNDERLAY2;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_UNDERLAY3 = None::WGL_SWAP_UNDERLAY3;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_UNDERLAY4 = None::WGL_SWAP_UNDERLAY4;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_UNDERLAY5 = None::WGL_SWAP_UNDERLAY5;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_UNDERLAY6 = None::WGL_SWAP_UNDERLAY6;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_UNDERLAY7 = None::WGL_SWAP_UNDERLAY7;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_UNDERLAY8 = None::WGL_SWAP_UNDERLAY8;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_UNDERLAY9 = None::WGL_SWAP_UNDERLAY9;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_UNDERLAY10 = None::WGL_SWAP_UNDERLAY10;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_UNDERLAY11 = None::WGL_SWAP_UNDERLAY11;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_UNDERLAY12 = None::WGL_SWAP_UNDERLAY12;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_UNDERLAY13 = None::WGL_SWAP_UNDERLAY13;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_UNDERLAY14 = None::WGL_SWAP_UNDERLAY14;
WGLBINDING_CONSTEXPR static const None WGL_SWAP_UNDERLAY15 = None::WGL_SWAP_UNDERLAY15;


} // namespace wgl
