#pragma once

#include <eglbinding/noegl.h>
#include <eglbinding/egl/functions.h>


namespace egl10ext
{

using egl::eglBindAPI;
using egl::eglBindTexImage;
using egl::eglClientWaitSync;
using egl::eglClientWaitSyncKHR;
using egl::eglClientWaitSyncNV;
using egl::eglCreateDRMImageMESA;
using egl::eglCreateFenceSyncNV;
using egl::eglCreateImage;
using egl::eglCreateImageKHR;
using egl::eglCreatePbufferFromClientBuffer;
using egl::eglCreatePixmapSurfaceHI;
using egl::eglCreatePlatformPixmapSurface;
using egl::eglCreatePlatformPixmapSurfaceEXT;
using egl::eglCreatePlatformWindowSurface;
using egl::eglCreatePlatformWindowSurfaceEXT;
using egl::eglCreateStreamFromFileDescriptorKHR;
using egl::eglCreateStreamKHR;
using egl::eglCreateStreamProducerSurfaceKHR;
using egl::eglCreateStreamSyncNV;
using egl::eglCreateSync;
using egl::eglCreateSync64KHR;
using egl::eglCreateSyncKHR;
using egl::eglDestroyImage;
using egl::eglDestroyImageKHR;
using egl::eglDestroyStreamKHR;
using egl::eglDestroySync;
using egl::eglDestroySyncKHR;
using egl::eglDestroySyncNV;
using egl::eglDupNativeFenceFDANDROID;
using egl::eglExportDMABUFImageMESA;
using egl::eglExportDMABUFImageQueryMESA;
using egl::eglExportDRMImageMESA;
using egl::eglFenceNV;
using egl::eglGetCurrentContext;
using egl::eglGetOutputLayersEXT;
using egl::eglGetOutputPortsEXT;
using egl::eglGetPlatformDisplay;
using egl::eglGetPlatformDisplayEXT;
using egl::eglGetStreamFileDescriptorKHR;
using egl::eglGetSyncAttrib;
using egl::eglGetSyncAttribKHR;
using egl::eglGetSyncAttribNV;
using egl::eglGetSystemTimeFrequencyNV;
using egl::eglGetSystemTimeNV;
using egl::eglLockSurfaceKHR;
using egl::eglOutputLayerAttribEXT;
using egl::eglOutputPortAttribEXT;
using egl::eglPostSubBufferNV;
using egl::eglQueryAPI;
using egl::eglQueryDeviceAttribEXT;
using egl::eglQueryDeviceStringEXT;
using egl::eglQueryDevicesEXT;
using egl::eglQueryDisplayAttribEXT;
using egl::eglQueryNativeDisplayNV;
using egl::eglQueryNativePixmapNV;
using egl::eglQueryNativeWindowNV;
using egl::eglQueryOutputLayerAttribEXT;
using egl::eglQueryOutputLayerStringEXT;
using egl::eglQueryOutputPortAttribEXT;
using egl::eglQueryOutputPortStringEXT;
using egl::eglQueryStreamKHR;
using egl::eglQueryStreamTimeKHR;
using egl::eglQueryStreamu64KHR;
using egl::eglQuerySurface64KHR;
using egl::eglQuerySurfacePointerANGLE;
using egl::eglReleaseTexImage;
using egl::eglReleaseThread;
using egl::eglSetBlobCacheFuncsANDROID;
using egl::eglSetDamageRegionKHR;
using egl::eglSignalSyncKHR;
using egl::eglSignalSyncNV;
using egl::eglStreamAttribKHR;
using egl::eglStreamConsumerAcquireKHR;
using egl::eglStreamConsumerGLTextureExternalKHR;
using egl::eglStreamConsumerOutputEXT;
using egl::eglStreamConsumerReleaseKHR;
using egl::eglSurfaceAttrib;
using egl::eglSwapBuffersRegion2NOK;
using egl::eglSwapBuffersRegionNOK;
using egl::eglSwapBuffersWithDamageEXT;
using egl::eglSwapBuffersWithDamageKHR;
using egl::eglSwapInterval;
using egl::eglUnlockSurfaceKHR;
using egl::eglWaitClient;
using egl::eglWaitSync;
using egl::eglWaitSyncKHR;

} // namespace egl10ext
