
#include "Meta_Maps.h"

#include <glxbinding/glx/enum.h>


using namespace glx;


namespace glxbinding
{


const std::unordered_map<std::string, GLenum> Meta_EnumsByString_-1 =
{
    { "GLX_3DFX_FULLSCREEN_MODE_MESA", GLenum::GLX_3DFX_FULLSCREEN_MODE_MESA },
    { "GLX_3DFX_WINDOW_MODE_MESA", GLenum::GLX_3DFX_WINDOW_MODE_MESA },
    { "GLX_ACCUM_ALPHA_SIZE", GLenum::GLX_ACCUM_ALPHA_SIZE },
    { "GLX_ACCUM_BLUE_SIZE", GLenum::GLX_ACCUM_BLUE_SIZE },
    { "GLX_ACCUM_GREEN_SIZE", GLenum::GLX_ACCUM_GREEN_SIZE },
    { "GLX_ACCUM_RED_SIZE", GLenum::GLX_ACCUM_RED_SIZE },
    { "GLX_ALPHA_SIZE", GLenum::GLX_ALPHA_SIZE },
    { "GLX_AUX0_EXT", GLenum::GLX_AUX0_EXT },
    { "GLX_AUX1_EXT", GLenum::GLX_AUX1_EXT },
    { "GLX_AUX2_EXT", GLenum::GLX_AUX2_EXT },
    { "GLX_AUX3_EXT", GLenum::GLX_AUX3_EXT },
    { "GLX_AUX4_EXT", GLenum::GLX_AUX4_EXT },
    { "GLX_AUX5_EXT", GLenum::GLX_AUX5_EXT },
    { "GLX_AUX6_EXT", GLenum::GLX_AUX6_EXT },
    { "GLX_AUX7_EXT", GLenum::GLX_AUX7_EXT },
    { "GLX_AUX8_EXT", GLenum::GLX_AUX8_EXT },
    { "GLX_AUX9_EXT", GLenum::GLX_AUX9_EXT },
    { "GLX_AUX_BUFFERS", GLenum::GLX_AUX_BUFFERS },
    { "GLX_BACK_BUFFER_AGE_EXT", GLenum::GLX_BACK_BUFFER_AGE_EXT },
    { "GLX_BACK_EXT", GLenum::GLX_BACK_EXT },
    { "GLX_BACK_LEFT_EXT", GLenum::GLX_BACK_LEFT_EXT },
    { "GLX_BACK_RIGHT_EXT", GLenum::GLX_BACK_RIGHT_EXT },
    { "GLX_BAD_ATTRIBUTE", GLenum::GLX_BAD_ATTRIBUTE },
    { "GLX_BAD_CONTEXT", GLenum::GLX_BAD_CONTEXT },
    { "GLX_BAD_ENUM", GLenum::GLX_BAD_ENUM },
    { "GLX_BAD_HYPERPIPE_CONFIG_SGIX", GLenum::GLX_BAD_HYPERPIPE_CONFIG_SGIX },
    { "GLX_BAD_HYPERPIPE_SGIX", GLenum::GLX_BAD_HYPERPIPE_SGIX },
    { "GLX_BAD_SCREEN", GLenum::GLX_BAD_SCREEN },
    { "GLX_BAD_VALUE", GLenum::GLX_BAD_VALUE },
    { "GLX_BAD_VISUAL", GLenum::GLX_BAD_VISUAL },
    { "GLX_BIND_TO_MIPMAP_TEXTURE_EXT", GLenum::GLX_BIND_TO_MIPMAP_TEXTURE_EXT },
    { "GLX_BIND_TO_TEXTURE_RGBA_EXT", GLenum::GLX_BIND_TO_TEXTURE_RGBA_EXT },
    { "GLX_BIND_TO_TEXTURE_RGB_EXT", GLenum::GLX_BIND_TO_TEXTURE_RGB_EXT },
    { "GLX_BIND_TO_TEXTURE_TARGETS_EXT", GLenum::GLX_BIND_TO_TEXTURE_TARGETS_EXT },
    { "GLX_BLENDED_RGBA_SGIS", GLenum::GLX_BLENDED_RGBA_SGIS },
    { "GLX_BLUE_SIZE", GLenum::GLX_BLUE_SIZE },
    { "GLX_BUFFER_SIZE", GLenum::GLX_BUFFER_SIZE },
    { "GLX_BufferSwapComplete", GLenum::GLX_BufferSwapComplete },
    { "GLX_COLOR_INDEX_TYPE", GLenum::GLX_COLOR_INDEX_TYPE },
    { "GLX_COLOR_INDEX_TYPE_SGIX", GLenum::GLX_COLOR_INDEX_TYPE_SGIX },
    { "GLX_COLOR_SAMPLES_NV", GLenum::GLX_COLOR_SAMPLES_NV },
    { "GLX_CONFIG_CAVEAT", GLenum::GLX_CONFIG_CAVEAT },
    { "GLX_CONTEXT_ALLOW_BUFFER_BYTE_ORDER_MISMATCH_ARB", GLenum::GLX_CONTEXT_ALLOW_BUFFER_BYTE_ORDER_MISMATCH_ARB },
    { "GLX_CONTEXT_FLAGS_ARB", GLenum::GLX_CONTEXT_FLAGS_ARB },
    { "GLX_CONTEXT_MAJOR_VERSION_ARB", GLenum::GLX_CONTEXT_MAJOR_VERSION_ARB },
    { "GLX_CONTEXT_MINOR_VERSION_ARB", GLenum::GLX_CONTEXT_MINOR_VERSION_ARB },
    { "GLX_CONTEXT_PROFILE_MASK_ARB", GLenum::GLX_CONTEXT_PROFILE_MASK_ARB },
    { "GLX_CONTEXT_RELEASE_BEHAVIOR_ARB", GLenum::GLX_CONTEXT_RELEASE_BEHAVIOR_ARB },
    { "GLX_CONTEXT_RELEASE_BEHAVIOR_FLUSH_ARB", GLenum::GLX_CONTEXT_RELEASE_BEHAVIOR_FLUSH_ARB },
    { "GLX_CONTEXT_RELEASE_BEHAVIOR_NONE_ARB", GLenum::GLX_CONTEXT_RELEASE_BEHAVIOR_NONE_ARB },
    { "GLX_CONTEXT_RESET_NOTIFICATION_STRATEGY_ARB", GLenum::GLX_CONTEXT_RESET_NOTIFICATION_STRATEGY_ARB },
    { "GLX_COPY_COMPLETE_INTEL", GLenum::GLX_COPY_COMPLETE_INTEL },
    { "GLX_COVERAGE_SAMPLES_NV", GLenum::GLX_COVERAGE_SAMPLES_NV },
    { "GLX_DAMAGED", GLenum::GLX_DAMAGED },
    { "GLX_DAMAGED_SGIX", GLenum::GLX_DAMAGED_SGIX },
    { "GLX_DEPTH_SIZE", GLenum::GLX_DEPTH_SIZE },
    { "GLX_DEVICE_ID_NV", GLenum::GLX_DEVICE_ID_NV },
    { "GLX_DIGITAL_MEDIA_PBUFFER_SGIX", GLenum::GLX_DIGITAL_MEDIA_PBUFFER_SGIX },
    { "GLX_DIRECT_COLOR", GLenum::GLX_DIRECT_COLOR },
    { "GLX_DIRECT_COLOR_EXT", GLenum::GLX_DIRECT_COLOR_EXT },
    { "GLX_DONT_CARE", GLenum::GLX_DONT_CARE },
    { "GLX_DOUBLEBUFFER", GLenum::GLX_DOUBLEBUFFER },
    { "GLX_DRAWABLE_TYPE", GLenum::GLX_DRAWABLE_TYPE },
    { "GLX_DRAWABLE_TYPE_SGIX", GLenum::GLX_DRAWABLE_TYPE_SGIX },
    { "GLX_EVENT_MASK", GLenum::GLX_EVENT_MASK },
    { "GLX_EVENT_MASK_SGIX", GLenum::GLX_EVENT_MASK_SGIX },
    { "GLX_EXCHANGE_COMPLETE_INTEL", GLenum::GLX_EXCHANGE_COMPLETE_INTEL },
    { "GLX_EXTENSIONS", GLenum::GLX_EXTENSIONS },
    { "GLX_EXTENSION_NAME", GLenum::GLX_EXTENSION_NAME },
    { "GLX_FBCONFIG_ID", GLenum::GLX_FBCONFIG_ID },
    { "GLX_FBCONFIG_ID_SGIX", GLenum::GLX_FBCONFIG_ID_SGIX },
    { "GLX_FLIP_COMPLETE_INTEL", GLenum::GLX_FLIP_COMPLETE_INTEL },
    { "GLX_FLOAT_COMPONENTS_NV", GLenum::GLX_FLOAT_COMPONENTS_NV },
    { "GLX_FRAMEBUFFER_SRGB_CAPABLE_ARB", GLenum::GLX_FRAMEBUFFER_SRGB_CAPABLE_ARB },
    { "GLX_FRAMEBUFFER_SRGB_CAPABLE_EXT", GLenum::GLX_FRAMEBUFFER_SRGB_CAPABLE_EXT },
    { "GLX_FRONT_EXT", GLenum::GLX_FRONT_EXT },
    { "GLX_FRONT_LEFT_EXT", GLenum::GLX_FRONT_LEFT_EXT },
    { "GLX_FRONT_RIGHT_EXT", GLenum::GLX_FRONT_RIGHT_EXT },
    { "GLX_GENERATE_RESET_ON_VIDEO_MEMORY_PURGE_NV", GLenum::GLX_GENERATE_RESET_ON_VIDEO_MEMORY_PURGE_NV },
    { "GLX_GPU_CLOCK_AMD", GLenum::GLX_GPU_CLOCK_AMD },
    { "GLX_GPU_FASTEST_TARGET_GPUS_AMD", GLenum::GLX_GPU_FASTEST_TARGET_GPUS_AMD },
    { "GLX_GPU_NUM_PIPES_AMD", GLenum::GLX_GPU_NUM_PIPES_AMD },
    { "GLX_GPU_NUM_RB_AMD", GLenum::GLX_GPU_NUM_RB_AMD },
    { "GLX_GPU_NUM_SIMD_AMD", GLenum::GLX_GPU_NUM_SIMD_AMD },
    { "GLX_GPU_NUM_SPI_AMD", GLenum::GLX_GPU_NUM_SPI_AMD },
    { "GLX_GPU_RAM_AMD", GLenum::GLX_GPU_RAM_AMD },
    { "GLX_GPU_RENDERER_STRING_AMD", GLenum::GLX_GPU_RENDERER_STRING_AMD },
    { "GLX_GPU_VENDOR_AMD", GLenum::GLX_GPU_VENDOR_AMD },
    { "GLX_GRAY_SCALE", GLenum::GLX_GRAY_SCALE },
    { "GLX_GRAY_SCALE_EXT", GLenum::GLX_GRAY_SCALE_EXT },
    { "GLX_GREEN_SIZE", GLenum::GLX_GREEN_SIZE },
    { "GLX_HEIGHT", GLenum::GLX_HEIGHT },
    { "GLX_HEIGHT_SGIX", GLenum::GLX_HEIGHT_SGIX },
    { "GLX_HYPERPIPE_ID_SGIX", GLenum::GLX_HYPERPIPE_ID_SGIX },
    { "GLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX", GLenum::GLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX },
    { "GLX_LARGEST_PBUFFER", GLenum::GLX_LARGEST_PBUFFER },
    { "GLX_LARGEST_PBUFFER_SGIX", GLenum::GLX_LARGEST_PBUFFER_SGIX },
    { "GLX_LATE_SWAPS_TEAR_EXT", GLenum::GLX_LATE_SWAPS_TEAR_EXT },
    { "GLX_LEVEL", GLenum::GLX_LEVEL },
    { "GLX_LOSE_CONTEXT_ON_RESET_ARB", GLenum::GLX_LOSE_CONTEXT_ON_RESET_ARB },
    { "GLX_MAX_PBUFFER_HEIGHT", GLenum::GLX_MAX_PBUFFER_HEIGHT },
    { "GLX_MAX_PBUFFER_HEIGHT_SGIX", GLenum::GLX_MAX_PBUFFER_HEIGHT_SGIX },
    { "GLX_MAX_PBUFFER_PIXELS", GLenum::GLX_MAX_PBUFFER_PIXELS },
    { "GLX_MAX_PBUFFER_PIXELS_SGIX", GLenum::GLX_MAX_PBUFFER_PIXELS_SGIX },
    { "GLX_MAX_PBUFFER_WIDTH", GLenum::GLX_MAX_PBUFFER_WIDTH },
    { "GLX_MAX_PBUFFER_WIDTH_SGIX", GLenum::GLX_MAX_PBUFFER_WIDTH_SGIX },
    { "GLX_MAX_SWAP_INTERVAL_EXT", GLenum::GLX_MAX_SWAP_INTERVAL_EXT },
    { "GLX_MIPMAP_TEXTURE_EXT", GLenum::GLX_MIPMAP_TEXTURE_EXT },
    { "GLX_MULTISAMPLE_SUB_RECT_HEIGHT_SGIS", GLenum::GLX_MULTISAMPLE_SUB_RECT_HEIGHT_SGIS },
    { "GLX_MULTISAMPLE_SUB_RECT_WIDTH_SGIS", GLenum::GLX_MULTISAMPLE_SUB_RECT_WIDTH_SGIS },
    { "GLX_NONE", GLenum::GLX_NONE },
    { "GLX_NONE_EXT", GLenum::GLX_NONE_EXT },
    { "GLX_NON_CONFORMANT_CONFIG", GLenum::GLX_NON_CONFORMANT_CONFIG },
    { "GLX_NON_CONFORMANT_VISUAL_EXT", GLenum::GLX_NON_CONFORMANT_VISUAL_EXT },
    { "GLX_NO_EXTENSION", GLenum::GLX_NO_EXTENSION },
    { "GLX_NO_RESET_NOTIFICATION_ARB", GLenum::GLX_NO_RESET_NOTIFICATION_ARB },
    { "GLX_NUM_VIDEO_CAPTURE_SLOTS_NV", GLenum::GLX_NUM_VIDEO_CAPTURE_SLOTS_NV },
    { "GLX_NUM_VIDEO_SLOTS_NV", GLenum::GLX_NUM_VIDEO_SLOTS_NV },
    { "GLX_OPTIMAL_PBUFFER_HEIGHT_SGIX", GLenum::GLX_OPTIMAL_PBUFFER_HEIGHT_SGIX },
    { "GLX_OPTIMAL_PBUFFER_WIDTH_SGIX", GLenum::GLX_OPTIMAL_PBUFFER_WIDTH_SGIX },
    { "GLX_PBUFFER", GLenum::GLX_PBUFFER },
    { "GLX_PBUFFER_HEIGHT", GLenum::GLX_PBUFFER_HEIGHT },
    { "GLX_PBUFFER_SGIX", GLenum::GLX_PBUFFER_SGIX },
    { "GLX_PBUFFER_WIDTH", GLenum::GLX_PBUFFER_WIDTH },
    { "GLX_PRESERVED_CONTENTS", GLenum::GLX_PRESERVED_CONTENTS },
    { "GLX_PRESERVED_CONTENTS_SGIX", GLenum::GLX_PRESERVED_CONTENTS_SGIX },
    { "GLX_PSEUDO_COLOR", GLenum::GLX_PSEUDO_COLOR },
    { "GLX_PSEUDO_COLOR_EXT", GLenum::GLX_PSEUDO_COLOR_EXT },
    { "GLX_PbufferClobber", GLenum::GLX_PbufferClobber },
    { "GLX_RED_SIZE", GLenum::GLX_RED_SIZE },
    { "GLX_RENDERER_ACCELERATED_MESA", GLenum::GLX_RENDERER_ACCELERATED_MESA },
    { "GLX_RENDERER_DEVICE_ID_MESA", GLenum::GLX_RENDERER_DEVICE_ID_MESA },
    { "GLX_RENDERER_ID_MESA", GLenum::GLX_RENDERER_ID_MESA },
    { "GLX_RENDERER_PREFERRED_PROFILE_MESA", GLenum::GLX_RENDERER_PREFERRED_PROFILE_MESA },
    { "GLX_RENDERER_UNIFIED_MEMORY_ARCHITECTURE_MESA", GLenum::GLX_RENDERER_UNIFIED_MEMORY_ARCHITECTURE_MESA },
    { "GLX_RENDERER_VENDOR_ID_MESA", GLenum::GLX_RENDERER_VENDOR_ID_MESA },
    { "GLX_RENDERER_VERSION_MESA", GLenum::GLX_RENDERER_VERSION_MESA },
    { "GLX_RENDERER_VIDEO_MEMORY_MESA", GLenum::GLX_RENDERER_VIDEO_MEMORY_MESA },
    { "GLX_RENDER_TYPE", GLenum::GLX_RENDER_TYPE },
    { "GLX_RENDER_TYPE_SGIX", GLenum::GLX_RENDER_TYPE_SGIX },
    { "GLX_RGBA", GLenum::GLX_RGBA },
    { "GLX_RGBA_FLOAT_TYPE_ARB", GLenum::GLX_RGBA_FLOAT_TYPE_ARB },
    { "GLX_RGBA_TYPE", GLenum::GLX_RGBA_TYPE },
    { "GLX_RGBA_TYPE_SGIX", GLenum::GLX_RGBA_TYPE_SGIX },
    { "GLX_RGBA_UNSIGNED_FLOAT_TYPE_EXT", GLenum::GLX_RGBA_UNSIGNED_FLOAT_TYPE_EXT },
    { "GLX_SAMPLES", GLenum::GLX_SAMPLES },
    { "GLX_SAMPLES_3DFX", GLenum::GLX_SAMPLES_3DFX },
    { "GLX_SAMPLES_ARB", GLenum::GLX_SAMPLES_ARB },
    { "GLX_SAMPLES_SGIS", GLenum::GLX_SAMPLES_SGIS },
    { "GLX_SAMPLE_BUFFERS", GLenum::GLX_SAMPLE_BUFFERS },
    { "GLX_SAMPLE_BUFFERS_3DFX", GLenum::GLX_SAMPLE_BUFFERS_3DFX },
    { "GLX_SAMPLE_BUFFERS_ARB", GLenum::GLX_SAMPLE_BUFFERS_ARB },
    { "GLX_SAMPLE_BUFFERS_SGIS", GLenum::GLX_SAMPLE_BUFFERS_SGIS },
    { "GLX_SAVED", GLenum::GLX_SAVED },
    { "GLX_SAVED_SGIX", GLenum::GLX_SAVED_SGIX },
    { "GLX_SCREEN", GLenum::GLX_SCREEN },
    { "GLX_SCREEN_EXT", GLenum::GLX_SCREEN_EXT },
    { "GLX_SHARE_CONTEXT_EXT", GLenum::GLX_SHARE_CONTEXT_EXT },
    { "GLX_SLOW_CONFIG", GLenum::GLX_SLOW_CONFIG },
    { "GLX_SLOW_VISUAL_EXT", GLenum::GLX_SLOW_VISUAL_EXT },
    { "GLX_STATIC_COLOR", GLenum::GLX_STATIC_COLOR },
    { "GLX_STATIC_COLOR_EXT", GLenum::GLX_STATIC_COLOR_EXT },
    { "GLX_STATIC_GRAY", GLenum::GLX_STATIC_GRAY },
    { "GLX_STATIC_GRAY_EXT", GLenum::GLX_STATIC_GRAY_EXT },
    { "GLX_STENCIL_SIZE", GLenum::GLX_STENCIL_SIZE },
    { "GLX_STEREO", GLenum::GLX_STEREO },
    { "GLX_STEREO_NOTIFY_EXT", GLenum::GLX_STEREO_NOTIFY_EXT },
    { "GLX_STEREO_TREE_EXT", GLenum::GLX_STEREO_TREE_EXT },
    { "GLX_SWAP_COPY_OML", GLenum::GLX_SWAP_COPY_OML },
    { "GLX_SWAP_EXCHANGE_OML", GLenum::GLX_SWAP_EXCHANGE_OML },
    { "GLX_SWAP_INTERVAL_EXT", GLenum::GLX_SWAP_INTERVAL_EXT },
    { "GLX_SWAP_METHOD_OML", GLenum::GLX_SWAP_METHOD_OML },
    { "GLX_SWAP_UNDEFINED_OML", GLenum::GLX_SWAP_UNDEFINED_OML },
    { "GLX_TEXTURE_1D_EXT", GLenum::GLX_TEXTURE_1D_EXT },
    { "GLX_TEXTURE_2D_EXT", GLenum::GLX_TEXTURE_2D_EXT },
    { "GLX_TEXTURE_FORMAT_EXT", GLenum::GLX_TEXTURE_FORMAT_EXT },
    { "GLX_TEXTURE_FORMAT_NONE_EXT", GLenum::GLX_TEXTURE_FORMAT_NONE_EXT },
    { "GLX_TEXTURE_FORMAT_RGBA_EXT", GLenum::GLX_TEXTURE_FORMAT_RGBA_EXT },
    { "GLX_TEXTURE_FORMAT_RGB_EXT", GLenum::GLX_TEXTURE_FORMAT_RGB_EXT },
    { "GLX_TEXTURE_RECTANGLE_EXT", GLenum::GLX_TEXTURE_RECTANGLE_EXT },
    { "GLX_TEXTURE_TARGET_EXT", GLenum::GLX_TEXTURE_TARGET_EXT },
    { "GLX_TRANSPARENT_ALPHA_VALUE", GLenum::GLX_TRANSPARENT_ALPHA_VALUE },
    { "GLX_TRANSPARENT_ALPHA_VALUE_EXT", GLenum::GLX_TRANSPARENT_ALPHA_VALUE_EXT },
    { "GLX_TRANSPARENT_BLUE_VALUE", GLenum::GLX_TRANSPARENT_BLUE_VALUE },
    { "GLX_TRANSPARENT_BLUE_VALUE_EXT", GLenum::GLX_TRANSPARENT_BLUE_VALUE_EXT },
    { "GLX_TRANSPARENT_GREEN_VALUE", GLenum::GLX_TRANSPARENT_GREEN_VALUE },
    { "GLX_TRANSPARENT_GREEN_VALUE_EXT", GLenum::GLX_TRANSPARENT_GREEN_VALUE_EXT },
    { "GLX_TRANSPARENT_INDEX", GLenum::GLX_TRANSPARENT_INDEX },
    { "GLX_TRANSPARENT_INDEX_EXT", GLenum::GLX_TRANSPARENT_INDEX_EXT },
    { "GLX_TRANSPARENT_INDEX_VALUE", GLenum::GLX_TRANSPARENT_INDEX_VALUE },
    { "GLX_TRANSPARENT_INDEX_VALUE_EXT", GLenum::GLX_TRANSPARENT_INDEX_VALUE_EXT },
    { "GLX_TRANSPARENT_RED_VALUE", GLenum::GLX_TRANSPARENT_RED_VALUE },
    { "GLX_TRANSPARENT_RED_VALUE_EXT", GLenum::GLX_TRANSPARENT_RED_VALUE_EXT },
    { "GLX_TRANSPARENT_RGB", GLenum::GLX_TRANSPARENT_RGB },
    { "GLX_TRANSPARENT_RGB_EXT", GLenum::GLX_TRANSPARENT_RGB_EXT },
    { "GLX_TRANSPARENT_TYPE", GLenum::GLX_TRANSPARENT_TYPE },
    { "GLX_TRANSPARENT_TYPE_EXT", GLenum::GLX_TRANSPARENT_TYPE_EXT },
    { "GLX_TRUE_COLOR", GLenum::GLX_TRUE_COLOR },
    { "GLX_TRUE_COLOR_EXT", GLenum::GLX_TRUE_COLOR_EXT },
    { "GLX_UNIQUE_ID_NV", GLenum::GLX_UNIQUE_ID_NV },
    { "GLX_USE_GL", GLenum::GLX_USE_GL },
    { "GLX_VENDOR", GLenum::GLX_VENDOR },
    { "GLX_VENDOR_NAMES_EXT", GLenum::GLX_VENDOR_NAMES_EXT },
    { "GLX_VERSION", GLenum::GLX_VERSION },
    { "GLX_VIDEO_OUT_ALPHA_NV", GLenum::GLX_VIDEO_OUT_ALPHA_NV },
    { "GLX_VIDEO_OUT_COLOR_AND_ALPHA_NV", GLenum::GLX_VIDEO_OUT_COLOR_AND_ALPHA_NV },
    { "GLX_VIDEO_OUT_COLOR_AND_DEPTH_NV", GLenum::GLX_VIDEO_OUT_COLOR_AND_DEPTH_NV },
    { "GLX_VIDEO_OUT_COLOR_NV", GLenum::GLX_VIDEO_OUT_COLOR_NV },
    { "GLX_VIDEO_OUT_DEPTH_NV", GLenum::GLX_VIDEO_OUT_DEPTH_NV },
    { "GLX_VIDEO_OUT_FIELD_1_NV", GLenum::GLX_VIDEO_OUT_FIELD_1_NV },
    { "GLX_VIDEO_OUT_FIELD_2_NV", GLenum::GLX_VIDEO_OUT_FIELD_2_NV },
    { "GLX_VIDEO_OUT_FRAME_NV", GLenum::GLX_VIDEO_OUT_FRAME_NV },
    { "GLX_VIDEO_OUT_STACKED_FIELDS_1_2_NV", GLenum::GLX_VIDEO_OUT_STACKED_FIELDS_1_2_NV },
    { "GLX_VIDEO_OUT_STACKED_FIELDS_2_1_NV", GLenum::GLX_VIDEO_OUT_STACKED_FIELDS_2_1_NV },
    { "GLX_VISUAL_CAVEAT_EXT", GLenum::GLX_VISUAL_CAVEAT_EXT },
    { "GLX_VISUAL_ID", GLenum::GLX_VISUAL_ID },
    { "GLX_VISUAL_ID_EXT", GLenum::GLX_VISUAL_ID_EXT },
    { "GLX_VISUAL_SELECT_GROUP_SGIX", GLenum::GLX_VISUAL_SELECT_GROUP_SGIX },
    { "GLX_WIDTH", GLenum::GLX_WIDTH },
    { "GLX_WIDTH_SGIX", GLenum::GLX_WIDTH_SGIX },
    { "GLX_WINDOW", GLenum::GLX_WINDOW },
    { "GLX_WINDOW_SGIX", GLenum::GLX_WINDOW_SGIX },
    { "GLX_X_RENDERABLE", GLenum::GLX_X_RENDERABLE },
    { "GLX_X_RENDERABLE_SGIX", GLenum::GLX_X_RENDERABLE_SGIX },
    { "GLX_X_VISUAL_TYPE", GLenum::GLX_X_VISUAL_TYPE },
    { "GLX_X_VISUAL_TYPE_EXT", GLenum::GLX_X_VISUAL_TYPE_EXT },
    { "GLX_Y_INVERTED_EXT", GLenum::GLX_Y_INVERTED_EXT },
    { "__GLX_NUMBER_EVENTS", GLenum::__GLX_NUMBER_EVENTS }
};

const std::unordered_map<std::string, GLenum> Meta_EnumsByString_0{};

const std::unordered_map<std::string, GLenum> Meta_EnumsByString_A{};

const std::unordered_map<std::string, GLenum> Meta_EnumsByString_B{};

const std::unordered_map<std::string, GLenum> Meta_EnumsByString_C =
{
    { "GLX_RENDERER_OPENGL_COMPATIBILITY_PROFILE_VERSION_MESA", GLenum::GLX_RENDERER_OPENGL_COMPATIBILITY_PROFILE_VERSION_MESA },
    { "GLX_RENDERER_OPENGL_CORE_PROFILE_VERSION_MESA", GLenum::GLX_RENDERER_OPENGL_CORE_PROFILE_VERSION_MESA }
};

const std::unordered_map<std::string, GLenum> Meta_EnumsByString_D{};

const std::unordered_map<std::string, GLenum> Meta_EnumsByString_E =
{
    { "GLX_RENDERER_OPENGL_ES2_PROFILE_VERSION_MESA", GLenum::GLX_RENDERER_OPENGL_ES2_PROFILE_VERSION_MESA },
    { "GLX_RENDERER_OPENGL_ES_PROFILE_VERSION_MESA", GLenum::GLX_RENDERER_OPENGL_ES_PROFILE_VERSION_MESA }
};

const std::unordered_map<std::string, GLenum> Meta_EnumsByString_F{};

const std::unordered_map<std::string, GLenum> Meta_EnumsByString_G{};

const std::unordered_map<std::string, GLenum> Meta_EnumsByString_H{};

const std::unordered_map<std::string, GLenum> Meta_EnumsByString_I{};

const std::unordered_map<std::string, GLenum> Meta_EnumsByString_J{};

const std::unordered_map<std::string, GLenum> Meta_EnumsByString_K{};

const std::unordered_map<std::string, GLenum> Meta_EnumsByString_L{};

const std::unordered_map<std::string, GLenum> Meta_EnumsByString_M{};

const std::unordered_map<std::string, GLenum> Meta_EnumsByString_N =
{
    { "GLX_CONTEXT_OPENGL_NO_ERROR_ARB", GLenum::GLX_CONTEXT_OPENGL_NO_ERROR_ARB }
};

const std::unordered_map<std::string, GLenum> Meta_EnumsByString_O{};

const std::unordered_map<std::string, GLenum> Meta_EnumsByString_P{};

const std::unordered_map<std::string, GLenum> Meta_EnumsByString_Q{};

const std::unordered_map<std::string, GLenum> Meta_EnumsByString_R{};

const std::unordered_map<std::string, GLenum> Meta_EnumsByString_S{};

const std::unordered_map<std::string, GLenum> Meta_EnumsByString_T{};

const std::unordered_map<std::string, GLenum> Meta_EnumsByString_U{};

const std::unordered_map<std::string, GLenum> Meta_EnumsByString_V =
{
    { "GLX_GPU_OPENGL_VERSION_STRING_AMD", GLenum::GLX_GPU_OPENGL_VERSION_STRING_AMD }
};

const std::unordered_map<std::string, GLenum> Meta_EnumsByString_W{};

const std::unordered_map<std::string, GLenum> Meta_EnumsByString_X{};

const std::unordered_map<std::string, GLenum> Meta_EnumsByString_Y{};

const std::unordered_map<std::string, GLenum> Meta_EnumsByString_Z{};

const std::array<std::unordered_map<std::string, glx::GLenum>, 28> Meta_EnumsByStringMaps =
{ {
    Meta_EnumsByString_-1,
    Meta_EnumsByString_0,
    Meta_EnumsByString_A,
    Meta_EnumsByString_B,
    Meta_EnumsByString_C,
    Meta_EnumsByString_D,
    Meta_EnumsByString_E,
    Meta_EnumsByString_F,
    Meta_EnumsByString_G,
    Meta_EnumsByString_H,
    Meta_EnumsByString_I,
    Meta_EnumsByString_J,
    Meta_EnumsByString_K,
    Meta_EnumsByString_L,
    Meta_EnumsByString_M,
    Meta_EnumsByString_N,
    Meta_EnumsByString_O,
    Meta_EnumsByString_P,
    Meta_EnumsByString_Q,
    Meta_EnumsByString_R,
    Meta_EnumsByString_S,
    Meta_EnumsByString_T,
    Meta_EnumsByString_U,
    Meta_EnumsByString_V,
    Meta_EnumsByString_W,
    Meta_EnumsByString_X,
    Meta_EnumsByString_Y,
    Meta_EnumsByString_Z
} };


} // namespace glxbinding
