
#include "Binding_pch.h"


using namespace gl;


namespace glbinding
{


Function<Binding, void> Binding::VDPAUFiniNV("glVDPAUFiniNV");
Function<Binding, void, GLvdpauSurfaceNV, GLenum, GLsizei, GLsizei *, GLint *> Binding::VDPAUGetSurfaceivNV("glVDPAUGetSurfaceivNV");
Function<Binding, void, const void *, const void *> Binding::VDPAUInitNV("glVDPAUInitNV");
Function<Binding, GLboolean, GLvdpauSurfaceNV> Binding::VDPAUIsSurfaceNV("glVDPAUIsSurfaceNV");
Function<Binding, void, GLsizei, const GLvdpauSurfaceNV *> Binding::VDPAUMapSurfacesNV("glVDPAUMapSurfacesNV");
Function<Binding, GLvdpauSurfaceNV, const void *, GLenum, GLsizei, const GLuint *> Binding::VDPAURegisterOutputSurfaceNV("glVDPAURegisterOutputSurfaceNV");
Function<Binding, GLvdpauSurfaceNV, const void *, GLenum, GLsizei, const GLuint *> Binding::VDPAURegisterVideoSurfaceNV("glVDPAURegisterVideoSurfaceNV");
Function<Binding, void, GLvdpauSurfaceNV, GLenum> Binding::VDPAUSurfaceAccessNV("glVDPAUSurfaceAccessNV");
Function<Binding, void, GLsizei, const GLvdpauSurfaceNV *> Binding::VDPAUUnmapSurfacesNV("glVDPAUUnmapSurfacesNV");
Function<Binding, void, GLvdpauSurfaceNV> Binding::VDPAUUnregisterSurfaceNV("glVDPAUUnregisterSurfaceNV");
Function<Binding, void, GLuint> Binding::ValidateProgram("glValidateProgram");
Function<Binding, void, GLhandleARB> Binding::ValidateProgramARB("glValidateProgramARB");
Function<Binding, void, GLuint> Binding::ValidateProgramPipeline("glValidateProgramPipeline");
Function<Binding, void, GLuint, GLenum, GLsizei, GLuint, GLuint> Binding::VariantArrayObjectATI("glVariantArrayObjectATI");
Function<Binding, void, GLuint, GLenum, GLuint, const void *> Binding::VariantPointerEXT("glVariantPointerEXT");
Function<Binding, void, GLuint, const GLbyte *> Binding::VariantbvEXT("glVariantbvEXT");
Function<Binding, void, GLuint, const GLdouble *> Binding::VariantdvEXT("glVariantdvEXT");
Function<Binding, void, GLuint, const GLfloat *> Binding::VariantfvEXT("glVariantfvEXT");
Function<Binding, void, GLuint, const GLint *> Binding::VariantivEXT("glVariantivEXT");
Function<Binding, void, GLuint, const GLshort *> Binding::VariantsvEXT("glVariantsvEXT");
Function<Binding, void, GLuint, const GLubyte *> Binding::VariantubvEXT("glVariantubvEXT");
Function<Binding, void, GLuint, const GLuint *> Binding::VariantuivEXT("glVariantuivEXT");
Function<Binding, void, GLuint, const GLushort *> Binding::VariantusvEXT("glVariantusvEXT");
Function<Binding, void, GLbyte, GLbyte> Binding::Vertex2bOES("glVertex2bOES");
Function<Binding, void, const GLbyte *> Binding::Vertex2bvOES("glVertex2bvOES");
Function<Binding, void, GLdouble, GLdouble> Binding::Vertex2d("glVertex2d");
Function<Binding, void, const GLdouble *> Binding::Vertex2dv("glVertex2dv");
Function<Binding, void, GLfloat, GLfloat> Binding::Vertex2f("glVertex2f");
Function<Binding, void, const GLfloat *> Binding::Vertex2fv("glVertex2fv");
Function<Binding, void, GLhalfNV, GLhalfNV> Binding::Vertex2hNV("glVertex2hNV");
Function<Binding, void, const GLhalfNV *> Binding::Vertex2hvNV("glVertex2hvNV");
Function<Binding, void, GLint, GLint> Binding::Vertex2i("glVertex2i");
Function<Binding, void, const GLint *> Binding::Vertex2iv("glVertex2iv");
Function<Binding, void, GLshort, GLshort> Binding::Vertex2s("glVertex2s");
Function<Binding, void, const GLshort *> Binding::Vertex2sv("glVertex2sv");
Function<Binding, void, GLfixed> Binding::Vertex2xOES("glVertex2xOES");
Function<Binding, void, const GLfixed *> Binding::Vertex2xvOES("glVertex2xvOES");
Function<Binding, void, GLbyte, GLbyte, GLbyte> Binding::Vertex3bOES("glVertex3bOES");
Function<Binding, void, const GLbyte *> Binding::Vertex3bvOES("glVertex3bvOES");
Function<Binding, void, GLdouble, GLdouble, GLdouble> Binding::Vertex3d("glVertex3d");
Function<Binding, void, const GLdouble *> Binding::Vertex3dv("glVertex3dv");
Function<Binding, void, GLfloat, GLfloat, GLfloat> Binding::Vertex3f("glVertex3f");
Function<Binding, void, const GLfloat *> Binding::Vertex3fv("glVertex3fv");
Function<Binding, void, GLhalfNV, GLhalfNV, GLhalfNV> Binding::Vertex3hNV("glVertex3hNV");
Function<Binding, void, const GLhalfNV *> Binding::Vertex3hvNV("glVertex3hvNV");
Function<Binding, void, GLint, GLint, GLint> Binding::Vertex3i("glVertex3i");
Function<Binding, void, const GLint *> Binding::Vertex3iv("glVertex3iv");
Function<Binding, void, GLshort, GLshort, GLshort> Binding::Vertex3s("glVertex3s");
Function<Binding, void, const GLshort *> Binding::Vertex3sv("glVertex3sv");
Function<Binding, void, GLfixed, GLfixed> Binding::Vertex3xOES("glVertex3xOES");
Function<Binding, void, const GLfixed *> Binding::Vertex3xvOES("glVertex3xvOES");
Function<Binding, void, GLbyte, GLbyte, GLbyte, GLbyte> Binding::Vertex4bOES("glVertex4bOES");
Function<Binding, void, const GLbyte *> Binding::Vertex4bvOES("glVertex4bvOES");
Function<Binding, void, GLdouble, GLdouble, GLdouble, GLdouble> Binding::Vertex4d("glVertex4d");
Function<Binding, void, const GLdouble *> Binding::Vertex4dv("glVertex4dv");
Function<Binding, void, GLfloat, GLfloat, GLfloat, GLfloat> Binding::Vertex4f("glVertex4f");
Function<Binding, void, const GLfloat *> Binding::Vertex4fv("glVertex4fv");
Function<Binding, void, GLhalfNV, GLhalfNV, GLhalfNV, GLhalfNV> Binding::Vertex4hNV("glVertex4hNV");
Function<Binding, void, const GLhalfNV *> Binding::Vertex4hvNV("glVertex4hvNV");
Function<Binding, void, GLint, GLint, GLint, GLint> Binding::Vertex4i("glVertex4i");
Function<Binding, void, const GLint *> Binding::Vertex4iv("glVertex4iv");
Function<Binding, void, GLshort, GLshort, GLshort, GLshort> Binding::Vertex4s("glVertex4s");
Function<Binding, void, const GLshort *> Binding::Vertex4sv("glVertex4sv");
Function<Binding, void, GLfixed, GLfixed, GLfixed> Binding::Vertex4xOES("glVertex4xOES");
Function<Binding, void, const GLfixed *> Binding::Vertex4xvOES("glVertex4xvOES");
Function<Binding, void, GLuint, GLuint, GLuint> Binding::VertexArrayAttribBinding("glVertexArrayAttribBinding");
Function<Binding, void, GLuint, GLuint, GLint, GLenum, GLboolean, GLuint> Binding::VertexArrayAttribFormat("glVertexArrayAttribFormat");
Function<Binding, void, GLuint, GLuint, GLint, GLenum, GLuint> Binding::VertexArrayAttribIFormat("glVertexArrayAttribIFormat");
Function<Binding, void, GLuint, GLuint, GLint, GLenum, GLuint> Binding::VertexArrayAttribLFormat("glVertexArrayAttribLFormat");
Function<Binding, void, GLuint, GLuint, GLuint, GLintptr, GLsizei> Binding::VertexArrayBindVertexBufferEXT("glVertexArrayBindVertexBufferEXT");
Function<Binding, void, GLuint, GLuint, GLuint> Binding::VertexArrayBindingDivisor("glVertexArrayBindingDivisor");
Function<Binding, void, GLuint, GLuint, GLint, GLenum, GLsizei, GLintptr> Binding::VertexArrayColorOffsetEXT("glVertexArrayColorOffsetEXT");
Function<Binding, void, GLuint, GLuint, GLsizei, GLintptr> Binding::VertexArrayEdgeFlagOffsetEXT("glVertexArrayEdgeFlagOffsetEXT");
Function<Binding, void, GLuint, GLuint> Binding::VertexArrayElementBuffer("glVertexArrayElementBuffer");
Function<Binding, void, GLuint, GLuint, GLenum, GLsizei, GLintptr> Binding::VertexArrayFogCoordOffsetEXT("glVertexArrayFogCoordOffsetEXT");
Function<Binding, void, GLuint, GLuint, GLenum, GLsizei, GLintptr> Binding::VertexArrayIndexOffsetEXT("glVertexArrayIndexOffsetEXT");
Function<Binding, void, GLuint, GLuint, GLenum, GLint, GLenum, GLsizei, GLintptr> Binding::VertexArrayMultiTexCoordOffsetEXT("glVertexArrayMultiTexCoordOffsetEXT");
Function<Binding, void, GLuint, GLuint, GLenum, GLsizei, GLintptr> Binding::VertexArrayNormalOffsetEXT("glVertexArrayNormalOffsetEXT");
Function<Binding, void, GLenum, GLint> Binding::VertexArrayParameteriAPPLE("glVertexArrayParameteriAPPLE");
Function<Binding, void, GLsizei, void *> Binding::VertexArrayRangeAPPLE("glVertexArrayRangeAPPLE");
Function<Binding, void, GLsizei, const void *> Binding::VertexArrayRangeNV("glVertexArrayRangeNV");
Function<Binding, void, GLuint, GLuint, GLint, GLenum, GLsizei, GLintptr> Binding::VertexArraySecondaryColorOffsetEXT("glVertexArraySecondaryColorOffsetEXT");
Function<Binding, void, GLuint, GLuint, GLint, GLenum, GLsizei, GLintptr> Binding::VertexArrayTexCoordOffsetEXT("glVertexArrayTexCoordOffsetEXT");
Function<Binding, void, GLuint, GLuint, GLuint> Binding::VertexArrayVertexAttribBindingEXT("glVertexArrayVertexAttribBindingEXT");
Function<Binding, void, GLuint, GLuint, GLuint> Binding::VertexArrayVertexAttribDivisorEXT("glVertexArrayVertexAttribDivisorEXT");
Function<Binding, void, GLuint, GLuint, GLint, GLenum, GLboolean, GLuint> Binding::VertexArrayVertexAttribFormatEXT("glVertexArrayVertexAttribFormatEXT");
Function<Binding, void, GLuint, GLuint, GLint, GLenum, GLuint> Binding::VertexArrayVertexAttribIFormatEXT("glVertexArrayVertexAttribIFormatEXT");
Function<Binding, void, GLuint, GLuint, GLuint, GLint, GLenum, GLsizei, GLintptr> Binding::VertexArrayVertexAttribIOffsetEXT("glVertexArrayVertexAttribIOffsetEXT");
Function<Binding, void, GLuint, GLuint, GLint, GLenum, GLuint> Binding::VertexArrayVertexAttribLFormatEXT("glVertexArrayVertexAttribLFormatEXT");
Function<Binding, void, GLuint, GLuint, GLuint, GLint, GLenum, GLsizei, GLintptr> Binding::VertexArrayVertexAttribLOffsetEXT("glVertexArrayVertexAttribLOffsetEXT");
Function<Binding, void, GLuint, GLuint, GLuint, GLint, GLenum, GLboolean, GLsizei, GLintptr> Binding::VertexArrayVertexAttribOffsetEXT("glVertexArrayVertexAttribOffsetEXT");
Function<Binding, void, GLuint, GLuint, GLuint> Binding::VertexArrayVertexBindingDivisorEXT("glVertexArrayVertexBindingDivisorEXT");
Function<Binding, void, GLuint, GLuint, GLuint, GLintptr, GLsizei> Binding::VertexArrayVertexBuffer("glVertexArrayVertexBuffer");
Function<Binding, void, GLuint, GLuint, GLsizei, const GLuint *, const GLintptr *, const GLsizei *> Binding::VertexArrayVertexBuffers("glVertexArrayVertexBuffers");
Function<Binding, void, GLuint, GLuint, GLint, GLenum, GLsizei, GLintptr> Binding::VertexArrayVertexOffsetEXT("glVertexArrayVertexOffsetEXT");
Function<Binding, void, GLuint, GLdouble> Binding::VertexAttrib1d("glVertexAttrib1d");
Function<Binding, void, GLuint, GLdouble> Binding::VertexAttrib1dARB("glVertexAttrib1dARB");
Function<Binding, void, GLuint, GLdouble> Binding::VertexAttrib1dNV("glVertexAttrib1dNV");
Function<Binding, void, GLuint, const GLdouble *> Binding::VertexAttrib1dv("glVertexAttrib1dv");
Function<Binding, void, GLuint, const GLdouble *> Binding::VertexAttrib1dvARB("glVertexAttrib1dvARB");
Function<Binding, void, GLuint, const GLdouble *> Binding::VertexAttrib1dvNV("glVertexAttrib1dvNV");
Function<Binding, void, GLuint, GLfloat> Binding::VertexAttrib1f("glVertexAttrib1f");
Function<Binding, void, GLuint, GLfloat> Binding::VertexAttrib1fARB("glVertexAttrib1fARB");
Function<Binding, void, GLuint, GLfloat> Binding::VertexAttrib1fNV("glVertexAttrib1fNV");
Function<Binding, void, GLuint, const GLfloat *> Binding::VertexAttrib1fv("glVertexAttrib1fv");
Function<Binding, void, GLuint, const GLfloat *> Binding::VertexAttrib1fvARB("glVertexAttrib1fvARB");
Function<Binding, void, GLuint, const GLfloat *> Binding::VertexAttrib1fvNV("glVertexAttrib1fvNV");
Function<Binding, void, GLuint, GLhalfNV> Binding::VertexAttrib1hNV("glVertexAttrib1hNV");
Function<Binding, void, GLuint, const GLhalfNV *> Binding::VertexAttrib1hvNV("glVertexAttrib1hvNV");
Function<Binding, void, GLuint, GLshort> Binding::VertexAttrib1s("glVertexAttrib1s");
Function<Binding, void, GLuint, GLshort> Binding::VertexAttrib1sARB("glVertexAttrib1sARB");
Function<Binding, void, GLuint, GLshort> Binding::VertexAttrib1sNV("glVertexAttrib1sNV");
Function<Binding, void, GLuint, const GLshort *> Binding::VertexAttrib1sv("glVertexAttrib1sv");
Function<Binding, void, GLuint, const GLshort *> Binding::VertexAttrib1svARB("glVertexAttrib1svARB");
Function<Binding, void, GLuint, const GLshort *> Binding::VertexAttrib1svNV("glVertexAttrib1svNV");
Function<Binding, void, GLuint, GLdouble, GLdouble> Binding::VertexAttrib2d("glVertexAttrib2d");
Function<Binding, void, GLuint, GLdouble, GLdouble> Binding::VertexAttrib2dARB("glVertexAttrib2dARB");
Function<Binding, void, GLuint, GLdouble, GLdouble> Binding::VertexAttrib2dNV("glVertexAttrib2dNV");
Function<Binding, void, GLuint, const GLdouble *> Binding::VertexAttrib2dv("glVertexAttrib2dv");
Function<Binding, void, GLuint, const GLdouble *> Binding::VertexAttrib2dvARB("glVertexAttrib2dvARB");
Function<Binding, void, GLuint, const GLdouble *> Binding::VertexAttrib2dvNV("glVertexAttrib2dvNV");
Function<Binding, void, GLuint, GLfloat, GLfloat> Binding::VertexAttrib2f("glVertexAttrib2f");
Function<Binding, void, GLuint, GLfloat, GLfloat> Binding::VertexAttrib2fARB("glVertexAttrib2fARB");
Function<Binding, void, GLuint, GLfloat, GLfloat> Binding::VertexAttrib2fNV("glVertexAttrib2fNV");
Function<Binding, void, GLuint, const GLfloat *> Binding::VertexAttrib2fv("glVertexAttrib2fv");
Function<Binding, void, GLuint, const GLfloat *> Binding::VertexAttrib2fvARB("glVertexAttrib2fvARB");
Function<Binding, void, GLuint, const GLfloat *> Binding::VertexAttrib2fvNV("glVertexAttrib2fvNV");
Function<Binding, void, GLuint, GLhalfNV, GLhalfNV> Binding::VertexAttrib2hNV("glVertexAttrib2hNV");
Function<Binding, void, GLuint, const GLhalfNV *> Binding::VertexAttrib2hvNV("glVertexAttrib2hvNV");
Function<Binding, void, GLuint, GLshort, GLshort> Binding::VertexAttrib2s("glVertexAttrib2s");
Function<Binding, void, GLuint, GLshort, GLshort> Binding::VertexAttrib2sARB("glVertexAttrib2sARB");
Function<Binding, void, GLuint, GLshort, GLshort> Binding::VertexAttrib2sNV("glVertexAttrib2sNV");
Function<Binding, void, GLuint, const GLshort *> Binding::VertexAttrib2sv("glVertexAttrib2sv");
Function<Binding, void, GLuint, const GLshort *> Binding::VertexAttrib2svARB("glVertexAttrib2svARB");
Function<Binding, void, GLuint, const GLshort *> Binding::VertexAttrib2svNV("glVertexAttrib2svNV");
Function<Binding, void, GLuint, GLdouble, GLdouble, GLdouble> Binding::VertexAttrib3d("glVertexAttrib3d");
Function<Binding, void, GLuint, GLdouble, GLdouble, GLdouble> Binding::VertexAttrib3dARB("glVertexAttrib3dARB");
Function<Binding, void, GLuint, GLdouble, GLdouble, GLdouble> Binding::VertexAttrib3dNV("glVertexAttrib3dNV");
Function<Binding, void, GLuint, const GLdouble *> Binding::VertexAttrib3dv("glVertexAttrib3dv");
Function<Binding, void, GLuint, const GLdouble *> Binding::VertexAttrib3dvARB("glVertexAttrib3dvARB");
Function<Binding, void, GLuint, const GLdouble *> Binding::VertexAttrib3dvNV("glVertexAttrib3dvNV");
Function<Binding, void, GLuint, GLfloat, GLfloat, GLfloat> Binding::VertexAttrib3f("glVertexAttrib3f");
Function<Binding, void, GLuint, GLfloat, GLfloat, GLfloat> Binding::VertexAttrib3fARB("glVertexAttrib3fARB");
Function<Binding, void, GLuint, GLfloat, GLfloat, GLfloat> Binding::VertexAttrib3fNV("glVertexAttrib3fNV");
Function<Binding, void, GLuint, const GLfloat *> Binding::VertexAttrib3fv("glVertexAttrib3fv");
Function<Binding, void, GLuint, const GLfloat *> Binding::VertexAttrib3fvARB("glVertexAttrib3fvARB");
Function<Binding, void, GLuint, const GLfloat *> Binding::VertexAttrib3fvNV("glVertexAttrib3fvNV");
Function<Binding, void, GLuint, GLhalfNV, GLhalfNV, GLhalfNV> Binding::VertexAttrib3hNV("glVertexAttrib3hNV");
Function<Binding, void, GLuint, const GLhalfNV *> Binding::VertexAttrib3hvNV("glVertexAttrib3hvNV");
Function<Binding, void, GLuint, GLshort, GLshort, GLshort> Binding::VertexAttrib3s("glVertexAttrib3s");
Function<Binding, void, GLuint, GLshort, GLshort, GLshort> Binding::VertexAttrib3sARB("glVertexAttrib3sARB");
Function<Binding, void, GLuint, GLshort, GLshort, GLshort> Binding::VertexAttrib3sNV("glVertexAttrib3sNV");
Function<Binding, void, GLuint, const GLshort *> Binding::VertexAttrib3sv("glVertexAttrib3sv");
Function<Binding, void, GLuint, const GLshort *> Binding::VertexAttrib3svARB("glVertexAttrib3svARB");
Function<Binding, void, GLuint, const GLshort *> Binding::VertexAttrib3svNV("glVertexAttrib3svNV");
Function<Binding, void, GLuint, const GLbyte *> Binding::VertexAttrib4Nbv("glVertexAttrib4Nbv");
Function<Binding, void, GLuint, const GLbyte *> Binding::VertexAttrib4NbvARB("glVertexAttrib4NbvARB");
Function<Binding, void, GLuint, const GLint *> Binding::VertexAttrib4Niv("glVertexAttrib4Niv");
Function<Binding, void, GLuint, const GLint *> Binding::VertexAttrib4NivARB("glVertexAttrib4NivARB");
Function<Binding, void, GLuint, const GLshort *> Binding::VertexAttrib4Nsv("glVertexAttrib4Nsv");
Function<Binding, void, GLuint, const GLshort *> Binding::VertexAttrib4NsvARB("glVertexAttrib4NsvARB");
Function<Binding, void, GLuint, GLubyte, GLubyte, GLubyte, GLubyte> Binding::VertexAttrib4Nub("glVertexAttrib4Nub");
Function<Binding, void, GLuint, GLubyte, GLubyte, GLubyte, GLubyte> Binding::VertexAttrib4NubARB("glVertexAttrib4NubARB");
Function<Binding, void, GLuint, const GLubyte *> Binding::VertexAttrib4Nubv("glVertexAttrib4Nubv");
Function<Binding, void, GLuint, const GLubyte *> Binding::VertexAttrib4NubvARB("glVertexAttrib4NubvARB");
Function<Binding, void, GLuint, const GLuint *> Binding::VertexAttrib4Nuiv("glVertexAttrib4Nuiv");
Function<Binding, void, GLuint, const GLuint *> Binding::VertexAttrib4NuivARB("glVertexAttrib4NuivARB");
Function<Binding, void, GLuint, const GLushort *> Binding::VertexAttrib4Nusv("glVertexAttrib4Nusv");
Function<Binding, void, GLuint, const GLushort *> Binding::VertexAttrib4NusvARB("glVertexAttrib4NusvARB");
Function<Binding, void, GLuint, const GLbyte *> Binding::VertexAttrib4bv("glVertexAttrib4bv");
Function<Binding, void, GLuint, const GLbyte *> Binding::VertexAttrib4bvARB("glVertexAttrib4bvARB");
Function<Binding, void, GLuint, GLdouble, GLdouble, GLdouble, GLdouble> Binding::VertexAttrib4d("glVertexAttrib4d");
Function<Binding, void, GLuint, GLdouble, GLdouble, GLdouble, GLdouble> Binding::VertexAttrib4dARB("glVertexAttrib4dARB");
Function<Binding, void, GLuint, GLdouble, GLdouble, GLdouble, GLdouble> Binding::VertexAttrib4dNV("glVertexAttrib4dNV");
Function<Binding, void, GLuint, const GLdouble *> Binding::VertexAttrib4dv("glVertexAttrib4dv");
Function<Binding, void, GLuint, const GLdouble *> Binding::VertexAttrib4dvARB("glVertexAttrib4dvARB");
Function<Binding, void, GLuint, const GLdouble *> Binding::VertexAttrib4dvNV("glVertexAttrib4dvNV");
Function<Binding, void, GLuint, GLfloat, GLfloat, GLfloat, GLfloat> Binding::VertexAttrib4f("glVertexAttrib4f");
Function<Binding, void, GLuint, GLfloat, GLfloat, GLfloat, GLfloat> Binding::VertexAttrib4fARB("glVertexAttrib4fARB");
Function<Binding, void, GLuint, GLfloat, GLfloat, GLfloat, GLfloat> Binding::VertexAttrib4fNV("glVertexAttrib4fNV");
Function<Binding, void, GLuint, const GLfloat *> Binding::VertexAttrib4fv("glVertexAttrib4fv");
Function<Binding, void, GLuint, const GLfloat *> Binding::VertexAttrib4fvARB("glVertexAttrib4fvARB");
Function<Binding, void, GLuint, const GLfloat *> Binding::VertexAttrib4fvNV("glVertexAttrib4fvNV");
Function<Binding, void, GLuint, GLhalfNV, GLhalfNV, GLhalfNV, GLhalfNV> Binding::VertexAttrib4hNV("glVertexAttrib4hNV");
Function<Binding, void, GLuint, const GLhalfNV *> Binding::VertexAttrib4hvNV("glVertexAttrib4hvNV");
Function<Binding, void, GLuint, const GLint *> Binding::VertexAttrib4iv("glVertexAttrib4iv");
Function<Binding, void, GLuint, const GLint *> Binding::VertexAttrib4ivARB("glVertexAttrib4ivARB");
Function<Binding, void, GLuint, GLshort, GLshort, GLshort, GLshort> Binding::VertexAttrib4s("glVertexAttrib4s");
Function<Binding, void, GLuint, GLshort, GLshort, GLshort, GLshort> Binding::VertexAttrib4sARB("glVertexAttrib4sARB");
Function<Binding, void, GLuint, GLshort, GLshort, GLshort, GLshort> Binding::VertexAttrib4sNV("glVertexAttrib4sNV");
Function<Binding, void, GLuint, const GLshort *> Binding::VertexAttrib4sv("glVertexAttrib4sv");
Function<Binding, void, GLuint, const GLshort *> Binding::VertexAttrib4svARB("glVertexAttrib4svARB");
Function<Binding, void, GLuint, const GLshort *> Binding::VertexAttrib4svNV("glVertexAttrib4svNV");
Function<Binding, void, GLuint, GLubyte, GLubyte, GLubyte, GLubyte> Binding::VertexAttrib4ubNV("glVertexAttrib4ubNV");
Function<Binding, void, GLuint, const GLubyte *> Binding::VertexAttrib4ubv("glVertexAttrib4ubv");
Function<Binding, void, GLuint, const GLubyte *> Binding::VertexAttrib4ubvARB("glVertexAttrib4ubvARB");
Function<Binding, void, GLuint, const GLubyte *> Binding::VertexAttrib4ubvNV("glVertexAttrib4ubvNV");
Function<Binding, void, GLuint, const GLuint *> Binding::VertexAttrib4uiv("glVertexAttrib4uiv");
Function<Binding, void, GLuint, const GLuint *> Binding::VertexAttrib4uivARB("glVertexAttrib4uivARB");
Function<Binding, void, GLuint, const GLushort *> Binding::VertexAttrib4usv("glVertexAttrib4usv");
Function<Binding, void, GLuint, const GLushort *> Binding::VertexAttrib4usvARB("glVertexAttrib4usvARB");
Function<Binding, void, GLuint, GLint, GLenum, GLboolean, GLsizei, GLuint, GLuint> Binding::VertexAttribArrayObjectATI("glVertexAttribArrayObjectATI");
Function<Binding, void, GLuint, GLuint> Binding::VertexAttribBinding("glVertexAttribBinding");
Function<Binding, void, GLuint, GLuint> Binding::VertexAttribDivisor("glVertexAttribDivisor");
Function<Binding, void, GLuint, GLuint> Binding::VertexAttribDivisorARB("glVertexAttribDivisorARB");
Function<Binding, void, GLuint, GLint, GLenum, GLboolean, GLuint> Binding::VertexAttribFormat("glVertexAttribFormat");
Function<Binding, void, GLuint, GLint, GLenum, GLboolean, GLsizei> Binding::VertexAttribFormatNV("glVertexAttribFormatNV");
Function<Binding, void, GLuint, GLint> Binding::VertexAttribI1i("glVertexAttribI1i");
Function<Binding, void, GLuint, GLint> Binding::VertexAttribI1iEXT("glVertexAttribI1iEXT");
Function<Binding, void, GLuint, const GLint *> Binding::VertexAttribI1iv("glVertexAttribI1iv");
Function<Binding, void, GLuint, const GLint *> Binding::VertexAttribI1ivEXT("glVertexAttribI1ivEXT");
Function<Binding, void, GLuint, GLuint> Binding::VertexAttribI1ui("glVertexAttribI1ui");
Function<Binding, void, GLuint, GLuint> Binding::VertexAttribI1uiEXT("glVertexAttribI1uiEXT");
Function<Binding, void, GLuint, const GLuint *> Binding::VertexAttribI1uiv("glVertexAttribI1uiv");
Function<Binding, void, GLuint, const GLuint *> Binding::VertexAttribI1uivEXT("glVertexAttribI1uivEXT");
Function<Binding, void, GLuint, GLint, GLint> Binding::VertexAttribI2i("glVertexAttribI2i");
Function<Binding, void, GLuint, GLint, GLint> Binding::VertexAttribI2iEXT("glVertexAttribI2iEXT");
Function<Binding, void, GLuint, const GLint *> Binding::VertexAttribI2iv("glVertexAttribI2iv");
Function<Binding, void, GLuint, const GLint *> Binding::VertexAttribI2ivEXT("glVertexAttribI2ivEXT");
Function<Binding, void, GLuint, GLuint, GLuint> Binding::VertexAttribI2ui("glVertexAttribI2ui");
Function<Binding, void, GLuint, GLuint, GLuint> Binding::VertexAttribI2uiEXT("glVertexAttribI2uiEXT");
Function<Binding, void, GLuint, const GLuint *> Binding::VertexAttribI2uiv("glVertexAttribI2uiv");
Function<Binding, void, GLuint, const GLuint *> Binding::VertexAttribI2uivEXT("glVertexAttribI2uivEXT");
Function<Binding, void, GLuint, GLint, GLint, GLint> Binding::VertexAttribI3i("glVertexAttribI3i");
Function<Binding, void, GLuint, GLint, GLint, GLint> Binding::VertexAttribI3iEXT("glVertexAttribI3iEXT");
Function<Binding, void, GLuint, const GLint *> Binding::VertexAttribI3iv("glVertexAttribI3iv");
Function<Binding, void, GLuint, const GLint *> Binding::VertexAttribI3ivEXT("glVertexAttribI3ivEXT");
Function<Binding, void, GLuint, GLuint, GLuint, GLuint> Binding::VertexAttribI3ui("glVertexAttribI3ui");
Function<Binding, void, GLuint, GLuint, GLuint, GLuint> Binding::VertexAttribI3uiEXT("glVertexAttribI3uiEXT");
Function<Binding, void, GLuint, const GLuint *> Binding::VertexAttribI3uiv("glVertexAttribI3uiv");
Function<Binding, void, GLuint, const GLuint *> Binding::VertexAttribI3uivEXT("glVertexAttribI3uivEXT");
Function<Binding, void, GLuint, const GLbyte *> Binding::VertexAttribI4bv("glVertexAttribI4bv");
Function<Binding, void, GLuint, const GLbyte *> Binding::VertexAttribI4bvEXT("glVertexAttribI4bvEXT");
Function<Binding, void, GLuint, GLint, GLint, GLint, GLint> Binding::VertexAttribI4i("glVertexAttribI4i");
Function<Binding, void, GLuint, GLint, GLint, GLint, GLint> Binding::VertexAttribI4iEXT("glVertexAttribI4iEXT");
Function<Binding, void, GLuint, const GLint *> Binding::VertexAttribI4iv("glVertexAttribI4iv");
Function<Binding, void, GLuint, const GLint *> Binding::VertexAttribI4ivEXT("glVertexAttribI4ivEXT");
Function<Binding, void, GLuint, const GLshort *> Binding::VertexAttribI4sv("glVertexAttribI4sv");
Function<Binding, void, GLuint, const GLshort *> Binding::VertexAttribI4svEXT("glVertexAttribI4svEXT");
Function<Binding, void, GLuint, const GLubyte *> Binding::VertexAttribI4ubv("glVertexAttribI4ubv");
Function<Binding, void, GLuint, const GLubyte *> Binding::VertexAttribI4ubvEXT("glVertexAttribI4ubvEXT");
Function<Binding, void, GLuint, GLuint, GLuint, GLuint, GLuint> Binding::VertexAttribI4ui("glVertexAttribI4ui");
Function<Binding, void, GLuint, GLuint, GLuint, GLuint, GLuint> Binding::VertexAttribI4uiEXT("glVertexAttribI4uiEXT");
Function<Binding, void, GLuint, const GLuint *> Binding::VertexAttribI4uiv("glVertexAttribI4uiv");
Function<Binding, void, GLuint, const GLuint *> Binding::VertexAttribI4uivEXT("glVertexAttribI4uivEXT");
Function<Binding, void, GLuint, const GLushort *> Binding::VertexAttribI4usv("glVertexAttribI4usv");
Function<Binding, void, GLuint, const GLushort *> Binding::VertexAttribI4usvEXT("glVertexAttribI4usvEXT");
Function<Binding, void, GLuint, GLint, GLenum, GLuint> Binding::VertexAttribIFormat("glVertexAttribIFormat");
Function<Binding, void, GLuint, GLint, GLenum, GLsizei> Binding::VertexAttribIFormatNV("glVertexAttribIFormatNV");
Function<Binding, void, GLuint, GLint, GLenum, GLsizei, const void *> Binding::VertexAttribIPointer("glVertexAttribIPointer");
Function<Binding, void, GLuint, GLint, GLenum, GLsizei, const void *> Binding::VertexAttribIPointerEXT("glVertexAttribIPointerEXT");
Function<Binding, void, GLuint, GLdouble> Binding::VertexAttribL1d("glVertexAttribL1d");
Function<Binding, void, GLuint, GLdouble> Binding::VertexAttribL1dEXT("glVertexAttribL1dEXT");
Function<Binding, void, GLuint, const GLdouble *> Binding::VertexAttribL1dv("glVertexAttribL1dv");
Function<Binding, void, GLuint, const GLdouble *> Binding::VertexAttribL1dvEXT("glVertexAttribL1dvEXT");
Function<Binding, void, GLuint, GLint64EXT> Binding::VertexAttribL1i64NV("glVertexAttribL1i64NV");
Function<Binding, void, GLuint, const GLint64EXT *> Binding::VertexAttribL1i64vNV("glVertexAttribL1i64vNV");
Function<Binding, void, GLuint, GLuint64EXT> Binding::VertexAttribL1ui64ARB("glVertexAttribL1ui64ARB");
Function<Binding, void, GLuint, GLuint64EXT> Binding::VertexAttribL1ui64NV("glVertexAttribL1ui64NV");
Function<Binding, void, GLuint, const GLuint64EXT *> Binding::VertexAttribL1ui64vARB("glVertexAttribL1ui64vARB");
Function<Binding, void, GLuint, const GLuint64EXT *> Binding::VertexAttribL1ui64vNV("glVertexAttribL1ui64vNV");
Function<Binding, void, GLuint, GLdouble, GLdouble> Binding::VertexAttribL2d("glVertexAttribL2d");
Function<Binding, void, GLuint, GLdouble, GLdouble> Binding::VertexAttribL2dEXT("glVertexAttribL2dEXT");
Function<Binding, void, GLuint, const GLdouble *> Binding::VertexAttribL2dv("glVertexAttribL2dv");
Function<Binding, void, GLuint, const GLdouble *> Binding::VertexAttribL2dvEXT("glVertexAttribL2dvEXT");
Function<Binding, void, GLuint, GLint64EXT, GLint64EXT> Binding::VertexAttribL2i64NV("glVertexAttribL2i64NV");
Function<Binding, void, GLuint, const GLint64EXT *> Binding::VertexAttribL2i64vNV("glVertexAttribL2i64vNV");
Function<Binding, void, GLuint, GLuint64EXT, GLuint64EXT> Binding::VertexAttribL2ui64NV("glVertexAttribL2ui64NV");
Function<Binding, void, GLuint, const GLuint64EXT *> Binding::VertexAttribL2ui64vNV("glVertexAttribL2ui64vNV");
Function<Binding, void, GLuint, GLdouble, GLdouble, GLdouble> Binding::VertexAttribL3d("glVertexAttribL3d");
Function<Binding, void, GLuint, GLdouble, GLdouble, GLdouble> Binding::VertexAttribL3dEXT("glVertexAttribL3dEXT");
Function<Binding, void, GLuint, const GLdouble *> Binding::VertexAttribL3dv("glVertexAttribL3dv");
Function<Binding, void, GLuint, const GLdouble *> Binding::VertexAttribL3dvEXT("glVertexAttribL3dvEXT");
Function<Binding, void, GLuint, GLint64EXT, GLint64EXT, GLint64EXT> Binding::VertexAttribL3i64NV("glVertexAttribL3i64NV");
Function<Binding, void, GLuint, const GLint64EXT *> Binding::VertexAttribL3i64vNV("glVertexAttribL3i64vNV");
Function<Binding, void, GLuint, GLuint64EXT, GLuint64EXT, GLuint64EXT> Binding::VertexAttribL3ui64NV("glVertexAttribL3ui64NV");
Function<Binding, void, GLuint, const GLuint64EXT *> Binding::VertexAttribL3ui64vNV("glVertexAttribL3ui64vNV");
Function<Binding, void, GLuint, GLdouble, GLdouble, GLdouble, GLdouble> Binding::VertexAttribL4d("glVertexAttribL4d");
Function<Binding, void, GLuint, GLdouble, GLdouble, GLdouble, GLdouble> Binding::VertexAttribL4dEXT("glVertexAttribL4dEXT");
Function<Binding, void, GLuint, const GLdouble *> Binding::VertexAttribL4dv("glVertexAttribL4dv");
Function<Binding, void, GLuint, const GLdouble *> Binding::VertexAttribL4dvEXT("glVertexAttribL4dvEXT");
Function<Binding, void, GLuint, GLint64EXT, GLint64EXT, GLint64EXT, GLint64EXT> Binding::VertexAttribL4i64NV("glVertexAttribL4i64NV");
Function<Binding, void, GLuint, const GLint64EXT *> Binding::VertexAttribL4i64vNV("glVertexAttribL4i64vNV");
Function<Binding, void, GLuint, GLuint64EXT, GLuint64EXT, GLuint64EXT, GLuint64EXT> Binding::VertexAttribL4ui64NV("glVertexAttribL4ui64NV");
Function<Binding, void, GLuint, const GLuint64EXT *> Binding::VertexAttribL4ui64vNV("glVertexAttribL4ui64vNV");
Function<Binding, void, GLuint, GLint, GLenum, GLuint> Binding::VertexAttribLFormat("glVertexAttribLFormat");
Function<Binding, void, GLuint, GLint, GLenum, GLsizei> Binding::VertexAttribLFormatNV("glVertexAttribLFormatNV");
Function<Binding, void, GLuint, GLint, GLenum, GLsizei, const void *> Binding::VertexAttribLPointer("glVertexAttribLPointer");
Function<Binding, void, GLuint, GLint, GLenum, GLsizei, const void *> Binding::VertexAttribLPointerEXT("glVertexAttribLPointerEXT");
Function<Binding, void, GLuint, GLenum, GLboolean, GLuint> Binding::VertexAttribP1ui("glVertexAttribP1ui");
Function<Binding, void, GLuint, GLenum, GLboolean, const GLuint *> Binding::VertexAttribP1uiv("glVertexAttribP1uiv");
Function<Binding, void, GLuint, GLenum, GLboolean, GLuint> Binding::VertexAttribP2ui("glVertexAttribP2ui");
Function<Binding, void, GLuint, GLenum, GLboolean, const GLuint *> Binding::VertexAttribP2uiv("glVertexAttribP2uiv");
Function<Binding, void, GLuint, GLenum, GLboolean, GLuint> Binding::VertexAttribP3ui("glVertexAttribP3ui");
Function<Binding, void, GLuint, GLenum, GLboolean, const GLuint *> Binding::VertexAttribP3uiv("glVertexAttribP3uiv");
Function<Binding, void, GLuint, GLenum, GLboolean, GLuint> Binding::VertexAttribP4ui("glVertexAttribP4ui");
Function<Binding, void, GLuint, GLenum, GLboolean, const GLuint *> Binding::VertexAttribP4uiv("glVertexAttribP4uiv");
Function<Binding, void, GLuint, GLenum, GLint> Binding::VertexAttribParameteriAMD("glVertexAttribParameteriAMD");
Function<Binding, void, GLuint, GLint, GLenum, GLboolean, GLsizei, const void *> Binding::VertexAttribPointer("glVertexAttribPointer");
Function<Binding, void, GLuint, GLint, GLenum, GLboolean, GLsizei, const void *> Binding::VertexAttribPointerARB("glVertexAttribPointerARB");
Function<Binding, void, GLuint, GLint, GLenum, GLsizei, const void *> Binding::VertexAttribPointerNV("glVertexAttribPointerNV");
Function<Binding, void, GLuint, GLsizei, const GLdouble *> Binding::VertexAttribs1dvNV("glVertexAttribs1dvNV");
Function<Binding, void, GLuint, GLsizei, const GLfloat *> Binding::VertexAttribs1fvNV("glVertexAttribs1fvNV");
Function<Binding, void, GLuint, GLsizei, const GLhalfNV *> Binding::VertexAttribs1hvNV("glVertexAttribs1hvNV");
Function<Binding, void, GLuint, GLsizei, const GLshort *> Binding::VertexAttribs1svNV("glVertexAttribs1svNV");
Function<Binding, void, GLuint, GLsizei, const GLdouble *> Binding::VertexAttribs2dvNV("glVertexAttribs2dvNV");
Function<Binding, void, GLuint, GLsizei, const GLfloat *> Binding::VertexAttribs2fvNV("glVertexAttribs2fvNV");
Function<Binding, void, GLuint, GLsizei, const GLhalfNV *> Binding::VertexAttribs2hvNV("glVertexAttribs2hvNV");
Function<Binding, void, GLuint, GLsizei, const GLshort *> Binding::VertexAttribs2svNV("glVertexAttribs2svNV");
Function<Binding, void, GLuint, GLsizei, const GLdouble *> Binding::VertexAttribs3dvNV("glVertexAttribs3dvNV");
Function<Binding, void, GLuint, GLsizei, const GLfloat *> Binding::VertexAttribs3fvNV("glVertexAttribs3fvNV");
Function<Binding, void, GLuint, GLsizei, const GLhalfNV *> Binding::VertexAttribs3hvNV("glVertexAttribs3hvNV");
Function<Binding, void, GLuint, GLsizei, const GLshort *> Binding::VertexAttribs3svNV("glVertexAttribs3svNV");
Function<Binding, void, GLuint, GLsizei, const GLdouble *> Binding::VertexAttribs4dvNV("glVertexAttribs4dvNV");
Function<Binding, void, GLuint, GLsizei, const GLfloat *> Binding::VertexAttribs4fvNV("glVertexAttribs4fvNV");
Function<Binding, void, GLuint, GLsizei, const GLhalfNV *> Binding::VertexAttribs4hvNV("glVertexAttribs4hvNV");
Function<Binding, void, GLuint, GLsizei, const GLshort *> Binding::VertexAttribs4svNV("glVertexAttribs4svNV");
Function<Binding, void, GLuint, GLsizei, const GLubyte *> Binding::VertexAttribs4ubvNV("glVertexAttribs4ubvNV");
Function<Binding, void, GLuint, GLuint> Binding::VertexBindingDivisor("glVertexBindingDivisor");
Function<Binding, void, GLint> Binding::VertexBlendARB("glVertexBlendARB");
Function<Binding, void, GLenum, GLfloat> Binding::VertexBlendEnvfATI("glVertexBlendEnvfATI");
Function<Binding, void, GLenum, GLint> Binding::VertexBlendEnviATI("glVertexBlendEnviATI");
Function<Binding, void, GLint, GLenum, GLsizei> Binding::VertexFormatNV("glVertexFormatNV");
Function<Binding, void, GLenum, GLuint> Binding::VertexP2ui("glVertexP2ui");
Function<Binding, void, GLenum, const GLuint *> Binding::VertexP2uiv("glVertexP2uiv");
Function<Binding, void, GLenum, GLuint> Binding::VertexP3ui("glVertexP3ui");
Function<Binding, void, GLenum, const GLuint *> Binding::VertexP3uiv("glVertexP3uiv");
Function<Binding, void, GLenum, GLuint> Binding::VertexP4ui("glVertexP4ui");
Function<Binding, void, GLenum, const GLuint *> Binding::VertexP4uiv("glVertexP4uiv");
Function<Binding, void, GLint, GLenum, GLsizei, const void *> Binding::VertexPointer("glVertexPointer");
Function<Binding, void, GLint, GLenum, GLsizei, GLsizei, const void *> Binding::VertexPointerEXT("glVertexPointerEXT");
Function<Binding, void, GLint, GLenum, GLint, const void **, GLint> Binding::VertexPointerListIBM("glVertexPointerListIBM");
Function<Binding, void, GLint, GLenum, const void **> Binding::VertexPointervINTEL("glVertexPointervINTEL");
Function<Binding, void, GLenum, GLdouble> Binding::VertexStream1dATI("glVertexStream1dATI");
Function<Binding, void, GLenum, const GLdouble *> Binding::VertexStream1dvATI("glVertexStream1dvATI");
Function<Binding, void, GLenum, GLfloat> Binding::VertexStream1fATI("glVertexStream1fATI");
Function<Binding, void, GLenum, const GLfloat *> Binding::VertexStream1fvATI("glVertexStream1fvATI");
Function<Binding, void, GLenum, GLint> Binding::VertexStream1iATI("glVertexStream1iATI");
Function<Binding, void, GLenum, const GLint *> Binding::VertexStream1ivATI("glVertexStream1ivATI");
Function<Binding, void, GLenum, GLshort> Binding::VertexStream1sATI("glVertexStream1sATI");
Function<Binding, void, GLenum, const GLshort *> Binding::VertexStream1svATI("glVertexStream1svATI");
Function<Binding, void, GLenum, GLdouble, GLdouble> Binding::VertexStream2dATI("glVertexStream2dATI");
Function<Binding, void, GLenum, const GLdouble *> Binding::VertexStream2dvATI("glVertexStream2dvATI");
Function<Binding, void, GLenum, GLfloat, GLfloat> Binding::VertexStream2fATI("glVertexStream2fATI");
Function<Binding, void, GLenum, const GLfloat *> Binding::VertexStream2fvATI("glVertexStream2fvATI");
Function<Binding, void, GLenum, GLint, GLint> Binding::VertexStream2iATI("glVertexStream2iATI");
Function<Binding, void, GLenum, const GLint *> Binding::VertexStream2ivATI("glVertexStream2ivATI");
Function<Binding, void, GLenum, GLshort, GLshort> Binding::VertexStream2sATI("glVertexStream2sATI");
Function<Binding, void, GLenum, const GLshort *> Binding::VertexStream2svATI("glVertexStream2svATI");
Function<Binding, void, GLenum, GLdouble, GLdouble, GLdouble> Binding::VertexStream3dATI("glVertexStream3dATI");
Function<Binding, void, GLenum, const GLdouble *> Binding::VertexStream3dvATI("glVertexStream3dvATI");
Function<Binding, void, GLenum, GLfloat, GLfloat, GLfloat> Binding::VertexStream3fATI("glVertexStream3fATI");
Function<Binding, void, GLenum, const GLfloat *> Binding::VertexStream3fvATI("glVertexStream3fvATI");
Function<Binding, void, GLenum, GLint, GLint, GLint> Binding::VertexStream3iATI("glVertexStream3iATI");
Function<Binding, void, GLenum, const GLint *> Binding::VertexStream3ivATI("glVertexStream3ivATI");
Function<Binding, void, GLenum, GLshort, GLshort, GLshort> Binding::VertexStream3sATI("glVertexStream3sATI");
Function<Binding, void, GLenum, const GLshort *> Binding::VertexStream3svATI("glVertexStream3svATI");
Function<Binding, void, GLenum, GLdouble, GLdouble, GLdouble, GLdouble> Binding::VertexStream4dATI("glVertexStream4dATI");
Function<Binding, void, GLenum, const GLdouble *> Binding::VertexStream4dvATI("glVertexStream4dvATI");
Function<Binding, void, GLenum, GLfloat, GLfloat, GLfloat, GLfloat> Binding::VertexStream4fATI("glVertexStream4fATI");
Function<Binding, void, GLenum, const GLfloat *> Binding::VertexStream4fvATI("glVertexStream4fvATI");
Function<Binding, void, GLenum, GLint, GLint, GLint, GLint> Binding::VertexStream4iATI("glVertexStream4iATI");
Function<Binding, void, GLenum, const GLint *> Binding::VertexStream4ivATI("glVertexStream4ivATI");
Function<Binding, void, GLenum, GLshort, GLshort, GLshort, GLshort> Binding::VertexStream4sATI("glVertexStream4sATI");
Function<Binding, void, GLenum, const GLshort *> Binding::VertexStream4svATI("glVertexStream4svATI");
Function<Binding, void, GLint, GLenum, GLsizei, const void *> Binding::VertexWeightPointerEXT("glVertexWeightPointerEXT");
Function<Binding, void, GLfloat> Binding::VertexWeightfEXT("glVertexWeightfEXT");
Function<Binding, void, const GLfloat *> Binding::VertexWeightfvEXT("glVertexWeightfvEXT");
Function<Binding, void, GLhalfNV> Binding::VertexWeighthNV("glVertexWeighthNV");
Function<Binding, void, const GLhalfNV *> Binding::VertexWeighthvNV("glVertexWeighthvNV");
Function<Binding, GLenum, GLuint, GLuint *, GLuint64EXT *> Binding::VideoCaptureNV("glVideoCaptureNV");
Function<Binding, void, GLuint, GLuint, GLenum, const GLdouble *> Binding::VideoCaptureStreamParameterdvNV("glVideoCaptureStreamParameterdvNV");
Function<Binding, void, GLuint, GLuint, GLenum, const GLfloat *> Binding::VideoCaptureStreamParameterfvNV("glVideoCaptureStreamParameterfvNV");
Function<Binding, void, GLuint, GLuint, GLenum, const GLint *> Binding::VideoCaptureStreamParameterivNV("glVideoCaptureStreamParameterivNV");
Function<Binding, void, GLint, GLint, GLsizei, GLsizei> Binding::Viewport("glViewport");
Function<Binding, void, GLuint, GLsizei, const GLfloat *> Binding::ViewportArrayv("glViewportArrayv");
Function<Binding, void, GLuint, GLfloat, GLfloat, GLfloat, GLfloat> Binding::ViewportIndexedf("glViewportIndexedf");
Function<Binding, void, GLuint, const GLfloat *> Binding::ViewportIndexedfv("glViewportIndexedfv");
Function<Binding, void, GLuint, GLfloat, GLfloat> Binding::ViewportPositionWScaleNV("glViewportPositionWScaleNV");
Function<Binding, void, GLuint, GLenum, GLenum, GLenum, GLenum> Binding::ViewportSwizzleNV("glViewportSwizzleNV");



} // namespace glbinding
