
#include "Binding_pch.h"


using namespace gl;


namespace glbinding
{


Function<Binding, void, GLuint> Binding::CallCommandListNV("glCallCommandListNV");
Function<Binding, void, GLuint> Binding::CallList("glCallList");
Function<Binding, void, GLsizei, GLenum, const void *> Binding::CallLists("glCallLists");
Function<Binding, GLenum, GLenum> Binding::CheckFramebufferStatus("glCheckFramebufferStatus");
Function<Binding, GLenum, GLenum> Binding::CheckFramebufferStatusEXT("glCheckFramebufferStatusEXT");
Function<Binding, GLenum, GLuint, GLenum> Binding::CheckNamedFramebufferStatus("glCheckNamedFramebufferStatus");
Function<Binding, GLenum, GLuint, GLenum> Binding::CheckNamedFramebufferStatusEXT("glCheckNamedFramebufferStatusEXT");
Function<Binding, void, GLenum, GLboolean> Binding::ClampColor("glClampColor");
Function<Binding, void, GLenum, GLboolean> Binding::ClampColorARB("glClampColorARB");
Function<Binding, void, ClearBufferMask> Binding::Clear("glClear");
Function<Binding, void, GLfloat, GLfloat, GLfloat, GLfloat> Binding::ClearAccum("glClearAccum");
Function<Binding, void, GLfixed, GLfixed, GLfixed, GLfixed> Binding::ClearAccumxOES("glClearAccumxOES");
Function<Binding, void, GLenum, GLenum, GLenum, GLenum, const void *> Binding::ClearBufferData("glClearBufferData");
Function<Binding, void, GLenum, GLenum, GLintptr, GLsizeiptr, GLenum, GLenum, const void *> Binding::ClearBufferSubData("glClearBufferSubData");
Function<Binding, void, GLenum, GLint, GLfloat, GLint> Binding::ClearBufferfi("glClearBufferfi");
Function<Binding, void, GLenum, GLint, const GLfloat *> Binding::ClearBufferfv("glClearBufferfv");
Function<Binding, void, GLenum, GLint, const GLint *> Binding::ClearBufferiv("glClearBufferiv");
Function<Binding, void, GLenum, GLint, const GLuint *> Binding::ClearBufferuiv("glClearBufferuiv");
Function<Binding, void, GLfloat, GLfloat, GLfloat, GLfloat> Binding::ClearColor("glClearColor");
Function<Binding, void, GLint, GLint, GLint, GLint> Binding::ClearColorIiEXT("glClearColorIiEXT");
Function<Binding, void, GLuint, GLuint, GLuint, GLuint> Binding::ClearColorIuiEXT("glClearColorIuiEXT");
Function<Binding, void, GLfixed, GLfixed, GLfixed, GLfixed> Binding::ClearColorxOES("glClearColorxOES");
Function<Binding, void, GLdouble> Binding::ClearDepth("glClearDepth");
Function<Binding, void, GLdouble> Binding::ClearDepthdNV("glClearDepthdNV");
Function<Binding, void, GLfloat> Binding::ClearDepthf("glClearDepthf");
Function<Binding, void, GLclampf> Binding::ClearDepthfOES("glClearDepthfOES");
Function<Binding, void, GLfixed> Binding::ClearDepthxOES("glClearDepthxOES");
Function<Binding, void, GLfloat> Binding::ClearIndex("glClearIndex");
Function<Binding, void, GLuint, GLenum, GLenum, GLenum, const void *> Binding::ClearNamedBufferData("glClearNamedBufferData");
Function<Binding, void, GLuint, GLenum, GLenum, GLenum, const void *> Binding::ClearNamedBufferDataEXT("glClearNamedBufferDataEXT");
Function<Binding, void, GLuint, GLenum, GLintptr, GLsizeiptr, GLenum, GLenum, const void *> Binding::ClearNamedBufferSubData("glClearNamedBufferSubData");
Function<Binding, void, GLuint, GLenum, GLsizeiptr, GLsizeiptr, GLenum, GLenum, const void *> Binding::ClearNamedBufferSubDataEXT("glClearNamedBufferSubDataEXT");
Function<Binding, void, GLuint, GLenum, GLint, GLfloat, GLint> Binding::ClearNamedFramebufferfi("glClearNamedFramebufferfi");
Function<Binding, void, GLuint, GLenum, GLint, const GLfloat *> Binding::ClearNamedFramebufferfv("glClearNamedFramebufferfv");
Function<Binding, void, GLuint, GLenum, GLint, const GLint *> Binding::ClearNamedFramebufferiv("glClearNamedFramebufferiv");
Function<Binding, void, GLuint, GLenum, GLint, const GLuint *> Binding::ClearNamedFramebufferuiv("glClearNamedFramebufferuiv");
Function<Binding, void, GLint> Binding::ClearStencil("glClearStencil");
Function<Binding, void, GLuint, GLint, GLenum, GLenum, const void *> Binding::ClearTexImage("glClearTexImage");
Function<Binding, void, GLuint, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLenum, const void *> Binding::ClearTexSubImage("glClearTexSubImage");
Function<Binding, void, GLenum> Binding::ClientActiveTexture("glClientActiveTexture");
Function<Binding, void, GLenum> Binding::ClientActiveTextureARB("glClientActiveTextureARB");
Function<Binding, void, GLenum> Binding::ClientActiveVertexStreamATI("glClientActiveVertexStreamATI");
Function<Binding, void, ClientAttribMask> Binding::ClientAttribDefaultEXT("glClientAttribDefaultEXT");
Function<Binding, GLenum, GLsync, SyncObjectMask, GLuint64> Binding::ClientWaitSync("glClientWaitSync");
Function<Binding, void, GLenum, GLenum> Binding::ClipControl("glClipControl");
Function<Binding, void, GLenum, const GLdouble *> Binding::ClipPlane("glClipPlane");
Function<Binding, void, GLenum, const GLfloat *> Binding::ClipPlanefOES("glClipPlanefOES");
Function<Binding, void, GLenum, const GLfixed *> Binding::ClipPlanexOES("glClipPlanexOES");
Function<Binding, void, GLbyte, GLbyte, GLbyte> Binding::Color3b("glColor3b");
Function<Binding, void, const GLbyte *> Binding::Color3bv("glColor3bv");
Function<Binding, void, GLdouble, GLdouble, GLdouble> Binding::Color3d("glColor3d");
Function<Binding, void, const GLdouble *> Binding::Color3dv("glColor3dv");
Function<Binding, void, GLfloat, GLfloat, GLfloat> Binding::Color3f("glColor3f");
Function<Binding, void, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat> Binding::Color3fVertex3fSUN("glColor3fVertex3fSUN");
Function<Binding, void, const GLfloat *, const GLfloat *> Binding::Color3fVertex3fvSUN("glColor3fVertex3fvSUN");
Function<Binding, void, const GLfloat *> Binding::Color3fv("glColor3fv");
Function<Binding, void, GLhalfNV, GLhalfNV, GLhalfNV> Binding::Color3hNV("glColor3hNV");
Function<Binding, void, const GLhalfNV *> Binding::Color3hvNV("glColor3hvNV");
Function<Binding, void, GLint, GLint, GLint> Binding::Color3i("glColor3i");
Function<Binding, void, const GLint *> Binding::Color3iv("glColor3iv");
Function<Binding, void, GLshort, GLshort, GLshort> Binding::Color3s("glColor3s");
Function<Binding, void, const GLshort *> Binding::Color3sv("glColor3sv");
Function<Binding, void, GLubyte, GLubyte, GLubyte> Binding::Color3ub("glColor3ub");
Function<Binding, void, const GLubyte *> Binding::Color3ubv("glColor3ubv");
Function<Binding, void, GLuint, GLuint, GLuint> Binding::Color3ui("glColor3ui");
Function<Binding, void, const GLuint *> Binding::Color3uiv("glColor3uiv");
Function<Binding, void, GLushort, GLushort, GLushort> Binding::Color3us("glColor3us");
Function<Binding, void, const GLushort *> Binding::Color3usv("glColor3usv");
Function<Binding, void, GLfixed, GLfixed, GLfixed> Binding::Color3xOES("glColor3xOES");
Function<Binding, void, const GLfixed *> Binding::Color3xvOES("glColor3xvOES");
Function<Binding, void, GLbyte, GLbyte, GLbyte, GLbyte> Binding::Color4b("glColor4b");
Function<Binding, void, const GLbyte *> Binding::Color4bv("glColor4bv");
Function<Binding, void, GLdouble, GLdouble, GLdouble, GLdouble> Binding::Color4d("glColor4d");
Function<Binding, void, const GLdouble *> Binding::Color4dv("glColor4dv");
Function<Binding, void, GLfloat, GLfloat, GLfloat, GLfloat> Binding::Color4f("glColor4f");
Function<Binding, void, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat> Binding::Color4fNormal3fVertex3fSUN("glColor4fNormal3fVertex3fSUN");
Function<Binding, void, const GLfloat *, const GLfloat *, const GLfloat *> Binding::Color4fNormal3fVertex3fvSUN("glColor4fNormal3fVertex3fvSUN");
Function<Binding, void, const GLfloat *> Binding::Color4fv("glColor4fv");
Function<Binding, void, GLhalfNV, GLhalfNV, GLhalfNV, GLhalfNV> Binding::Color4hNV("glColor4hNV");
Function<Binding, void, const GLhalfNV *> Binding::Color4hvNV("glColor4hvNV");
Function<Binding, void, GLint, GLint, GLint, GLint> Binding::Color4i("glColor4i");
Function<Binding, void, const GLint *> Binding::Color4iv("glColor4iv");
Function<Binding, void, GLshort, GLshort, GLshort, GLshort> Binding::Color4s("glColor4s");
Function<Binding, void, const GLshort *> Binding::Color4sv("glColor4sv");
Function<Binding, void, GLubyte, GLubyte, GLubyte, GLubyte> Binding::Color4ub("glColor4ub");
Function<Binding, void, GLubyte, GLubyte, GLubyte, GLubyte, GLfloat, GLfloat> Binding::Color4ubVertex2fSUN("glColor4ubVertex2fSUN");
Function<Binding, void, const GLubyte *, const GLfloat *> Binding::Color4ubVertex2fvSUN("glColor4ubVertex2fvSUN");
Function<Binding, void, GLubyte, GLubyte, GLubyte, GLubyte, GLfloat, GLfloat, GLfloat> Binding::Color4ubVertex3fSUN("glColor4ubVertex3fSUN");
Function<Binding, void, const GLubyte *, const GLfloat *> Binding::Color4ubVertex3fvSUN("glColor4ubVertex3fvSUN");
Function<Binding, void, const GLubyte *> Binding::Color4ubv("glColor4ubv");
Function<Binding, void, GLuint, GLuint, GLuint, GLuint> Binding::Color4ui("glColor4ui");
Function<Binding, void, const GLuint *> Binding::Color4uiv("glColor4uiv");
Function<Binding, void, GLushort, GLushort, GLushort, GLushort> Binding::Color4us("glColor4us");
Function<Binding, void, const GLushort *> Binding::Color4usv("glColor4usv");
Function<Binding, void, GLfixed, GLfixed, GLfixed, GLfixed> Binding::Color4xOES("glColor4xOES");
Function<Binding, void, const GLfixed *> Binding::Color4xvOES("glColor4xvOES");
Function<Binding, void, GLint, GLenum, GLsizei> Binding::ColorFormatNV("glColorFormatNV");
Function<Binding, void, GLenum, GLuint, GLuint, GLuint, GLuint, GLuint, GLuint> Binding::ColorFragmentOp1ATI("glColorFragmentOp1ATI");
Function<Binding, void, GLenum, GLuint, GLuint, GLuint, GLuint, GLuint, GLuint, GLuint, GLuint, GLuint> Binding::ColorFragmentOp2ATI("glColorFragmentOp2ATI");
Function<Binding, void, GLenum, GLuint, GLuint, GLuint, GLuint, GLuint, GLuint, GLuint, GLuint, GLuint, GLuint, GLuint, GLuint> Binding::ColorFragmentOp3ATI("glColorFragmentOp3ATI");
Function<Binding, void, GLboolean, GLboolean, GLboolean, GLboolean> Binding::ColorMask("glColorMask");
Function<Binding, void, GLuint, GLboolean, GLboolean, GLboolean, GLboolean> Binding::ColorMaskIndexedEXT("glColorMaskIndexedEXT");
Function<Binding, void, GLuint, GLboolean, GLboolean, GLboolean, GLboolean> Binding::ColorMaski("glColorMaski");
Function<Binding, void, GLenum, GLenum> Binding::ColorMaterial("glColorMaterial");
Function<Binding, void, GLenum, GLuint> Binding::ColorP3ui("glColorP3ui");
Function<Binding, void, GLenum, const GLuint *> Binding::ColorP3uiv("glColorP3uiv");
Function<Binding, void, GLenum, GLuint> Binding::ColorP4ui("glColorP4ui");
Function<Binding, void, GLenum, const GLuint *> Binding::ColorP4uiv("glColorP4uiv");
Function<Binding, void, GLint, GLenum, GLsizei, const void *> Binding::ColorPointer("glColorPointer");
Function<Binding, void, GLint, GLenum, GLsizei, GLsizei, const void *> Binding::ColorPointerEXT("glColorPointerEXT");
Function<Binding, void, GLint, GLenum, GLint, const void **, GLint> Binding::ColorPointerListIBM("glColorPointerListIBM");
Function<Binding, void, GLint, GLenum, const void **> Binding::ColorPointervINTEL("glColorPointervINTEL");
Function<Binding, void, GLenum, GLsizei, GLsizei, GLenum, GLenum, const void *> Binding::ColorSubTable("glColorSubTable");
Function<Binding, void, GLenum, GLsizei, GLsizei, GLenum, GLenum, const void *> Binding::ColorSubTableEXT("glColorSubTableEXT");
Function<Binding, void, GLenum, GLenum, GLsizei, GLenum, GLenum, const void *> Binding::ColorTable("glColorTable");
Function<Binding, void, GLenum, GLenum, GLsizei, GLenum, GLenum, const void *> Binding::ColorTableEXT("glColorTableEXT");
Function<Binding, void, GLenum, GLenum, const GLfloat *> Binding::ColorTableParameterfv("glColorTableParameterfv");
Function<Binding, void, GLenum, GLenum, const GLfloat *> Binding::ColorTableParameterfvSGI("glColorTableParameterfvSGI");
Function<Binding, void, GLenum, GLenum, const GLint *> Binding::ColorTableParameteriv("glColorTableParameteriv");
Function<Binding, void, GLenum, GLenum, const GLint *> Binding::ColorTableParameterivSGI("glColorTableParameterivSGI");
Function<Binding, void, GLenum, GLenum, GLsizei, GLenum, GLenum, const void *> Binding::ColorTableSGI("glColorTableSGI");
Function<Binding, void, GLenum, GLenum, GLenum, GLenum, GLenum, GLenum> Binding::CombinerInputNV("glCombinerInputNV");
Function<Binding, void, GLenum, GLenum, GLenum, GLenum, GLenum, GLenum, GLenum, GLboolean, GLboolean, GLboolean> Binding::CombinerOutputNV("glCombinerOutputNV");
Function<Binding, void, GLenum, GLfloat> Binding::CombinerParameterfNV("glCombinerParameterfNV");
Function<Binding, void, GLenum, const GLfloat *> Binding::CombinerParameterfvNV("glCombinerParameterfvNV");
Function<Binding, void, GLenum, GLint> Binding::CombinerParameteriNV("glCombinerParameteriNV");
Function<Binding, void, GLenum, const GLint *> Binding::CombinerParameterivNV("glCombinerParameterivNV");
Function<Binding, void, GLenum, GLenum, const GLfloat *> Binding::CombinerStageParameterfvNV("glCombinerStageParameterfvNV");
Function<Binding, void, GLuint, GLuint> Binding::CommandListSegmentsNV("glCommandListSegmentsNV");
Function<Binding, void, GLuint> Binding::CompileCommandListNV("glCompileCommandListNV");
Function<Binding, void, GLuint> Binding::CompileShader("glCompileShader");
Function<Binding, void, GLhandleARB> Binding::CompileShaderARB("glCompileShaderARB");
Function<Binding, void, GLuint, GLsizei, const GLchar *const*, const GLint *> Binding::CompileShaderIncludeARB("glCompileShaderIncludeARB");
Function<Binding, void, GLenum, GLenum, GLint, GLenum, GLsizei, GLint, GLsizei, const void *> Binding::CompressedMultiTexImage1DEXT("glCompressedMultiTexImage1DEXT");
Function<Binding, void, GLenum, GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLsizei, const void *> Binding::CompressedMultiTexImage2DEXT("glCompressedMultiTexImage2DEXT");
Function<Binding, void, GLenum, GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLsizei, const void *> Binding::CompressedMultiTexImage3DEXT("glCompressedMultiTexImage3DEXT");
Function<Binding, void, GLenum, GLenum, GLint, GLint, GLsizei, GLenum, GLsizei, const void *> Binding::CompressedMultiTexSubImage1DEXT("glCompressedMultiTexSubImage1DEXT");
Function<Binding, void, GLenum, GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, const void *> Binding::CompressedMultiTexSubImage2DEXT("glCompressedMultiTexSubImage2DEXT");
Function<Binding, void, GLenum, GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLsizei, const void *> Binding::CompressedMultiTexSubImage3DEXT("glCompressedMultiTexSubImage3DEXT");
Function<Binding, void, GLenum, GLint, GLenum, GLsizei, GLint, GLsizei, const void *> Binding::CompressedTexImage1D("glCompressedTexImage1D");
Function<Binding, void, GLenum, GLint, GLenum, GLsizei, GLint, GLsizei, const void *> Binding::CompressedTexImage1DARB("glCompressedTexImage1DARB");
Function<Binding, void, GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLsizei, const void *> Binding::CompressedTexImage2D("glCompressedTexImage2D");
Function<Binding, void, GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLsizei, const void *> Binding::CompressedTexImage2DARB("glCompressedTexImage2DARB");
Function<Binding, void, GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLsizei, const void *> Binding::CompressedTexImage3D("glCompressedTexImage3D");
Function<Binding, void, GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLsizei, const void *> Binding::CompressedTexImage3DARB("glCompressedTexImage3DARB");
Function<Binding, void, GLenum, GLint, GLint, GLsizei, GLenum, GLsizei, const void *> Binding::CompressedTexSubImage1D("glCompressedTexSubImage1D");
Function<Binding, void, GLenum, GLint, GLint, GLsizei, GLenum, GLsizei, const void *> Binding::CompressedTexSubImage1DARB("glCompressedTexSubImage1DARB");
Function<Binding, void, GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, const void *> Binding::CompressedTexSubImage2D("glCompressedTexSubImage2D");
Function<Binding, void, GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, const void *> Binding::CompressedTexSubImage2DARB("glCompressedTexSubImage2DARB");
Function<Binding, void, GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLsizei, const void *> Binding::CompressedTexSubImage3D("glCompressedTexSubImage3D");
Function<Binding, void, GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLsizei, const void *> Binding::CompressedTexSubImage3DARB("glCompressedTexSubImage3DARB");
Function<Binding, void, GLuint, GLenum, GLint, GLenum, GLsizei, GLint, GLsizei, const void *> Binding::CompressedTextureImage1DEXT("glCompressedTextureImage1DEXT");
Function<Binding, void, GLuint, GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLsizei, const void *> Binding::CompressedTextureImage2DEXT("glCompressedTextureImage2DEXT");
Function<Binding, void, GLuint, GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLsizei, const void *> Binding::CompressedTextureImage3DEXT("glCompressedTextureImage3DEXT");
Function<Binding, void, GLuint, GLint, GLint, GLsizei, GLenum, GLsizei, const void *> Binding::CompressedTextureSubImage1D("glCompressedTextureSubImage1D");
Function<Binding, void, GLuint, GLenum, GLint, GLint, GLsizei, GLenum, GLsizei, const void *> Binding::CompressedTextureSubImage1DEXT("glCompressedTextureSubImage1DEXT");
Function<Binding, void, GLuint, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, const void *> Binding::CompressedTextureSubImage2D("glCompressedTextureSubImage2D");
Function<Binding, void, GLuint, GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, const void *> Binding::CompressedTextureSubImage2DEXT("glCompressedTextureSubImage2DEXT");
Function<Binding, void, GLuint, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLsizei, const void *> Binding::CompressedTextureSubImage3D("glCompressedTextureSubImage3D");
Function<Binding, void, GLuint, GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLsizei, const void *> Binding::CompressedTextureSubImage3DEXT("glCompressedTextureSubImage3DEXT");
Function<Binding, void, GLenum, GLfloat> Binding::ConservativeRasterParameterfNV("glConservativeRasterParameterfNV");
Function<Binding, void, GLenum, GLint> Binding::ConservativeRasterParameteriNV("glConservativeRasterParameteriNV");
Function<Binding, void, GLenum, GLenum, GLsizei, GLenum, GLenum, const void *> Binding::ConvolutionFilter1D("glConvolutionFilter1D");
Function<Binding, void, GLenum, GLenum, GLsizei, GLenum, GLenum, const void *> Binding::ConvolutionFilter1DEXT("glConvolutionFilter1DEXT");
Function<Binding, void, GLenum, GLenum, GLsizei, GLsizei, GLenum, GLenum, const void *> Binding::ConvolutionFilter2D("glConvolutionFilter2D");
Function<Binding, void, GLenum, GLenum, GLsizei, GLsizei, GLenum, GLenum, const void *> Binding::ConvolutionFilter2DEXT("glConvolutionFilter2DEXT");
Function<Binding, void, GLenum, GLenum, GLfloat> Binding::ConvolutionParameterf("glConvolutionParameterf");
Function<Binding, void, GLenum, GLenum, GLfloat> Binding::ConvolutionParameterfEXT("glConvolutionParameterfEXT");
Function<Binding, void, GLenum, GLenum, const GLfloat *> Binding::ConvolutionParameterfv("glConvolutionParameterfv");
Function<Binding, void, GLenum, GLenum, const GLfloat *> Binding::ConvolutionParameterfvEXT("glConvolutionParameterfvEXT");
Function<Binding, void, GLenum, GLenum, GLint> Binding::ConvolutionParameteri("glConvolutionParameteri");
Function<Binding, void, GLenum, GLenum, GLint> Binding::ConvolutionParameteriEXT("glConvolutionParameteriEXT");
Function<Binding, void, GLenum, GLenum, const GLint *> Binding::ConvolutionParameteriv("glConvolutionParameteriv");
Function<Binding, void, GLenum, GLenum, const GLint *> Binding::ConvolutionParameterivEXT("glConvolutionParameterivEXT");
Function<Binding, void, GLenum, GLenum, GLfixed> Binding::ConvolutionParameterxOES("glConvolutionParameterxOES");
Function<Binding, void, GLenum, GLenum, const GLfixed *> Binding::ConvolutionParameterxvOES("glConvolutionParameterxvOES");
Function<Binding, void, GLenum, GLenum, GLintptr, GLintptr, GLsizeiptr> Binding::CopyBufferSubData("glCopyBufferSubData");
Function<Binding, void, GLenum, GLsizei, GLint, GLint, GLsizei> Binding::CopyColorSubTable("glCopyColorSubTable");
Function<Binding, void, GLenum, GLsizei, GLint, GLint, GLsizei> Binding::CopyColorSubTableEXT("glCopyColorSubTableEXT");
Function<Binding, void, GLenum, GLenum, GLint, GLint, GLsizei> Binding::CopyColorTable("glCopyColorTable");
Function<Binding, void, GLenum, GLenum, GLint, GLint, GLsizei> Binding::CopyColorTableSGI("glCopyColorTableSGI");
Function<Binding, void, GLenum, GLenum, GLint, GLint, GLsizei> Binding::CopyConvolutionFilter1D("glCopyConvolutionFilter1D");
Function<Binding, void, GLenum, GLenum, GLint, GLint, GLsizei> Binding::CopyConvolutionFilter1DEXT("glCopyConvolutionFilter1DEXT");
Function<Binding, void, GLenum, GLenum, GLint, GLint, GLsizei, GLsizei> Binding::CopyConvolutionFilter2D("glCopyConvolutionFilter2D");
Function<Binding, void, GLenum, GLenum, GLint, GLint, GLsizei, GLsizei> Binding::CopyConvolutionFilter2DEXT("glCopyConvolutionFilter2DEXT");
Function<Binding, void, GLuint, GLenum, GLint, GLint, GLint, GLint, GLuint, GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei> Binding::CopyImageSubData("glCopyImageSubData");
Function<Binding, void, GLuint, GLenum, GLint, GLint, GLint, GLint, GLuint, GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei> Binding::CopyImageSubDataNV("glCopyImageSubDataNV");
Function<Binding, void, GLenum, GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLint> Binding::CopyMultiTexImage1DEXT("glCopyMultiTexImage1DEXT");
Function<Binding, void, GLenum, GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLsizei, GLint> Binding::CopyMultiTexImage2DEXT("glCopyMultiTexImage2DEXT");
Function<Binding, void, GLenum, GLenum, GLint, GLint, GLint, GLint, GLsizei> Binding::CopyMultiTexSubImage1DEXT("glCopyMultiTexSubImage1DEXT");
Function<Binding, void, GLenum, GLenum, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei> Binding::CopyMultiTexSubImage2DEXT("glCopyMultiTexSubImage2DEXT");
Function<Binding, void, GLenum, GLenum, GLint, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei> Binding::CopyMultiTexSubImage3DEXT("glCopyMultiTexSubImage3DEXT");
Function<Binding, void, GLuint, GLuint, GLintptr, GLintptr, GLsizeiptr> Binding::CopyNamedBufferSubData("glCopyNamedBufferSubData");
Function<Binding, void, GLuint, GLuint> Binding::CopyPathNV("glCopyPathNV");
Function<Binding, void, GLint, GLint, GLsizei, GLsizei, GLenum> Binding::CopyPixels("glCopyPixels");
Function<Binding, void, GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLint> Binding::CopyTexImage1D("glCopyTexImage1D");
Function<Binding, void, GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLint> Binding::CopyTexImage1DEXT("glCopyTexImage1DEXT");
Function<Binding, void, GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLsizei, GLint> Binding::CopyTexImage2D("glCopyTexImage2D");
Function<Binding, void, GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLsizei, GLint> Binding::CopyTexImage2DEXT("glCopyTexImage2DEXT");
Function<Binding, void, GLenum, GLint, GLint, GLint, GLint, GLsizei> Binding::CopyTexSubImage1D("glCopyTexSubImage1D");
Function<Binding, void, GLenum, GLint, GLint, GLint, GLint, GLsizei> Binding::CopyTexSubImage1DEXT("glCopyTexSubImage1DEXT");
Function<Binding, void, GLenum, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei> Binding::CopyTexSubImage2D("glCopyTexSubImage2D");
Function<Binding, void, GLenum, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei> Binding::CopyTexSubImage2DEXT("glCopyTexSubImage2DEXT");
Function<Binding, void, GLenum, GLint, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei> Binding::CopyTexSubImage3D("glCopyTexSubImage3D");
Function<Binding, void, GLenum, GLint, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei> Binding::CopyTexSubImage3DEXT("glCopyTexSubImage3DEXT");
Function<Binding, void, GLuint, GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLint> Binding::CopyTextureImage1DEXT("glCopyTextureImage1DEXT");
Function<Binding, void, GLuint, GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLsizei, GLint> Binding::CopyTextureImage2DEXT("glCopyTextureImage2DEXT");
Function<Binding, void, GLuint, GLint, GLint, GLint, GLint, GLsizei> Binding::CopyTextureSubImage1D("glCopyTextureSubImage1D");
Function<Binding, void, GLuint, GLenum, GLint, GLint, GLint, GLint, GLsizei> Binding::CopyTextureSubImage1DEXT("glCopyTextureSubImage1DEXT");
Function<Binding, void, GLuint, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei> Binding::CopyTextureSubImage2D("glCopyTextureSubImage2D");
Function<Binding, void, GLuint, GLenum, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei> Binding::CopyTextureSubImage2DEXT("glCopyTextureSubImage2DEXT");
Function<Binding, void, GLuint, GLint, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei> Binding::CopyTextureSubImage3D("glCopyTextureSubImage3D");
Function<Binding, void, GLuint, GLenum, GLint, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei> Binding::CopyTextureSubImage3DEXT("glCopyTextureSubImage3DEXT");
Function<Binding, void, GLsizei, GLenum, const void *, GLuint, GLenum, GLenum, const GLfloat *> Binding::CoverFillPathInstancedNV("glCoverFillPathInstancedNV");
Function<Binding, void, GLuint, GLenum> Binding::CoverFillPathNV("glCoverFillPathNV");
Function<Binding, void, GLsizei, GLenum, const void *, GLuint, GLenum, GLenum, const GLfloat *> Binding::CoverStrokePathInstancedNV("glCoverStrokePathInstancedNV");
Function<Binding, void, GLuint, GLenum> Binding::CoverStrokePathNV("glCoverStrokePathNV");
Function<Binding, void, GLenum> Binding::CoverageModulationNV("glCoverageModulationNV");
Function<Binding, void, GLsizei, const GLfloat *> Binding::CoverageModulationTableNV("glCoverageModulationTableNV");
Function<Binding, void, GLsizei, GLuint *> Binding::CreateBuffers("glCreateBuffers");
Function<Binding, void, GLsizei, GLuint *> Binding::CreateCommandListsNV("glCreateCommandListsNV");
Function<Binding, void, GLsizei, GLuint *> Binding::CreateFramebuffers("glCreateFramebuffers");
Function<Binding, void, GLsizei, GLuint *> Binding::CreateMemoryObjectsEXT("glCreateMemoryObjectsEXT");
Function<Binding, void, GLuint, GLuint *> Binding::CreatePerfQueryINTEL("glCreatePerfQueryINTEL");
Function<Binding, GLuint> Binding::CreateProgram("glCreateProgram");
Function<Binding, GLhandleARB> Binding::CreateProgramObjectARB("glCreateProgramObjectARB");
Function<Binding, void, GLsizei, GLuint *> Binding::CreateProgramPipelines("glCreateProgramPipelines");
Function<Binding, void, GLenum, GLsizei, GLuint *> Binding::CreateQueries("glCreateQueries");
Function<Binding, void, GLsizei, GLuint *> Binding::CreateRenderbuffers("glCreateRenderbuffers");
Function<Binding, void, GLsizei, GLuint *> Binding::CreateSamplers("glCreateSamplers");
Function<Binding, GLuint, GLenum> Binding::CreateShader("glCreateShader");
Function<Binding, GLhandleARB, GLenum> Binding::CreateShaderObjectARB("glCreateShaderObjectARB");
Function<Binding, GLuint, GLenum, const GLchar *> Binding::CreateShaderProgramEXT("glCreateShaderProgramEXT");
Function<Binding, GLuint, GLenum, GLsizei, const GLchar *const*> Binding::CreateShaderProgramv("glCreateShaderProgramv");
Function<Binding, void, GLsizei, GLuint *> Binding::CreateStatesNV("glCreateStatesNV");
Function<Binding, GLsync, _cl_context *, _cl_event *, UnusedMask> Binding::CreateSyncFromCLeventARB("glCreateSyncFromCLeventARB");
Function<Binding, void, GLenum, GLsizei, GLuint *> Binding::CreateTextures("glCreateTextures");
Function<Binding, void, GLsizei, GLuint *> Binding::CreateTransformFeedbacks("glCreateTransformFeedbacks");
Function<Binding, void, GLsizei, GLuint *> Binding::CreateVertexArrays("glCreateVertexArrays");
Function<Binding, void, GLenum> Binding::CullFace("glCullFace");
Function<Binding, void, GLenum, GLdouble *> Binding::CullParameterdvEXT("glCullParameterdvEXT");
Function<Binding, void, GLenum, GLfloat *> Binding::CullParameterfvEXT("glCullParameterfvEXT");
Function<Binding, void, GLint> Binding::CurrentPaletteMatrixARB("glCurrentPaletteMatrixARB");



} // namespace glbinding
