
// on gcc, this file is used since compilation of single file is fast
// for msvc, in contrast, this file is not added to the project, since /bigobj would be required

#include "Binding_objects_a.cpp"
#include "Binding_objects_b.cpp"
#include "Binding_objects_c.cpp"
#include "Binding_objects_d.cpp"
#include "Binding_objects_e.cpp"
#include "Binding_objects_f.cpp"
#include "Binding_objects_g.cpp"
#include "Binding_objects_h.cpp"
#include "Binding_objects_i.cpp"
#include "Binding_objects_j.cpp"
#include "Binding_objects_k.cpp"
#include "Binding_objects_l.cpp"
#include "Binding_objects_m.cpp"
#include "Binding_objects_n.cpp"
#include "Binding_objects_o.cpp"
#include "Binding_objects_p.cpp"
#include "Binding_objects_q.cpp"
#include "Binding_objects_r.cpp"
#include "Binding_objects_s.cpp"
#include "Binding_objects_t.cpp"
#include "Binding_objects_u.cpp"
#include "Binding_objects_v.cpp"
#include "Binding_objects_w.cpp"
#include "Binding_objects_x.cpp"
#include "Binding_objects_y.cpp"
#include "Binding_objects_z.cpp"
