
#pragma once


#include <glxbinding/nogl.h>

#include <glxbinding/glxbinding_features.h>

#include <glxbinding/SharedBitfield.h>


namespace glx
{



// import bitfields to namespace

GLXBINDING_CONSTEXPR static const None GL_NONE_BIT = None::GL_NONE_BIT;
GLXBINDING_CONSTEXPR static const None GLX_SYNC_FRAME_SGIX = None::GLX_SYNC_FRAME_SGIX;
GLXBINDING_CONSTEXPR static const None GLX_CONTEXT_CORE_PROFILE_BIT_ARB = None::GLX_CONTEXT_CORE_PROFILE_BIT_ARB;
GLXBINDING_CONSTEXPR static const None GLX_CONTEXT_DEBUG_BIT_ARB = None::GLX_CONTEXT_DEBUG_BIT_ARB;
GLXBINDING_CONSTEXPR static const None GLX_FRONT_LEFT_BUFFER_BIT = None::GLX_FRONT_LEFT_BUFFER_BIT;
GLXBINDING_CONSTEXPR static const None GLX_FRONT_LEFT_BUFFER_BIT_SGIX = None::GLX_FRONT_LEFT_BUFFER_BIT_SGIX;
GLXBINDING_CONSTEXPR static const None GLX_HYPERPIPE_DISPLAY_PIPE_SGIX = None::GLX_HYPERPIPE_DISPLAY_PIPE_SGIX;
GLXBINDING_CONSTEXPR static const None GLX_PIPE_RECT_SGIX = None::GLX_PIPE_RECT_SGIX;
GLXBINDING_CONSTEXPR static const None GLX_RGBA_BIT = None::GLX_RGBA_BIT;
GLXBINDING_CONSTEXPR static const None GLX_RGBA_BIT_SGIX = None::GLX_RGBA_BIT_SGIX;
GLXBINDING_CONSTEXPR static const None GLX_STEREO_NOTIFY_MASK_EXT = None::GLX_STEREO_NOTIFY_MASK_EXT;
GLXBINDING_CONSTEXPR static const None GLX_SYNC_SWAP_SGIX = None::GLX_SYNC_SWAP_SGIX;
GLXBINDING_CONSTEXPR static const None GLX_TEXTURE_1D_BIT_EXT = None::GLX_TEXTURE_1D_BIT_EXT;
GLXBINDING_CONSTEXPR static const None GLX_WINDOW_BIT = None::GLX_WINDOW_BIT;
GLXBINDING_CONSTEXPR static const None GLX_WINDOW_BIT_SGIX = None::GLX_WINDOW_BIT_SGIX;
GLXBINDING_CONSTEXPR static const None GLX_COLOR_INDEX_BIT = None::GLX_COLOR_INDEX_BIT;
GLXBINDING_CONSTEXPR static const None GLX_COLOR_INDEX_BIT_SGIX = None::GLX_COLOR_INDEX_BIT_SGIX;
GLXBINDING_CONSTEXPR static const None GLX_CONTEXT_COMPATIBILITY_PROFILE_BIT_ARB = None::GLX_CONTEXT_COMPATIBILITY_PROFILE_BIT_ARB;
GLXBINDING_CONSTEXPR static const None GLX_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB = None::GLX_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB;
GLXBINDING_CONSTEXPR static const None GLX_FRONT_RIGHT_BUFFER_BIT = None::GLX_FRONT_RIGHT_BUFFER_BIT;
GLXBINDING_CONSTEXPR static const None GLX_FRONT_RIGHT_BUFFER_BIT_SGIX = None::GLX_FRONT_RIGHT_BUFFER_BIT_SGIX;
GLXBINDING_CONSTEXPR static const None GLX_HYPERPIPE_RENDER_PIPE_SGIX = None::GLX_HYPERPIPE_RENDER_PIPE_SGIX;
GLXBINDING_CONSTEXPR static const None GLX_PIPE_RECT_LIMITS_SGIX = None::GLX_PIPE_RECT_LIMITS_SGIX;
GLXBINDING_CONSTEXPR static const None GLX_PIXMAP_BIT = None::GLX_PIXMAP_BIT;
GLXBINDING_CONSTEXPR static const None GLX_PIXMAP_BIT_SGIX = None::GLX_PIXMAP_BIT_SGIX;
GLXBINDING_CONSTEXPR static const None GLX_TEXTURE_2D_BIT_EXT = None::GLX_TEXTURE_2D_BIT_EXT;
GLXBINDING_CONSTEXPR static const None GLX_HYPERPIPE_STEREO_SGIX = None::GLX_HYPERPIPE_STEREO_SGIX;
GLXBINDING_CONSTEXPR static const None GLX_BACK_LEFT_BUFFER_BIT = None::GLX_BACK_LEFT_BUFFER_BIT;
GLXBINDING_CONSTEXPR static const None GLX_BACK_LEFT_BUFFER_BIT_SGIX = None::GLX_BACK_LEFT_BUFFER_BIT_SGIX;
GLXBINDING_CONSTEXPR static const None GLX_CONTEXT_ES2_PROFILE_BIT_EXT = None::GLX_CONTEXT_ES2_PROFILE_BIT_EXT;
GLXBINDING_CONSTEXPR static const None GLX_CONTEXT_ES_PROFILE_BIT_EXT = None::GLX_CONTEXT_ES_PROFILE_BIT_EXT;
GLXBINDING_CONSTEXPR static const None GLX_CONTEXT_ROBUST_ACCESS_BIT_ARB = None::GLX_CONTEXT_ROBUST_ACCESS_BIT_ARB;
GLXBINDING_CONSTEXPR static const None GLX_HYPERPIPE_PIXEL_AVERAGE_SGIX = None::GLX_HYPERPIPE_PIXEL_AVERAGE_SGIX;
GLXBINDING_CONSTEXPR static const None GLX_PBUFFER_BIT = None::GLX_PBUFFER_BIT;
GLXBINDING_CONSTEXPR static const None GLX_PBUFFER_BIT_SGIX = None::GLX_PBUFFER_BIT_SGIX;
GLXBINDING_CONSTEXPR static const None GLX_RGBA_FLOAT_BIT_ARB = None::GLX_RGBA_FLOAT_BIT_ARB;
GLXBINDING_CONSTEXPR static const None GLX_TEXTURE_RECTANGLE_BIT_EXT = None::GLX_TEXTURE_RECTANGLE_BIT_EXT;
GLXBINDING_CONSTEXPR static const None GLX_BACK_RIGHT_BUFFER_BIT = None::GLX_BACK_RIGHT_BUFFER_BIT;
GLXBINDING_CONSTEXPR static const None GLX_BACK_RIGHT_BUFFER_BIT_SGIX = None::GLX_BACK_RIGHT_BUFFER_BIT_SGIX;
GLXBINDING_CONSTEXPR static const None GLX_CONTEXT_RESET_ISOLATION_BIT_ARB = None::GLX_CONTEXT_RESET_ISOLATION_BIT_ARB;
GLXBINDING_CONSTEXPR static const None GLX_RGBA_UNSIGNED_FLOAT_BIT_EXT = None::GLX_RGBA_UNSIGNED_FLOAT_BIT_EXT;
GLXBINDING_CONSTEXPR static const None GLX_AUX_BUFFERS_BIT = None::GLX_AUX_BUFFERS_BIT;
GLXBINDING_CONSTEXPR static const None GLX_AUX_BUFFERS_BIT_SGIX = None::GLX_AUX_BUFFERS_BIT_SGIX;
GLXBINDING_CONSTEXPR static const None GLX_DEPTH_BUFFER_BIT = None::GLX_DEPTH_BUFFER_BIT;
GLXBINDING_CONSTEXPR static const None GLX_DEPTH_BUFFER_BIT_SGIX = None::GLX_DEPTH_BUFFER_BIT_SGIX;
GLXBINDING_CONSTEXPR static const None GLX_STENCIL_BUFFER_BIT = None::GLX_STENCIL_BUFFER_BIT;
GLXBINDING_CONSTEXPR static const None GLX_STENCIL_BUFFER_BIT_SGIX = None::GLX_STENCIL_BUFFER_BIT_SGIX;
GLXBINDING_CONSTEXPR static const None GLX_ACCUM_BUFFER_BIT = None::GLX_ACCUM_BUFFER_BIT;
GLXBINDING_CONSTEXPR static const None GLX_ACCUM_BUFFER_BIT_SGIX = None::GLX_ACCUM_BUFFER_BIT_SGIX;
GLXBINDING_CONSTEXPR static const None GLX_SAMPLE_BUFFERS_BIT_SGIX = None::GLX_SAMPLE_BUFFERS_BIT_SGIX;
GLXBINDING_CONSTEXPR static const None GLX_BUFFER_SWAP_COMPLETE_INTEL_MASK = None::GLX_BUFFER_SWAP_COMPLETE_INTEL_MASK;
GLXBINDING_CONSTEXPR static const None GLX_BUFFER_CLOBBER_MASK_SGIX = None::GLX_BUFFER_CLOBBER_MASK_SGIX;
GLXBINDING_CONSTEXPR static const None GLX_PBUFFER_CLOBBER_MASK = None::GLX_PBUFFER_CLOBBER_MASK;


} // namespace glx
