
#pragma once


#include <glxbinding/nogl.h>

#include <glxbinding/glxbinding_features.h>


namespace glx
{


enum class GLenum : unsigned int
{
    // __UNGROUPED__

    GLX_EXTENSION_NAME                                     = "GLX",
    GLX_CONTEXT_RELEASE_BEHAVIOR_NONE_ARB                  = 0,
    GLX_PbufferClobber                                     = 0,
    GLX_STEREO_NOTIFY_EXT                                  = 0x00000000,
    GLX_3DFX_WINDOW_MODE_MESA                              = 0x1, // decimal value: 1
    GLX_VENDOR                                             = 0x1, // decimal value: 1
    GLX_GPU_VENDOR_AMD                                     = 0x1F00, // decimal value: 7936
    GLX_GPU_RENDERER_STRING_AMD                            = 0x1F01, // decimal value: 7937
    GLX_GPU_OPENGL_VERSION_STRING_AMD                      = 0x1F02, // decimal value: 7938
    GLX_3DFX_FULLSCREEN_MODE_MESA                          = 0x2, // decimal value: 2
    GLX_VERSION                                            = 0x2, // decimal value: 2
    GLX_CONFIG_CAVEAT                                      = 0x20, // decimal value: 32
    GLX_VISUAL_CAVEAT_EXT                                  = 0x20, // decimal value: 32
    GLX_CONTEXT_MAJOR_VERSION_ARB                          = 0x2091, // decimal value: 8337
    GLX_CONTEXT_MINOR_VERSION_ARB                          = 0x2092, // decimal value: 8338
    GLX_CONTEXT_FLAGS_ARB                                  = 0x2094, // decimal value: 8340
    GLX_CONTEXT_ALLOW_BUFFER_BYTE_ORDER_MISMATCH_ARB       = 0x2095, // decimal value: 8341
    GLX_CONTEXT_RELEASE_BEHAVIOR_ARB                       = 0x2097, // decimal value: 8343
    GLX_CONTEXT_RELEASE_BEHAVIOR_FLUSH_ARB                 = 0x2098, // decimal value: 8344
    GLX_FLOAT_COMPONENTS_NV                                = 0x20B0, // decimal value: 8368
    GLX_RGBA_UNSIGNED_FLOAT_TYPE_EXT                       = 0x20B1, // decimal value: 8369
    GLX_FRAMEBUFFER_SRGB_CAPABLE_ARB                       = 0x20B2, // decimal value: 8370
    GLX_FRAMEBUFFER_SRGB_CAPABLE_EXT                       = 0x20B2, // decimal value: 8370
    GLX_COLOR_SAMPLES_NV                                   = 0x20B3, // decimal value: 8371
    GLX_RGBA_FLOAT_TYPE_ARB                                = 0x20B9, // decimal value: 8377
    GLX_VIDEO_OUT_COLOR_NV                                 = 0x20C3, // decimal value: 8387
    GLX_VIDEO_OUT_ALPHA_NV                                 = 0x20C4, // decimal value: 8388
    GLX_VIDEO_OUT_DEPTH_NV                                 = 0x20C5, // decimal value: 8389
    GLX_VIDEO_OUT_COLOR_AND_ALPHA_NV                       = 0x20C6, // decimal value: 8390
    GLX_VIDEO_OUT_COLOR_AND_DEPTH_NV                       = 0x20C7, // decimal value: 8391
    GLX_VIDEO_OUT_FRAME_NV                                 = 0x20C8, // decimal value: 8392
    GLX_VIDEO_OUT_FIELD_1_NV                               = 0x20C9, // decimal value: 8393
    GLX_VIDEO_OUT_FIELD_2_NV                               = 0x20CA, // decimal value: 8394
    GLX_VIDEO_OUT_STACKED_FIELDS_1_2_NV                    = 0x20CB, // decimal value: 8395
    GLX_VIDEO_OUT_STACKED_FIELDS_2_1_NV                    = 0x20CC, // decimal value: 8396
    GLX_DEVICE_ID_NV                                       = 0x20CD, // decimal value: 8397
    GLX_UNIQUE_ID_NV                                       = 0x20CE, // decimal value: 8398
    GLX_NUM_VIDEO_CAPTURE_SLOTS_NV                         = 0x20CF, // decimal value: 8399
    GLX_BIND_TO_TEXTURE_RGB_EXT                            = 0x20D0, // decimal value: 8400
    GLX_BIND_TO_TEXTURE_RGBA_EXT                           = 0x20D1, // decimal value: 8401
    GLX_BIND_TO_MIPMAP_TEXTURE_EXT                         = 0x20D2, // decimal value: 8402
    GLX_BIND_TO_TEXTURE_TARGETS_EXT                        = 0x20D3, // decimal value: 8403
    GLX_Y_INVERTED_EXT                                     = 0x20D4, // decimal value: 8404
    GLX_TEXTURE_FORMAT_EXT                                 = 0x20D5, // decimal value: 8405
    GLX_TEXTURE_TARGET_EXT                                 = 0x20D6, // decimal value: 8406
    GLX_MIPMAP_TEXTURE_EXT                                 = 0x20D7, // decimal value: 8407
    GLX_TEXTURE_FORMAT_NONE_EXT                            = 0x20D8, // decimal value: 8408
    GLX_TEXTURE_FORMAT_RGB_EXT                             = 0x20D9, // decimal value: 8409
    GLX_TEXTURE_FORMAT_RGBA_EXT                            = 0x20DA, // decimal value: 8410
    GLX_TEXTURE_1D_EXT                                     = 0x20DB, // decimal value: 8411
    GLX_TEXTURE_2D_EXT                                     = 0x20DC, // decimal value: 8412
    GLX_TEXTURE_RECTANGLE_EXT                              = 0x20DD, // decimal value: 8413
    GLX_FRONT_EXT                                          = 0x20DE, // decimal value: 8414
    GLX_FRONT_LEFT_EXT                                     = 0x20DE, // decimal value: 8414
    GLX_FRONT_RIGHT_EXT                                    = 0x20DF, // decimal value: 8415
    GLX_BACK_EXT                                           = 0x20E0, // decimal value: 8416
    GLX_BACK_LEFT_EXT                                      = 0x20E0, // decimal value: 8416
    GLX_BACK_RIGHT_EXT                                     = 0x20E1, // decimal value: 8417
    GLX_AUX0_EXT                                           = 0x20E2, // decimal value: 8418
    GLX_AUX1_EXT                                           = 0x20E3, // decimal value: 8419
    GLX_AUX2_EXT                                           = 0x20E4, // decimal value: 8420
    GLX_AUX3_EXT                                           = 0x20E5, // decimal value: 8421
    GLX_AUX4_EXT                                           = 0x20E6, // decimal value: 8422
    GLX_AUX5_EXT                                           = 0x20E7, // decimal value: 8423
    GLX_AUX6_EXT                                           = 0x20E8, // decimal value: 8424
    GLX_AUX7_EXT                                           = 0x20E9, // decimal value: 8425
    GLX_AUX8_EXT                                           = 0x20EA, // decimal value: 8426
    GLX_AUX9_EXT                                           = 0x20EB, // decimal value: 8427
    GLX_NUM_VIDEO_SLOTS_NV                                 = 0x20F0, // decimal value: 8432
    GLX_SWAP_INTERVAL_EXT                                  = 0x20F1, // decimal value: 8433
    GLX_MAX_SWAP_INTERVAL_EXT                              = 0x20F2, // decimal value: 8434
    GLX_LATE_SWAPS_TEAR_EXT                                = 0x20F3, // decimal value: 8435
    GLX_BACK_BUFFER_AGE_EXT                                = 0x20F4, // decimal value: 8436
    GLX_STEREO_TREE_EXT                                    = 0x20F5, // decimal value: 8437
    GLX_VENDOR_NAMES_EXT                                   = 0x20F6, // decimal value: 8438
    GLX_GENERATE_RESET_ON_VIDEO_MEMORY_PURGE_NV            = 0x20F7, // decimal value: 8439
    GLX_GPU_FASTEST_TARGET_GPUS_AMD                        = 0x21A2, // decimal value: 8610
    GLX_GPU_RAM_AMD                                        = 0x21A3, // decimal value: 8611
    GLX_GPU_CLOCK_AMD                                      = 0x21A4, // decimal value: 8612
    GLX_GPU_NUM_PIPES_AMD                                  = 0x21A5, // decimal value: 8613
    GLX_GPU_NUM_SIMD_AMD                                   = 0x21A6, // decimal value: 8614
    GLX_GPU_NUM_RB_AMD                                     = 0x21A7, // decimal value: 8615
    GLX_GPU_NUM_SPI_AMD                                    = 0x21A8, // decimal value: 8616
    GLX_X_VISUAL_TYPE                                      = 0x22, // decimal value: 34
    GLX_X_VISUAL_TYPE_EXT                                  = 0x22, // decimal value: 34
    GLX_TRANSPARENT_TYPE                                   = 0x23, // decimal value: 35
    GLX_TRANSPARENT_TYPE_EXT                               = 0x23, // decimal value: 35
    GLX_TRANSPARENT_INDEX_VALUE                            = 0x24, // decimal value: 36
    GLX_TRANSPARENT_INDEX_VALUE_EXT                        = 0x24, // decimal value: 36
    GLX_TRANSPARENT_RED_VALUE                              = 0x25, // decimal value: 37
    GLX_TRANSPARENT_RED_VALUE_EXT                          = 0x25, // decimal value: 37
    GLX_TRANSPARENT_GREEN_VALUE                            = 0x26, // decimal value: 38
    GLX_TRANSPARENT_GREEN_VALUE_EXT                        = 0x26, // decimal value: 38
    GLX_TRANSPARENT_BLUE_VALUE                             = 0x27, // decimal value: 39
    GLX_TRANSPARENT_BLUE_VALUE_EXT                         = 0x27, // decimal value: 39
    GLX_TRANSPARENT_ALPHA_VALUE                            = 0x28, // decimal value: 40
    GLX_TRANSPARENT_ALPHA_VALUE_EXT                        = 0x28, // decimal value: 40
    GLX_EXTENSIONS                                         = 0x3, // decimal value: 3
    GLX_CONTEXT_OPENGL_NO_ERROR_ARB                        = 0x31B3, // decimal value: 12723
    GLX_NONE                                               = 0x8000, // decimal value: 32768
    GLX_NONE_EXT                                           = 0x8000, // decimal value: 32768
    GLX_SLOW_CONFIG                                        = 0x8001, // decimal value: 32769
    GLX_SLOW_VISUAL_EXT                                    = 0x8001, // decimal value: 32769
    GLX_TRUE_COLOR                                         = 0x8002, // decimal value: 32770
    GLX_TRUE_COLOR_EXT                                     = 0x8002, // decimal value: 32770
    GLX_DIRECT_COLOR                                       = 0x8003, // decimal value: 32771
    GLX_DIRECT_COLOR_EXT                                   = 0x8003, // decimal value: 32771
    GLX_PSEUDO_COLOR                                       = 0x8004, // decimal value: 32772
    GLX_PSEUDO_COLOR_EXT                                   = 0x8004, // decimal value: 32772
    GLX_STATIC_COLOR                                       = 0x8005, // decimal value: 32773
    GLX_STATIC_COLOR_EXT                                   = 0x8005, // decimal value: 32773
    GLX_GRAY_SCALE                                         = 0x8006, // decimal value: 32774
    GLX_GRAY_SCALE_EXT                                     = 0x8006, // decimal value: 32774
    GLX_STATIC_GRAY                                        = 0x8007, // decimal value: 32775
    GLX_STATIC_GRAY_EXT                                    = 0x8007, // decimal value: 32775
    GLX_TRANSPARENT_RGB                                    = 0x8008, // decimal value: 32776
    GLX_TRANSPARENT_RGB_EXT                                = 0x8008, // decimal value: 32776
    GLX_TRANSPARENT_INDEX                                  = 0x8009, // decimal value: 32777
    GLX_TRANSPARENT_INDEX_EXT                              = 0x8009, // decimal value: 32777
    GLX_SHARE_CONTEXT_EXT                                  = 0x800A, // decimal value: 32778
    GLX_VISUAL_ID                                          = 0x800B, // decimal value: 32779
    GLX_VISUAL_ID_EXT                                      = 0x800B, // decimal value: 32779
    GLX_SCREEN                                             = 0x800C, // decimal value: 32780
    GLX_SCREEN_EXT                                         = 0x800C, // decimal value: 32780
    GLX_NON_CONFORMANT_CONFIG                              = 0x800D, // decimal value: 32781
    GLX_NON_CONFORMANT_VISUAL_EXT                          = 0x800D, // decimal value: 32781
    GLX_DRAWABLE_TYPE                                      = 0x8010, // decimal value: 32784
    GLX_DRAWABLE_TYPE_SGIX                                 = 0x8010, // decimal value: 32784
    GLX_RENDER_TYPE                                        = 0x8011, // decimal value: 32785
    GLX_RENDER_TYPE_SGIX                                   = 0x8011, // decimal value: 32785
    GLX_X_RENDERABLE                                       = 0x8012, // decimal value: 32786
    GLX_X_RENDERABLE_SGIX                                  = 0x8012, // decimal value: 32786
    GLX_FBCONFIG_ID                                        = 0x8013, // decimal value: 32787
    GLX_FBCONFIG_ID_SGIX                                   = 0x8013, // decimal value: 32787
    GLX_RGBA_TYPE                                          = 0x8014, // decimal value: 32788
    GLX_RGBA_TYPE_SGIX                                     = 0x8014, // decimal value: 32788
    GLX_COLOR_INDEX_TYPE                                   = 0x8015, // decimal value: 32789
    GLX_COLOR_INDEX_TYPE_SGIX                              = 0x8015, // decimal value: 32789
    GLX_MAX_PBUFFER_WIDTH                                  = 0x8016, // decimal value: 32790
    GLX_MAX_PBUFFER_WIDTH_SGIX                             = 0x8016, // decimal value: 32790
    GLX_MAX_PBUFFER_HEIGHT                                 = 0x8017, // decimal value: 32791
    GLX_MAX_PBUFFER_HEIGHT_SGIX                            = 0x8017, // decimal value: 32791
    GLX_MAX_PBUFFER_PIXELS                                 = 0x8018, // decimal value: 32792
    GLX_MAX_PBUFFER_PIXELS_SGIX                            = 0x8018, // decimal value: 32792
    GLX_OPTIMAL_PBUFFER_WIDTH_SGIX                         = 0x8019, // decimal value: 32793
    GLX_OPTIMAL_PBUFFER_HEIGHT_SGIX                        = 0x801A, // decimal value: 32794
    GLX_PRESERVED_CONTENTS                                 = 0x801B, // decimal value: 32795
    GLX_PRESERVED_CONTENTS_SGIX                            = 0x801B, // decimal value: 32795
    GLX_LARGEST_PBUFFER                                    = 0x801C, // decimal value: 32796
    GLX_LARGEST_PBUFFER_SGIX                               = 0x801C, // decimal value: 32796
    GLX_WIDTH                                              = 0x801D, // decimal value: 32797
    GLX_WIDTH_SGIX                                         = 0x801D, // decimal value: 32797
    GLX_HEIGHT                                             = 0x801E, // decimal value: 32798
    GLX_HEIGHT_SGIX                                        = 0x801E, // decimal value: 32798
    GLX_EVENT_MASK                                         = 0x801F, // decimal value: 32799
    GLX_EVENT_MASK_SGIX                                    = 0x801F, // decimal value: 32799
    GLX_DAMAGED                                            = 0x8020, // decimal value: 32800
    GLX_DAMAGED_SGIX                                       = 0x8020, // decimal value: 32800
    GLX_SAVED                                              = 0x8021, // decimal value: 32801
    GLX_SAVED_SGIX                                         = 0x8021, // decimal value: 32801
    GLX_WINDOW                                             = 0x8022, // decimal value: 32802
    GLX_WINDOW_SGIX                                        = 0x8022, // decimal value: 32802
    GLX_PBUFFER                                            = 0x8023, // decimal value: 32803
    GLX_PBUFFER_SGIX                                       = 0x8023, // decimal value: 32803
    GLX_DIGITAL_MEDIA_PBUFFER_SGIX                         = 0x8024, // decimal value: 32804
    GLX_BLENDED_RGBA_SGIS                                  = 0x8025, // decimal value: 32805
    GLX_MULTISAMPLE_SUB_RECT_WIDTH_SGIS                    = 0x8026, // decimal value: 32806
    GLX_MULTISAMPLE_SUB_RECT_HEIGHT_SGIS                   = 0x8027, // decimal value: 32807
    GLX_VISUAL_SELECT_GROUP_SGIX                           = 0x8028, // decimal value: 32808
    GLX_HYPERPIPE_ID_SGIX                                  = 0x8030, // decimal value: 32816
    GLX_PBUFFER_HEIGHT                                     = 0x8040, // decimal value: 32832
    GLX_PBUFFER_WIDTH                                      = 0x8041, // decimal value: 32833
    GLX_SAMPLE_BUFFERS_3DFX                                = 0x8050, // decimal value: 32848
    GLX_SAMPLES_3DFX                                       = 0x8051, // decimal value: 32849
    GLX_SWAP_METHOD_OML                                    = 0x8060, // decimal value: 32864
    GLX_SWAP_EXCHANGE_OML                                  = 0x8061, // decimal value: 32865
    GLX_SWAP_COPY_OML                                      = 0x8062, // decimal value: 32866
    GLX_SWAP_UNDEFINED_OML                                 = 0x8063, // decimal value: 32867
    GLX_EXCHANGE_COMPLETE_INTEL                            = 0x8180, // decimal value: 33152
    GLX_COPY_COMPLETE_INTEL                                = 0x8181, // decimal value: 33153
    GLX_FLIP_COMPLETE_INTEL                                = 0x8182, // decimal value: 33154
    GLX_RENDERER_VENDOR_ID_MESA                            = 0x8183, // decimal value: 33155
    GLX_RENDERER_DEVICE_ID_MESA                            = 0x8184, // decimal value: 33156
    GLX_RENDERER_VERSION_MESA                              = 0x8185, // decimal value: 33157
    GLX_RENDERER_ACCELERATED_MESA                          = 0x8186, // decimal value: 33158
    GLX_RENDERER_VIDEO_MEMORY_MESA                         = 0x8187, // decimal value: 33159
    GLX_RENDERER_UNIFIED_MEMORY_ARCHITECTURE_MESA          = 0x8188, // decimal value: 33160
    GLX_RENDERER_PREFERRED_PROFILE_MESA                    = 0x8189, // decimal value: 33161
    GLX_RENDERER_OPENGL_CORE_PROFILE_VERSION_MESA          = 0x818A, // decimal value: 33162
    GLX_RENDERER_OPENGL_COMPATIBILITY_PROFILE_VERSION_MESA = 0x818B, // decimal value: 33163
    GLX_RENDERER_OPENGL_ES_PROFILE_VERSION_MESA            = 0x818C, // decimal value: 33164
    GLX_RENDERER_OPENGL_ES2_PROFILE_VERSION_MESA           = 0x818D, // decimal value: 33165
    GLX_RENDERER_ID_MESA                                   = 0x818E, // decimal value: 33166
    GLX_LOSE_CONTEXT_ON_RESET_ARB                          = 0x8252, // decimal value: 33362
    GLX_CONTEXT_RESET_NOTIFICATION_STRATEGY_ARB            = 0x8256, // decimal value: 33366
    GLX_NO_RESET_NOTIFICATION_ARB                          = 0x8261, // decimal value: 33377
    GLX_CONTEXT_PROFILE_MASK_ARB                           = 0x9126, // decimal value: 37158
    GLX_DONT_CARE                                          = 0xFFFFFFFF, // decimal value: 4294967295
    GLX_BAD_SCREEN                                         = 1,
    GLX_BufferSwapComplete                                 = 1,
    GLX_USE_GL                                             = 1,
    GLX_BLUE_SIZE                                          = 10,
    GLX_SAMPLE_BUFFERS                                     = 100000,
    GLX_SAMPLE_BUFFERS_ARB                                 = 100000,
    GLX_SAMPLE_BUFFERS_SGIS                                = 100000,
    GLX_COVERAGE_SAMPLES_NV                                = 100001,
    GLX_SAMPLES                                            = 100001,
    GLX_SAMPLES_ARB                                        = 100001,
    GLX_SAMPLES_SGIS                                       = 100001,
    GLX_ALPHA_SIZE                                         = 11,
    GLX_DEPTH_SIZE                                         = 12,
    GLX_STENCIL_SIZE                                       = 13,
    GLX_ACCUM_RED_SIZE                                     = 14,
    GLX_ACCUM_GREEN_SIZE                                   = 15,
    GLX_ACCUM_BLUE_SIZE                                    = 16,
    GLX_ACCUM_ALPHA_SIZE                                   = 17,
    __GLX_NUMBER_EVENTS                                    = 17,
    GLX_BAD_ATTRIBUTE                                      = 2,
    GLX_BUFFER_SIZE                                        = 2,
    GLX_LEVEL                                              = 3,
    GLX_NO_EXTENSION                                       = 3,
    GLX_BAD_VISUAL                                         = 4,
    GLX_RGBA                                               = 4,
    GLX_BAD_CONTEXT                                        = 5,
    GLX_DOUBLEBUFFER                                       = 5,
    GLX_BAD_VALUE                                          = 6,
    GLX_STEREO                                             = 6,
    GLX_AUX_BUFFERS                                        = 7,
    GLX_BAD_ENUM                                           = 7,
    GLX_RED_SIZE                                           = 8,
    GLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX                    = 80,
    GLX_GREEN_SIZE                                         = 9,
    GLX_BAD_HYPERPIPE_CONFIG_SGIX                          = 91,
    GLX_BAD_HYPERPIPE_SGIX                                 = 92,

};


// import enums to namespace

// __UNGROUPED__

GLXBINDING_CONSTEXPR static const GLenum GLX_EXTENSION_NAME = GLenum::GLX_EXTENSION_NAME;
GLXBINDING_CONSTEXPR static const GLenum GLX_CONTEXT_RELEASE_BEHAVIOR_NONE_ARB = GLenum::GLX_CONTEXT_RELEASE_BEHAVIOR_NONE_ARB;
GLXBINDING_CONSTEXPR static const GLenum GLX_PbufferClobber = GLenum::GLX_PbufferClobber;
GLXBINDING_CONSTEXPR static const GLenum GLX_STEREO_NOTIFY_EXT = GLenum::GLX_STEREO_NOTIFY_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_3DFX_WINDOW_MODE_MESA = GLenum::GLX_3DFX_WINDOW_MODE_MESA;
GLXBINDING_CONSTEXPR static const GLenum GLX_VENDOR = GLenum::GLX_VENDOR;
GLXBINDING_CONSTEXPR static const GLenum GLX_GPU_VENDOR_AMD = GLenum::GLX_GPU_VENDOR_AMD;
GLXBINDING_CONSTEXPR static const GLenum GLX_GPU_RENDERER_STRING_AMD = GLenum::GLX_GPU_RENDERER_STRING_AMD;
GLXBINDING_CONSTEXPR static const GLenum GLX_GPU_OPENGL_VERSION_STRING_AMD = GLenum::GLX_GPU_OPENGL_VERSION_STRING_AMD;
GLXBINDING_CONSTEXPR static const GLenum GLX_3DFX_FULLSCREEN_MODE_MESA = GLenum::GLX_3DFX_FULLSCREEN_MODE_MESA;
GLXBINDING_CONSTEXPR static const GLenum GLX_VERSION = GLenum::GLX_VERSION;
GLXBINDING_CONSTEXPR static const GLenum GLX_CONFIG_CAVEAT = GLenum::GLX_CONFIG_CAVEAT;
GLXBINDING_CONSTEXPR static const GLenum GLX_VISUAL_CAVEAT_EXT = GLenum::GLX_VISUAL_CAVEAT_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_CONTEXT_MAJOR_VERSION_ARB = GLenum::GLX_CONTEXT_MAJOR_VERSION_ARB;
GLXBINDING_CONSTEXPR static const GLenum GLX_CONTEXT_MINOR_VERSION_ARB = GLenum::GLX_CONTEXT_MINOR_VERSION_ARB;
GLXBINDING_CONSTEXPR static const GLenum GLX_CONTEXT_FLAGS_ARB = GLenum::GLX_CONTEXT_FLAGS_ARB;
GLXBINDING_CONSTEXPR static const GLenum GLX_CONTEXT_ALLOW_BUFFER_BYTE_ORDER_MISMATCH_ARB = GLenum::GLX_CONTEXT_ALLOW_BUFFER_BYTE_ORDER_MISMATCH_ARB;
GLXBINDING_CONSTEXPR static const GLenum GLX_CONTEXT_RELEASE_BEHAVIOR_ARB = GLenum::GLX_CONTEXT_RELEASE_BEHAVIOR_ARB;
GLXBINDING_CONSTEXPR static const GLenum GLX_CONTEXT_RELEASE_BEHAVIOR_FLUSH_ARB = GLenum::GLX_CONTEXT_RELEASE_BEHAVIOR_FLUSH_ARB;
GLXBINDING_CONSTEXPR static const GLenum GLX_FLOAT_COMPONENTS_NV = GLenum::GLX_FLOAT_COMPONENTS_NV;
GLXBINDING_CONSTEXPR static const GLenum GLX_RGBA_UNSIGNED_FLOAT_TYPE_EXT = GLenum::GLX_RGBA_UNSIGNED_FLOAT_TYPE_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_FRAMEBUFFER_SRGB_CAPABLE_ARB = GLenum::GLX_FRAMEBUFFER_SRGB_CAPABLE_ARB;
GLXBINDING_CONSTEXPR static const GLenum GLX_FRAMEBUFFER_SRGB_CAPABLE_EXT = GLenum::GLX_FRAMEBUFFER_SRGB_CAPABLE_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_COLOR_SAMPLES_NV = GLenum::GLX_COLOR_SAMPLES_NV;
GLXBINDING_CONSTEXPR static const GLenum GLX_RGBA_FLOAT_TYPE_ARB = GLenum::GLX_RGBA_FLOAT_TYPE_ARB;
GLXBINDING_CONSTEXPR static const GLenum GLX_VIDEO_OUT_COLOR_NV = GLenum::GLX_VIDEO_OUT_COLOR_NV;
GLXBINDING_CONSTEXPR static const GLenum GLX_VIDEO_OUT_ALPHA_NV = GLenum::GLX_VIDEO_OUT_ALPHA_NV;
GLXBINDING_CONSTEXPR static const GLenum GLX_VIDEO_OUT_DEPTH_NV = GLenum::GLX_VIDEO_OUT_DEPTH_NV;
GLXBINDING_CONSTEXPR static const GLenum GLX_VIDEO_OUT_COLOR_AND_ALPHA_NV = GLenum::GLX_VIDEO_OUT_COLOR_AND_ALPHA_NV;
GLXBINDING_CONSTEXPR static const GLenum GLX_VIDEO_OUT_COLOR_AND_DEPTH_NV = GLenum::GLX_VIDEO_OUT_COLOR_AND_DEPTH_NV;
GLXBINDING_CONSTEXPR static const GLenum GLX_VIDEO_OUT_FRAME_NV = GLenum::GLX_VIDEO_OUT_FRAME_NV;
GLXBINDING_CONSTEXPR static const GLenum GLX_VIDEO_OUT_FIELD_1_NV = GLenum::GLX_VIDEO_OUT_FIELD_1_NV;
GLXBINDING_CONSTEXPR static const GLenum GLX_VIDEO_OUT_FIELD_2_NV = GLenum::GLX_VIDEO_OUT_FIELD_2_NV;
GLXBINDING_CONSTEXPR static const GLenum GLX_VIDEO_OUT_STACKED_FIELDS_1_2_NV = GLenum::GLX_VIDEO_OUT_STACKED_FIELDS_1_2_NV;
GLXBINDING_CONSTEXPR static const GLenum GLX_VIDEO_OUT_STACKED_FIELDS_2_1_NV = GLenum::GLX_VIDEO_OUT_STACKED_FIELDS_2_1_NV;
GLXBINDING_CONSTEXPR static const GLenum GLX_DEVICE_ID_NV = GLenum::GLX_DEVICE_ID_NV;
GLXBINDING_CONSTEXPR static const GLenum GLX_UNIQUE_ID_NV = GLenum::GLX_UNIQUE_ID_NV;
GLXBINDING_CONSTEXPR static const GLenum GLX_NUM_VIDEO_CAPTURE_SLOTS_NV = GLenum::GLX_NUM_VIDEO_CAPTURE_SLOTS_NV;
GLXBINDING_CONSTEXPR static const GLenum GLX_BIND_TO_TEXTURE_RGB_EXT = GLenum::GLX_BIND_TO_TEXTURE_RGB_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_BIND_TO_TEXTURE_RGBA_EXT = GLenum::GLX_BIND_TO_TEXTURE_RGBA_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_BIND_TO_MIPMAP_TEXTURE_EXT = GLenum::GLX_BIND_TO_MIPMAP_TEXTURE_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_BIND_TO_TEXTURE_TARGETS_EXT = GLenum::GLX_BIND_TO_TEXTURE_TARGETS_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_Y_INVERTED_EXT = GLenum::GLX_Y_INVERTED_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_TEXTURE_FORMAT_EXT = GLenum::GLX_TEXTURE_FORMAT_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_TEXTURE_TARGET_EXT = GLenum::GLX_TEXTURE_TARGET_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_MIPMAP_TEXTURE_EXT = GLenum::GLX_MIPMAP_TEXTURE_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_TEXTURE_FORMAT_NONE_EXT = GLenum::GLX_TEXTURE_FORMAT_NONE_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_TEXTURE_FORMAT_RGB_EXT = GLenum::GLX_TEXTURE_FORMAT_RGB_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_TEXTURE_FORMAT_RGBA_EXT = GLenum::GLX_TEXTURE_FORMAT_RGBA_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_TEXTURE_1D_EXT = GLenum::GLX_TEXTURE_1D_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_TEXTURE_2D_EXT = GLenum::GLX_TEXTURE_2D_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_TEXTURE_RECTANGLE_EXT = GLenum::GLX_TEXTURE_RECTANGLE_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_FRONT_EXT = GLenum::GLX_FRONT_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_FRONT_LEFT_EXT = GLenum::GLX_FRONT_LEFT_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_FRONT_RIGHT_EXT = GLenum::GLX_FRONT_RIGHT_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_BACK_EXT = GLenum::GLX_BACK_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_BACK_LEFT_EXT = GLenum::GLX_BACK_LEFT_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_BACK_RIGHT_EXT = GLenum::GLX_BACK_RIGHT_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_AUX0_EXT = GLenum::GLX_AUX0_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_AUX1_EXT = GLenum::GLX_AUX1_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_AUX2_EXT = GLenum::GLX_AUX2_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_AUX3_EXT = GLenum::GLX_AUX3_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_AUX4_EXT = GLenum::GLX_AUX4_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_AUX5_EXT = GLenum::GLX_AUX5_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_AUX6_EXT = GLenum::GLX_AUX6_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_AUX7_EXT = GLenum::GLX_AUX7_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_AUX8_EXT = GLenum::GLX_AUX8_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_AUX9_EXT = GLenum::GLX_AUX9_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_NUM_VIDEO_SLOTS_NV = GLenum::GLX_NUM_VIDEO_SLOTS_NV;
GLXBINDING_CONSTEXPR static const GLenum GLX_SWAP_INTERVAL_EXT = GLenum::GLX_SWAP_INTERVAL_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_MAX_SWAP_INTERVAL_EXT = GLenum::GLX_MAX_SWAP_INTERVAL_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_LATE_SWAPS_TEAR_EXT = GLenum::GLX_LATE_SWAPS_TEAR_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_BACK_BUFFER_AGE_EXT = GLenum::GLX_BACK_BUFFER_AGE_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_STEREO_TREE_EXT = GLenum::GLX_STEREO_TREE_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_VENDOR_NAMES_EXT = GLenum::GLX_VENDOR_NAMES_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_GENERATE_RESET_ON_VIDEO_MEMORY_PURGE_NV = GLenum::GLX_GENERATE_RESET_ON_VIDEO_MEMORY_PURGE_NV;
GLXBINDING_CONSTEXPR static const GLenum GLX_GPU_FASTEST_TARGET_GPUS_AMD = GLenum::GLX_GPU_FASTEST_TARGET_GPUS_AMD;
GLXBINDING_CONSTEXPR static const GLenum GLX_GPU_RAM_AMD = GLenum::GLX_GPU_RAM_AMD;
GLXBINDING_CONSTEXPR static const GLenum GLX_GPU_CLOCK_AMD = GLenum::GLX_GPU_CLOCK_AMD;
GLXBINDING_CONSTEXPR static const GLenum GLX_GPU_NUM_PIPES_AMD = GLenum::GLX_GPU_NUM_PIPES_AMD;
GLXBINDING_CONSTEXPR static const GLenum GLX_GPU_NUM_SIMD_AMD = GLenum::GLX_GPU_NUM_SIMD_AMD;
GLXBINDING_CONSTEXPR static const GLenum GLX_GPU_NUM_RB_AMD = GLenum::GLX_GPU_NUM_RB_AMD;
GLXBINDING_CONSTEXPR static const GLenum GLX_GPU_NUM_SPI_AMD = GLenum::GLX_GPU_NUM_SPI_AMD;
GLXBINDING_CONSTEXPR static const GLenum GLX_X_VISUAL_TYPE = GLenum::GLX_X_VISUAL_TYPE;
GLXBINDING_CONSTEXPR static const GLenum GLX_X_VISUAL_TYPE_EXT = GLenum::GLX_X_VISUAL_TYPE_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_TRANSPARENT_TYPE = GLenum::GLX_TRANSPARENT_TYPE;
GLXBINDING_CONSTEXPR static const GLenum GLX_TRANSPARENT_TYPE_EXT = GLenum::GLX_TRANSPARENT_TYPE_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_TRANSPARENT_INDEX_VALUE = GLenum::GLX_TRANSPARENT_INDEX_VALUE;
GLXBINDING_CONSTEXPR static const GLenum GLX_TRANSPARENT_INDEX_VALUE_EXT = GLenum::GLX_TRANSPARENT_INDEX_VALUE_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_TRANSPARENT_RED_VALUE = GLenum::GLX_TRANSPARENT_RED_VALUE;
GLXBINDING_CONSTEXPR static const GLenum GLX_TRANSPARENT_RED_VALUE_EXT = GLenum::GLX_TRANSPARENT_RED_VALUE_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_TRANSPARENT_GREEN_VALUE = GLenum::GLX_TRANSPARENT_GREEN_VALUE;
GLXBINDING_CONSTEXPR static const GLenum GLX_TRANSPARENT_GREEN_VALUE_EXT = GLenum::GLX_TRANSPARENT_GREEN_VALUE_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_TRANSPARENT_BLUE_VALUE = GLenum::GLX_TRANSPARENT_BLUE_VALUE;
GLXBINDING_CONSTEXPR static const GLenum GLX_TRANSPARENT_BLUE_VALUE_EXT = GLenum::GLX_TRANSPARENT_BLUE_VALUE_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_TRANSPARENT_ALPHA_VALUE = GLenum::GLX_TRANSPARENT_ALPHA_VALUE;
GLXBINDING_CONSTEXPR static const GLenum GLX_TRANSPARENT_ALPHA_VALUE_EXT = GLenum::GLX_TRANSPARENT_ALPHA_VALUE_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_EXTENSIONS = GLenum::GLX_EXTENSIONS;
GLXBINDING_CONSTEXPR static const GLenum GLX_CONTEXT_OPENGL_NO_ERROR_ARB = GLenum::GLX_CONTEXT_OPENGL_NO_ERROR_ARB;
GLXBINDING_CONSTEXPR static const GLenum GLX_NONE = GLenum::GLX_NONE;
GLXBINDING_CONSTEXPR static const GLenum GLX_NONE_EXT = GLenum::GLX_NONE_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_SLOW_CONFIG = GLenum::GLX_SLOW_CONFIG;
GLXBINDING_CONSTEXPR static const GLenum GLX_SLOW_VISUAL_EXT = GLenum::GLX_SLOW_VISUAL_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_TRUE_COLOR = GLenum::GLX_TRUE_COLOR;
GLXBINDING_CONSTEXPR static const GLenum GLX_TRUE_COLOR_EXT = GLenum::GLX_TRUE_COLOR_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_DIRECT_COLOR = GLenum::GLX_DIRECT_COLOR;
GLXBINDING_CONSTEXPR static const GLenum GLX_DIRECT_COLOR_EXT = GLenum::GLX_DIRECT_COLOR_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_PSEUDO_COLOR = GLenum::GLX_PSEUDO_COLOR;
GLXBINDING_CONSTEXPR static const GLenum GLX_PSEUDO_COLOR_EXT = GLenum::GLX_PSEUDO_COLOR_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_STATIC_COLOR = GLenum::GLX_STATIC_COLOR;
GLXBINDING_CONSTEXPR static const GLenum GLX_STATIC_COLOR_EXT = GLenum::GLX_STATIC_COLOR_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_GRAY_SCALE = GLenum::GLX_GRAY_SCALE;
GLXBINDING_CONSTEXPR static const GLenum GLX_GRAY_SCALE_EXT = GLenum::GLX_GRAY_SCALE_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_STATIC_GRAY = GLenum::GLX_STATIC_GRAY;
GLXBINDING_CONSTEXPR static const GLenum GLX_STATIC_GRAY_EXT = GLenum::GLX_STATIC_GRAY_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_TRANSPARENT_RGB = GLenum::GLX_TRANSPARENT_RGB;
GLXBINDING_CONSTEXPR static const GLenum GLX_TRANSPARENT_RGB_EXT = GLenum::GLX_TRANSPARENT_RGB_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_TRANSPARENT_INDEX = GLenum::GLX_TRANSPARENT_INDEX;
GLXBINDING_CONSTEXPR static const GLenum GLX_TRANSPARENT_INDEX_EXT = GLenum::GLX_TRANSPARENT_INDEX_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_SHARE_CONTEXT_EXT = GLenum::GLX_SHARE_CONTEXT_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_VISUAL_ID = GLenum::GLX_VISUAL_ID;
GLXBINDING_CONSTEXPR static const GLenum GLX_VISUAL_ID_EXT = GLenum::GLX_VISUAL_ID_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_SCREEN = GLenum::GLX_SCREEN;
GLXBINDING_CONSTEXPR static const GLenum GLX_SCREEN_EXT = GLenum::GLX_SCREEN_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_NON_CONFORMANT_CONFIG = GLenum::GLX_NON_CONFORMANT_CONFIG;
GLXBINDING_CONSTEXPR static const GLenum GLX_NON_CONFORMANT_VISUAL_EXT = GLenum::GLX_NON_CONFORMANT_VISUAL_EXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_DRAWABLE_TYPE = GLenum::GLX_DRAWABLE_TYPE;
GLXBINDING_CONSTEXPR static const GLenum GLX_DRAWABLE_TYPE_SGIX = GLenum::GLX_DRAWABLE_TYPE_SGIX;
GLXBINDING_CONSTEXPR static const GLenum GLX_RENDER_TYPE = GLenum::GLX_RENDER_TYPE;
GLXBINDING_CONSTEXPR static const GLenum GLX_RENDER_TYPE_SGIX = GLenum::GLX_RENDER_TYPE_SGIX;
GLXBINDING_CONSTEXPR static const GLenum GLX_X_RENDERABLE = GLenum::GLX_X_RENDERABLE;
GLXBINDING_CONSTEXPR static const GLenum GLX_X_RENDERABLE_SGIX = GLenum::GLX_X_RENDERABLE_SGIX;
GLXBINDING_CONSTEXPR static const GLenum GLX_FBCONFIG_ID = GLenum::GLX_FBCONFIG_ID;
GLXBINDING_CONSTEXPR static const GLenum GLX_FBCONFIG_ID_SGIX = GLenum::GLX_FBCONFIG_ID_SGIX;
GLXBINDING_CONSTEXPR static const GLenum GLX_RGBA_TYPE = GLenum::GLX_RGBA_TYPE;
GLXBINDING_CONSTEXPR static const GLenum GLX_RGBA_TYPE_SGIX = GLenum::GLX_RGBA_TYPE_SGIX;
GLXBINDING_CONSTEXPR static const GLenum GLX_COLOR_INDEX_TYPE = GLenum::GLX_COLOR_INDEX_TYPE;
GLXBINDING_CONSTEXPR static const GLenum GLX_COLOR_INDEX_TYPE_SGIX = GLenum::GLX_COLOR_INDEX_TYPE_SGIX;
GLXBINDING_CONSTEXPR static const GLenum GLX_MAX_PBUFFER_WIDTH = GLenum::GLX_MAX_PBUFFER_WIDTH;
GLXBINDING_CONSTEXPR static const GLenum GLX_MAX_PBUFFER_WIDTH_SGIX = GLenum::GLX_MAX_PBUFFER_WIDTH_SGIX;
GLXBINDING_CONSTEXPR static const GLenum GLX_MAX_PBUFFER_HEIGHT = GLenum::GLX_MAX_PBUFFER_HEIGHT;
GLXBINDING_CONSTEXPR static const GLenum GLX_MAX_PBUFFER_HEIGHT_SGIX = GLenum::GLX_MAX_PBUFFER_HEIGHT_SGIX;
GLXBINDING_CONSTEXPR static const GLenum GLX_MAX_PBUFFER_PIXELS = GLenum::GLX_MAX_PBUFFER_PIXELS;
GLXBINDING_CONSTEXPR static const GLenum GLX_MAX_PBUFFER_PIXELS_SGIX = GLenum::GLX_MAX_PBUFFER_PIXELS_SGIX;
GLXBINDING_CONSTEXPR static const GLenum GLX_OPTIMAL_PBUFFER_WIDTH_SGIX = GLenum::GLX_OPTIMAL_PBUFFER_WIDTH_SGIX;
GLXBINDING_CONSTEXPR static const GLenum GLX_OPTIMAL_PBUFFER_HEIGHT_SGIX = GLenum::GLX_OPTIMAL_PBUFFER_HEIGHT_SGIX;
GLXBINDING_CONSTEXPR static const GLenum GLX_PRESERVED_CONTENTS = GLenum::GLX_PRESERVED_CONTENTS;
GLXBINDING_CONSTEXPR static const GLenum GLX_PRESERVED_CONTENTS_SGIX = GLenum::GLX_PRESERVED_CONTENTS_SGIX;
GLXBINDING_CONSTEXPR static const GLenum GLX_LARGEST_PBUFFER = GLenum::GLX_LARGEST_PBUFFER;
GLXBINDING_CONSTEXPR static const GLenum GLX_LARGEST_PBUFFER_SGIX = GLenum::GLX_LARGEST_PBUFFER_SGIX;
GLXBINDING_CONSTEXPR static const GLenum GLX_WIDTH = GLenum::GLX_WIDTH;
GLXBINDING_CONSTEXPR static const GLenum GLX_WIDTH_SGIX = GLenum::GLX_WIDTH_SGIX;
GLXBINDING_CONSTEXPR static const GLenum GLX_HEIGHT = GLenum::GLX_HEIGHT;
GLXBINDING_CONSTEXPR static const GLenum GLX_HEIGHT_SGIX = GLenum::GLX_HEIGHT_SGIX;
GLXBINDING_CONSTEXPR static const GLenum GLX_EVENT_MASK = GLenum::GLX_EVENT_MASK;
GLXBINDING_CONSTEXPR static const GLenum GLX_EVENT_MASK_SGIX = GLenum::GLX_EVENT_MASK_SGIX;
GLXBINDING_CONSTEXPR static const GLenum GLX_DAMAGED = GLenum::GLX_DAMAGED;
GLXBINDING_CONSTEXPR static const GLenum GLX_DAMAGED_SGIX = GLenum::GLX_DAMAGED_SGIX;
GLXBINDING_CONSTEXPR static const GLenum GLX_SAVED = GLenum::GLX_SAVED;
GLXBINDING_CONSTEXPR static const GLenum GLX_SAVED_SGIX = GLenum::GLX_SAVED_SGIX;
GLXBINDING_CONSTEXPR static const GLenum GLX_WINDOW = GLenum::GLX_WINDOW;
GLXBINDING_CONSTEXPR static const GLenum GLX_WINDOW_SGIX = GLenum::GLX_WINDOW_SGIX;
GLXBINDING_CONSTEXPR static const GLenum GLX_PBUFFER = GLenum::GLX_PBUFFER;
GLXBINDING_CONSTEXPR static const GLenum GLX_PBUFFER_SGIX = GLenum::GLX_PBUFFER_SGIX;
GLXBINDING_CONSTEXPR static const GLenum GLX_DIGITAL_MEDIA_PBUFFER_SGIX = GLenum::GLX_DIGITAL_MEDIA_PBUFFER_SGIX;
GLXBINDING_CONSTEXPR static const GLenum GLX_BLENDED_RGBA_SGIS = GLenum::GLX_BLENDED_RGBA_SGIS;
GLXBINDING_CONSTEXPR static const GLenum GLX_MULTISAMPLE_SUB_RECT_WIDTH_SGIS = GLenum::GLX_MULTISAMPLE_SUB_RECT_WIDTH_SGIS;
GLXBINDING_CONSTEXPR static const GLenum GLX_MULTISAMPLE_SUB_RECT_HEIGHT_SGIS = GLenum::GLX_MULTISAMPLE_SUB_RECT_HEIGHT_SGIS;
GLXBINDING_CONSTEXPR static const GLenum GLX_VISUAL_SELECT_GROUP_SGIX = GLenum::GLX_VISUAL_SELECT_GROUP_SGIX;
GLXBINDING_CONSTEXPR static const GLenum GLX_HYPERPIPE_ID_SGIX = GLenum::GLX_HYPERPIPE_ID_SGIX;
GLXBINDING_CONSTEXPR static const GLenum GLX_PBUFFER_HEIGHT = GLenum::GLX_PBUFFER_HEIGHT;
GLXBINDING_CONSTEXPR static const GLenum GLX_PBUFFER_WIDTH = GLenum::GLX_PBUFFER_WIDTH;
GLXBINDING_CONSTEXPR static const GLenum GLX_SAMPLE_BUFFERS_3DFX = GLenum::GLX_SAMPLE_BUFFERS_3DFX;
GLXBINDING_CONSTEXPR static const GLenum GLX_SAMPLES_3DFX = GLenum::GLX_SAMPLES_3DFX;
GLXBINDING_CONSTEXPR static const GLenum GLX_SWAP_METHOD_OML = GLenum::GLX_SWAP_METHOD_OML;
GLXBINDING_CONSTEXPR static const GLenum GLX_SWAP_EXCHANGE_OML = GLenum::GLX_SWAP_EXCHANGE_OML;
GLXBINDING_CONSTEXPR static const GLenum GLX_SWAP_COPY_OML = GLenum::GLX_SWAP_COPY_OML;
GLXBINDING_CONSTEXPR static const GLenum GLX_SWAP_UNDEFINED_OML = GLenum::GLX_SWAP_UNDEFINED_OML;
GLXBINDING_CONSTEXPR static const GLenum GLX_EXCHANGE_COMPLETE_INTEL = GLenum::GLX_EXCHANGE_COMPLETE_INTEL;
GLXBINDING_CONSTEXPR static const GLenum GLX_COPY_COMPLETE_INTEL = GLenum::GLX_COPY_COMPLETE_INTEL;
GLXBINDING_CONSTEXPR static const GLenum GLX_FLIP_COMPLETE_INTEL = GLenum::GLX_FLIP_COMPLETE_INTEL;
GLXBINDING_CONSTEXPR static const GLenum GLX_RENDERER_VENDOR_ID_MESA = GLenum::GLX_RENDERER_VENDOR_ID_MESA;
GLXBINDING_CONSTEXPR static const GLenum GLX_RENDERER_DEVICE_ID_MESA = GLenum::GLX_RENDERER_DEVICE_ID_MESA;
GLXBINDING_CONSTEXPR static const GLenum GLX_RENDERER_VERSION_MESA = GLenum::GLX_RENDERER_VERSION_MESA;
GLXBINDING_CONSTEXPR static const GLenum GLX_RENDERER_ACCELERATED_MESA = GLenum::GLX_RENDERER_ACCELERATED_MESA;
GLXBINDING_CONSTEXPR static const GLenum GLX_RENDERER_VIDEO_MEMORY_MESA = GLenum::GLX_RENDERER_VIDEO_MEMORY_MESA;
GLXBINDING_CONSTEXPR static const GLenum GLX_RENDERER_UNIFIED_MEMORY_ARCHITECTURE_MESA = GLenum::GLX_RENDERER_UNIFIED_MEMORY_ARCHITECTURE_MESA;
GLXBINDING_CONSTEXPR static const GLenum GLX_RENDERER_PREFERRED_PROFILE_MESA = GLenum::GLX_RENDERER_PREFERRED_PROFILE_MESA;
GLXBINDING_CONSTEXPR static const GLenum GLX_RENDERER_OPENGL_CORE_PROFILE_VERSION_MESA = GLenum::GLX_RENDERER_OPENGL_CORE_PROFILE_VERSION_MESA;
GLXBINDING_CONSTEXPR static const GLenum GLX_RENDERER_OPENGL_COMPATIBILITY_PROFILE_VERSION_MESA = GLenum::GLX_RENDERER_OPENGL_COMPATIBILITY_PROFILE_VERSION_MESA;
GLXBINDING_CONSTEXPR static const GLenum GLX_RENDERER_OPENGL_ES_PROFILE_VERSION_MESA = GLenum::GLX_RENDERER_OPENGL_ES_PROFILE_VERSION_MESA;
GLXBINDING_CONSTEXPR static const GLenum GLX_RENDERER_OPENGL_ES2_PROFILE_VERSION_MESA = GLenum::GLX_RENDERER_OPENGL_ES2_PROFILE_VERSION_MESA;
GLXBINDING_CONSTEXPR static const GLenum GLX_RENDERER_ID_MESA = GLenum::GLX_RENDERER_ID_MESA;
GLXBINDING_CONSTEXPR static const GLenum GLX_LOSE_CONTEXT_ON_RESET_ARB = GLenum::GLX_LOSE_CONTEXT_ON_RESET_ARB;
GLXBINDING_CONSTEXPR static const GLenum GLX_CONTEXT_RESET_NOTIFICATION_STRATEGY_ARB = GLenum::GLX_CONTEXT_RESET_NOTIFICATION_STRATEGY_ARB;
GLXBINDING_CONSTEXPR static const GLenum GLX_NO_RESET_NOTIFICATION_ARB = GLenum::GLX_NO_RESET_NOTIFICATION_ARB;
GLXBINDING_CONSTEXPR static const GLenum GLX_CONTEXT_PROFILE_MASK_ARB = GLenum::GLX_CONTEXT_PROFILE_MASK_ARB;
GLXBINDING_CONSTEXPR static const GLenum GLX_DONT_CARE = GLenum::GLX_DONT_CARE;
GLXBINDING_CONSTEXPR static const GLenum GLX_BAD_SCREEN = GLenum::GLX_BAD_SCREEN;
GLXBINDING_CONSTEXPR static const GLenum GLX_BufferSwapComplete = GLenum::GLX_BufferSwapComplete;
GLXBINDING_CONSTEXPR static const GLenum GLX_USE_GL = GLenum::GLX_USE_GL;
GLXBINDING_CONSTEXPR static const GLenum GLX_BLUE_SIZE = GLenum::GLX_BLUE_SIZE;
GLXBINDING_CONSTEXPR static const GLenum GLX_SAMPLE_BUFFERS = GLenum::GLX_SAMPLE_BUFFERS;
GLXBINDING_CONSTEXPR static const GLenum GLX_SAMPLE_BUFFERS_ARB = GLenum::GLX_SAMPLE_BUFFERS_ARB;
GLXBINDING_CONSTEXPR static const GLenum GLX_SAMPLE_BUFFERS_SGIS = GLenum::GLX_SAMPLE_BUFFERS_SGIS;
GLXBINDING_CONSTEXPR static const GLenum GLX_COVERAGE_SAMPLES_NV = GLenum::GLX_COVERAGE_SAMPLES_NV;
GLXBINDING_CONSTEXPR static const GLenum GLX_SAMPLES = GLenum::GLX_SAMPLES;
GLXBINDING_CONSTEXPR static const GLenum GLX_SAMPLES_ARB = GLenum::GLX_SAMPLES_ARB;
GLXBINDING_CONSTEXPR static const GLenum GLX_SAMPLES_SGIS = GLenum::GLX_SAMPLES_SGIS;
GLXBINDING_CONSTEXPR static const GLenum GLX_ALPHA_SIZE = GLenum::GLX_ALPHA_SIZE;
GLXBINDING_CONSTEXPR static const GLenum GLX_DEPTH_SIZE = GLenum::GLX_DEPTH_SIZE;
GLXBINDING_CONSTEXPR static const GLenum GLX_STENCIL_SIZE = GLenum::GLX_STENCIL_SIZE;
GLXBINDING_CONSTEXPR static const GLenum GLX_ACCUM_RED_SIZE = GLenum::GLX_ACCUM_RED_SIZE;
GLXBINDING_CONSTEXPR static const GLenum GLX_ACCUM_GREEN_SIZE = GLenum::GLX_ACCUM_GREEN_SIZE;
GLXBINDING_CONSTEXPR static const GLenum GLX_ACCUM_BLUE_SIZE = GLenum::GLX_ACCUM_BLUE_SIZE;
GLXBINDING_CONSTEXPR static const GLenum GLX_ACCUM_ALPHA_SIZE = GLenum::GLX_ACCUM_ALPHA_SIZE;
GLXBINDING_CONSTEXPR static const GLenum __GLX_NUMBER_EVENTS = GLenum::__GLX_NUMBER_EVENTS;
GLXBINDING_CONSTEXPR static const GLenum GLX_BAD_ATTRIBUTE = GLenum::GLX_BAD_ATTRIBUTE;
GLXBINDING_CONSTEXPR static const GLenum GLX_BUFFER_SIZE = GLenum::GLX_BUFFER_SIZE;
GLXBINDING_CONSTEXPR static const GLenum GLX_LEVEL = GLenum::GLX_LEVEL;
GLXBINDING_CONSTEXPR static const GLenum GLX_NO_EXTENSION = GLenum::GLX_NO_EXTENSION;
GLXBINDING_CONSTEXPR static const GLenum GLX_BAD_VISUAL = GLenum::GLX_BAD_VISUAL;
GLXBINDING_CONSTEXPR static const GLenum GLX_RGBA = GLenum::GLX_RGBA;
GLXBINDING_CONSTEXPR static const GLenum GLX_BAD_CONTEXT = GLenum::GLX_BAD_CONTEXT;
GLXBINDING_CONSTEXPR static const GLenum GLX_DOUBLEBUFFER = GLenum::GLX_DOUBLEBUFFER;
GLXBINDING_CONSTEXPR static const GLenum GLX_BAD_VALUE = GLenum::GLX_BAD_VALUE;
GLXBINDING_CONSTEXPR static const GLenum GLX_STEREO = GLenum::GLX_STEREO;
GLXBINDING_CONSTEXPR static const GLenum GLX_AUX_BUFFERS = GLenum::GLX_AUX_BUFFERS;
GLXBINDING_CONSTEXPR static const GLenum GLX_BAD_ENUM = GLenum::GLX_BAD_ENUM;
GLXBINDING_CONSTEXPR static const GLenum GLX_RED_SIZE = GLenum::GLX_RED_SIZE;
GLXBINDING_CONSTEXPR static const GLenum GLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX = GLenum::GLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX;
GLXBINDING_CONSTEXPR static const GLenum GLX_GREEN_SIZE = GLenum::GLX_GREEN_SIZE;
GLXBINDING_CONSTEXPR static const GLenum GLX_BAD_HYPERPIPE_CONFIG_SGIX = GLenum::GLX_BAD_HYPERPIPE_CONFIG_SGIX;
GLXBINDING_CONSTEXPR static const GLenum GLX_BAD_HYPERPIPE_SGIX = GLenum::GLX_BAD_HYPERPIPE_SGIX;



} // namespace glx
