
#include "Binding_pch.h"


using namespace glsc;


namespace glscbinding
{


const Binding::array_t Binding::s_functions =
{{
    &ActiveTexture,
    &BindBuffer,
    &BindFramebuffer,
    &BindRenderbuffer,
    &BindTexture,
    &BlendColor,
    &BlendEquation,
    &BlendEquationSeparate,
    &BlendFunc,
    &BlendFuncSeparate,
    &BufferData,
    &BufferSubData,
    &CheckFramebufferStatus,
    &Clear,
    &ClearColor,
    &ClearDepthf,
    &ClearStencil,
    &ColorMask,
    &CompressedTexSubImage2D,
    &CreateProgram,
    &CullFace,
    &DepthFunc,
    &DepthMask,
    &DepthRangef,
    &Disable,
    &DisableVertexAttribArray,
    &DrawArrays,
    &DrawRangeElements,
    &Enable,
    &EnableVertexAttribArray,
    &Finish,
    &Flush,
    &FramebufferRenderbuffer,
    &FramebufferTexture2D,
    &FrontFace,
    &GenBuffers,
    &GenFramebuffers,
    &GenRenderbuffers,
    &GenTextures,
    &GenerateMipmap,
    &GetAttribLocation,
    &GetBooleanv,
    &GetBufferParameteriv,
    &GetError,
    &GetFloatv,
    &GetFramebufferAttachmentParameteriv,
    &GetGraphicsResetStatus,
    &GetIntegerv,
    &GetProgramiv,
    &GetRenderbufferParameteriv,
    &GetString,
    &GetTexParameterfv,
    &GetTexParameteriv,
    &GetUniformLocation,
    &GetVertexAttribPointerv,
    &GetVertexAttribfv,
    &GetVertexAttribiv,
    &GetnUniformfv,
    &GetnUniformiv,
    &Hint,
    &IsEnabled,
    &LineWidth,
    &PixelStorei,
    &PolygonOffset,
    &ProgramBinary,
    &ReadnPixels,
    &RenderbufferStorage,
    &SampleCoverage,
    &Scissor,
    &StencilFunc,
    &StencilFuncSeparate,
    &StencilMask,
    &StencilMaskSeparate,
    &StencilOp,
    &StencilOpSeparate,
    &TexParameterf,
    &TexParameterfv,
    &TexParameteri,
    &TexParameteriv,
    &TexStorage2D,
    &TexSubImage2D,
    &Uniform1f,
    &Uniform1fv,
    &Uniform1i,
    &Uniform1iv,
    &Uniform2f,
    &Uniform2fv,
    &Uniform2i,
    &Uniform2iv,
    &Uniform3f,
    &Uniform3fv,
    &Uniform3i,
    &Uniform3iv,
    &Uniform4f,
    &Uniform4fv,
    &Uniform4i,
    &Uniform4iv,
    &UniformMatrix2fv,
    &UniformMatrix3fv,
    &UniformMatrix4fv,
    &UseProgram,
    &VertexAttrib1f,
    &VertexAttrib1fv,
    &VertexAttrib2f,
    &VertexAttrib2fv,
    &VertexAttrib3f,
    &VertexAttrib3fv,
    &VertexAttrib4f,
    &VertexAttrib4fv,
    &VertexAttribPointer,
    &Viewport
}};


} // namespace glscbinding
