
#pragma once


#include <eglbinding/noegl.h>

#include <eglbinding/eglbinding_features.h>

#include <eglbinding/SharedBitfield.h>


namespace egl
{



// import bitfields to namespace

EGLBINDING_CONSTEXPR static const None GL_NONE_BIT = None::GL_NONE_BIT;
EGLBINDING_CONSTEXPR static const None EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT = None::EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT;
EGLBINDING_CONSTEXPR static const None EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT_KHR = None::EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT_KHR;
EGLBINDING_CONSTEXPR static const None EGL_CONTEXT_OPENGL_DEBUG_BIT_KHR = None::EGL_CONTEXT_OPENGL_DEBUG_BIT_KHR;
EGLBINDING_CONSTEXPR static const None EGL_DRM_BUFFER_USE_SCANOUT_MESA = None::EGL_DRM_BUFFER_USE_SCANOUT_MESA;
EGLBINDING_CONSTEXPR static const None EGL_NATIVE_BUFFER_USAGE_PROTECTED_BIT_ANDROID = None::EGL_NATIVE_BUFFER_USAGE_PROTECTED_BIT_ANDROID;
EGLBINDING_CONSTEXPR static const None EGL_CONTEXT_OPENGL_COMPATIBILITY_PROFILE_BIT = None::EGL_CONTEXT_OPENGL_COMPATIBILITY_PROFILE_BIT;
EGLBINDING_CONSTEXPR static const None EGL_CONTEXT_OPENGL_COMPATIBILITY_PROFILE_BIT_KHR = None::EGL_CONTEXT_OPENGL_COMPATIBILITY_PROFILE_BIT_KHR;
EGLBINDING_CONSTEXPR static const None EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE_BIT_KHR = None::EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE_BIT_KHR;
EGLBINDING_CONSTEXPR static const None EGL_DRM_BUFFER_USE_SHARE_MESA = None::EGL_DRM_BUFFER_USE_SHARE_MESA;
EGLBINDING_CONSTEXPR static const None EGL_NATIVE_BUFFER_USAGE_RENDERBUFFER_BIT_ANDROID = None::EGL_NATIVE_BUFFER_USAGE_RENDERBUFFER_BIT_ANDROID;
EGLBINDING_CONSTEXPR static const None EGL_CONTEXT_OPENGL_ROBUST_ACCESS_BIT_KHR = None::EGL_CONTEXT_OPENGL_ROBUST_ACCESS_BIT_KHR;
EGLBINDING_CONSTEXPR static const None EGL_DRM_BUFFER_USE_CURSOR_MESA = None::EGL_DRM_BUFFER_USE_CURSOR_MESA;
EGLBINDING_CONSTEXPR static const None EGL_NATIVE_BUFFER_USAGE_TEXTURE_BIT_ANDROID = None::EGL_NATIVE_BUFFER_USAGE_TEXTURE_BIT_ANDROID;
EGLBINDING_CONSTEXPR static const None EGL_OPENGL_ES3_BIT = None::EGL_OPENGL_ES3_BIT;
EGLBINDING_CONSTEXPR static const None EGL_OPENGL_ES3_BIT_KHR = None::EGL_OPENGL_ES3_BIT_KHR;
EGLBINDING_CONSTEXPR static const None EGL_OPENGL_ES_BIT = None::EGL_OPENGL_ES_BIT;
EGLBINDING_CONSTEXPR static const None EGL_PBUFFER_BIT = None::EGL_PBUFFER_BIT;
EGLBINDING_CONSTEXPR static const None EGL_READ_SURFACE_BIT_KHR = None::EGL_READ_SURFACE_BIT_KHR;
EGLBINDING_CONSTEXPR static const None EGL_SYNC_FLUSH_COMMANDS_BIT = None::EGL_SYNC_FLUSH_COMMANDS_BIT;
EGLBINDING_CONSTEXPR static const None EGL_SYNC_FLUSH_COMMANDS_BIT_KHR = None::EGL_SYNC_FLUSH_COMMANDS_BIT_KHR;
EGLBINDING_CONSTEXPR static const None EGL_SYNC_FLUSH_COMMANDS_BIT_NV = None::EGL_SYNC_FLUSH_COMMANDS_BIT_NV;
EGLBINDING_CONSTEXPR static const None EGL_OPENVG_BIT = None::EGL_OPENVG_BIT;
EGLBINDING_CONSTEXPR static const None EGL_PIXMAP_BIT = None::EGL_PIXMAP_BIT;
EGLBINDING_CONSTEXPR static const None EGL_WRITE_SURFACE_BIT_KHR = None::EGL_WRITE_SURFACE_BIT_KHR;
EGLBINDING_CONSTEXPR static const None EGL_OPENGL_ES2_BIT = None::EGL_OPENGL_ES2_BIT;
EGLBINDING_CONSTEXPR static const None EGL_WINDOW_BIT = None::EGL_WINDOW_BIT;
EGLBINDING_CONSTEXPR static const None EGL_OPENGL_BIT = None::EGL_OPENGL_BIT;
EGLBINDING_CONSTEXPR static const None EGL_VG_COLORSPACE_LINEAR_BIT = None::EGL_VG_COLORSPACE_LINEAR_BIT;
EGLBINDING_CONSTEXPR static const None EGL_VG_COLORSPACE_LINEAR_BIT_KHR = None::EGL_VG_COLORSPACE_LINEAR_BIT_KHR;
EGLBINDING_CONSTEXPR static const None EGL_VG_ALPHA_FORMAT_PRE_BIT = None::EGL_VG_ALPHA_FORMAT_PRE_BIT;
EGLBINDING_CONSTEXPR static const None EGL_VG_ALPHA_FORMAT_PRE_BIT_KHR = None::EGL_VG_ALPHA_FORMAT_PRE_BIT_KHR;
EGLBINDING_CONSTEXPR static const None EGL_LOCK_SURFACE_BIT_KHR = None::EGL_LOCK_SURFACE_BIT_KHR;
EGLBINDING_CONSTEXPR static const None EGL_OPTIMAL_FORMAT_BIT_KHR = None::EGL_OPTIMAL_FORMAT_BIT_KHR;
EGLBINDING_CONSTEXPR static const None EGL_MULTISAMPLE_RESOLVE_BOX_BIT = None::EGL_MULTISAMPLE_RESOLVE_BOX_BIT;
EGLBINDING_CONSTEXPR static const None EGL_SWAP_BEHAVIOR_PRESERVED_BIT = None::EGL_SWAP_BEHAVIOR_PRESERVED_BIT;
EGLBINDING_CONSTEXPR static const None EGL_STREAM_BIT_KHR = None::EGL_STREAM_BIT_KHR;
EGLBINDING_CONSTEXPR static const None EGL_MUTABLE_RENDER_BUFFER_BIT_KHR = None::EGL_MUTABLE_RENDER_BUFFER_BIT_KHR;


} // namespace egl
