#pragma once

#include <eglbinding/noegl.h>


namespace egl
{

enum class EGLenum : unsigned int
{
    // __UNGROUPED__

    EGL_DONT_CARE                                      = static_cast<unsigned int>(-1),
    EGL_NO_FILE_DESCRIPTOR_KHR                         = static_cast<unsigned int>(-1),
    EGL_NO_NATIVE_FENCE_FD_ANDROID                     = static_cast<unsigned int>(-1),
    EGL_UNKNOWN                                        = static_cast<unsigned int>(-1),
    EGL_DEFAULT_DISPLAY                                = 0,
    EGL_DEPTH_ENCODING_NONE_NV                         = 0,
    EGL_NO_CONTEXT                                     = 0,
    EGL_NO_DEVICE_EXT                                  = 0,
    EGL_NO_DISPLAY                                     = 0,
    EGL_NO_IMAGE                                       = 0,
    EGL_NO_IMAGE_KHR                                   = 0,
    EGL_NO_OUTPUT_LAYER_EXT                            = 0,
    EGL_NO_OUTPUT_PORT_EXT                             = 0,
    EGL_NO_STREAM_KHR                                  = 0,
    EGL_NO_SURFACE                                     = 0,
    EGL_NO_SYNC                                        = 0,
    EGL_NO_SYNC_KHR                                    = 0,
    EGL_NO_SYNC_NV                                     = 0,
    EGL_ALREADY_SIGNALED_NV                            = 30,
    EGL_BITMAP_PIXEL_ALPHA_OFFSET_KHR                  = 30,
    EGL_BITMAP_PIXEL_BLUE_OFFSET_KHR                   = 30,
    EGL_BITMAP_PIXEL_GREEN_OFFSET_KHR                  = 30,
    EGL_BITMAP_PIXEL_LUMINANCE_OFFSET_KHR              = 30,
    EGL_CONDITION_SATISFIED_NV                         = 30,
    EGL_CONTEXT_FLAGS_KHR                              = 30,
    EGL_CONTEXT_MINOR_VERSION                          = 30,
    EGL_CONTEXT_MINOR_VERSION_KHR                      = 30,
    EGL_CONTEXT_OPENGL_PROFILE_MASK                    = 30,
    EGL_CONTEXT_OPENGL_PROFILE_MASK_KHR                = 30,
    EGL_CONTEXT_OPENGL_ROBUST_ACCESS_EXT               = 30,
    EGL_GL_TEXTURE_LEVEL                               = 30,
    EGL_GL_TEXTURE_LEVEL_KHR                           = 30,
    EGL_GL_TEXTURE_ZOFFSET                             = 30,
    EGL_GL_TEXTURE_ZOFFSET_KHR                         = 30,
    EGL_LOWER_LEFT_KHR                                 = 30,
    EGL_POST_SUB_BUFFER_SUPPORTED_NV                   = 30,
    EGL_SYNC_CL_EVENT                                  = 30,
    EGL_SYNC_CL_EVENT_COMPLETE                         = 30,
    EGL_SYNC_CL_EVENT_COMPLETE_KHR                     = 30,
    EGL_SYNC_CL_EVENT_KHR                              = 30,
    EGL_SYNC_CONDITION_NV                              = 30,
    EGL_SYNC_FENCE_NV                                  = 30,
    EGL_SYNC_REUSABLE_KHR                              = 30,
    EGL_SYNC_TYPE_NV                                   = 30,
    EGL_TIMEOUT_EXPIRED_NV                             = 30,
    EGL_UPPER_LEFT_KHR                                 = 30,
    EGL_VG_PARENT_IMAGE_KHR                            = 30,
    EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY     = 31,
    EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_KHR = 31,
    EGL_LOSE_CONTEXT_ON_RESET                          = 31,
    EGL_LOSE_CONTEXT_ON_RESET_EXT                      = 31,
    EGL_LOSE_CONTEXT_ON_RESET_KHR                      = 31,
    EGL_NO_RESET_NOTIFICATION                          = 31,
    EGL_NO_RESET_NOTIFICATION_EXT                      = 31,
    EGL_NO_RESET_NOTIFICATION_KHR                      = 31,
    EGL_STREAM_FIFO_LENGTH_KHR                         = 31,
    EGL_STREAM_TIME_CONSUMER_KHR                       = 31,
    EGL_STREAM_TIME_NOW_KHR                            = 31,
    EGL_STREAM_TIME_PRODUCER_KHR                       = 31,
    EGL_BAD_NATIVE_PIXMAP                              = 300,
    EGL_BAD_NATIVE_WINDOW                              = 300,
    EGL_BAD_PARAMETER                                  = 300,
    EGL_BAD_SURFACE                                    = 300,
    EGL_CONTEXT_LOST                                   = 300,
    EGL_COVERAGE_BUFFERS_NV                            = 300,
    EGL_FORMAT_RGB_565_EXACT_KHR                       = 300,
    EGL_NATIVE_PIXMAP_KHR                              = 300,
    EGL_OPENGL_ES_API                                  = 300,
    EGL_SYNC_PRIOR_COMMANDS_COMPLETE                   = 300,
    EGL_SYNC_PRIOR_COMMANDS_COMPLETE_KHR               = 300,
    EGL_COVERAGE_SAMPLES_NV                            = 301,
    EGL_FORMAT_RGB_565_KHR                             = 301,
    EGL_GL_TEXTURE_2D                                  = 301,
    EGL_GL_TEXTURE_2D_KHR                              = 301,
    EGL_OPENVG_API                                     = 301,
    EGL_SYNC_STATUS                                    = 301,
    EGL_SYNC_STATUS_KHR                                = 301,
    EGL_DEPTH_ENCODING_NV                              = 302,
    EGL_FORMAT_RGBA_8888_EXACT_KHR                     = 302,
    EGL_GL_TEXTURE_3D                                  = 302,
    EGL_GL_TEXTURE_3D_KHR                              = 302,
    EGL_IMAGE_PRESERVED                                = 302,
    EGL_IMAGE_PRESERVED_KHR                            = 302,
    EGL_MAX_PBUFFER_HEIGHT                             = 302,
    EGL_MAX_PBUFFER_PIXELS                             = 302,
    EGL_MAX_PBUFFER_WIDTH                              = 302,
    EGL_NATIVE_RENDERABLE                              = 302,
    EGL_NATIVE_VISUAL_ID                               = 302,
    EGL_NATIVE_VISUAL_TYPE                             = 302,
    EGL_OPENGL_API                                     = 302,
    EGL_SIGNALED                                       = 302,
    EGL_SIGNALED_KHR                                   = 302,
    EGL_ALPHA_MASK_SIZE                                = 303,
    EGL_BIND_TO_TEXTURE_RGBA                           = 303,
    EGL_COLOR_BUFFER_TYPE                              = 303,
    EGL_DEPTH_ENCODING_NONLINEAR_NV                    = 303,
    EGL_FORMAT_RGBA_8888_KHR                           = 303,
    EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_X                 = 303,
    EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_X_KHR             = 303,
    EGL_LUMINANCE_SIZE                                 = 303,
    EGL_MAX_SWAP_INTERVAL                              = 303,
    EGL_MIN_SWAP_INTERVAL                              = 303,
    EGL_UNSIGNALED                                     = 303,
    EGL_UNSIGNALED_KHR                                 = 303,
    EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_X                 = 304,
    EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_X_KHR             = 304,
    EGL_MAP_PRESERVE_PIXELS_KHR                        = 304,
    EGL_CORE_NATIVE_ENGINE                             = 305,
    EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Y                 = 305,
    EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Y_KHR             = 305,
    EGL_LOCK_USAGE_HINT_KHR                            = 305,
    EGL_NO_TEXTURE                                     = 305,
    EGL_READ                                           = 305,
    EGL_TEXTURE_2D                                     = 305,
    EGL_TEXTURE_RGB                                    = 305,
    EGL_TEXTURE_RGBA                                   = 305,
    EGL_TIMEOUT_EXPIRED                                = 305,
    EGL_TIMEOUT_EXPIRED_KHR                            = 305,
    EGL_BITMAP_POINTER_KHR                             = 306,
    EGL_CONDITION_SATISFIED                            = 306,
    EGL_CONDITION_SATISFIED_KHR                        = 306,
    EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y                 = 306,
    EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y_KHR             = 306,
    EGL_SYNC_PRIOR_COMMANDS_COMPLETE_NV                = 306,
    EGL_BITMAP_PITCH_KHR                               = 307,
    EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Z                 = 307,
    EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Z_KHR             = 307,
    EGL_SYNC_STATUS_NV                                 = 307,
    EGL_SYNC_TYPE                                      = 307,
    EGL_SYNC_TYPE_KHR                                  = 307,
    EGL_Y_INVERTED_NOK                                 = 307,
    EGL_ALPHA_FORMAT_NONPRE                            = 308,
    EGL_ALPHA_FORMAT_PRE                               = 308,
    EGL_BITMAP_ORIGIN_KHR                              = 308,
    EGL_CLIENT_APIS                                    = 308,
    EGL_COLORSPACE_LINEAR                              = 308,
    EGL_GL_COLORSPACE_LINEAR                           = 308,
    EGL_GL_COLORSPACE_LINEAR_KHR                       = 308,
    EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z                 = 308,
    EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z_KHR             = 308,
    EGL_LUMINANCE_BUFFER                               = 308,
    EGL_RGB_BUFFER                                     = 308,
    EGL_SIGNALED_NV                                    = 308,
    EGL_SYNC_CONDITION                                 = 308,
    EGL_SYNC_CONDITION_KHR                             = 308,
    EGL_VG_ALPHA_FORMAT_NONPRE                         = 308,
    EGL_VG_ALPHA_FORMAT_PRE                            = 308,
    EGL_VG_COLORSPACE_LINEAR                           = 308,
    EGL_BITMAP_PIXEL_RED_OFFSET_KHR                    = 309,
    EGL_CL_EVENT_HANDLE                                = 309,
    EGL_CL_EVENT_HANDLE_KHR                            = 309,
    EGL_GL_COLORSPACE                                  = 309,
    EGL_GL_COLORSPACE_KHR                              = 309,
    EGL_GL_RENDERBUFFER                                = 309,
    EGL_GL_RENDERBUFFER_KHR                            = 309,
    EGL_MULTISAMPLE_RESOLVE_BOX                        = 309,
    EGL_MULTISAMPLE_RESOLVE_DEFAULT                    = 309,
    EGL_SYNC_FENCE                                     = 309,
    EGL_SYNC_FENCE_KHR                                 = 309,
    EGL_UNSIGNALED_NV                                  = 309,
    EGL_CONTEXT_OPENGL_DEBUG                           = 310,
    EGL_DRM_BUFFER_FORMAT_MESA                         = 310,
    EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE              = 311,
    EGL_DRM_BUFFER_USE_MESA                            = 311,
    EGL_CONTEXT_OPENGL_ROBUST_ACCESS                   = 312,
    EGL_DRM_BUFFER_FORMAT_ARGB32_MESA                  = 312,
    EGL_BUFFER_AGE_EXT                                 = 313,
    EGL_BUFFER_AGE_KHR                                 = 313,
    EGL_CONTEXT_OPENGL_NO_ERROR_KHR                    = 313,
    EGL_DRM_BUFFER_MESA                                = 313,
    EGL_PLATFORM_DEVICE_EXT                            = 313,
    EGL_DRM_BUFFER_STRIDE_MESA                         = 314,
    EGL_PLATFORM_X11_EXT                               = 315,
    EGL_PLATFORM_X11_KHR                               = 315,
    EGL_PLATFORM_X11_SCREEN_EXT                        = 316,
    EGL_PLATFORM_X11_SCREEN_KHR                        = 316,
    EGL_PLATFORM_GBM_KHR                               = 317,
    EGL_PLATFORM_GBM_MESA                              = 317,
    EGL_PLATFORM_WAYLAND_EXT                           = 318,
    EGL_PLATFORM_WAYLAND_KHR                           = 318,
    EGL_NATIVE_BUFFER_TIZEN                            = 320,
    EGL_PROTECTED_CONTENT_EXT                          = 320,
    EGL_BAD_STATE_KHR                                  = 321,
    EGL_BAD_STREAM_KHR                                 = 321,
    EGL_CONSUMER_ACQUIRE_TIMEOUT_USEC_KHR              = 321,
    EGL_NATIVE_SURFACE_TIZEN                           = 321,
    EGL_STREAM_STATE_DISCONNECTED_KHR                  = 321,
    EGL_SYNC_NEW_FRAME_NV                              = 321,
    EGL_BAD_DEVICE_EXT                                 = 322,
    EGL_BAD_OUTPUT_LAYER_EXT                           = 322,
    EGL_BAD_OUTPUT_PORT_EXT                            = 322,
    EGL_DEVICE_EXT                                     = 322,
    EGL_SWAP_INTERVAL_EXT                              = 322,
    EGL_CUDA_DEVICE_NV                                 = 323,
    EGL_CUDA_EVENT_HANDLE_NV                           = 323,
    EGL_SYNC_CUDA_EVENT_COMPLETE_NV                    = 323,
    EGL_SYNC_CUDA_EVENT_NV                             = 323,
    EGL_DMA_BUF_PLANE2_PITCH_EXT                       = 327,
    EGL_ITU_REC601_EXT                                 = 327,
    EGL_SAMPLE_RANGE_HINT_EXT                          = 327,
    EGL_YUV_CHROMA_HORIZONTAL_SITING_HINT_EXT          = 327,
    EGL_YUV_CHROMA_VERTICAL_SITING_HINT_EXT            = 327,
    EGL_YUV_COLOR_SPACE_HINT_EXT                       = 327,
    EGL_D3D9_DEVICE_ANGLE                              = 330,
    EGL_YUV_CSC_STANDARD_2020_EXT                      = 330,
    EGL_YUV_CSC_STANDARD_601_EXT                       = 330,
    EGL_YUV_CSC_STANDARD_709_EXT                       = 330,
    EGL_YUV_CSC_STANDARD_EXT                           = 330,
    EGL_D3D11_DEVICE_ANGLE                             = 331,
    EGL_YUV_PLANE_BPP_0_EXT                            = 331,
    EGL_YUV_PLANE_BPP_10_EXT                           = 331,
    EGL_YUV_PLANE_BPP_8_EXT                            = 331,
    EGL_YUV_PLANE_BPP_EXT                              = 331,
    EGL_COLOR_FORMAT_HI                                = 870,
    EGL_COLOR_RGB_HI                                   = 871,
    EGL_COLOR_RGBA_HI                                  = 872,
    EGL_COLOR_ARGB_HI                                  = 873,
    EGL_CLIENT_PIXMAP_POINTER_HI                       = 874,
    EGL_SUCCESS                                        = 3000,
    EGL_NOT_INITIALIZED                                = 3001,
    EGL_BAD_ACCESS                                     = 3002,
    EGL_BAD_ALLOC                                      = 3003,
    EGL_BAD_ATTRIBUTE                                  = 3004,
    EGL_BAD_CONFIG                                     = 3005,
    EGL_BAD_CONTEXT                                    = 3006,
    EGL_BAD_CURRENT_SURFACE                            = 3007,
    EGL_BAD_DISPLAY                                    = 3008,
    EGL_BAD_MATCH                                      = 3009,
    EGL_BUFFER_SIZE                                    = 3020,
    EGL_ALPHA_SIZE                                     = 3021,
    EGL_BLUE_SIZE                                      = 3022,
    EGL_GREEN_SIZE                                     = 3023,
    EGL_RED_SIZE                                       = 3024,
    EGL_DEPTH_SIZE                                     = 3025,
    EGL_STENCIL_SIZE                                   = 3026,
    EGL_CONFIG_CAVEAT                                  = 3027,
    EGL_CONFIG_ID                                      = 3028,
    EGL_LEVEL                                          = 3029,
    EGL_SAMPLES                                        = 3031,
    EGL_SAMPLE_BUFFERS                                 = 3032,
    EGL_SURFACE_TYPE                                   = 3033,
    EGL_TRANSPARENT_TYPE                               = 3034,
    EGL_TRANSPARENT_BLUE_VALUE                         = 3035,
    EGL_TRANSPARENT_GREEN_VALUE                        = 3036,
    EGL_TRANSPARENT_RED_VALUE                          = 3037,
    EGL_NONE                                           = 3038,
    EGL_BIND_TO_TEXTURE_RGB                            = 3039,
    EGL_RENDERABLE_TYPE                                = 3040,
    EGL_MATCH_NATIVE_PIXMAP                            = 3041,
    EGL_CONFORMANT                                     = 3042,
    EGL_CONFORMANT_KHR                                 = 3042,
    EGL_MATCH_FORMAT_KHR                               = 3043,
    EGL_SLOW_CONFIG                                    = 3050,
    EGL_NON_CONFORMANT_CONFIG                          = 3051,
    EGL_TRANSPARENT_RGB                                = 3052,
    EGL_VENDOR                                         = 3053,
    EGL_VERSION                                        = 3054,
    EGL_EXTENSIONS                                     = 3055,
    EGL_HEIGHT                                         = 3056,
    EGL_WIDTH                                          = 3057,
    EGL_LARGEST_PBUFFER                                = 3058,
    EGL_DRAW                                           = 3059,
    EGL_TEXTURE_FORMAT                                 = 3080,
    EGL_TEXTURE_TARGET                                 = 3081,
    EGL_MIPMAP_TEXTURE                                 = 3082,
    EGL_MIPMAP_LEVEL                                   = 3083,
    EGL_BACK_BUFFER                                    = 3084,
    EGL_SINGLE_BUFFER                                  = 3085,
    EGL_RENDER_BUFFER                                  = 3086,
    EGL_COLORSPACE                                     = 3087,
    EGL_VG_COLORSPACE                                  = 3087,
    EGL_ALPHA_FORMAT                                   = 3088,
    EGL_VG_ALPHA_FORMAT                                = 3088,
    EGL_COLORSPACE_sRGB                                = 3089,
    EGL_GL_COLORSPACE_SRGB                             = 3089,
    EGL_GL_COLORSPACE_SRGB_KHR                         = 3089,
    EGL_VG_COLORSPACE_sRGB                             = 3089,
    EGL_HORIZONTAL_RESOLUTION                          = 3090,
    EGL_VERTICAL_RESOLUTION                            = 3091,
    EGL_PIXEL_ASPECT_RATIO                             = 3092,
    EGL_SWAP_BEHAVIOR                                  = 3093,
    EGL_BUFFER_PRESERVED                               = 3094,
    EGL_BUFFER_DESTROYED                               = 3095,
    EGL_OPENVG_IMAGE                                   = 3096,
    EGL_CONTEXT_CLIENT_TYPE                            = 3097,
    EGL_CONTEXT_CLIENT_VERSION                         = 3098,
    EGL_CONTEXT_MAJOR_VERSION                          = 3098,
    EGL_CONTEXT_MAJOR_VERSION_KHR                      = 3098,
    EGL_MULTISAMPLE_RESOLVE                            = 3099,
    EGL_CONTEXT_PRIORITY_LEVEL_IMG                     = 3100,
    EGL_CONTEXT_PRIORITY_HIGH_IMG                      = 3101,
    EGL_CONTEXT_PRIORITY_MEDIUM_IMG                    = 3102,
    EGL_CONTEXT_PRIORITY_LOW_IMG                       = 3103,
    EGL_BITMAP_PIXEL_SIZE_KHR                          = 3110,
    EGL_COVERAGE_SAMPLE_RESOLVE_NV                     = 3131,
    EGL_COVERAGE_SAMPLE_RESOLVE_DEFAULT_NV             = 3132,
    EGL_COVERAGE_SAMPLE_RESOLVE_NONE_NV                = 3133,
    EGL_MULTIVIEW_VIEW_COUNT_EXT                       = 3134,
    EGL_AUTO_STEREO_NV                                 = 3136,
    EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_EXT = 3138,
    EGL_NATIVE_BUFFER_ANDROID                          = 3140,
    EGL_PLATFORM_ANDROID_KHR                           = 3141,
    EGL_RECORDABLE_ANDROID                             = 3142,
    EGL_SYNC_NATIVE_FENCE_ANDROID                      = 3144,
    EGL_SYNC_NATIVE_FENCE_FD_ANDROID                   = 3145,
    EGL_SYNC_NATIVE_FENCE_SIGNALED_ANDROID             = 3146,
    EGL_FRAMEBUFFER_TARGET_ANDROID                     = 3147,
    EGL_D3D_TEXTURE_2D_SHARE_HANDLE_ANGLE              = 3200,
    EGL_FIXED_SIZE_ANGLE                               = 3201,
    EGL_CONSUMER_LATENCY_USEC_KHR                      = 3210,
    EGL_PRODUCER_FRAME_KHR                             = 3212,
    EGL_CONSUMER_FRAME_KHR                             = 3213,
    EGL_STREAM_STATE_KHR                               = 3214,
    EGL_STREAM_STATE_CREATED_KHR                       = 3215,
    EGL_STREAM_STATE_CONNECTING_KHR                    = 3216,
    EGL_STREAM_STATE_EMPTY_KHR                         = 3217,
    EGL_STREAM_STATE_NEW_FRAME_AVAILABLE_KHR           = 3218,
    EGL_STREAM_STATE_OLD_FRAME_AVAILABLE_KHR           = 3219,
    EGL_DRM_DEVICE_FILE_EXT                            = 3233,
    EGL_DRM_CRTC_EXT                                   = 3234,
    EGL_DRM_PLANE_EXT                                  = 3235,
    EGL_DRM_CONNECTOR_EXT                              = 3236,
    EGL_OPENWF_DEVICE_ID_EXT                           = 3237,
    EGL_OPENWF_PIPELINE_ID_EXT                         = 3238,
    EGL_OPENWF_PORT_ID_EXT                             = 3239,
    EGL_LINUX_DMA_BUF_EXT                              = 3270,
    EGL_LINUX_DRM_FOURCC_EXT                           = 3271,
    EGL_DMA_BUF_PLANE0_FD_EXT                          = 3272,
    EGL_DMA_BUF_PLANE0_OFFSET_EXT                      = 3273,
    EGL_DMA_BUF_PLANE0_PITCH_EXT                       = 3274,
    EGL_DMA_BUF_PLANE1_FD_EXT                          = 3275,
    EGL_DMA_BUF_PLANE1_OFFSET_EXT                      = 3276,
    EGL_DMA_BUF_PLANE1_PITCH_EXT                       = 3277,
    EGL_DMA_BUF_PLANE2_FD_EXT                          = 3278,
    EGL_DMA_BUF_PLANE2_OFFSET_EXT                      = 3279,
    EGL_ITU_REC709_EXT                                 = 3280,
    EGL_ITU_REC2020_EXT                                = 3281,
    EGL_YUV_FULL_RANGE_EXT                             = 3282,
    EGL_YUV_NARROW_RANGE_EXT                           = 3283,
    EGL_YUV_CHROMA_SITING_0_EXT                        = 3284,
    EGL_YUV_CHROMA_SITING_0_5_EXT                      = 3285,
    EGL_DISCARD_SAMPLES_ARM                            = 3286,
    EGL_YUV_BUFFER_EXT                                 = 3300,
    EGL_YUV_ORDER_EXT                                  = 3301,
    EGL_YUV_ORDER_YUV_EXT                              = 3302,
    EGL_YUV_ORDER_YVU_EXT                              = 3303,
    EGL_YUV_ORDER_YUYV_EXT                             = 3304,
    EGL_YUV_ORDER_UYVY_EXT                             = 3305,
    EGL_YUV_ORDER_YVYU_EXT                             = 3306,
    EGL_YUV_ORDER_VYUY_EXT                             = 3307,
    EGL_YUV_ORDER_AYUV_EXT                             = 3308,
    EGL_YUV_NUMBER_OF_PLANES_EXT                       = 3311,
    EGL_YUV_SUBSAMPLE_EXT                              = 3312,
    EGL_YUV_SUBSAMPLE_4_2_0_EXT                        = 3313,
    EGL_YUV_SUBSAMPLE_4_2_2_EXT                        = 3314,
    EGL_YUV_SUBSAMPLE_4_4_4_EXT                        = 3315,
    EGL_YUV_DEPTH_RANGE_EXT                            = 3317,
    EGL_YUV_DEPTH_RANGE_LIMITED_EXT                    = 3318,
    EGL_YUV_DEPTH_RANGE_FULL_EXT                       = 3319,
    EGL_DISPLAY_SCALING                                = 10000,

};

// import enums to namespace


// __UNGROUPED__

static const EGLenum EGL_DONT_CARE = EGLenum::EGL_DONT_CARE;
static const EGLenum EGL_NO_FILE_DESCRIPTOR_KHR = EGLenum::EGL_NO_FILE_DESCRIPTOR_KHR;
static const EGLenum EGL_NO_NATIVE_FENCE_FD_ANDROID = EGLenum::EGL_NO_NATIVE_FENCE_FD_ANDROID;
static const EGLenum EGL_UNKNOWN = EGLenum::EGL_UNKNOWN;
static const EGLenum EGL_DEFAULT_DISPLAY = EGLenum::EGL_DEFAULT_DISPLAY;
static const EGLenum EGL_DEPTH_ENCODING_NONE_NV = EGLenum::EGL_DEPTH_ENCODING_NONE_NV;
static const EGLenum EGL_NO_CONTEXT = EGLenum::EGL_NO_CONTEXT;
static const EGLenum EGL_NO_DEVICE_EXT = EGLenum::EGL_NO_DEVICE_EXT;
static const EGLenum EGL_NO_DISPLAY = EGLenum::EGL_NO_DISPLAY;
static const EGLenum EGL_NO_IMAGE = EGLenum::EGL_NO_IMAGE;
static const EGLenum EGL_NO_IMAGE_KHR = EGLenum::EGL_NO_IMAGE_KHR;
static const EGLenum EGL_NO_OUTPUT_LAYER_EXT = EGLenum::EGL_NO_OUTPUT_LAYER_EXT;
static const EGLenum EGL_NO_OUTPUT_PORT_EXT = EGLenum::EGL_NO_OUTPUT_PORT_EXT;
static const EGLenum EGL_NO_STREAM_KHR = EGLenum::EGL_NO_STREAM_KHR;
static const EGLenum EGL_NO_SURFACE = EGLenum::EGL_NO_SURFACE;
static const EGLenum EGL_NO_SYNC = EGLenum::EGL_NO_SYNC;
static const EGLenum EGL_NO_SYNC_KHR = EGLenum::EGL_NO_SYNC_KHR;
static const EGLenum EGL_NO_SYNC_NV = EGLenum::EGL_NO_SYNC_NV;
static const EGLenum EGL_ALREADY_SIGNALED_NV = EGLenum::EGL_ALREADY_SIGNALED_NV;
static const EGLenum EGL_BITMAP_PIXEL_ALPHA_OFFSET_KHR = EGLenum::EGL_BITMAP_PIXEL_ALPHA_OFFSET_KHR;
static const EGLenum EGL_BITMAP_PIXEL_BLUE_OFFSET_KHR = EGLenum::EGL_BITMAP_PIXEL_BLUE_OFFSET_KHR;
static const EGLenum EGL_BITMAP_PIXEL_GREEN_OFFSET_KHR = EGLenum::EGL_BITMAP_PIXEL_GREEN_OFFSET_KHR;
static const EGLenum EGL_BITMAP_PIXEL_LUMINANCE_OFFSET_KHR = EGLenum::EGL_BITMAP_PIXEL_LUMINANCE_OFFSET_KHR;
static const EGLenum EGL_CONDITION_SATISFIED_NV = EGLenum::EGL_CONDITION_SATISFIED_NV;
static const EGLenum EGL_CONTEXT_FLAGS_KHR = EGLenum::EGL_CONTEXT_FLAGS_KHR;
static const EGLenum EGL_CONTEXT_MINOR_VERSION = EGLenum::EGL_CONTEXT_MINOR_VERSION;
static const EGLenum EGL_CONTEXT_MINOR_VERSION_KHR = EGLenum::EGL_CONTEXT_MINOR_VERSION_KHR;
static const EGLenum EGL_CONTEXT_OPENGL_PROFILE_MASK = EGLenum::EGL_CONTEXT_OPENGL_PROFILE_MASK;
static const EGLenum EGL_CONTEXT_OPENGL_PROFILE_MASK_KHR = EGLenum::EGL_CONTEXT_OPENGL_PROFILE_MASK_KHR;
static const EGLenum EGL_CONTEXT_OPENGL_ROBUST_ACCESS_EXT = EGLenum::EGL_CONTEXT_OPENGL_ROBUST_ACCESS_EXT;
static const EGLenum EGL_GL_TEXTURE_LEVEL = EGLenum::EGL_GL_TEXTURE_LEVEL;
static const EGLenum EGL_GL_TEXTURE_LEVEL_KHR = EGLenum::EGL_GL_TEXTURE_LEVEL_KHR;
static const EGLenum EGL_GL_TEXTURE_ZOFFSET = EGLenum::EGL_GL_TEXTURE_ZOFFSET;
static const EGLenum EGL_GL_TEXTURE_ZOFFSET_KHR = EGLenum::EGL_GL_TEXTURE_ZOFFSET_KHR;
static const EGLenum EGL_LOWER_LEFT_KHR = EGLenum::EGL_LOWER_LEFT_KHR;
static const EGLenum EGL_POST_SUB_BUFFER_SUPPORTED_NV = EGLenum::EGL_POST_SUB_BUFFER_SUPPORTED_NV;
static const EGLenum EGL_SYNC_CL_EVENT = EGLenum::EGL_SYNC_CL_EVENT;
static const EGLenum EGL_SYNC_CL_EVENT_COMPLETE = EGLenum::EGL_SYNC_CL_EVENT_COMPLETE;
static const EGLenum EGL_SYNC_CL_EVENT_COMPLETE_KHR = EGLenum::EGL_SYNC_CL_EVENT_COMPLETE_KHR;
static const EGLenum EGL_SYNC_CL_EVENT_KHR = EGLenum::EGL_SYNC_CL_EVENT_KHR;
static const EGLenum EGL_SYNC_CONDITION_NV = EGLenum::EGL_SYNC_CONDITION_NV;
static const EGLenum EGL_SYNC_FENCE_NV = EGLenum::EGL_SYNC_FENCE_NV;
static const EGLenum EGL_SYNC_REUSABLE_KHR = EGLenum::EGL_SYNC_REUSABLE_KHR;
static const EGLenum EGL_SYNC_TYPE_NV = EGLenum::EGL_SYNC_TYPE_NV;
static const EGLenum EGL_TIMEOUT_EXPIRED_NV = EGLenum::EGL_TIMEOUT_EXPIRED_NV;
static const EGLenum EGL_UPPER_LEFT_KHR = EGLenum::EGL_UPPER_LEFT_KHR;
static const EGLenum EGL_VG_PARENT_IMAGE_KHR = EGLenum::EGL_VG_PARENT_IMAGE_KHR;
static const EGLenum EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY = EGLenum::EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY;
static const EGLenum EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_KHR = EGLenum::EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_KHR;
static const EGLenum EGL_LOSE_CONTEXT_ON_RESET = EGLenum::EGL_LOSE_CONTEXT_ON_RESET;
static const EGLenum EGL_LOSE_CONTEXT_ON_RESET_EXT = EGLenum::EGL_LOSE_CONTEXT_ON_RESET_EXT;
static const EGLenum EGL_LOSE_CONTEXT_ON_RESET_KHR = EGLenum::EGL_LOSE_CONTEXT_ON_RESET_KHR;
static const EGLenum EGL_NO_RESET_NOTIFICATION = EGLenum::EGL_NO_RESET_NOTIFICATION;
static const EGLenum EGL_NO_RESET_NOTIFICATION_EXT = EGLenum::EGL_NO_RESET_NOTIFICATION_EXT;
static const EGLenum EGL_NO_RESET_NOTIFICATION_KHR = EGLenum::EGL_NO_RESET_NOTIFICATION_KHR;
static const EGLenum EGL_STREAM_FIFO_LENGTH_KHR = EGLenum::EGL_STREAM_FIFO_LENGTH_KHR;
static const EGLenum EGL_STREAM_TIME_CONSUMER_KHR = EGLenum::EGL_STREAM_TIME_CONSUMER_KHR;
static const EGLenum EGL_STREAM_TIME_NOW_KHR = EGLenum::EGL_STREAM_TIME_NOW_KHR;
static const EGLenum EGL_STREAM_TIME_PRODUCER_KHR = EGLenum::EGL_STREAM_TIME_PRODUCER_KHR;
static const EGLenum EGL_BAD_NATIVE_PIXMAP = EGLenum::EGL_BAD_NATIVE_PIXMAP;
static const EGLenum EGL_BAD_NATIVE_WINDOW = EGLenum::EGL_BAD_NATIVE_WINDOW;
static const EGLenum EGL_BAD_PARAMETER = EGLenum::EGL_BAD_PARAMETER;
static const EGLenum EGL_BAD_SURFACE = EGLenum::EGL_BAD_SURFACE;
static const EGLenum EGL_CONTEXT_LOST = EGLenum::EGL_CONTEXT_LOST;
static const EGLenum EGL_COVERAGE_BUFFERS_NV = EGLenum::EGL_COVERAGE_BUFFERS_NV;
static const EGLenum EGL_FORMAT_RGB_565_EXACT_KHR = EGLenum::EGL_FORMAT_RGB_565_EXACT_KHR;
static const EGLenum EGL_NATIVE_PIXMAP_KHR = EGLenum::EGL_NATIVE_PIXMAP_KHR;
static const EGLenum EGL_OPENGL_ES_API = EGLenum::EGL_OPENGL_ES_API;
static const EGLenum EGL_SYNC_PRIOR_COMMANDS_COMPLETE = EGLenum::EGL_SYNC_PRIOR_COMMANDS_COMPLETE;
static const EGLenum EGL_SYNC_PRIOR_COMMANDS_COMPLETE_KHR = EGLenum::EGL_SYNC_PRIOR_COMMANDS_COMPLETE_KHR;
static const EGLenum EGL_COVERAGE_SAMPLES_NV = EGLenum::EGL_COVERAGE_SAMPLES_NV;
static const EGLenum EGL_FORMAT_RGB_565_KHR = EGLenum::EGL_FORMAT_RGB_565_KHR;
static const EGLenum EGL_GL_TEXTURE_2D = EGLenum::EGL_GL_TEXTURE_2D;
static const EGLenum EGL_GL_TEXTURE_2D_KHR = EGLenum::EGL_GL_TEXTURE_2D_KHR;
static const EGLenum EGL_OPENVG_API = EGLenum::EGL_OPENVG_API;
static const EGLenum EGL_SYNC_STATUS = EGLenum::EGL_SYNC_STATUS;
static const EGLenum EGL_SYNC_STATUS_KHR = EGLenum::EGL_SYNC_STATUS_KHR;
static const EGLenum EGL_DEPTH_ENCODING_NV = EGLenum::EGL_DEPTH_ENCODING_NV;
static const EGLenum EGL_FORMAT_RGBA_8888_EXACT_KHR = EGLenum::EGL_FORMAT_RGBA_8888_EXACT_KHR;
static const EGLenum EGL_GL_TEXTURE_3D = EGLenum::EGL_GL_TEXTURE_3D;
static const EGLenum EGL_GL_TEXTURE_3D_KHR = EGLenum::EGL_GL_TEXTURE_3D_KHR;
static const EGLenum EGL_IMAGE_PRESERVED = EGLenum::EGL_IMAGE_PRESERVED;
static const EGLenum EGL_IMAGE_PRESERVED_KHR = EGLenum::EGL_IMAGE_PRESERVED_KHR;
static const EGLenum EGL_MAX_PBUFFER_HEIGHT = EGLenum::EGL_MAX_PBUFFER_HEIGHT;
static const EGLenum EGL_MAX_PBUFFER_PIXELS = EGLenum::EGL_MAX_PBUFFER_PIXELS;
static const EGLenum EGL_MAX_PBUFFER_WIDTH = EGLenum::EGL_MAX_PBUFFER_WIDTH;
static const EGLenum EGL_NATIVE_RENDERABLE = EGLenum::EGL_NATIVE_RENDERABLE;
static const EGLenum EGL_NATIVE_VISUAL_ID = EGLenum::EGL_NATIVE_VISUAL_ID;
static const EGLenum EGL_NATIVE_VISUAL_TYPE = EGLenum::EGL_NATIVE_VISUAL_TYPE;
static const EGLenum EGL_OPENGL_API = EGLenum::EGL_OPENGL_API;
static const EGLenum EGL_SIGNALED = EGLenum::EGL_SIGNALED;
static const EGLenum EGL_SIGNALED_KHR = EGLenum::EGL_SIGNALED_KHR;
static const EGLenum EGL_ALPHA_MASK_SIZE = EGLenum::EGL_ALPHA_MASK_SIZE;
static const EGLenum EGL_BIND_TO_TEXTURE_RGBA = EGLenum::EGL_BIND_TO_TEXTURE_RGBA;
static const EGLenum EGL_COLOR_BUFFER_TYPE = EGLenum::EGL_COLOR_BUFFER_TYPE;
static const EGLenum EGL_DEPTH_ENCODING_NONLINEAR_NV = EGLenum::EGL_DEPTH_ENCODING_NONLINEAR_NV;
static const EGLenum EGL_FORMAT_RGBA_8888_KHR = EGLenum::EGL_FORMAT_RGBA_8888_KHR;
static const EGLenum EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_X = EGLenum::EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_X;
static const EGLenum EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_X_KHR = EGLenum::EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_X_KHR;
static const EGLenum EGL_LUMINANCE_SIZE = EGLenum::EGL_LUMINANCE_SIZE;
static const EGLenum EGL_MAX_SWAP_INTERVAL = EGLenum::EGL_MAX_SWAP_INTERVAL;
static const EGLenum EGL_MIN_SWAP_INTERVAL = EGLenum::EGL_MIN_SWAP_INTERVAL;
static const EGLenum EGL_UNSIGNALED = EGLenum::EGL_UNSIGNALED;
static const EGLenum EGL_UNSIGNALED_KHR = EGLenum::EGL_UNSIGNALED_KHR;
static const EGLenum EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_X = EGLenum::EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_X;
static const EGLenum EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_X_KHR = EGLenum::EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_X_KHR;
static const EGLenum EGL_MAP_PRESERVE_PIXELS_KHR = EGLenum::EGL_MAP_PRESERVE_PIXELS_KHR;
static const EGLenum EGL_CORE_NATIVE_ENGINE = EGLenum::EGL_CORE_NATIVE_ENGINE;
static const EGLenum EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Y = EGLenum::EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Y;
static const EGLenum EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Y_KHR = EGLenum::EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Y_KHR;
static const EGLenum EGL_LOCK_USAGE_HINT_KHR = EGLenum::EGL_LOCK_USAGE_HINT_KHR;
static const EGLenum EGL_NO_TEXTURE = EGLenum::EGL_NO_TEXTURE;
static const EGLenum EGL_READ = EGLenum::EGL_READ;
static const EGLenum EGL_TEXTURE_2D = EGLenum::EGL_TEXTURE_2D;
static const EGLenum EGL_TEXTURE_RGB = EGLenum::EGL_TEXTURE_RGB;
static const EGLenum EGL_TEXTURE_RGBA = EGLenum::EGL_TEXTURE_RGBA;
static const EGLenum EGL_TIMEOUT_EXPIRED = EGLenum::EGL_TIMEOUT_EXPIRED;
static const EGLenum EGL_TIMEOUT_EXPIRED_KHR = EGLenum::EGL_TIMEOUT_EXPIRED_KHR;
static const EGLenum EGL_BITMAP_POINTER_KHR = EGLenum::EGL_BITMAP_POINTER_KHR;
static const EGLenum EGL_CONDITION_SATISFIED = EGLenum::EGL_CONDITION_SATISFIED;
static const EGLenum EGL_CONDITION_SATISFIED_KHR = EGLenum::EGL_CONDITION_SATISFIED_KHR;
static const EGLenum EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y = EGLenum::EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y;
static const EGLenum EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y_KHR = EGLenum::EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y_KHR;
static const EGLenum EGL_SYNC_PRIOR_COMMANDS_COMPLETE_NV = EGLenum::EGL_SYNC_PRIOR_COMMANDS_COMPLETE_NV;
static const EGLenum EGL_BITMAP_PITCH_KHR = EGLenum::EGL_BITMAP_PITCH_KHR;
static const EGLenum EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Z = EGLenum::EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Z;
static const EGLenum EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Z_KHR = EGLenum::EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Z_KHR;
static const EGLenum EGL_SYNC_STATUS_NV = EGLenum::EGL_SYNC_STATUS_NV;
static const EGLenum EGL_SYNC_TYPE = EGLenum::EGL_SYNC_TYPE;
static const EGLenum EGL_SYNC_TYPE_KHR = EGLenum::EGL_SYNC_TYPE_KHR;
static const EGLenum EGL_Y_INVERTED_NOK = EGLenum::EGL_Y_INVERTED_NOK;
static const EGLenum EGL_ALPHA_FORMAT_NONPRE = EGLenum::EGL_ALPHA_FORMAT_NONPRE;
static const EGLenum EGL_ALPHA_FORMAT_PRE = EGLenum::EGL_ALPHA_FORMAT_PRE;
static const EGLenum EGL_BITMAP_ORIGIN_KHR = EGLenum::EGL_BITMAP_ORIGIN_KHR;
static const EGLenum EGL_CLIENT_APIS = EGLenum::EGL_CLIENT_APIS;
static const EGLenum EGL_COLORSPACE_LINEAR = EGLenum::EGL_COLORSPACE_LINEAR;
static const EGLenum EGL_GL_COLORSPACE_LINEAR = EGLenum::EGL_GL_COLORSPACE_LINEAR;
static const EGLenum EGL_GL_COLORSPACE_LINEAR_KHR = EGLenum::EGL_GL_COLORSPACE_LINEAR_KHR;
static const EGLenum EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z = EGLenum::EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z;
static const EGLenum EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z_KHR = EGLenum::EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z_KHR;
static const EGLenum EGL_LUMINANCE_BUFFER = EGLenum::EGL_LUMINANCE_BUFFER;
static const EGLenum EGL_RGB_BUFFER = EGLenum::EGL_RGB_BUFFER;
static const EGLenum EGL_SIGNALED_NV = EGLenum::EGL_SIGNALED_NV;
static const EGLenum EGL_SYNC_CONDITION = EGLenum::EGL_SYNC_CONDITION;
static const EGLenum EGL_SYNC_CONDITION_KHR = EGLenum::EGL_SYNC_CONDITION_KHR;
static const EGLenum EGL_VG_ALPHA_FORMAT_NONPRE = EGLenum::EGL_VG_ALPHA_FORMAT_NONPRE;
static const EGLenum EGL_VG_ALPHA_FORMAT_PRE = EGLenum::EGL_VG_ALPHA_FORMAT_PRE;
static const EGLenum EGL_VG_COLORSPACE_LINEAR = EGLenum::EGL_VG_COLORSPACE_LINEAR;
static const EGLenum EGL_BITMAP_PIXEL_RED_OFFSET_KHR = EGLenum::EGL_BITMAP_PIXEL_RED_OFFSET_KHR;
static const EGLenum EGL_CL_EVENT_HANDLE = EGLenum::EGL_CL_EVENT_HANDLE;
static const EGLenum EGL_CL_EVENT_HANDLE_KHR = EGLenum::EGL_CL_EVENT_HANDLE_KHR;
static const EGLenum EGL_GL_COLORSPACE = EGLenum::EGL_GL_COLORSPACE;
static const EGLenum EGL_GL_COLORSPACE_KHR = EGLenum::EGL_GL_COLORSPACE_KHR;
static const EGLenum EGL_GL_RENDERBUFFER = EGLenum::EGL_GL_RENDERBUFFER;
static const EGLenum EGL_GL_RENDERBUFFER_KHR = EGLenum::EGL_GL_RENDERBUFFER_KHR;
static const EGLenum EGL_MULTISAMPLE_RESOLVE_BOX = EGLenum::EGL_MULTISAMPLE_RESOLVE_BOX;
static const EGLenum EGL_MULTISAMPLE_RESOLVE_DEFAULT = EGLenum::EGL_MULTISAMPLE_RESOLVE_DEFAULT;
static const EGLenum EGL_SYNC_FENCE = EGLenum::EGL_SYNC_FENCE;
static const EGLenum EGL_SYNC_FENCE_KHR = EGLenum::EGL_SYNC_FENCE_KHR;
static const EGLenum EGL_UNSIGNALED_NV = EGLenum::EGL_UNSIGNALED_NV;
static const EGLenum EGL_CONTEXT_OPENGL_DEBUG = EGLenum::EGL_CONTEXT_OPENGL_DEBUG;
static const EGLenum EGL_DRM_BUFFER_FORMAT_MESA = EGLenum::EGL_DRM_BUFFER_FORMAT_MESA;
static const EGLenum EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE = EGLenum::EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE;
static const EGLenum EGL_DRM_BUFFER_USE_MESA = EGLenum::EGL_DRM_BUFFER_USE_MESA;
static const EGLenum EGL_CONTEXT_OPENGL_ROBUST_ACCESS = EGLenum::EGL_CONTEXT_OPENGL_ROBUST_ACCESS;
static const EGLenum EGL_DRM_BUFFER_FORMAT_ARGB32_MESA = EGLenum::EGL_DRM_BUFFER_FORMAT_ARGB32_MESA;
static const EGLenum EGL_BUFFER_AGE_EXT = EGLenum::EGL_BUFFER_AGE_EXT;
static const EGLenum EGL_BUFFER_AGE_KHR = EGLenum::EGL_BUFFER_AGE_KHR;
static const EGLenum EGL_CONTEXT_OPENGL_NO_ERROR_KHR = EGLenum::EGL_CONTEXT_OPENGL_NO_ERROR_KHR;
static const EGLenum EGL_DRM_BUFFER_MESA = EGLenum::EGL_DRM_BUFFER_MESA;
static const EGLenum EGL_PLATFORM_DEVICE_EXT = EGLenum::EGL_PLATFORM_DEVICE_EXT;
static const EGLenum EGL_DRM_BUFFER_STRIDE_MESA = EGLenum::EGL_DRM_BUFFER_STRIDE_MESA;
static const EGLenum EGL_PLATFORM_X11_EXT = EGLenum::EGL_PLATFORM_X11_EXT;
static const EGLenum EGL_PLATFORM_X11_KHR = EGLenum::EGL_PLATFORM_X11_KHR;
static const EGLenum EGL_PLATFORM_X11_SCREEN_EXT = EGLenum::EGL_PLATFORM_X11_SCREEN_EXT;
static const EGLenum EGL_PLATFORM_X11_SCREEN_KHR = EGLenum::EGL_PLATFORM_X11_SCREEN_KHR;
static const EGLenum EGL_PLATFORM_GBM_KHR = EGLenum::EGL_PLATFORM_GBM_KHR;
static const EGLenum EGL_PLATFORM_GBM_MESA = EGLenum::EGL_PLATFORM_GBM_MESA;
static const EGLenum EGL_PLATFORM_WAYLAND_EXT = EGLenum::EGL_PLATFORM_WAYLAND_EXT;
static const EGLenum EGL_PLATFORM_WAYLAND_KHR = EGLenum::EGL_PLATFORM_WAYLAND_KHR;
static const EGLenum EGL_NATIVE_BUFFER_TIZEN = EGLenum::EGL_NATIVE_BUFFER_TIZEN;
static const EGLenum EGL_PROTECTED_CONTENT_EXT = EGLenum::EGL_PROTECTED_CONTENT_EXT;
static const EGLenum EGL_BAD_STATE_KHR = EGLenum::EGL_BAD_STATE_KHR;
static const EGLenum EGL_BAD_STREAM_KHR = EGLenum::EGL_BAD_STREAM_KHR;
static const EGLenum EGL_CONSUMER_ACQUIRE_TIMEOUT_USEC_KHR = EGLenum::EGL_CONSUMER_ACQUIRE_TIMEOUT_USEC_KHR;
static const EGLenum EGL_NATIVE_SURFACE_TIZEN = EGLenum::EGL_NATIVE_SURFACE_TIZEN;
static const EGLenum EGL_STREAM_STATE_DISCONNECTED_KHR = EGLenum::EGL_STREAM_STATE_DISCONNECTED_KHR;
static const EGLenum EGL_SYNC_NEW_FRAME_NV = EGLenum::EGL_SYNC_NEW_FRAME_NV;
static const EGLenum EGL_BAD_DEVICE_EXT = EGLenum::EGL_BAD_DEVICE_EXT;
static const EGLenum EGL_BAD_OUTPUT_LAYER_EXT = EGLenum::EGL_BAD_OUTPUT_LAYER_EXT;
static const EGLenum EGL_BAD_OUTPUT_PORT_EXT = EGLenum::EGL_BAD_OUTPUT_PORT_EXT;
static const EGLenum EGL_DEVICE_EXT = EGLenum::EGL_DEVICE_EXT;
static const EGLenum EGL_SWAP_INTERVAL_EXT = EGLenum::EGL_SWAP_INTERVAL_EXT;
static const EGLenum EGL_CUDA_DEVICE_NV = EGLenum::EGL_CUDA_DEVICE_NV;
static const EGLenum EGL_CUDA_EVENT_HANDLE_NV = EGLenum::EGL_CUDA_EVENT_HANDLE_NV;
static const EGLenum EGL_SYNC_CUDA_EVENT_COMPLETE_NV = EGLenum::EGL_SYNC_CUDA_EVENT_COMPLETE_NV;
static const EGLenum EGL_SYNC_CUDA_EVENT_NV = EGLenum::EGL_SYNC_CUDA_EVENT_NV;
static const EGLenum EGL_DMA_BUF_PLANE2_PITCH_EXT = EGLenum::EGL_DMA_BUF_PLANE2_PITCH_EXT;
static const EGLenum EGL_ITU_REC601_EXT = EGLenum::EGL_ITU_REC601_EXT;
static const EGLenum EGL_SAMPLE_RANGE_HINT_EXT = EGLenum::EGL_SAMPLE_RANGE_HINT_EXT;
static const EGLenum EGL_YUV_CHROMA_HORIZONTAL_SITING_HINT_EXT = EGLenum::EGL_YUV_CHROMA_HORIZONTAL_SITING_HINT_EXT;
static const EGLenum EGL_YUV_CHROMA_VERTICAL_SITING_HINT_EXT = EGLenum::EGL_YUV_CHROMA_VERTICAL_SITING_HINT_EXT;
static const EGLenum EGL_YUV_COLOR_SPACE_HINT_EXT = EGLenum::EGL_YUV_COLOR_SPACE_HINT_EXT;
static const EGLenum EGL_D3D9_DEVICE_ANGLE = EGLenum::EGL_D3D9_DEVICE_ANGLE;
static const EGLenum EGL_YUV_CSC_STANDARD_2020_EXT = EGLenum::EGL_YUV_CSC_STANDARD_2020_EXT;
static const EGLenum EGL_YUV_CSC_STANDARD_601_EXT = EGLenum::EGL_YUV_CSC_STANDARD_601_EXT;
static const EGLenum EGL_YUV_CSC_STANDARD_709_EXT = EGLenum::EGL_YUV_CSC_STANDARD_709_EXT;
static const EGLenum EGL_YUV_CSC_STANDARD_EXT = EGLenum::EGL_YUV_CSC_STANDARD_EXT;
static const EGLenum EGL_D3D11_DEVICE_ANGLE = EGLenum::EGL_D3D11_DEVICE_ANGLE;
static const EGLenum EGL_YUV_PLANE_BPP_0_EXT = EGLenum::EGL_YUV_PLANE_BPP_0_EXT;
static const EGLenum EGL_YUV_PLANE_BPP_10_EXT = EGLenum::EGL_YUV_PLANE_BPP_10_EXT;
static const EGLenum EGL_YUV_PLANE_BPP_8_EXT = EGLenum::EGL_YUV_PLANE_BPP_8_EXT;
static const EGLenum EGL_YUV_PLANE_BPP_EXT = EGLenum::EGL_YUV_PLANE_BPP_EXT;
static const EGLenum EGL_COLOR_FORMAT_HI = EGLenum::EGL_COLOR_FORMAT_HI;
static const EGLenum EGL_COLOR_RGB_HI = EGLenum::EGL_COLOR_RGB_HI;
static const EGLenum EGL_COLOR_RGBA_HI = EGLenum::EGL_COLOR_RGBA_HI;
static const EGLenum EGL_COLOR_ARGB_HI = EGLenum::EGL_COLOR_ARGB_HI;
static const EGLenum EGL_CLIENT_PIXMAP_POINTER_HI = EGLenum::EGL_CLIENT_PIXMAP_POINTER_HI;
static const EGLenum EGL_SUCCESS = EGLenum::EGL_SUCCESS;
static const EGLenum EGL_NOT_INITIALIZED = EGLenum::EGL_NOT_INITIALIZED;
static const EGLenum EGL_BAD_ACCESS = EGLenum::EGL_BAD_ACCESS;
static const EGLenum EGL_BAD_ALLOC = EGLenum::EGL_BAD_ALLOC;
static const EGLenum EGL_BAD_ATTRIBUTE = EGLenum::EGL_BAD_ATTRIBUTE;
static const EGLenum EGL_BAD_CONFIG = EGLenum::EGL_BAD_CONFIG;
static const EGLenum EGL_BAD_CONTEXT = EGLenum::EGL_BAD_CONTEXT;
static const EGLenum EGL_BAD_CURRENT_SURFACE = EGLenum::EGL_BAD_CURRENT_SURFACE;
static const EGLenum EGL_BAD_DISPLAY = EGLenum::EGL_BAD_DISPLAY;
static const EGLenum EGL_BAD_MATCH = EGLenum::EGL_BAD_MATCH;
static const EGLenum EGL_BUFFER_SIZE = EGLenum::EGL_BUFFER_SIZE;
static const EGLenum EGL_ALPHA_SIZE = EGLenum::EGL_ALPHA_SIZE;
static const EGLenum EGL_BLUE_SIZE = EGLenum::EGL_BLUE_SIZE;
static const EGLenum EGL_GREEN_SIZE = EGLenum::EGL_GREEN_SIZE;
static const EGLenum EGL_RED_SIZE = EGLenum::EGL_RED_SIZE;
static const EGLenum EGL_DEPTH_SIZE = EGLenum::EGL_DEPTH_SIZE;
static const EGLenum EGL_STENCIL_SIZE = EGLenum::EGL_STENCIL_SIZE;
static const EGLenum EGL_CONFIG_CAVEAT = EGLenum::EGL_CONFIG_CAVEAT;
static const EGLenum EGL_CONFIG_ID = EGLenum::EGL_CONFIG_ID;
static const EGLenum EGL_LEVEL = EGLenum::EGL_LEVEL;
static const EGLenum EGL_SAMPLES = EGLenum::EGL_SAMPLES;
static const EGLenum EGL_SAMPLE_BUFFERS = EGLenum::EGL_SAMPLE_BUFFERS;
static const EGLenum EGL_SURFACE_TYPE = EGLenum::EGL_SURFACE_TYPE;
static const EGLenum EGL_TRANSPARENT_TYPE = EGLenum::EGL_TRANSPARENT_TYPE;
static const EGLenum EGL_TRANSPARENT_BLUE_VALUE = EGLenum::EGL_TRANSPARENT_BLUE_VALUE;
static const EGLenum EGL_TRANSPARENT_GREEN_VALUE = EGLenum::EGL_TRANSPARENT_GREEN_VALUE;
static const EGLenum EGL_TRANSPARENT_RED_VALUE = EGLenum::EGL_TRANSPARENT_RED_VALUE;
static const EGLenum EGL_NONE = EGLenum::EGL_NONE;
static const EGLenum EGL_BIND_TO_TEXTURE_RGB = EGLenum::EGL_BIND_TO_TEXTURE_RGB;
static const EGLenum EGL_RENDERABLE_TYPE = EGLenum::EGL_RENDERABLE_TYPE;
static const EGLenum EGL_MATCH_NATIVE_PIXMAP = EGLenum::EGL_MATCH_NATIVE_PIXMAP;
static const EGLenum EGL_CONFORMANT = EGLenum::EGL_CONFORMANT;
static const EGLenum EGL_CONFORMANT_KHR = EGLenum::EGL_CONFORMANT_KHR;
static const EGLenum EGL_MATCH_FORMAT_KHR = EGLenum::EGL_MATCH_FORMAT_KHR;
static const EGLenum EGL_SLOW_CONFIG = EGLenum::EGL_SLOW_CONFIG;
static const EGLenum EGL_NON_CONFORMANT_CONFIG = EGLenum::EGL_NON_CONFORMANT_CONFIG;
static const EGLenum EGL_TRANSPARENT_RGB = EGLenum::EGL_TRANSPARENT_RGB;
static const EGLenum EGL_VENDOR = EGLenum::EGL_VENDOR;
static const EGLenum EGL_VERSION = EGLenum::EGL_VERSION;
static const EGLenum EGL_EXTENSIONS = EGLenum::EGL_EXTENSIONS;
static const EGLenum EGL_HEIGHT = EGLenum::EGL_HEIGHT;
static const EGLenum EGL_WIDTH = EGLenum::EGL_WIDTH;
static const EGLenum EGL_LARGEST_PBUFFER = EGLenum::EGL_LARGEST_PBUFFER;
static const EGLenum EGL_DRAW = EGLenum::EGL_DRAW;
static const EGLenum EGL_TEXTURE_FORMAT = EGLenum::EGL_TEXTURE_FORMAT;
static const EGLenum EGL_TEXTURE_TARGET = EGLenum::EGL_TEXTURE_TARGET;
static const EGLenum EGL_MIPMAP_TEXTURE = EGLenum::EGL_MIPMAP_TEXTURE;
static const EGLenum EGL_MIPMAP_LEVEL = EGLenum::EGL_MIPMAP_LEVEL;
static const EGLenum EGL_BACK_BUFFER = EGLenum::EGL_BACK_BUFFER;
static const EGLenum EGL_SINGLE_BUFFER = EGLenum::EGL_SINGLE_BUFFER;
static const EGLenum EGL_RENDER_BUFFER = EGLenum::EGL_RENDER_BUFFER;
static const EGLenum EGL_COLORSPACE = EGLenum::EGL_COLORSPACE;
static const EGLenum EGL_VG_COLORSPACE = EGLenum::EGL_VG_COLORSPACE;
static const EGLenum EGL_ALPHA_FORMAT = EGLenum::EGL_ALPHA_FORMAT;
static const EGLenum EGL_VG_ALPHA_FORMAT = EGLenum::EGL_VG_ALPHA_FORMAT;
static const EGLenum EGL_COLORSPACE_sRGB = EGLenum::EGL_COLORSPACE_sRGB;
static const EGLenum EGL_GL_COLORSPACE_SRGB = EGLenum::EGL_GL_COLORSPACE_SRGB;
static const EGLenum EGL_GL_COLORSPACE_SRGB_KHR = EGLenum::EGL_GL_COLORSPACE_SRGB_KHR;
static const EGLenum EGL_VG_COLORSPACE_sRGB = EGLenum::EGL_VG_COLORSPACE_sRGB;
static const EGLenum EGL_HORIZONTAL_RESOLUTION = EGLenum::EGL_HORIZONTAL_RESOLUTION;
static const EGLenum EGL_VERTICAL_RESOLUTION = EGLenum::EGL_VERTICAL_RESOLUTION;
static const EGLenum EGL_PIXEL_ASPECT_RATIO = EGLenum::EGL_PIXEL_ASPECT_RATIO;
static const EGLenum EGL_SWAP_BEHAVIOR = EGLenum::EGL_SWAP_BEHAVIOR;
static const EGLenum EGL_BUFFER_PRESERVED = EGLenum::EGL_BUFFER_PRESERVED;
static const EGLenum EGL_BUFFER_DESTROYED = EGLenum::EGL_BUFFER_DESTROYED;
static const EGLenum EGL_OPENVG_IMAGE = EGLenum::EGL_OPENVG_IMAGE;
static const EGLenum EGL_CONTEXT_CLIENT_TYPE = EGLenum::EGL_CONTEXT_CLIENT_TYPE;
static const EGLenum EGL_CONTEXT_CLIENT_VERSION = EGLenum::EGL_CONTEXT_CLIENT_VERSION;
static const EGLenum EGL_CONTEXT_MAJOR_VERSION = EGLenum::EGL_CONTEXT_MAJOR_VERSION;
static const EGLenum EGL_CONTEXT_MAJOR_VERSION_KHR = EGLenum::EGL_CONTEXT_MAJOR_VERSION_KHR;
static const EGLenum EGL_MULTISAMPLE_RESOLVE = EGLenum::EGL_MULTISAMPLE_RESOLVE;
static const EGLenum EGL_CONTEXT_PRIORITY_LEVEL_IMG = EGLenum::EGL_CONTEXT_PRIORITY_LEVEL_IMG;
static const EGLenum EGL_CONTEXT_PRIORITY_HIGH_IMG = EGLenum::EGL_CONTEXT_PRIORITY_HIGH_IMG;
static const EGLenum EGL_CONTEXT_PRIORITY_MEDIUM_IMG = EGLenum::EGL_CONTEXT_PRIORITY_MEDIUM_IMG;
static const EGLenum EGL_CONTEXT_PRIORITY_LOW_IMG = EGLenum::EGL_CONTEXT_PRIORITY_LOW_IMG;
static const EGLenum EGL_BITMAP_PIXEL_SIZE_KHR = EGLenum::EGL_BITMAP_PIXEL_SIZE_KHR;
static const EGLenum EGL_COVERAGE_SAMPLE_RESOLVE_NV = EGLenum::EGL_COVERAGE_SAMPLE_RESOLVE_NV;
static const EGLenum EGL_COVERAGE_SAMPLE_RESOLVE_DEFAULT_NV = EGLenum::EGL_COVERAGE_SAMPLE_RESOLVE_DEFAULT_NV;
static const EGLenum EGL_COVERAGE_SAMPLE_RESOLVE_NONE_NV = EGLenum::EGL_COVERAGE_SAMPLE_RESOLVE_NONE_NV;
static const EGLenum EGL_MULTIVIEW_VIEW_COUNT_EXT = EGLenum::EGL_MULTIVIEW_VIEW_COUNT_EXT;
static const EGLenum EGL_AUTO_STEREO_NV = EGLenum::EGL_AUTO_STEREO_NV;
static const EGLenum EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_EXT = EGLenum::EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_EXT;
static const EGLenum EGL_NATIVE_BUFFER_ANDROID = EGLenum::EGL_NATIVE_BUFFER_ANDROID;
static const EGLenum EGL_PLATFORM_ANDROID_KHR = EGLenum::EGL_PLATFORM_ANDROID_KHR;
static const EGLenum EGL_RECORDABLE_ANDROID = EGLenum::EGL_RECORDABLE_ANDROID;
static const EGLenum EGL_SYNC_NATIVE_FENCE_ANDROID = EGLenum::EGL_SYNC_NATIVE_FENCE_ANDROID;
static const EGLenum EGL_SYNC_NATIVE_FENCE_FD_ANDROID = EGLenum::EGL_SYNC_NATIVE_FENCE_FD_ANDROID;
static const EGLenum EGL_SYNC_NATIVE_FENCE_SIGNALED_ANDROID = EGLenum::EGL_SYNC_NATIVE_FENCE_SIGNALED_ANDROID;
static const EGLenum EGL_FRAMEBUFFER_TARGET_ANDROID = EGLenum::EGL_FRAMEBUFFER_TARGET_ANDROID;
static const EGLenum EGL_D3D_TEXTURE_2D_SHARE_HANDLE_ANGLE = EGLenum::EGL_D3D_TEXTURE_2D_SHARE_HANDLE_ANGLE;
static const EGLenum EGL_FIXED_SIZE_ANGLE = EGLenum::EGL_FIXED_SIZE_ANGLE;
static const EGLenum EGL_CONSUMER_LATENCY_USEC_KHR = EGLenum::EGL_CONSUMER_LATENCY_USEC_KHR;
static const EGLenum EGL_PRODUCER_FRAME_KHR = EGLenum::EGL_PRODUCER_FRAME_KHR;
static const EGLenum EGL_CONSUMER_FRAME_KHR = EGLenum::EGL_CONSUMER_FRAME_KHR;
static const EGLenum EGL_STREAM_STATE_KHR = EGLenum::EGL_STREAM_STATE_KHR;
static const EGLenum EGL_STREAM_STATE_CREATED_KHR = EGLenum::EGL_STREAM_STATE_CREATED_KHR;
static const EGLenum EGL_STREAM_STATE_CONNECTING_KHR = EGLenum::EGL_STREAM_STATE_CONNECTING_KHR;
static const EGLenum EGL_STREAM_STATE_EMPTY_KHR = EGLenum::EGL_STREAM_STATE_EMPTY_KHR;
static const EGLenum EGL_STREAM_STATE_NEW_FRAME_AVAILABLE_KHR = EGLenum::EGL_STREAM_STATE_NEW_FRAME_AVAILABLE_KHR;
static const EGLenum EGL_STREAM_STATE_OLD_FRAME_AVAILABLE_KHR = EGLenum::EGL_STREAM_STATE_OLD_FRAME_AVAILABLE_KHR;
static const EGLenum EGL_DRM_DEVICE_FILE_EXT = EGLenum::EGL_DRM_DEVICE_FILE_EXT;
static const EGLenum EGL_DRM_CRTC_EXT = EGLenum::EGL_DRM_CRTC_EXT;
static const EGLenum EGL_DRM_PLANE_EXT = EGLenum::EGL_DRM_PLANE_EXT;
static const EGLenum EGL_DRM_CONNECTOR_EXT = EGLenum::EGL_DRM_CONNECTOR_EXT;
static const EGLenum EGL_OPENWF_DEVICE_ID_EXT = EGLenum::EGL_OPENWF_DEVICE_ID_EXT;
static const EGLenum EGL_OPENWF_PIPELINE_ID_EXT = EGLenum::EGL_OPENWF_PIPELINE_ID_EXT;
static const EGLenum EGL_OPENWF_PORT_ID_EXT = EGLenum::EGL_OPENWF_PORT_ID_EXT;
static const EGLenum EGL_LINUX_DMA_BUF_EXT = EGLenum::EGL_LINUX_DMA_BUF_EXT;
static const EGLenum EGL_LINUX_DRM_FOURCC_EXT = EGLenum::EGL_LINUX_DRM_FOURCC_EXT;
static const EGLenum EGL_DMA_BUF_PLANE0_FD_EXT = EGLenum::EGL_DMA_BUF_PLANE0_FD_EXT;
static const EGLenum EGL_DMA_BUF_PLANE0_OFFSET_EXT = EGLenum::EGL_DMA_BUF_PLANE0_OFFSET_EXT;
static const EGLenum EGL_DMA_BUF_PLANE0_PITCH_EXT = EGLenum::EGL_DMA_BUF_PLANE0_PITCH_EXT;
static const EGLenum EGL_DMA_BUF_PLANE1_FD_EXT = EGLenum::EGL_DMA_BUF_PLANE1_FD_EXT;
static const EGLenum EGL_DMA_BUF_PLANE1_OFFSET_EXT = EGLenum::EGL_DMA_BUF_PLANE1_OFFSET_EXT;
static const EGLenum EGL_DMA_BUF_PLANE1_PITCH_EXT = EGLenum::EGL_DMA_BUF_PLANE1_PITCH_EXT;
static const EGLenum EGL_DMA_BUF_PLANE2_FD_EXT = EGLenum::EGL_DMA_BUF_PLANE2_FD_EXT;
static const EGLenum EGL_DMA_BUF_PLANE2_OFFSET_EXT = EGLenum::EGL_DMA_BUF_PLANE2_OFFSET_EXT;
static const EGLenum EGL_ITU_REC709_EXT = EGLenum::EGL_ITU_REC709_EXT;
static const EGLenum EGL_ITU_REC2020_EXT = EGLenum::EGL_ITU_REC2020_EXT;
static const EGLenum EGL_YUV_FULL_RANGE_EXT = EGLenum::EGL_YUV_FULL_RANGE_EXT;
static const EGLenum EGL_YUV_NARROW_RANGE_EXT = EGLenum::EGL_YUV_NARROW_RANGE_EXT;
static const EGLenum EGL_YUV_CHROMA_SITING_0_EXT = EGLenum::EGL_YUV_CHROMA_SITING_0_EXT;
static const EGLenum EGL_YUV_CHROMA_SITING_0_5_EXT = EGLenum::EGL_YUV_CHROMA_SITING_0_5_EXT;
static const EGLenum EGL_DISCARD_SAMPLES_ARM = EGLenum::EGL_DISCARD_SAMPLES_ARM;
static const EGLenum EGL_YUV_BUFFER_EXT = EGLenum::EGL_YUV_BUFFER_EXT;
static const EGLenum EGL_YUV_ORDER_EXT = EGLenum::EGL_YUV_ORDER_EXT;
static const EGLenum EGL_YUV_ORDER_YUV_EXT = EGLenum::EGL_YUV_ORDER_YUV_EXT;
static const EGLenum EGL_YUV_ORDER_YVU_EXT = EGLenum::EGL_YUV_ORDER_YVU_EXT;
static const EGLenum EGL_YUV_ORDER_YUYV_EXT = EGLenum::EGL_YUV_ORDER_YUYV_EXT;
static const EGLenum EGL_YUV_ORDER_UYVY_EXT = EGLenum::EGL_YUV_ORDER_UYVY_EXT;
static const EGLenum EGL_YUV_ORDER_YVYU_EXT = EGLenum::EGL_YUV_ORDER_YVYU_EXT;
static const EGLenum EGL_YUV_ORDER_VYUY_EXT = EGLenum::EGL_YUV_ORDER_VYUY_EXT;
static const EGLenum EGL_YUV_ORDER_AYUV_EXT = EGLenum::EGL_YUV_ORDER_AYUV_EXT;
static const EGLenum EGL_YUV_NUMBER_OF_PLANES_EXT = EGLenum::EGL_YUV_NUMBER_OF_PLANES_EXT;
static const EGLenum EGL_YUV_SUBSAMPLE_EXT = EGLenum::EGL_YUV_SUBSAMPLE_EXT;
static const EGLenum EGL_YUV_SUBSAMPLE_4_2_0_EXT = EGLenum::EGL_YUV_SUBSAMPLE_4_2_0_EXT;
static const EGLenum EGL_YUV_SUBSAMPLE_4_2_2_EXT = EGLenum::EGL_YUV_SUBSAMPLE_4_2_2_EXT;
static const EGLenum EGL_YUV_SUBSAMPLE_4_4_4_EXT = EGLenum::EGL_YUV_SUBSAMPLE_4_4_4_EXT;
static const EGLenum EGL_YUV_DEPTH_RANGE_EXT = EGLenum::EGL_YUV_DEPTH_RANGE_EXT;
static const EGLenum EGL_YUV_DEPTH_RANGE_LIMITED_EXT = EGLenum::EGL_YUV_DEPTH_RANGE_LIMITED_EXT;
static const EGLenum EGL_YUV_DEPTH_RANGE_FULL_EXT = EGLenum::EGL_YUV_DEPTH_RANGE_FULL_EXT;
static const EGLenum EGL_DISPLAY_SCALING = EGLenum::EGL_DISPLAY_SCALING;

} // namespace egl
