#pragma once

#include <eglbinding/noegl.h>


namespace egl
{

enum class EGLenum : unsigned int
{
    // __UNGROUPED__

    EGL_NO_CONTEXT                                     = ((EGLContext)0),
    EGL_NO_DEVICE_EXT                                  = ((EGLDeviceEXT)(0)),
    EGL_NO_DISPLAY                                     = ((EGLDisplay)0),
    EGL_NO_IMAGE                                       = ((EGLImage)0),
    EGL_NO_IMAGE_KHR                                   = ((EGLImageKHR)0),
    EGL_DEFAULT_DISPLAY                                = ((EGLNativeDisplayType)0),
    EGL_NO_FILE_DESCRIPTOR_KHR                         = ((EGLNativeFileDescriptorKHR)(-1)),
    EGL_NO_OUTPUT_LAYER_EXT                            = ((EGLOutputLayerEXT)0),
    EGL_NO_OUTPUT_PORT_EXT                             = ((EGLOutputPortEXT)0),
    EGL_NO_STREAM_KHR                                  = ((EGLStreamKHR)0),
    EGL_NO_SURFACE                                     = ((EGLSurface)0),
    EGL_NO_SYNC                                        = ((EGLSync)0),
    EGL_NO_SYNC_KHR                                    = ((EGLSyncKHR)0),
    EGL_NO_SYNC_NV                                     = ((EGLSyncNV)0),
    EGL_DONT_CARE                                      = ((EGLint)-1),
    EGL_UNKNOWN                                        = ((EGLint)-1),
    EGL_NO_NATIVE_FENCE_FD_ANDROID                     = static_cast<unsigned int>(-1),
    EGL_DEPTH_ENCODING_NONE_NV                         = 0,
    EGL_SUCCESS                                        = 0x3000,
    EGL_NOT_INITIALIZED                                = 0x3001,
    EGL_BAD_ACCESS                                     = 0x3002,
    EGL_BAD_ALLOC                                      = 0x3003,
    EGL_BAD_ATTRIBUTE                                  = 0x3004,
    EGL_BAD_CONFIG                                     = 0x3005,
    EGL_BAD_CONTEXT                                    = 0x3006,
    EGL_BAD_CURRENT_SURFACE                            = 0x3007,
    EGL_BAD_DISPLAY                                    = 0x3008,
    EGL_BAD_MATCH                                      = 0x3009,
    EGL_BAD_NATIVE_PIXMAP                              = 0x300A,
    EGL_BAD_NATIVE_WINDOW                              = 0x300B,
    EGL_BAD_PARAMETER                                  = 0x300C,
    EGL_BAD_SURFACE                                    = 0x300D,
    EGL_CONTEXT_LOST                                   = 0x300E,
    EGL_BUFFER_SIZE                                    = 0x3020,
    EGL_ALPHA_SIZE                                     = 0x3021,
    EGL_BLUE_SIZE                                      = 0x3022,
    EGL_GREEN_SIZE                                     = 0x3023,
    EGL_RED_SIZE                                       = 0x3024,
    EGL_DEPTH_SIZE                                     = 0x3025,
    EGL_STENCIL_SIZE                                   = 0x3026,
    EGL_CONFIG_CAVEAT                                  = 0x3027,
    EGL_CONFIG_ID                                      = 0x3028,
    EGL_LEVEL                                          = 0x3029,
    EGL_MAX_PBUFFER_HEIGHT                             = 0x302A,
    EGL_MAX_PBUFFER_PIXELS                             = 0x302B,
    EGL_MAX_PBUFFER_WIDTH                              = 0x302C,
    EGL_NATIVE_RENDERABLE                              = 0x302D,
    EGL_NATIVE_VISUAL_ID                               = 0x302E,
    EGL_NATIVE_VISUAL_TYPE                             = 0x302F,
    EGL_SAMPLES                                        = 0x3031,
    EGL_SAMPLE_BUFFERS                                 = 0x3032,
    EGL_SURFACE_TYPE                                   = 0x3033,
    EGL_TRANSPARENT_TYPE                               = 0x3034,
    EGL_TRANSPARENT_BLUE_VALUE                         = 0x3035,
    EGL_TRANSPARENT_GREEN_VALUE                        = 0x3036,
    EGL_TRANSPARENT_RED_VALUE                          = 0x3037,
    EGL_NONE                                           = 0x3038,
    EGL_BIND_TO_TEXTURE_RGB                            = 0x3039,
    EGL_BIND_TO_TEXTURE_RGBA                           = 0x303A,
    EGL_MIN_SWAP_INTERVAL                              = 0x303B,
    EGL_MAX_SWAP_INTERVAL                              = 0x303C,
    EGL_LUMINANCE_SIZE                                 = 0x303D,
    EGL_ALPHA_MASK_SIZE                                = 0x303E,
    EGL_COLOR_BUFFER_TYPE                              = 0x303F,
    EGL_RENDERABLE_TYPE                                = 0x3040,
    EGL_MATCH_NATIVE_PIXMAP                            = 0x3041,
    EGL_CONFORMANT                                     = 0x3042,
    EGL_CONFORMANT_KHR                                 = 0x3042,
    EGL_MATCH_FORMAT_KHR                               = 0x3043,
    EGL_SLOW_CONFIG                                    = 0x3050,
    EGL_NON_CONFORMANT_CONFIG                          = 0x3051,
    EGL_TRANSPARENT_RGB                                = 0x3052,
    EGL_VENDOR                                         = 0x3053,
    EGL_VERSION                                        = 0x3054,
    EGL_EXTENSIONS                                     = 0x3055,
    EGL_HEIGHT                                         = 0x3056,
    EGL_WIDTH                                          = 0x3057,
    EGL_LARGEST_PBUFFER                                = 0x3058,
    EGL_DRAW                                           = 0x3059,
    EGL_READ                                           = 0x305A,
    EGL_CORE_NATIVE_ENGINE                             = 0x305B,
    EGL_NO_TEXTURE                                     = 0x305C,
    EGL_TEXTURE_RGB                                    = 0x305D,
    EGL_TEXTURE_RGBA                                   = 0x305E,
    EGL_TEXTURE_2D                                     = 0x305F,
    EGL_Y_INVERTED_NOK                                 = 0x307F,
    EGL_TEXTURE_FORMAT                                 = 0x3080,
    EGL_TEXTURE_TARGET                                 = 0x3081,
    EGL_MIPMAP_TEXTURE                                 = 0x3082,
    EGL_MIPMAP_LEVEL                                   = 0x3083,
    EGL_BACK_BUFFER                                    = 0x3084,
    EGL_SINGLE_BUFFER                                  = 0x3085,
    EGL_RENDER_BUFFER                                  = 0x3086,
    EGL_COLORSPACE                                     = 0x3087,
    EGL_VG_COLORSPACE                                  = 0x3087,
    EGL_ALPHA_FORMAT                                   = 0x3088,
    EGL_VG_ALPHA_FORMAT                                = 0x3088,
    EGL_COLORSPACE_sRGB                                = 0x3089,
    EGL_GL_COLORSPACE_SRGB                             = 0x3089,
    EGL_GL_COLORSPACE_SRGB_KHR                         = 0x3089,
    EGL_VG_COLORSPACE_sRGB                             = 0x3089,
    EGL_COLORSPACE_LINEAR                              = 0x308A,
    EGL_GL_COLORSPACE_LINEAR                           = 0x308A,
    EGL_GL_COLORSPACE_LINEAR_KHR                       = 0x308A,
    EGL_VG_COLORSPACE_LINEAR                           = 0x308A,
    EGL_ALPHA_FORMAT_NONPRE                            = 0x308B,
    EGL_VG_ALPHA_FORMAT_NONPRE                         = 0x308B,
    EGL_ALPHA_FORMAT_PRE                               = 0x308C,
    EGL_VG_ALPHA_FORMAT_PRE                            = 0x308C,
    EGL_CLIENT_APIS                                    = 0x308D,
    EGL_RGB_BUFFER                                     = 0x308E,
    EGL_LUMINANCE_BUFFER                               = 0x308F,
    EGL_HORIZONTAL_RESOLUTION                          = 0x3090,
    EGL_VERTICAL_RESOLUTION                            = 0x3091,
    EGL_PIXEL_ASPECT_RATIO                             = 0x3092,
    EGL_SWAP_BEHAVIOR                                  = 0x3093,
    EGL_BUFFER_PRESERVED                               = 0x3094,
    EGL_BUFFER_DESTROYED                               = 0x3095,
    EGL_OPENVG_IMAGE                                   = 0x3096,
    EGL_CONTEXT_CLIENT_TYPE                            = 0x3097,
    EGL_CONTEXT_CLIENT_VERSION                         = 0x3098,
    EGL_CONTEXT_MAJOR_VERSION                          = 0x3098,
    EGL_CONTEXT_MAJOR_VERSION_KHR                      = 0x3098,
    EGL_MULTISAMPLE_RESOLVE                            = 0x3099,
    EGL_MULTISAMPLE_RESOLVE_DEFAULT                    = 0x309A,
    EGL_MULTISAMPLE_RESOLVE_BOX                        = 0x309B,
    EGL_CL_EVENT_HANDLE                                = 0x309C,
    EGL_CL_EVENT_HANDLE_KHR                            = 0x309C,
    EGL_GL_COLORSPACE                                  = 0x309D,
    EGL_GL_COLORSPACE_KHR                              = 0x309D,
    EGL_OPENGL_ES_API                                  = 0x30A0,
    EGL_OPENVG_API                                     = 0x30A1,
    EGL_OPENGL_API                                     = 0x30A2,
    EGL_NATIVE_PIXMAP_KHR                              = 0x30B0,
    EGL_GL_TEXTURE_2D                                  = 0x30B1,
    EGL_GL_TEXTURE_2D_KHR                              = 0x30B1,
    EGL_GL_TEXTURE_3D                                  = 0x30B2,
    EGL_GL_TEXTURE_3D_KHR                              = 0x30B2,
    EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_X                 = 0x30B3,
    EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_X_KHR             = 0x30B3,
    EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_X                 = 0x30B4,
    EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_X_KHR             = 0x30B4,
    EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Y                 = 0x30B5,
    EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Y_KHR             = 0x30B5,
    EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y                 = 0x30B6,
    EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y_KHR             = 0x30B6,
    EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Z                 = 0x30B7,
    EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Z_KHR             = 0x30B7,
    EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z                 = 0x30B8,
    EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z_KHR             = 0x30B8,
    EGL_GL_RENDERBUFFER                                = 0x30B9,
    EGL_GL_RENDERBUFFER_KHR                            = 0x30B9,
    EGL_VG_PARENT_IMAGE_KHR                            = 0x30BA,
    EGL_GL_TEXTURE_LEVEL                               = 0x30BC,
    EGL_GL_TEXTURE_LEVEL_KHR                           = 0x30BC,
    EGL_GL_TEXTURE_ZOFFSET                             = 0x30BD,
    EGL_GL_TEXTURE_ZOFFSET_KHR                         = 0x30BD,
    EGL_POST_SUB_BUFFER_SUPPORTED_NV                   = 0x30BE,
    EGL_CONTEXT_OPENGL_ROBUST_ACCESS_EXT               = 0x30BF,
    EGL_FORMAT_RGB_565_EXACT_KHR                       = 0x30C0,
    EGL_FORMAT_RGB_565_KHR                             = 0x30C1,
    EGL_FORMAT_RGBA_8888_EXACT_KHR                     = 0x30C2,
    EGL_FORMAT_RGBA_8888_KHR                           = 0x30C3,
    EGL_MAP_PRESERVE_PIXELS_KHR                        = 0x30C4,
    EGL_LOCK_USAGE_HINT_KHR                            = 0x30C5,
    EGL_BITMAP_POINTER_KHR                             = 0x30C6,
    EGL_BITMAP_PITCH_KHR                               = 0x30C7,
    EGL_BITMAP_ORIGIN_KHR                              = 0x30C8,
    EGL_BITMAP_PIXEL_RED_OFFSET_KHR                    = 0x30C9,
    EGL_BITMAP_PIXEL_GREEN_OFFSET_KHR                  = 0x30CA,
    EGL_BITMAP_PIXEL_BLUE_OFFSET_KHR                   = 0x30CB,
    EGL_BITMAP_PIXEL_ALPHA_OFFSET_KHR                  = 0x30CC,
    EGL_BITMAP_PIXEL_LUMINANCE_OFFSET_KHR              = 0x30CD,
    EGL_LOWER_LEFT_KHR                                 = 0x30CE,
    EGL_UPPER_LEFT_KHR                                 = 0x30CF,
    EGL_IMAGE_PRESERVED                                = 0x30D2,
    EGL_IMAGE_PRESERVED_KHR                            = 0x30D2,
    EGL_COVERAGE_BUFFERS_NV                            = 0x30E0,
    EGL_COVERAGE_SAMPLES_NV                            = 0x30E1,
    EGL_DEPTH_ENCODING_NV                              = 0x30E2,
    EGL_DEPTH_ENCODING_NONLINEAR_NV                    = 0x30E3,
    EGL_SYNC_PRIOR_COMMANDS_COMPLETE_NV                = 0x30E6,
    EGL_SYNC_STATUS_NV                                 = 0x30E7,
    EGL_SIGNALED_NV                                    = 0x30E8,
    EGL_UNSIGNALED_NV                                  = 0x30E9,
    EGL_ALREADY_SIGNALED_NV                            = 0x30EA,
    EGL_TIMEOUT_EXPIRED_NV                             = 0x30EB,
    EGL_CONDITION_SATISFIED_NV                         = 0x30EC,
    EGL_SYNC_TYPE_NV                                   = 0x30ED,
    EGL_SYNC_CONDITION_NV                              = 0x30EE,
    EGL_SYNC_FENCE_NV                                  = 0x30EF,
    EGL_SYNC_PRIOR_COMMANDS_COMPLETE                   = 0x30F0,
    EGL_SYNC_PRIOR_COMMANDS_COMPLETE_KHR               = 0x30F0,
    EGL_SYNC_STATUS                                    = 0x30F1,
    EGL_SYNC_STATUS_KHR                                = 0x30F1,
    EGL_SIGNALED                                       = 0x30F2,
    EGL_SIGNALED_KHR                                   = 0x30F2,
    EGL_UNSIGNALED                                     = 0x30F3,
    EGL_UNSIGNALED_KHR                                 = 0x30F3,
    EGL_TIMEOUT_EXPIRED                                = 0x30F5,
    EGL_TIMEOUT_EXPIRED_KHR                            = 0x30F5,
    EGL_CONDITION_SATISFIED                            = 0x30F6,
    EGL_CONDITION_SATISFIED_KHR                        = 0x30F6,
    EGL_SYNC_TYPE                                      = 0x30F7,
    EGL_SYNC_TYPE_KHR                                  = 0x30F7,
    EGL_SYNC_CONDITION                                 = 0x30F8,
    EGL_SYNC_CONDITION_KHR                             = 0x30F8,
    EGL_SYNC_FENCE                                     = 0x30F9,
    EGL_SYNC_FENCE_KHR                                 = 0x30F9,
    EGL_SYNC_REUSABLE_KHR                              = 0x30FA,
    EGL_CONTEXT_MINOR_VERSION                          = 0x30FB,
    EGL_CONTEXT_MINOR_VERSION_KHR                      = 0x30FB,
    EGL_CONTEXT_FLAGS_KHR                              = 0x30FC,
    EGL_CONTEXT_OPENGL_PROFILE_MASK                    = 0x30FD,
    EGL_CONTEXT_OPENGL_PROFILE_MASK_KHR                = 0x30FD,
    EGL_SYNC_CL_EVENT                                  = 0x30FE,
    EGL_SYNC_CL_EVENT_KHR                              = 0x30FE,
    EGL_SYNC_CL_EVENT_COMPLETE                         = 0x30FF,
    EGL_SYNC_CL_EVENT_COMPLETE_KHR                     = 0x30FF,
    EGL_CONTEXT_PRIORITY_LEVEL_IMG                     = 0x3100,
    EGL_CONTEXT_PRIORITY_HIGH_IMG                      = 0x3101,
    EGL_CONTEXT_PRIORITY_MEDIUM_IMG                    = 0x3102,
    EGL_CONTEXT_PRIORITY_LOW_IMG                       = 0x3103,
    EGL_BITMAP_PIXEL_SIZE_KHR                          = 0x3110,
    EGL_COVERAGE_SAMPLE_RESOLVE_NV                     = 0x3131,
    EGL_COVERAGE_SAMPLE_RESOLVE_DEFAULT_NV             = 0x3132,
    EGL_COVERAGE_SAMPLE_RESOLVE_NONE_NV                = 0x3133,
    EGL_MULTIVIEW_VIEW_COUNT_EXT                       = 0x3134,
    EGL_AUTO_STEREO_NV                                 = 0x3136,
    EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_EXT = 0x3138,
    EGL_BUFFER_AGE_EXT                                 = 0x313D,
    EGL_BUFFER_AGE_KHR                                 = 0x313D,
    EGL_PLATFORM_DEVICE_EXT                            = 0x313F,
    EGL_NATIVE_BUFFER_ANDROID                          = 0x3140,
    EGL_PLATFORM_ANDROID_KHR                           = 0x3141,
    EGL_RECORDABLE_ANDROID                             = 0x3142,
    EGL_SYNC_NATIVE_FENCE_ANDROID                      = 0x3144,
    EGL_SYNC_NATIVE_FENCE_FD_ANDROID                   = 0x3145,
    EGL_SYNC_NATIVE_FENCE_SIGNALED_ANDROID             = 0x3146,
    EGL_FRAMEBUFFER_TARGET_ANDROID                     = 0x3147,
    EGL_CONTEXT_OPENGL_DEBUG                           = 0x31B0,
    EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE              = 0x31B1,
    EGL_CONTEXT_OPENGL_ROBUST_ACCESS                   = 0x31B2,
    EGL_CONTEXT_OPENGL_NO_ERROR_KHR                    = 0x31B3,
    EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY     = 0x31BD,
    EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_KHR = 0x31BD,
    EGL_NO_RESET_NOTIFICATION                          = 0x31BE,
    EGL_NO_RESET_NOTIFICATION_EXT                      = 0x31BE,
    EGL_NO_RESET_NOTIFICATION_KHR                      = 0x31BE,
    EGL_LOSE_CONTEXT_ON_RESET                          = 0x31BF,
    EGL_LOSE_CONTEXT_ON_RESET_EXT                      = 0x31BF,
    EGL_LOSE_CONTEXT_ON_RESET_KHR                      = 0x31BF,
    EGL_DRM_BUFFER_FORMAT_MESA                         = 0x31D0,
    EGL_DRM_BUFFER_USE_MESA                            = 0x31D1,
    EGL_DRM_BUFFER_FORMAT_ARGB32_MESA                  = 0x31D2,
    EGL_DRM_BUFFER_MESA                                = 0x31D3,
    EGL_DRM_BUFFER_STRIDE_MESA                         = 0x31D4,
    EGL_PLATFORM_X11_EXT                               = 0x31D5,
    EGL_PLATFORM_X11_KHR                               = 0x31D5,
    EGL_PLATFORM_X11_SCREEN_EXT                        = 0x31D6,
    EGL_PLATFORM_X11_SCREEN_KHR                        = 0x31D6,
    EGL_PLATFORM_GBM_KHR                               = 0x31D7,
    EGL_PLATFORM_GBM_MESA                              = 0x31D7,
    EGL_PLATFORM_WAYLAND_EXT                           = 0x31D8,
    EGL_PLATFORM_WAYLAND_KHR                           = 0x31D8,
    EGL_STREAM_FIFO_LENGTH_KHR                         = 0x31FC,
    EGL_STREAM_TIME_NOW_KHR                            = 0x31FD,
    EGL_STREAM_TIME_CONSUMER_KHR                       = 0x31FE,
    EGL_STREAM_TIME_PRODUCER_KHR                       = 0x31FF,
    EGL_D3D_TEXTURE_2D_SHARE_HANDLE_ANGLE              = 0x3200,
    EGL_FIXED_SIZE_ANGLE                               = 0x3201,
    EGL_CONSUMER_LATENCY_USEC_KHR                      = 0x3210,
    EGL_PRODUCER_FRAME_KHR                             = 0x3212,
    EGL_CONSUMER_FRAME_KHR                             = 0x3213,
    EGL_STREAM_STATE_KHR                               = 0x3214,
    EGL_STREAM_STATE_CREATED_KHR                       = 0x3215,
    EGL_STREAM_STATE_CONNECTING_KHR                    = 0x3216,
    EGL_STREAM_STATE_EMPTY_KHR                         = 0x3217,
    EGL_STREAM_STATE_NEW_FRAME_AVAILABLE_KHR           = 0x3218,
    EGL_STREAM_STATE_OLD_FRAME_AVAILABLE_KHR           = 0x3219,
    EGL_STREAM_STATE_DISCONNECTED_KHR                  = 0x321A,
    EGL_BAD_STREAM_KHR                                 = 0x321B,
    EGL_BAD_STATE_KHR                                  = 0x321C,
    EGL_CONSUMER_ACQUIRE_TIMEOUT_USEC_KHR              = 0x321E,
    EGL_SYNC_NEW_FRAME_NV                              = 0x321F,
    EGL_BAD_DEVICE_EXT                                 = 0x322B,
    EGL_DEVICE_EXT                                     = 0x322C,
    EGL_BAD_OUTPUT_LAYER_EXT                           = 0x322D,
    EGL_BAD_OUTPUT_PORT_EXT                            = 0x322E,
    EGL_SWAP_INTERVAL_EXT                              = 0x322F,
    EGL_DRM_DEVICE_FILE_EXT                            = 0x3233,
    EGL_DRM_CRTC_EXT                                   = 0x3234,
    EGL_DRM_PLANE_EXT                                  = 0x3235,
    EGL_DRM_CONNECTOR_EXT                              = 0x3236,
    EGL_OPENWF_DEVICE_ID_EXT                           = 0x3237,
    EGL_OPENWF_PIPELINE_ID_EXT                         = 0x3238,
    EGL_OPENWF_PORT_ID_EXT                             = 0x3239,
    EGL_CUDA_DEVICE_NV                                 = 0x323A,
    EGL_CUDA_EVENT_HANDLE_NV                           = 0x323B,
    EGL_SYNC_CUDA_EVENT_NV                             = 0x323C,
    EGL_SYNC_CUDA_EVENT_COMPLETE_NV                    = 0x323D,
    EGL_LINUX_DMA_BUF_EXT                              = 0x3270,
    EGL_LINUX_DRM_FOURCC_EXT                           = 0x3271,
    EGL_DMA_BUF_PLANE0_FD_EXT                          = 0x3272,
    EGL_DMA_BUF_PLANE0_OFFSET_EXT                      = 0x3273,
    EGL_DMA_BUF_PLANE0_PITCH_EXT                       = 0x3274,
    EGL_DMA_BUF_PLANE1_FD_EXT                          = 0x3275,
    EGL_DMA_BUF_PLANE1_OFFSET_EXT                      = 0x3276,
    EGL_DMA_BUF_PLANE1_PITCH_EXT                       = 0x3277,
    EGL_DMA_BUF_PLANE2_FD_EXT                          = 0x3278,
    EGL_DMA_BUF_PLANE2_OFFSET_EXT                      = 0x3279,
    EGL_DMA_BUF_PLANE2_PITCH_EXT                       = 0x327A,
    EGL_YUV_COLOR_SPACE_HINT_EXT                       = 0x327B,
    EGL_SAMPLE_RANGE_HINT_EXT                          = 0x327C,
    EGL_YUV_CHROMA_HORIZONTAL_SITING_HINT_EXT          = 0x327D,
    EGL_YUV_CHROMA_VERTICAL_SITING_HINT_EXT            = 0x327E,
    EGL_ITU_REC601_EXT                                 = 0x327F,
    EGL_ITU_REC709_EXT                                 = 0x3280,
    EGL_ITU_REC2020_EXT                                = 0x3281,
    EGL_YUV_FULL_RANGE_EXT                             = 0x3282,
    EGL_YUV_NARROW_RANGE_EXT                           = 0x3283,
    EGL_YUV_CHROMA_SITING_0_EXT                        = 0x3284,
    EGL_YUV_CHROMA_SITING_0_5_EXT                      = 0x3285,
    EGL_DISCARD_SAMPLES_ARM                            = 0x3286,
    EGL_NATIVE_BUFFER_TIZEN                            = 0x32A0,
    EGL_NATIVE_SURFACE_TIZEN                           = 0x32A1,
    EGL_PROTECTED_CONTENT_EXT                          = 0x32C0,
    EGL_YUV_BUFFER_EXT                                 = 0x3300,
    EGL_YUV_ORDER_EXT                                  = 0x3301,
    EGL_YUV_ORDER_YUV_EXT                              = 0x3302,
    EGL_YUV_ORDER_YVU_EXT                              = 0x3303,
    EGL_YUV_ORDER_YUYV_EXT                             = 0x3304,
    EGL_YUV_ORDER_UYVY_EXT                             = 0x3305,
    EGL_YUV_ORDER_YVYU_EXT                             = 0x3306,
    EGL_YUV_ORDER_VYUY_EXT                             = 0x3307,
    EGL_YUV_ORDER_AYUV_EXT                             = 0x3308,
    EGL_YUV_CSC_STANDARD_EXT                           = 0x330A,
    EGL_YUV_CSC_STANDARD_601_EXT                       = 0x330B,
    EGL_YUV_CSC_STANDARD_709_EXT                       = 0x330C,
    EGL_YUV_CSC_STANDARD_2020_EXT                      = 0x330D,
    EGL_YUV_NUMBER_OF_PLANES_EXT                       = 0x3311,
    EGL_YUV_SUBSAMPLE_EXT                              = 0x3312,
    EGL_YUV_SUBSAMPLE_4_2_0_EXT                        = 0x3313,
    EGL_YUV_SUBSAMPLE_4_2_2_EXT                        = 0x3314,
    EGL_YUV_SUBSAMPLE_4_4_4_EXT                        = 0x3315,
    EGL_YUV_DEPTH_RANGE_EXT                            = 0x3317,
    EGL_YUV_DEPTH_RANGE_LIMITED_EXT                    = 0x3318,
    EGL_YUV_DEPTH_RANGE_FULL_EXT                       = 0x3319,
    EGL_YUV_PLANE_BPP_EXT                              = 0x331A,
    EGL_YUV_PLANE_BPP_0_EXT                            = 0x331B,
    EGL_YUV_PLANE_BPP_8_EXT                            = 0x331C,
    EGL_YUV_PLANE_BPP_10_EXT                           = 0x331D,
    EGL_D3D9_DEVICE_ANGLE                              = 0x33A0,
    EGL_D3D11_DEVICE_ANGLE                             = 0x33A1,
    EGL_COLOR_FORMAT_HI                                = 0x8F70,
    EGL_COLOR_RGB_HI                                   = 0x8F71,
    EGL_COLOR_RGBA_HI                                  = 0x8F72,
    EGL_COLOR_ARGB_HI                                  = 0x8F73,
    EGL_CLIENT_PIXMAP_POINTER_HI                       = 0x8F74,
    EGL_DISPLAY_SCALING                                = 10000,

};

// import enums to namespace


// __UNGROUPED__

static const EGLenum EGL_NO_CONTEXT = EGLenum::EGL_NO_CONTEXT;
static const EGLenum EGL_NO_DEVICE_EXT = EGLenum::EGL_NO_DEVICE_EXT;
static const EGLenum EGL_NO_DISPLAY = EGLenum::EGL_NO_DISPLAY;
static const EGLenum EGL_NO_IMAGE = EGLenum::EGL_NO_IMAGE;
static const EGLenum EGL_NO_IMAGE_KHR = EGLenum::EGL_NO_IMAGE_KHR;
static const EGLenum EGL_DEFAULT_DISPLAY = EGLenum::EGL_DEFAULT_DISPLAY;
static const EGLenum EGL_NO_FILE_DESCRIPTOR_KHR = EGLenum::EGL_NO_FILE_DESCRIPTOR_KHR;
static const EGLenum EGL_NO_OUTPUT_LAYER_EXT = EGLenum::EGL_NO_OUTPUT_LAYER_EXT;
static const EGLenum EGL_NO_OUTPUT_PORT_EXT = EGLenum::EGL_NO_OUTPUT_PORT_EXT;
static const EGLenum EGL_NO_STREAM_KHR = EGLenum::EGL_NO_STREAM_KHR;
static const EGLenum EGL_NO_SURFACE = EGLenum::EGL_NO_SURFACE;
static const EGLenum EGL_NO_SYNC = EGLenum::EGL_NO_SYNC;
static const EGLenum EGL_NO_SYNC_KHR = EGLenum::EGL_NO_SYNC_KHR;
static const EGLenum EGL_NO_SYNC_NV = EGLenum::EGL_NO_SYNC_NV;
static const EGLenum EGL_DONT_CARE = EGLenum::EGL_DONT_CARE;
static const EGLenum EGL_UNKNOWN = EGLenum::EGL_UNKNOWN;
static const EGLenum EGL_NO_NATIVE_FENCE_FD_ANDROID = EGLenum::EGL_NO_NATIVE_FENCE_FD_ANDROID;
static const EGLenum EGL_DEPTH_ENCODING_NONE_NV = EGLenum::EGL_DEPTH_ENCODING_NONE_NV;
static const EGLenum EGL_SUCCESS = EGLenum::EGL_SUCCESS;
static const EGLenum EGL_NOT_INITIALIZED = EGLenum::EGL_NOT_INITIALIZED;
static const EGLenum EGL_BAD_ACCESS = EGLenum::EGL_BAD_ACCESS;
static const EGLenum EGL_BAD_ALLOC = EGLenum::EGL_BAD_ALLOC;
static const EGLenum EGL_BAD_ATTRIBUTE = EGLenum::EGL_BAD_ATTRIBUTE;
static const EGLenum EGL_BAD_CONFIG = EGLenum::EGL_BAD_CONFIG;
static const EGLenum EGL_BAD_CONTEXT = EGLenum::EGL_BAD_CONTEXT;
static const EGLenum EGL_BAD_CURRENT_SURFACE = EGLenum::EGL_BAD_CURRENT_SURFACE;
static const EGLenum EGL_BAD_DISPLAY = EGLenum::EGL_BAD_DISPLAY;
static const EGLenum EGL_BAD_MATCH = EGLenum::EGL_BAD_MATCH;
static const EGLenum EGL_BAD_NATIVE_PIXMAP = EGLenum::EGL_BAD_NATIVE_PIXMAP;
static const EGLenum EGL_BAD_NATIVE_WINDOW = EGLenum::EGL_BAD_NATIVE_WINDOW;
static const EGLenum EGL_BAD_PARAMETER = EGLenum::EGL_BAD_PARAMETER;
static const EGLenum EGL_BAD_SURFACE = EGLenum::EGL_BAD_SURFACE;
static const EGLenum EGL_CONTEXT_LOST = EGLenum::EGL_CONTEXT_LOST;
static const EGLenum EGL_BUFFER_SIZE = EGLenum::EGL_BUFFER_SIZE;
static const EGLenum EGL_ALPHA_SIZE = EGLenum::EGL_ALPHA_SIZE;
static const EGLenum EGL_BLUE_SIZE = EGLenum::EGL_BLUE_SIZE;
static const EGLenum EGL_GREEN_SIZE = EGLenum::EGL_GREEN_SIZE;
static const EGLenum EGL_RED_SIZE = EGLenum::EGL_RED_SIZE;
static const EGLenum EGL_DEPTH_SIZE = EGLenum::EGL_DEPTH_SIZE;
static const EGLenum EGL_STENCIL_SIZE = EGLenum::EGL_STENCIL_SIZE;
static const EGLenum EGL_CONFIG_CAVEAT = EGLenum::EGL_CONFIG_CAVEAT;
static const EGLenum EGL_CONFIG_ID = EGLenum::EGL_CONFIG_ID;
static const EGLenum EGL_LEVEL = EGLenum::EGL_LEVEL;
static const EGLenum EGL_MAX_PBUFFER_HEIGHT = EGLenum::EGL_MAX_PBUFFER_HEIGHT;
static const EGLenum EGL_MAX_PBUFFER_PIXELS = EGLenum::EGL_MAX_PBUFFER_PIXELS;
static const EGLenum EGL_MAX_PBUFFER_WIDTH = EGLenum::EGL_MAX_PBUFFER_WIDTH;
static const EGLenum EGL_NATIVE_RENDERABLE = EGLenum::EGL_NATIVE_RENDERABLE;
static const EGLenum EGL_NATIVE_VISUAL_ID = EGLenum::EGL_NATIVE_VISUAL_ID;
static const EGLenum EGL_NATIVE_VISUAL_TYPE = EGLenum::EGL_NATIVE_VISUAL_TYPE;
static const EGLenum EGL_SAMPLES = EGLenum::EGL_SAMPLES;
static const EGLenum EGL_SAMPLE_BUFFERS = EGLenum::EGL_SAMPLE_BUFFERS;
static const EGLenum EGL_SURFACE_TYPE = EGLenum::EGL_SURFACE_TYPE;
static const EGLenum EGL_TRANSPARENT_TYPE = EGLenum::EGL_TRANSPARENT_TYPE;
static const EGLenum EGL_TRANSPARENT_BLUE_VALUE = EGLenum::EGL_TRANSPARENT_BLUE_VALUE;
static const EGLenum EGL_TRANSPARENT_GREEN_VALUE = EGLenum::EGL_TRANSPARENT_GREEN_VALUE;
static const EGLenum EGL_TRANSPARENT_RED_VALUE = EGLenum::EGL_TRANSPARENT_RED_VALUE;
static const EGLenum EGL_NONE = EGLenum::EGL_NONE;
static const EGLenum EGL_BIND_TO_TEXTURE_RGB = EGLenum::EGL_BIND_TO_TEXTURE_RGB;
static const EGLenum EGL_BIND_TO_TEXTURE_RGBA = EGLenum::EGL_BIND_TO_TEXTURE_RGBA;
static const EGLenum EGL_MIN_SWAP_INTERVAL = EGLenum::EGL_MIN_SWAP_INTERVAL;
static const EGLenum EGL_MAX_SWAP_INTERVAL = EGLenum::EGL_MAX_SWAP_INTERVAL;
static const EGLenum EGL_LUMINANCE_SIZE = EGLenum::EGL_LUMINANCE_SIZE;
static const EGLenum EGL_ALPHA_MASK_SIZE = EGLenum::EGL_ALPHA_MASK_SIZE;
static const EGLenum EGL_COLOR_BUFFER_TYPE = EGLenum::EGL_COLOR_BUFFER_TYPE;
static const EGLenum EGL_RENDERABLE_TYPE = EGLenum::EGL_RENDERABLE_TYPE;
static const EGLenum EGL_MATCH_NATIVE_PIXMAP = EGLenum::EGL_MATCH_NATIVE_PIXMAP;
static const EGLenum EGL_CONFORMANT = EGLenum::EGL_CONFORMANT;
static const EGLenum EGL_CONFORMANT_KHR = EGLenum::EGL_CONFORMANT_KHR;
static const EGLenum EGL_MATCH_FORMAT_KHR = EGLenum::EGL_MATCH_FORMAT_KHR;
static const EGLenum EGL_SLOW_CONFIG = EGLenum::EGL_SLOW_CONFIG;
static const EGLenum EGL_NON_CONFORMANT_CONFIG = EGLenum::EGL_NON_CONFORMANT_CONFIG;
static const EGLenum EGL_TRANSPARENT_RGB = EGLenum::EGL_TRANSPARENT_RGB;
static const EGLenum EGL_VENDOR = EGLenum::EGL_VENDOR;
static const EGLenum EGL_VERSION = EGLenum::EGL_VERSION;
static const EGLenum EGL_EXTENSIONS = EGLenum::EGL_EXTENSIONS;
static const EGLenum EGL_HEIGHT = EGLenum::EGL_HEIGHT;
static const EGLenum EGL_WIDTH = EGLenum::EGL_WIDTH;
static const EGLenum EGL_LARGEST_PBUFFER = EGLenum::EGL_LARGEST_PBUFFER;
static const EGLenum EGL_DRAW = EGLenum::EGL_DRAW;
static const EGLenum EGL_READ = EGLenum::EGL_READ;
static const EGLenum EGL_CORE_NATIVE_ENGINE = EGLenum::EGL_CORE_NATIVE_ENGINE;
static const EGLenum EGL_NO_TEXTURE = EGLenum::EGL_NO_TEXTURE;
static const EGLenum EGL_TEXTURE_RGB = EGLenum::EGL_TEXTURE_RGB;
static const EGLenum EGL_TEXTURE_RGBA = EGLenum::EGL_TEXTURE_RGBA;
static const EGLenum EGL_TEXTURE_2D = EGLenum::EGL_TEXTURE_2D;
static const EGLenum EGL_Y_INVERTED_NOK = EGLenum::EGL_Y_INVERTED_NOK;
static const EGLenum EGL_TEXTURE_FORMAT = EGLenum::EGL_TEXTURE_FORMAT;
static const EGLenum EGL_TEXTURE_TARGET = EGLenum::EGL_TEXTURE_TARGET;
static const EGLenum EGL_MIPMAP_TEXTURE = EGLenum::EGL_MIPMAP_TEXTURE;
static const EGLenum EGL_MIPMAP_LEVEL = EGLenum::EGL_MIPMAP_LEVEL;
static const EGLenum EGL_BACK_BUFFER = EGLenum::EGL_BACK_BUFFER;
static const EGLenum EGL_SINGLE_BUFFER = EGLenum::EGL_SINGLE_BUFFER;
static const EGLenum EGL_RENDER_BUFFER = EGLenum::EGL_RENDER_BUFFER;
static const EGLenum EGL_COLORSPACE = EGLenum::EGL_COLORSPACE;
static const EGLenum EGL_VG_COLORSPACE = EGLenum::EGL_VG_COLORSPACE;
static const EGLenum EGL_ALPHA_FORMAT = EGLenum::EGL_ALPHA_FORMAT;
static const EGLenum EGL_VG_ALPHA_FORMAT = EGLenum::EGL_VG_ALPHA_FORMAT;
static const EGLenum EGL_COLORSPACE_sRGB = EGLenum::EGL_COLORSPACE_sRGB;
static const EGLenum EGL_GL_COLORSPACE_SRGB = EGLenum::EGL_GL_COLORSPACE_SRGB;
static const EGLenum EGL_GL_COLORSPACE_SRGB_KHR = EGLenum::EGL_GL_COLORSPACE_SRGB_KHR;
static const EGLenum EGL_VG_COLORSPACE_sRGB = EGLenum::EGL_VG_COLORSPACE_sRGB;
static const EGLenum EGL_COLORSPACE_LINEAR = EGLenum::EGL_COLORSPACE_LINEAR;
static const EGLenum EGL_GL_COLORSPACE_LINEAR = EGLenum::EGL_GL_COLORSPACE_LINEAR;
static const EGLenum EGL_GL_COLORSPACE_LINEAR_KHR = EGLenum::EGL_GL_COLORSPACE_LINEAR_KHR;
static const EGLenum EGL_VG_COLORSPACE_LINEAR = EGLenum::EGL_VG_COLORSPACE_LINEAR;
static const EGLenum EGL_ALPHA_FORMAT_NONPRE = EGLenum::EGL_ALPHA_FORMAT_NONPRE;
static const EGLenum EGL_VG_ALPHA_FORMAT_NONPRE = EGLenum::EGL_VG_ALPHA_FORMAT_NONPRE;
static const EGLenum EGL_ALPHA_FORMAT_PRE = EGLenum::EGL_ALPHA_FORMAT_PRE;
static const EGLenum EGL_VG_ALPHA_FORMAT_PRE = EGLenum::EGL_VG_ALPHA_FORMAT_PRE;
static const EGLenum EGL_CLIENT_APIS = EGLenum::EGL_CLIENT_APIS;
static const EGLenum EGL_RGB_BUFFER = EGLenum::EGL_RGB_BUFFER;
static const EGLenum EGL_LUMINANCE_BUFFER = EGLenum::EGL_LUMINANCE_BUFFER;
static const EGLenum EGL_HORIZONTAL_RESOLUTION = EGLenum::EGL_HORIZONTAL_RESOLUTION;
static const EGLenum EGL_VERTICAL_RESOLUTION = EGLenum::EGL_VERTICAL_RESOLUTION;
static const EGLenum EGL_PIXEL_ASPECT_RATIO = EGLenum::EGL_PIXEL_ASPECT_RATIO;
static const EGLenum EGL_SWAP_BEHAVIOR = EGLenum::EGL_SWAP_BEHAVIOR;
static const EGLenum EGL_BUFFER_PRESERVED = EGLenum::EGL_BUFFER_PRESERVED;
static const EGLenum EGL_BUFFER_DESTROYED = EGLenum::EGL_BUFFER_DESTROYED;
static const EGLenum EGL_OPENVG_IMAGE = EGLenum::EGL_OPENVG_IMAGE;
static const EGLenum EGL_CONTEXT_CLIENT_TYPE = EGLenum::EGL_CONTEXT_CLIENT_TYPE;
static const EGLenum EGL_CONTEXT_CLIENT_VERSION = EGLenum::EGL_CONTEXT_CLIENT_VERSION;
static const EGLenum EGL_CONTEXT_MAJOR_VERSION = EGLenum::EGL_CONTEXT_MAJOR_VERSION;
static const EGLenum EGL_CONTEXT_MAJOR_VERSION_KHR = EGLenum::EGL_CONTEXT_MAJOR_VERSION_KHR;
static const EGLenum EGL_MULTISAMPLE_RESOLVE = EGLenum::EGL_MULTISAMPLE_RESOLVE;
static const EGLenum EGL_MULTISAMPLE_RESOLVE_DEFAULT = EGLenum::EGL_MULTISAMPLE_RESOLVE_DEFAULT;
static const EGLenum EGL_MULTISAMPLE_RESOLVE_BOX = EGLenum::EGL_MULTISAMPLE_RESOLVE_BOX;
static const EGLenum EGL_CL_EVENT_HANDLE = EGLenum::EGL_CL_EVENT_HANDLE;
static const EGLenum EGL_CL_EVENT_HANDLE_KHR = EGLenum::EGL_CL_EVENT_HANDLE_KHR;
static const EGLenum EGL_GL_COLORSPACE = EGLenum::EGL_GL_COLORSPACE;
static const EGLenum EGL_GL_COLORSPACE_KHR = EGLenum::EGL_GL_COLORSPACE_KHR;
static const EGLenum EGL_OPENGL_ES_API = EGLenum::EGL_OPENGL_ES_API;
static const EGLenum EGL_OPENVG_API = EGLenum::EGL_OPENVG_API;
static const EGLenum EGL_OPENGL_API = EGLenum::EGL_OPENGL_API;
static const EGLenum EGL_NATIVE_PIXMAP_KHR = EGLenum::EGL_NATIVE_PIXMAP_KHR;
static const EGLenum EGL_GL_TEXTURE_2D = EGLenum::EGL_GL_TEXTURE_2D;
static const EGLenum EGL_GL_TEXTURE_2D_KHR = EGLenum::EGL_GL_TEXTURE_2D_KHR;
static const EGLenum EGL_GL_TEXTURE_3D = EGLenum::EGL_GL_TEXTURE_3D;
static const EGLenum EGL_GL_TEXTURE_3D_KHR = EGLenum::EGL_GL_TEXTURE_3D_KHR;
static const EGLenum EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_X = EGLenum::EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_X;
static const EGLenum EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_X_KHR = EGLenum::EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_X_KHR;
static const EGLenum EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_X = EGLenum::EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_X;
static const EGLenum EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_X_KHR = EGLenum::EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_X_KHR;
static const EGLenum EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Y = EGLenum::EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Y;
static const EGLenum EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Y_KHR = EGLenum::EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Y_KHR;
static const EGLenum EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y = EGLenum::EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y;
static const EGLenum EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y_KHR = EGLenum::EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y_KHR;
static const EGLenum EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Z = EGLenum::EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Z;
static const EGLenum EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Z_KHR = EGLenum::EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Z_KHR;
static const EGLenum EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z = EGLenum::EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z;
static const EGLenum EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z_KHR = EGLenum::EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z_KHR;
static const EGLenum EGL_GL_RENDERBUFFER = EGLenum::EGL_GL_RENDERBUFFER;
static const EGLenum EGL_GL_RENDERBUFFER_KHR = EGLenum::EGL_GL_RENDERBUFFER_KHR;
static const EGLenum EGL_VG_PARENT_IMAGE_KHR = EGLenum::EGL_VG_PARENT_IMAGE_KHR;
static const EGLenum EGL_GL_TEXTURE_LEVEL = EGLenum::EGL_GL_TEXTURE_LEVEL;
static const EGLenum EGL_GL_TEXTURE_LEVEL_KHR = EGLenum::EGL_GL_TEXTURE_LEVEL_KHR;
static const EGLenum EGL_GL_TEXTURE_ZOFFSET = EGLenum::EGL_GL_TEXTURE_ZOFFSET;
static const EGLenum EGL_GL_TEXTURE_ZOFFSET_KHR = EGLenum::EGL_GL_TEXTURE_ZOFFSET_KHR;
static const EGLenum EGL_POST_SUB_BUFFER_SUPPORTED_NV = EGLenum::EGL_POST_SUB_BUFFER_SUPPORTED_NV;
static const EGLenum EGL_CONTEXT_OPENGL_ROBUST_ACCESS_EXT = EGLenum::EGL_CONTEXT_OPENGL_ROBUST_ACCESS_EXT;
static const EGLenum EGL_FORMAT_RGB_565_EXACT_KHR = EGLenum::EGL_FORMAT_RGB_565_EXACT_KHR;
static const EGLenum EGL_FORMAT_RGB_565_KHR = EGLenum::EGL_FORMAT_RGB_565_KHR;
static const EGLenum EGL_FORMAT_RGBA_8888_EXACT_KHR = EGLenum::EGL_FORMAT_RGBA_8888_EXACT_KHR;
static const EGLenum EGL_FORMAT_RGBA_8888_KHR = EGLenum::EGL_FORMAT_RGBA_8888_KHR;
static const EGLenum EGL_MAP_PRESERVE_PIXELS_KHR = EGLenum::EGL_MAP_PRESERVE_PIXELS_KHR;
static const EGLenum EGL_LOCK_USAGE_HINT_KHR = EGLenum::EGL_LOCK_USAGE_HINT_KHR;
static const EGLenum EGL_BITMAP_POINTER_KHR = EGLenum::EGL_BITMAP_POINTER_KHR;
static const EGLenum EGL_BITMAP_PITCH_KHR = EGLenum::EGL_BITMAP_PITCH_KHR;
static const EGLenum EGL_BITMAP_ORIGIN_KHR = EGLenum::EGL_BITMAP_ORIGIN_KHR;
static const EGLenum EGL_BITMAP_PIXEL_RED_OFFSET_KHR = EGLenum::EGL_BITMAP_PIXEL_RED_OFFSET_KHR;
static const EGLenum EGL_BITMAP_PIXEL_GREEN_OFFSET_KHR = EGLenum::EGL_BITMAP_PIXEL_GREEN_OFFSET_KHR;
static const EGLenum EGL_BITMAP_PIXEL_BLUE_OFFSET_KHR = EGLenum::EGL_BITMAP_PIXEL_BLUE_OFFSET_KHR;
static const EGLenum EGL_BITMAP_PIXEL_ALPHA_OFFSET_KHR = EGLenum::EGL_BITMAP_PIXEL_ALPHA_OFFSET_KHR;
static const EGLenum EGL_BITMAP_PIXEL_LUMINANCE_OFFSET_KHR = EGLenum::EGL_BITMAP_PIXEL_LUMINANCE_OFFSET_KHR;
static const EGLenum EGL_LOWER_LEFT_KHR = EGLenum::EGL_LOWER_LEFT_KHR;
static const EGLenum EGL_UPPER_LEFT_KHR = EGLenum::EGL_UPPER_LEFT_KHR;
static const EGLenum EGL_IMAGE_PRESERVED = EGLenum::EGL_IMAGE_PRESERVED;
static const EGLenum EGL_IMAGE_PRESERVED_KHR = EGLenum::EGL_IMAGE_PRESERVED_KHR;
static const EGLenum EGL_COVERAGE_BUFFERS_NV = EGLenum::EGL_COVERAGE_BUFFERS_NV;
static const EGLenum EGL_COVERAGE_SAMPLES_NV = EGLenum::EGL_COVERAGE_SAMPLES_NV;
static const EGLenum EGL_DEPTH_ENCODING_NV = EGLenum::EGL_DEPTH_ENCODING_NV;
static const EGLenum EGL_DEPTH_ENCODING_NONLINEAR_NV = EGLenum::EGL_DEPTH_ENCODING_NONLINEAR_NV;
static const EGLenum EGL_SYNC_PRIOR_COMMANDS_COMPLETE_NV = EGLenum::EGL_SYNC_PRIOR_COMMANDS_COMPLETE_NV;
static const EGLenum EGL_SYNC_STATUS_NV = EGLenum::EGL_SYNC_STATUS_NV;
static const EGLenum EGL_SIGNALED_NV = EGLenum::EGL_SIGNALED_NV;
static const EGLenum EGL_UNSIGNALED_NV = EGLenum::EGL_UNSIGNALED_NV;
static const EGLenum EGL_ALREADY_SIGNALED_NV = EGLenum::EGL_ALREADY_SIGNALED_NV;
static const EGLenum EGL_TIMEOUT_EXPIRED_NV = EGLenum::EGL_TIMEOUT_EXPIRED_NV;
static const EGLenum EGL_CONDITION_SATISFIED_NV = EGLenum::EGL_CONDITION_SATISFIED_NV;
static const EGLenum EGL_SYNC_TYPE_NV = EGLenum::EGL_SYNC_TYPE_NV;
static const EGLenum EGL_SYNC_CONDITION_NV = EGLenum::EGL_SYNC_CONDITION_NV;
static const EGLenum EGL_SYNC_FENCE_NV = EGLenum::EGL_SYNC_FENCE_NV;
static const EGLenum EGL_SYNC_PRIOR_COMMANDS_COMPLETE = EGLenum::EGL_SYNC_PRIOR_COMMANDS_COMPLETE;
static const EGLenum EGL_SYNC_PRIOR_COMMANDS_COMPLETE_KHR = EGLenum::EGL_SYNC_PRIOR_COMMANDS_COMPLETE_KHR;
static const EGLenum EGL_SYNC_STATUS = EGLenum::EGL_SYNC_STATUS;
static const EGLenum EGL_SYNC_STATUS_KHR = EGLenum::EGL_SYNC_STATUS_KHR;
static const EGLenum EGL_SIGNALED = EGLenum::EGL_SIGNALED;
static const EGLenum EGL_SIGNALED_KHR = EGLenum::EGL_SIGNALED_KHR;
static const EGLenum EGL_UNSIGNALED = EGLenum::EGL_UNSIGNALED;
static const EGLenum EGL_UNSIGNALED_KHR = EGLenum::EGL_UNSIGNALED_KHR;
static const EGLenum EGL_TIMEOUT_EXPIRED = EGLenum::EGL_TIMEOUT_EXPIRED;
static const EGLenum EGL_TIMEOUT_EXPIRED_KHR = EGLenum::EGL_TIMEOUT_EXPIRED_KHR;
static const EGLenum EGL_CONDITION_SATISFIED = EGLenum::EGL_CONDITION_SATISFIED;
static const EGLenum EGL_CONDITION_SATISFIED_KHR = EGLenum::EGL_CONDITION_SATISFIED_KHR;
static const EGLenum EGL_SYNC_TYPE = EGLenum::EGL_SYNC_TYPE;
static const EGLenum EGL_SYNC_TYPE_KHR = EGLenum::EGL_SYNC_TYPE_KHR;
static const EGLenum EGL_SYNC_CONDITION = EGLenum::EGL_SYNC_CONDITION;
static const EGLenum EGL_SYNC_CONDITION_KHR = EGLenum::EGL_SYNC_CONDITION_KHR;
static const EGLenum EGL_SYNC_FENCE = EGLenum::EGL_SYNC_FENCE;
static const EGLenum EGL_SYNC_FENCE_KHR = EGLenum::EGL_SYNC_FENCE_KHR;
static const EGLenum EGL_SYNC_REUSABLE_KHR = EGLenum::EGL_SYNC_REUSABLE_KHR;
static const EGLenum EGL_CONTEXT_MINOR_VERSION = EGLenum::EGL_CONTEXT_MINOR_VERSION;
static const EGLenum EGL_CONTEXT_MINOR_VERSION_KHR = EGLenum::EGL_CONTEXT_MINOR_VERSION_KHR;
static const EGLenum EGL_CONTEXT_FLAGS_KHR = EGLenum::EGL_CONTEXT_FLAGS_KHR;
static const EGLenum EGL_CONTEXT_OPENGL_PROFILE_MASK = EGLenum::EGL_CONTEXT_OPENGL_PROFILE_MASK;
static const EGLenum EGL_CONTEXT_OPENGL_PROFILE_MASK_KHR = EGLenum::EGL_CONTEXT_OPENGL_PROFILE_MASK_KHR;
static const EGLenum EGL_SYNC_CL_EVENT = EGLenum::EGL_SYNC_CL_EVENT;
static const EGLenum EGL_SYNC_CL_EVENT_KHR = EGLenum::EGL_SYNC_CL_EVENT_KHR;
static const EGLenum EGL_SYNC_CL_EVENT_COMPLETE = EGLenum::EGL_SYNC_CL_EVENT_COMPLETE;
static const EGLenum EGL_SYNC_CL_EVENT_COMPLETE_KHR = EGLenum::EGL_SYNC_CL_EVENT_COMPLETE_KHR;
static const EGLenum EGL_CONTEXT_PRIORITY_LEVEL_IMG = EGLenum::EGL_CONTEXT_PRIORITY_LEVEL_IMG;
static const EGLenum EGL_CONTEXT_PRIORITY_HIGH_IMG = EGLenum::EGL_CONTEXT_PRIORITY_HIGH_IMG;
static const EGLenum EGL_CONTEXT_PRIORITY_MEDIUM_IMG = EGLenum::EGL_CONTEXT_PRIORITY_MEDIUM_IMG;
static const EGLenum EGL_CONTEXT_PRIORITY_LOW_IMG = EGLenum::EGL_CONTEXT_PRIORITY_LOW_IMG;
static const EGLenum EGL_BITMAP_PIXEL_SIZE_KHR = EGLenum::EGL_BITMAP_PIXEL_SIZE_KHR;
static const EGLenum EGL_COVERAGE_SAMPLE_RESOLVE_NV = EGLenum::EGL_COVERAGE_SAMPLE_RESOLVE_NV;
static const EGLenum EGL_COVERAGE_SAMPLE_RESOLVE_DEFAULT_NV = EGLenum::EGL_COVERAGE_SAMPLE_RESOLVE_DEFAULT_NV;
static const EGLenum EGL_COVERAGE_SAMPLE_RESOLVE_NONE_NV = EGLenum::EGL_COVERAGE_SAMPLE_RESOLVE_NONE_NV;
static const EGLenum EGL_MULTIVIEW_VIEW_COUNT_EXT = EGLenum::EGL_MULTIVIEW_VIEW_COUNT_EXT;
static const EGLenum EGL_AUTO_STEREO_NV = EGLenum::EGL_AUTO_STEREO_NV;
static const EGLenum EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_EXT = EGLenum::EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_EXT;
static const EGLenum EGL_BUFFER_AGE_EXT = EGLenum::EGL_BUFFER_AGE_EXT;
static const EGLenum EGL_BUFFER_AGE_KHR = EGLenum::EGL_BUFFER_AGE_KHR;
static const EGLenum EGL_PLATFORM_DEVICE_EXT = EGLenum::EGL_PLATFORM_DEVICE_EXT;
static const EGLenum EGL_NATIVE_BUFFER_ANDROID = EGLenum::EGL_NATIVE_BUFFER_ANDROID;
static const EGLenum EGL_PLATFORM_ANDROID_KHR = EGLenum::EGL_PLATFORM_ANDROID_KHR;
static const EGLenum EGL_RECORDABLE_ANDROID = EGLenum::EGL_RECORDABLE_ANDROID;
static const EGLenum EGL_SYNC_NATIVE_FENCE_ANDROID = EGLenum::EGL_SYNC_NATIVE_FENCE_ANDROID;
static const EGLenum EGL_SYNC_NATIVE_FENCE_FD_ANDROID = EGLenum::EGL_SYNC_NATIVE_FENCE_FD_ANDROID;
static const EGLenum EGL_SYNC_NATIVE_FENCE_SIGNALED_ANDROID = EGLenum::EGL_SYNC_NATIVE_FENCE_SIGNALED_ANDROID;
static const EGLenum EGL_FRAMEBUFFER_TARGET_ANDROID = EGLenum::EGL_FRAMEBUFFER_TARGET_ANDROID;
static const EGLenum EGL_CONTEXT_OPENGL_DEBUG = EGLenum::EGL_CONTEXT_OPENGL_DEBUG;
static const EGLenum EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE = EGLenum::EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE;
static const EGLenum EGL_CONTEXT_OPENGL_ROBUST_ACCESS = EGLenum::EGL_CONTEXT_OPENGL_ROBUST_ACCESS;
static const EGLenum EGL_CONTEXT_OPENGL_NO_ERROR_KHR = EGLenum::EGL_CONTEXT_OPENGL_NO_ERROR_KHR;
static const EGLenum EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY = EGLenum::EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY;
static const EGLenum EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_KHR = EGLenum::EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_KHR;
static const EGLenum EGL_NO_RESET_NOTIFICATION = EGLenum::EGL_NO_RESET_NOTIFICATION;
static const EGLenum EGL_NO_RESET_NOTIFICATION_EXT = EGLenum::EGL_NO_RESET_NOTIFICATION_EXT;
static const EGLenum EGL_NO_RESET_NOTIFICATION_KHR = EGLenum::EGL_NO_RESET_NOTIFICATION_KHR;
static const EGLenum EGL_LOSE_CONTEXT_ON_RESET = EGLenum::EGL_LOSE_CONTEXT_ON_RESET;
static const EGLenum EGL_LOSE_CONTEXT_ON_RESET_EXT = EGLenum::EGL_LOSE_CONTEXT_ON_RESET_EXT;
static const EGLenum EGL_LOSE_CONTEXT_ON_RESET_KHR = EGLenum::EGL_LOSE_CONTEXT_ON_RESET_KHR;
static const EGLenum EGL_DRM_BUFFER_FORMAT_MESA = EGLenum::EGL_DRM_BUFFER_FORMAT_MESA;
static const EGLenum EGL_DRM_BUFFER_USE_MESA = EGLenum::EGL_DRM_BUFFER_USE_MESA;
static const EGLenum EGL_DRM_BUFFER_FORMAT_ARGB32_MESA = EGLenum::EGL_DRM_BUFFER_FORMAT_ARGB32_MESA;
static const EGLenum EGL_DRM_BUFFER_MESA = EGLenum::EGL_DRM_BUFFER_MESA;
static const EGLenum EGL_DRM_BUFFER_STRIDE_MESA = EGLenum::EGL_DRM_BUFFER_STRIDE_MESA;
static const EGLenum EGL_PLATFORM_X11_EXT = EGLenum::EGL_PLATFORM_X11_EXT;
static const EGLenum EGL_PLATFORM_X11_KHR = EGLenum::EGL_PLATFORM_X11_KHR;
static const EGLenum EGL_PLATFORM_X11_SCREEN_EXT = EGLenum::EGL_PLATFORM_X11_SCREEN_EXT;
static const EGLenum EGL_PLATFORM_X11_SCREEN_KHR = EGLenum::EGL_PLATFORM_X11_SCREEN_KHR;
static const EGLenum EGL_PLATFORM_GBM_KHR = EGLenum::EGL_PLATFORM_GBM_KHR;
static const EGLenum EGL_PLATFORM_GBM_MESA = EGLenum::EGL_PLATFORM_GBM_MESA;
static const EGLenum EGL_PLATFORM_WAYLAND_EXT = EGLenum::EGL_PLATFORM_WAYLAND_EXT;
static const EGLenum EGL_PLATFORM_WAYLAND_KHR = EGLenum::EGL_PLATFORM_WAYLAND_KHR;
static const EGLenum EGL_STREAM_FIFO_LENGTH_KHR = EGLenum::EGL_STREAM_FIFO_LENGTH_KHR;
static const EGLenum EGL_STREAM_TIME_NOW_KHR = EGLenum::EGL_STREAM_TIME_NOW_KHR;
static const EGLenum EGL_STREAM_TIME_CONSUMER_KHR = EGLenum::EGL_STREAM_TIME_CONSUMER_KHR;
static const EGLenum EGL_STREAM_TIME_PRODUCER_KHR = EGLenum::EGL_STREAM_TIME_PRODUCER_KHR;
static const EGLenum EGL_D3D_TEXTURE_2D_SHARE_HANDLE_ANGLE = EGLenum::EGL_D3D_TEXTURE_2D_SHARE_HANDLE_ANGLE;
static const EGLenum EGL_FIXED_SIZE_ANGLE = EGLenum::EGL_FIXED_SIZE_ANGLE;
static const EGLenum EGL_CONSUMER_LATENCY_USEC_KHR = EGLenum::EGL_CONSUMER_LATENCY_USEC_KHR;
static const EGLenum EGL_PRODUCER_FRAME_KHR = EGLenum::EGL_PRODUCER_FRAME_KHR;
static const EGLenum EGL_CONSUMER_FRAME_KHR = EGLenum::EGL_CONSUMER_FRAME_KHR;
static const EGLenum EGL_STREAM_STATE_KHR = EGLenum::EGL_STREAM_STATE_KHR;
static const EGLenum EGL_STREAM_STATE_CREATED_KHR = EGLenum::EGL_STREAM_STATE_CREATED_KHR;
static const EGLenum EGL_STREAM_STATE_CONNECTING_KHR = EGLenum::EGL_STREAM_STATE_CONNECTING_KHR;
static const EGLenum EGL_STREAM_STATE_EMPTY_KHR = EGLenum::EGL_STREAM_STATE_EMPTY_KHR;
static const EGLenum EGL_STREAM_STATE_NEW_FRAME_AVAILABLE_KHR = EGLenum::EGL_STREAM_STATE_NEW_FRAME_AVAILABLE_KHR;
static const EGLenum EGL_STREAM_STATE_OLD_FRAME_AVAILABLE_KHR = EGLenum::EGL_STREAM_STATE_OLD_FRAME_AVAILABLE_KHR;
static const EGLenum EGL_STREAM_STATE_DISCONNECTED_KHR = EGLenum::EGL_STREAM_STATE_DISCONNECTED_KHR;
static const EGLenum EGL_BAD_STREAM_KHR = EGLenum::EGL_BAD_STREAM_KHR;
static const EGLenum EGL_BAD_STATE_KHR = EGLenum::EGL_BAD_STATE_KHR;
static const EGLenum EGL_CONSUMER_ACQUIRE_TIMEOUT_USEC_KHR = EGLenum::EGL_CONSUMER_ACQUIRE_TIMEOUT_USEC_KHR;
static const EGLenum EGL_SYNC_NEW_FRAME_NV = EGLenum::EGL_SYNC_NEW_FRAME_NV;
static const EGLenum EGL_BAD_DEVICE_EXT = EGLenum::EGL_BAD_DEVICE_EXT;
static const EGLenum EGL_DEVICE_EXT = EGLenum::EGL_DEVICE_EXT;
static const EGLenum EGL_BAD_OUTPUT_LAYER_EXT = EGLenum::EGL_BAD_OUTPUT_LAYER_EXT;
static const EGLenum EGL_BAD_OUTPUT_PORT_EXT = EGLenum::EGL_BAD_OUTPUT_PORT_EXT;
static const EGLenum EGL_SWAP_INTERVAL_EXT = EGLenum::EGL_SWAP_INTERVAL_EXT;
static const EGLenum EGL_DRM_DEVICE_FILE_EXT = EGLenum::EGL_DRM_DEVICE_FILE_EXT;
static const EGLenum EGL_DRM_CRTC_EXT = EGLenum::EGL_DRM_CRTC_EXT;
static const EGLenum EGL_DRM_PLANE_EXT = EGLenum::EGL_DRM_PLANE_EXT;
static const EGLenum EGL_DRM_CONNECTOR_EXT = EGLenum::EGL_DRM_CONNECTOR_EXT;
static const EGLenum EGL_OPENWF_DEVICE_ID_EXT = EGLenum::EGL_OPENWF_DEVICE_ID_EXT;
static const EGLenum EGL_OPENWF_PIPELINE_ID_EXT = EGLenum::EGL_OPENWF_PIPELINE_ID_EXT;
static const EGLenum EGL_OPENWF_PORT_ID_EXT = EGLenum::EGL_OPENWF_PORT_ID_EXT;
static const EGLenum EGL_CUDA_DEVICE_NV = EGLenum::EGL_CUDA_DEVICE_NV;
static const EGLenum EGL_CUDA_EVENT_HANDLE_NV = EGLenum::EGL_CUDA_EVENT_HANDLE_NV;
static const EGLenum EGL_SYNC_CUDA_EVENT_NV = EGLenum::EGL_SYNC_CUDA_EVENT_NV;
static const EGLenum EGL_SYNC_CUDA_EVENT_COMPLETE_NV = EGLenum::EGL_SYNC_CUDA_EVENT_COMPLETE_NV;
static const EGLenum EGL_LINUX_DMA_BUF_EXT = EGLenum::EGL_LINUX_DMA_BUF_EXT;
static const EGLenum EGL_LINUX_DRM_FOURCC_EXT = EGLenum::EGL_LINUX_DRM_FOURCC_EXT;
static const EGLenum EGL_DMA_BUF_PLANE0_FD_EXT = EGLenum::EGL_DMA_BUF_PLANE0_FD_EXT;
static const EGLenum EGL_DMA_BUF_PLANE0_OFFSET_EXT = EGLenum::EGL_DMA_BUF_PLANE0_OFFSET_EXT;
static const EGLenum EGL_DMA_BUF_PLANE0_PITCH_EXT = EGLenum::EGL_DMA_BUF_PLANE0_PITCH_EXT;
static const EGLenum EGL_DMA_BUF_PLANE1_FD_EXT = EGLenum::EGL_DMA_BUF_PLANE1_FD_EXT;
static const EGLenum EGL_DMA_BUF_PLANE1_OFFSET_EXT = EGLenum::EGL_DMA_BUF_PLANE1_OFFSET_EXT;
static const EGLenum EGL_DMA_BUF_PLANE1_PITCH_EXT = EGLenum::EGL_DMA_BUF_PLANE1_PITCH_EXT;
static const EGLenum EGL_DMA_BUF_PLANE2_FD_EXT = EGLenum::EGL_DMA_BUF_PLANE2_FD_EXT;
static const EGLenum EGL_DMA_BUF_PLANE2_OFFSET_EXT = EGLenum::EGL_DMA_BUF_PLANE2_OFFSET_EXT;
static const EGLenum EGL_DMA_BUF_PLANE2_PITCH_EXT = EGLenum::EGL_DMA_BUF_PLANE2_PITCH_EXT;
static const EGLenum EGL_YUV_COLOR_SPACE_HINT_EXT = EGLenum::EGL_YUV_COLOR_SPACE_HINT_EXT;
static const EGLenum EGL_SAMPLE_RANGE_HINT_EXT = EGLenum::EGL_SAMPLE_RANGE_HINT_EXT;
static const EGLenum EGL_YUV_CHROMA_HORIZONTAL_SITING_HINT_EXT = EGLenum::EGL_YUV_CHROMA_HORIZONTAL_SITING_HINT_EXT;
static const EGLenum EGL_YUV_CHROMA_VERTICAL_SITING_HINT_EXT = EGLenum::EGL_YUV_CHROMA_VERTICAL_SITING_HINT_EXT;
static const EGLenum EGL_ITU_REC601_EXT = EGLenum::EGL_ITU_REC601_EXT;
static const EGLenum EGL_ITU_REC709_EXT = EGLenum::EGL_ITU_REC709_EXT;
static const EGLenum EGL_ITU_REC2020_EXT = EGLenum::EGL_ITU_REC2020_EXT;
static const EGLenum EGL_YUV_FULL_RANGE_EXT = EGLenum::EGL_YUV_FULL_RANGE_EXT;
static const EGLenum EGL_YUV_NARROW_RANGE_EXT = EGLenum::EGL_YUV_NARROW_RANGE_EXT;
static const EGLenum EGL_YUV_CHROMA_SITING_0_EXT = EGLenum::EGL_YUV_CHROMA_SITING_0_EXT;
static const EGLenum EGL_YUV_CHROMA_SITING_0_5_EXT = EGLenum::EGL_YUV_CHROMA_SITING_0_5_EXT;
static const EGLenum EGL_DISCARD_SAMPLES_ARM = EGLenum::EGL_DISCARD_SAMPLES_ARM;
static const EGLenum EGL_NATIVE_BUFFER_TIZEN = EGLenum::EGL_NATIVE_BUFFER_TIZEN;
static const EGLenum EGL_NATIVE_SURFACE_TIZEN = EGLenum::EGL_NATIVE_SURFACE_TIZEN;
static const EGLenum EGL_PROTECTED_CONTENT_EXT = EGLenum::EGL_PROTECTED_CONTENT_EXT;
static const EGLenum EGL_YUV_BUFFER_EXT = EGLenum::EGL_YUV_BUFFER_EXT;
static const EGLenum EGL_YUV_ORDER_EXT = EGLenum::EGL_YUV_ORDER_EXT;
static const EGLenum EGL_YUV_ORDER_YUV_EXT = EGLenum::EGL_YUV_ORDER_YUV_EXT;
static const EGLenum EGL_YUV_ORDER_YVU_EXT = EGLenum::EGL_YUV_ORDER_YVU_EXT;
static const EGLenum EGL_YUV_ORDER_YUYV_EXT = EGLenum::EGL_YUV_ORDER_YUYV_EXT;
static const EGLenum EGL_YUV_ORDER_UYVY_EXT = EGLenum::EGL_YUV_ORDER_UYVY_EXT;
static const EGLenum EGL_YUV_ORDER_YVYU_EXT = EGLenum::EGL_YUV_ORDER_YVYU_EXT;
static const EGLenum EGL_YUV_ORDER_VYUY_EXT = EGLenum::EGL_YUV_ORDER_VYUY_EXT;
static const EGLenum EGL_YUV_ORDER_AYUV_EXT = EGLenum::EGL_YUV_ORDER_AYUV_EXT;
static const EGLenum EGL_YUV_CSC_STANDARD_EXT = EGLenum::EGL_YUV_CSC_STANDARD_EXT;
static const EGLenum EGL_YUV_CSC_STANDARD_601_EXT = EGLenum::EGL_YUV_CSC_STANDARD_601_EXT;
static const EGLenum EGL_YUV_CSC_STANDARD_709_EXT = EGLenum::EGL_YUV_CSC_STANDARD_709_EXT;
static const EGLenum EGL_YUV_CSC_STANDARD_2020_EXT = EGLenum::EGL_YUV_CSC_STANDARD_2020_EXT;
static const EGLenum EGL_YUV_NUMBER_OF_PLANES_EXT = EGLenum::EGL_YUV_NUMBER_OF_PLANES_EXT;
static const EGLenum EGL_YUV_SUBSAMPLE_EXT = EGLenum::EGL_YUV_SUBSAMPLE_EXT;
static const EGLenum EGL_YUV_SUBSAMPLE_4_2_0_EXT = EGLenum::EGL_YUV_SUBSAMPLE_4_2_0_EXT;
static const EGLenum EGL_YUV_SUBSAMPLE_4_2_2_EXT = EGLenum::EGL_YUV_SUBSAMPLE_4_2_2_EXT;
static const EGLenum EGL_YUV_SUBSAMPLE_4_4_4_EXT = EGLenum::EGL_YUV_SUBSAMPLE_4_4_4_EXT;
static const EGLenum EGL_YUV_DEPTH_RANGE_EXT = EGLenum::EGL_YUV_DEPTH_RANGE_EXT;
static const EGLenum EGL_YUV_DEPTH_RANGE_LIMITED_EXT = EGLenum::EGL_YUV_DEPTH_RANGE_LIMITED_EXT;
static const EGLenum EGL_YUV_DEPTH_RANGE_FULL_EXT = EGLenum::EGL_YUV_DEPTH_RANGE_FULL_EXT;
static const EGLenum EGL_YUV_PLANE_BPP_EXT = EGLenum::EGL_YUV_PLANE_BPP_EXT;
static const EGLenum EGL_YUV_PLANE_BPP_0_EXT = EGLenum::EGL_YUV_PLANE_BPP_0_EXT;
static const EGLenum EGL_YUV_PLANE_BPP_8_EXT = EGLenum::EGL_YUV_PLANE_BPP_8_EXT;
static const EGLenum EGL_YUV_PLANE_BPP_10_EXT = EGLenum::EGL_YUV_PLANE_BPP_10_EXT;
static const EGLenum EGL_D3D9_DEVICE_ANGLE = EGLenum::EGL_D3D9_DEVICE_ANGLE;
static const EGLenum EGL_D3D11_DEVICE_ANGLE = EGLenum::EGL_D3D11_DEVICE_ANGLE;
static const EGLenum EGL_COLOR_FORMAT_HI = EGLenum::EGL_COLOR_FORMAT_HI;
static const EGLenum EGL_COLOR_RGB_HI = EGLenum::EGL_COLOR_RGB_HI;
static const EGLenum EGL_COLOR_RGBA_HI = EGLenum::EGL_COLOR_RGBA_HI;
static const EGLenum EGL_COLOR_ARGB_HI = EGLenum::EGL_COLOR_ARGB_HI;
static const EGLenum EGL_CLIENT_PIXMAP_POINTER_HI = EGLenum::EGL_CLIENT_PIXMAP_POINTER_HI;
static const EGLenum EGL_DISPLAY_SCALING = EGLenum::EGL_DISPLAY_SCALING;

} // namespace egl
