
#include "Binding_pch.h"


using namespace gles;


namespace glesbinding
{


Function<Binding, void, GLsizei, GLuint *> Binding::GenBuffers("glGenBuffers");
Function<Binding, void, GLsizei, GLuint *> Binding::GenFencesNV("glGenFencesNV");
Function<Binding, void, GLsizei, GLuint *> Binding::GenFramebuffers("glGenFramebuffers");
Function<Binding, GLuint, GLsizei> Binding::GenPathsNV("glGenPathsNV");
Function<Binding, void, GLsizei, GLuint *> Binding::GenPerfMonitorsAMD("glGenPerfMonitorsAMD");
Function<Binding, void, GLsizei, GLuint *> Binding::GenProgramPipelines("glGenProgramPipelines");
Function<Binding, void, GLsizei, GLuint *> Binding::GenQueries("glGenQueries");
Function<Binding, void, GLsizei, GLuint *> Binding::GenQueriesEXT("glGenQueriesEXT");
Function<Binding, void, GLsizei, GLuint *> Binding::GenRenderbuffers("glGenRenderbuffers");
Function<Binding, void, GLsizei, GLuint *> Binding::GenSamplers("glGenSamplers");
Function<Binding, void, GLsizei, GLuint *> Binding::GenSemaphoresEXT("glGenSemaphoresEXT");
Function<Binding, void, GLsizei, GLuint *> Binding::GenTextures("glGenTextures");
Function<Binding, void, GLsizei, GLuint *> Binding::GenTransformFeedbacks("glGenTransformFeedbacks");
Function<Binding, void, GLsizei, GLuint *> Binding::GenVertexArrays("glGenVertexArrays");
Function<Binding, void, GLsizei, GLuint *> Binding::GenVertexArraysOES("glGenVertexArraysOES");
Function<Binding, void, GLenum> Binding::GenerateMipmap("glGenerateMipmap");
Function<Binding, void, GLuint, GLuint, GLsizei, GLsizei *, GLint *, GLenum *, GLchar *> Binding::GetActiveAttrib("glGetActiveAttrib");
Function<Binding, void, GLuint, GLuint, GLsizei, GLsizei *, GLint *, GLenum *, GLchar *> Binding::GetActiveUniform("glGetActiveUniform");
Function<Binding, void, GLuint, GLuint, GLsizei, GLsizei *, GLchar *> Binding::GetActiveUniformBlockName("glGetActiveUniformBlockName");
Function<Binding, void, GLuint, GLuint, GLenum, GLint *> Binding::GetActiveUniformBlockiv("glGetActiveUniformBlockiv");
Function<Binding, void, GLuint, GLsizei, const GLuint *, GLenum, GLint *> Binding::GetActiveUniformsiv("glGetActiveUniformsiv");
Function<Binding, void, GLuint, GLsizei, GLsizei *, GLuint *> Binding::GetAttachedShaders("glGetAttachedShaders");
Function<Binding, GLint, GLuint, const GLchar *> Binding::GetAttribLocation("glGetAttribLocation");
Function<Binding, void, GLenum, GLuint, GLboolean *> Binding::GetBooleani_v("glGetBooleani_v");
Function<Binding, void, GLenum, GLboolean *> Binding::GetBooleanv("glGetBooleanv");
Function<Binding, void, GLenum, GLenum, GLint64 *> Binding::GetBufferParameteri64v("glGetBufferParameteri64v");
Function<Binding, void, GLenum, GLenum, GLint *> Binding::GetBufferParameteriv("glGetBufferParameteriv");
Function<Binding, void, GLenum, GLenum, void **> Binding::GetBufferPointerv("glGetBufferPointerv");
Function<Binding, void, GLenum, GLenum, void **> Binding::GetBufferPointervOES("glGetBufferPointervOES");
Function<Binding, void, GLsizei, GLfloat *> Binding::GetCoverageModulationTableNV("glGetCoverageModulationTableNV");
Function<Binding, GLuint, GLuint, GLsizei, GLenum *, GLenum *, GLuint *, GLenum *, GLsizei *, GLchar *> Binding::GetDebugMessageLog("glGetDebugMessageLog");
Function<Binding, void, GLuint, GLsizei, GLsizei *, GLchar *> Binding::GetDriverControlStringQCOM("glGetDriverControlStringQCOM");
Function<Binding, void, GLint *, GLsizei, GLuint *> Binding::GetDriverControlsQCOM("glGetDriverControlsQCOM");
Function<Binding, GLenum> Binding::GetError("glGetError");
Function<Binding, void, GLuint, GLenum, GLint *> Binding::GetFenceivNV("glGetFenceivNV");
Function<Binding, void, GLuint *> Binding::GetFirstPerfQueryIdINTEL("glGetFirstPerfQueryIdINTEL");
Function<Binding, void, GLenum, GLuint, GLfloat *> Binding::GetFloati_vNV("glGetFloati_vNV");
Function<Binding, void, GLenum, GLuint, GLfloat *> Binding::GetFloati_vOES("glGetFloati_vOES");
Function<Binding, void, GLenum, GLfloat *> Binding::GetFloatv("glGetFloatv");
Function<Binding, GLint, GLuint, const GLchar *> Binding::GetFragDataIndexEXT("glGetFragDataIndexEXT");
Function<Binding, GLint, GLuint, const GLchar *> Binding::GetFragDataLocation("glGetFragDataLocation");
Function<Binding, void, GLenum, GLenum, GLenum, GLint *> Binding::GetFramebufferAttachmentParameteriv("glGetFramebufferAttachmentParameteriv");
Function<Binding, void, GLenum, GLenum, GLint *> Binding::GetFramebufferParameteriv("glGetFramebufferParameteriv");
Function<Binding, GLsizei, GLuint> Binding::GetFramebufferPixelLocalStorageSizeEXT("glGetFramebufferPixelLocalStorageSizeEXT");
Function<Binding, GLenum> Binding::GetGraphicsResetStatus("glGetGraphicsResetStatus");
Function<Binding, GLenum> Binding::GetGraphicsResetStatusEXT("glGetGraphicsResetStatusEXT");
Function<Binding, GLuint64, GLuint, GLint, GLboolean, GLint, GLenum> Binding::GetImageHandleNV("glGetImageHandleNV");
Function<Binding, void, GLenum, GLuint, GLint64 *> Binding::GetInteger64i_v("glGetInteger64i_v");
Function<Binding, void, GLenum, GLint64 *> Binding::GetInteger64v("glGetInteger64v");
Function<Binding, void, GLenum, GLint64 *> Binding::GetInteger64vAPPLE("glGetInteger64vAPPLE");
Function<Binding, void, GLenum, GLuint, GLint *> Binding::GetIntegeri_v("glGetIntegeri_v");
Function<Binding, void, GLenum, GLuint, GLint *> Binding::GetIntegeri_vEXT("glGetIntegeri_vEXT");
Function<Binding, void, GLenum, GLint *> Binding::GetIntegerv("glGetIntegerv");
Function<Binding, void, GLenum, GLenum, GLsizei, GLenum, GLsizei, GLint *> Binding::GetInternalformatSampleivNV("glGetInternalformatSampleivNV");
Function<Binding, void, GLenum, GLenum, GLenum, GLsizei, GLint *> Binding::GetInternalformativ("glGetInternalformativ");
Function<Binding, void, GLuint, GLenum, GLint *> Binding::GetMemoryObjectParameterivEXT("glGetMemoryObjectParameterivEXT");
Function<Binding, void, GLenum, GLuint, GLfloat *> Binding::GetMultisamplefv("glGetMultisamplefv");
Function<Binding, void, GLuint, GLuint *> Binding::GetNextPerfQueryIdINTEL("glGetNextPerfQueryIdINTEL");
Function<Binding, void, GLenum, GLuint, GLsizei, GLsizei *, GLchar *> Binding::GetObjectLabel("glGetObjectLabel");
Function<Binding, void, GLenum, GLuint, GLsizei, GLsizei *, GLchar *> Binding::GetObjectLabelEXT("glGetObjectLabelEXT");
Function<Binding, void, const void *, GLsizei, GLsizei *, GLchar *> Binding::GetObjectPtrLabel("glGetObjectPtrLabel");
Function<Binding, void, GLuint, GLubyte *> Binding::GetPathCommandsNV("glGetPathCommandsNV");
Function<Binding, void, GLuint, GLfloat *> Binding::GetPathCoordsNV("glGetPathCoordsNV");
Function<Binding, void, GLuint, GLfloat *> Binding::GetPathDashArrayNV("glGetPathDashArrayNV");
Function<Binding, GLfloat, GLuint, GLsizei, GLsizei> Binding::GetPathLengthNV("glGetPathLengthNV");
Function<Binding, void, PathRenderingMaskNV, GLuint, GLsizei, GLsizei, GLfloat *> Binding::GetPathMetricRangeNV("glGetPathMetricRangeNV");
Function<Binding, void, PathRenderingMaskNV, GLsizei, GLenum, const void *, GLuint, GLsizei, GLfloat *> Binding::GetPathMetricsNV("glGetPathMetricsNV");
Function<Binding, void, GLuint, GLenum, GLfloat *> Binding::GetPathParameterfvNV("glGetPathParameterfvNV");
Function<Binding, void, GLuint, GLenum, GLint *> Binding::GetPathParameterivNV("glGetPathParameterivNV");
Function<Binding, void, GLenum, GLsizei, GLenum, const void *, GLuint, GLfloat, GLfloat, GLenum, GLfloat *> Binding::GetPathSpacingNV("glGetPathSpacingNV");
Function<Binding, void, GLuint, GLuint, GLuint, GLchar *, GLuint, GLchar *, GLuint *, GLuint *, GLuint *, GLuint *, GLuint64 *> Binding::GetPerfCounterInfoINTEL("glGetPerfCounterInfoINTEL");
Function<Binding, void, GLuint, GLenum, GLsizei, GLuint *, GLint *> Binding::GetPerfMonitorCounterDataAMD("glGetPerfMonitorCounterDataAMD");
Function<Binding, void, GLuint, GLuint, GLenum, void *> Binding::GetPerfMonitorCounterInfoAMD("glGetPerfMonitorCounterInfoAMD");
Function<Binding, void, GLuint, GLuint, GLsizei, GLsizei *, GLchar *> Binding::GetPerfMonitorCounterStringAMD("glGetPerfMonitorCounterStringAMD");
Function<Binding, void, GLuint, GLint *, GLint *, GLsizei, GLuint *> Binding::GetPerfMonitorCountersAMD("glGetPerfMonitorCountersAMD");
Function<Binding, void, GLuint, GLsizei, GLsizei *, GLchar *> Binding::GetPerfMonitorGroupStringAMD("glGetPerfMonitorGroupStringAMD");
Function<Binding, void, GLint *, GLsizei, GLuint *> Binding::GetPerfMonitorGroupsAMD("glGetPerfMonitorGroupsAMD");
Function<Binding, void, GLuint, GLuint, GLsizei, void *, GLuint *> Binding::GetPerfQueryDataINTEL("glGetPerfQueryDataINTEL");
Function<Binding, void, GLchar *, GLuint *> Binding::GetPerfQueryIdByNameINTEL("glGetPerfQueryIdByNameINTEL");
Function<Binding, void, GLuint, GLuint, GLchar *, GLuint *, GLuint *, GLuint *, GLuint *> Binding::GetPerfQueryInfoINTEL("glGetPerfQueryInfoINTEL");
Function<Binding, void, GLenum, void **> Binding::GetPointerv("glGetPointerv");
Function<Binding, void, GLuint, GLsizei, GLsizei *, GLenum *, void *> Binding::GetProgramBinary("glGetProgramBinary");
Function<Binding, void, GLuint, GLsizei, GLsizei *, GLenum *, void *> Binding::GetProgramBinaryOES("glGetProgramBinaryOES");
Function<Binding, void, GLuint, GLsizei, GLsizei *, GLchar *> Binding::GetProgramInfoLog("glGetProgramInfoLog");
Function<Binding, void, GLuint, GLenum, GLenum, GLint *> Binding::GetProgramInterfaceiv("glGetProgramInterfaceiv");
Function<Binding, void, GLuint, GLsizei, GLsizei *, GLchar *> Binding::GetProgramPipelineInfoLog("glGetProgramPipelineInfoLog");
Function<Binding, void, GLuint, GLenum, GLint *> Binding::GetProgramPipelineiv("glGetProgramPipelineiv");
Function<Binding, GLuint, GLuint, GLenum, const GLchar *> Binding::GetProgramResourceIndex("glGetProgramResourceIndex");
Function<Binding, GLint, GLuint, GLenum, const GLchar *> Binding::GetProgramResourceLocation("glGetProgramResourceLocation");
Function<Binding, GLint, GLuint, GLenum, const GLchar *> Binding::GetProgramResourceLocationIndexEXT("glGetProgramResourceLocationIndexEXT");
Function<Binding, void, GLuint, GLenum, GLuint, GLsizei, GLsizei *, GLchar *> Binding::GetProgramResourceName("glGetProgramResourceName");
Function<Binding, void, GLuint, GLenum, GLuint, GLsizei, const GLenum *, GLsizei, GLsizei *, GLfloat *> Binding::GetProgramResourcefvNV("glGetProgramResourcefvNV");
Function<Binding, void, GLuint, GLenum, GLuint, GLsizei, const GLenum *, GLsizei, GLsizei *, GLint *> Binding::GetProgramResourceiv("glGetProgramResourceiv");
Function<Binding, void, GLuint, GLenum, GLint *> Binding::GetProgramiv("glGetProgramiv");
Function<Binding, void, GLuint, GLenum, GLint64 *> Binding::GetQueryObjecti64vEXT("glGetQueryObjecti64vEXT");
Function<Binding, void, GLuint, GLenum, GLint *> Binding::GetQueryObjectivEXT("glGetQueryObjectivEXT");
Function<Binding, void, GLuint, GLenum, GLuint64 *> Binding::GetQueryObjectui64vEXT("glGetQueryObjectui64vEXT");
Function<Binding, void, GLuint, GLenum, GLuint *> Binding::GetQueryObjectuiv("glGetQueryObjectuiv");
Function<Binding, void, GLuint, GLenum, GLuint *> Binding::GetQueryObjectuivEXT("glGetQueryObjectuivEXT");
Function<Binding, void, GLenum, GLenum, GLint *> Binding::GetQueryiv("glGetQueryiv");
Function<Binding, void, GLenum, GLenum, GLint *> Binding::GetQueryivEXT("glGetQueryivEXT");
Function<Binding, void, GLenum, GLenum, GLint *> Binding::GetRenderbufferParameteriv("glGetRenderbufferParameteriv");
Function<Binding, void, GLuint, GLenum, GLint *> Binding::GetSamplerParameterIiv("glGetSamplerParameterIiv");
Function<Binding, void, GLuint, GLenum, GLint *> Binding::GetSamplerParameterIivEXT("glGetSamplerParameterIivEXT");
Function<Binding, void, GLuint, GLenum, GLint *> Binding::GetSamplerParameterIivOES("glGetSamplerParameterIivOES");
Function<Binding, void, GLuint, GLenum, GLuint *> Binding::GetSamplerParameterIuiv("glGetSamplerParameterIuiv");
Function<Binding, void, GLuint, GLenum, GLuint *> Binding::GetSamplerParameterIuivEXT("glGetSamplerParameterIuivEXT");
Function<Binding, void, GLuint, GLenum, GLuint *> Binding::GetSamplerParameterIuivOES("glGetSamplerParameterIuivOES");
Function<Binding, void, GLuint, GLenum, GLfloat *> Binding::GetSamplerParameterfv("glGetSamplerParameterfv");
Function<Binding, void, GLuint, GLenum, GLint *> Binding::GetSamplerParameteriv("glGetSamplerParameteriv");
Function<Binding, void, GLuint, GLenum, GLuint64 *> Binding::GetSemaphoreParameterui64vEXT("glGetSemaphoreParameterui64vEXT");
Function<Binding, void, GLuint, GLsizei, GLsizei *, GLchar *> Binding::GetShaderInfoLog("glGetShaderInfoLog");
Function<Binding, void, GLenum, GLenum, GLint *, GLint *> Binding::GetShaderPrecisionFormat("glGetShaderPrecisionFormat");
Function<Binding, void, GLuint, GLsizei, GLsizei *, GLchar *> Binding::GetShaderSource("glGetShaderSource");
Function<Binding, void, GLuint, GLenum, GLint *> Binding::GetShaderiv("glGetShaderiv");
Function<Binding, const GLubyte *, GLenum> Binding::GetString("glGetString");
Function<Binding, const GLubyte *, GLenum, GLuint> Binding::GetStringi("glGetStringi");
Function<Binding, void, GLsync, GLenum, GLsizei, GLsizei *, GLint *> Binding::GetSynciv("glGetSynciv");
Function<Binding, void, GLsync, GLenum, GLsizei, GLsizei *, GLint *> Binding::GetSyncivAPPLE("glGetSyncivAPPLE");
Function<Binding, void, GLenum, GLint, GLenum, GLfloat *> Binding::GetTexLevelParameterfv("glGetTexLevelParameterfv");
Function<Binding, void, GLenum, GLint, GLenum, GLint *> Binding::GetTexLevelParameteriv("glGetTexLevelParameteriv");
Function<Binding, void, GLenum, GLenum, GLint *> Binding::GetTexParameterIiv("glGetTexParameterIiv");
Function<Binding, void, GLenum, GLenum, GLint *> Binding::GetTexParameterIivEXT("glGetTexParameterIivEXT");
Function<Binding, void, GLenum, GLenum, GLint *> Binding::GetTexParameterIivOES("glGetTexParameterIivOES");
Function<Binding, void, GLenum, GLenum, GLuint *> Binding::GetTexParameterIuiv("glGetTexParameterIuiv");
Function<Binding, void, GLenum, GLenum, GLuint *> Binding::GetTexParameterIuivEXT("glGetTexParameterIuivEXT");
Function<Binding, void, GLenum, GLenum, GLuint *> Binding::GetTexParameterIuivOES("glGetTexParameterIuivOES");
Function<Binding, void, GLenum, GLenum, GLfloat *> Binding::GetTexParameterfv("glGetTexParameterfv");
Function<Binding, void, GLenum, GLenum, GLint *> Binding::GetTexParameteriv("glGetTexParameteriv");
Function<Binding, GLuint64, GLuint> Binding::GetTextureHandleIMG("glGetTextureHandleIMG");
Function<Binding, GLuint64, GLuint> Binding::GetTextureHandleNV("glGetTextureHandleNV");
Function<Binding, GLuint64, GLuint, GLuint> Binding::GetTextureSamplerHandleIMG("glGetTextureSamplerHandleIMG");
Function<Binding, GLuint64, GLuint, GLuint> Binding::GetTextureSamplerHandleNV("glGetTextureSamplerHandleNV");
Function<Binding, void, GLuint, GLuint, GLsizei, GLsizei *, GLsizei *, GLenum *, GLchar *> Binding::GetTransformFeedbackVarying("glGetTransformFeedbackVarying");
Function<Binding, void, GLuint, GLsizei, GLsizei *, GLchar *> Binding::GetTranslatedShaderSourceANGLE("glGetTranslatedShaderSourceANGLE");
Function<Binding, GLuint, GLuint, const GLchar *> Binding::GetUniformBlockIndex("glGetUniformBlockIndex");
Function<Binding, void, GLuint, GLsizei, const GLchar *const*, GLuint *> Binding::GetUniformIndices("glGetUniformIndices");
Function<Binding, GLint, GLuint, const GLchar *> Binding::GetUniformLocation("glGetUniformLocation");
Function<Binding, void, GLuint, GLint, GLfloat *> Binding::GetUniformfv("glGetUniformfv");
Function<Binding, void, GLuint, GLint, GLint64EXT *> Binding::GetUniformi64vNV("glGetUniformi64vNV");
Function<Binding, void, GLuint, GLint, GLint *> Binding::GetUniformiv("glGetUniformiv");
Function<Binding, void, GLuint, GLint, GLuint *> Binding::GetUniformuiv("glGetUniformuiv");
Function<Binding, void, GLenum, GLuint, GLubyte *> Binding::GetUnsignedBytei_vEXT("glGetUnsignedBytei_vEXT");
Function<Binding, void, GLenum, GLubyte *> Binding::GetUnsignedBytevEXT("glGetUnsignedBytevEXT");
Function<Binding, void, GLuint, GLenum, GLint *> Binding::GetVertexAttribIiv("glGetVertexAttribIiv");
Function<Binding, void, GLuint, GLenum, GLuint *> Binding::GetVertexAttribIuiv("glGetVertexAttribIuiv");
Function<Binding, void, GLuint, GLenum, void **> Binding::GetVertexAttribPointerv("glGetVertexAttribPointerv");
Function<Binding, void, GLuint, GLenum, GLfloat *> Binding::GetVertexAttribfv("glGetVertexAttribfv");
Function<Binding, void, GLuint, GLenum, GLint *> Binding::GetVertexAttribiv("glGetVertexAttribiv");
Function<Binding, GLVULKANPROCNV, const GLchar *> Binding::GetVkProcAddrNV("glGetVkProcAddrNV");
Function<Binding, void, GLuint, GLint, GLsizei, GLfloat *> Binding::GetnUniformfv("glGetnUniformfv");
Function<Binding, void, GLuint, GLint, GLsizei, GLfloat *> Binding::GetnUniformfvEXT("glGetnUniformfvEXT");
Function<Binding, void, GLuint, GLint, GLsizei, GLint *> Binding::GetnUniformiv("glGetnUniformiv");
Function<Binding, void, GLuint, GLint, GLsizei, GLint *> Binding::GetnUniformivEXT("glGetnUniformivEXT");
Function<Binding, void, GLuint, GLint, GLsizei, GLuint *> Binding::GetnUniformuiv("glGetnUniformuiv");



} // namespace glesbinding
